SKINS = GLOBAL.STRINGS.SKIN_NAMES
SKINSDESC = GLOBAL.STRINGS.SKIN_DESCRIPTIONS
STRINGS = GLOBAL.STRINGS.NAMES
UI = GLOBAL.STRINGS.UI


--Re-names to existing items
STRINGS.AMULET = "次级生命护身符"
STRINGS.BEESWAX = "蜡"



-------------------------------------------------- Strings

STRINGS.CREEPINGFEAR = "潜伏恐惧"
STRINGS.DREADEYE = "恐惧之眼"

STRINGS.UNCOMPROMISING_RAT = "老鼠" -- Maybe change the name with a pun with Robber or Raider, any idea ?
STRINGS.UNCOMPROMISING_CAVERAT = "穴居鼠" -- The aggressive cousin
STRINGS.UNCOMPROMISING_PACKRAT = "背包鼠" -- The hoarding cousin
STRINGS.UNCOMPROMISING_RATHERD = "鼠群"
STRINGS.UNCOMPROMISING_RATBURROW = "鼠穴"
STRINGS.UNCOMPROMISING_WINKYBURROW = "温奇的鼠穴"
STRINGS.UNCOMPROMISING_WINKYBURROW_MASTER = "温奇的鼠穴"
STRINGS.UNCOMPROMISING_WINKYHOMEBURROW = "温奇的定居鼠穴"
STRINGS.PIED_RAT = "花衣吹笛者"
STRINGS.PIED_PIPER_FLUTE = "鼠笛"
STRINGS.GASMASK = "鹅毛面具"
STRINGS.WATER = "雨水"
STRINGS.RAIN = "雨水"
STRINGS.SPORECLOUD_TOAD = "孢子云"
STRINGS.MOCK_DRAGONFLY = "时令龙蝇"
STRINGS.UM_SAND = "沙子"
STRINGS.UM_SANDHILL = "沙堆"
STRINGS.SNOWPILE = "雪堆"
STRINGS.SNOWGOGGLES = "猫眼护目镜"
STRINGS.UM_SPIDERQUEENCORPSE = "蜘蛛女王尸体"
STRINGS.RATPOISON = "毒果酱陷阱"
STRINGS.RATPOISONBOTTLE = "毒果酱"
STRINGS.LEECHSWARM = "花粉螨"
STRINGS.LAITLEECH = "水蛭群"
STRINGS.SHOCKWORM = "洞穴电鳗"


STRINGS.ZASPBERRY = "电光浆果"
STRINGS.ZASPBERRY_LESSER = "小电光浆果"
STRINGS.ZASPBERRY_PLANT = "可疑植物"

STRINGS.SNOWMONG = "雪怪"
STRINGS.MINOTAUR_BOULDER = "远古石板"
STRINGS.MINOTAUR_BOULDER_BIG = "巨型远古石板"
STRINGS.MINOTAUR_ORGAN = "暗影心脏"
STRINGS.MOCK_DRAGONFLY = "时令龙蝇"

STRINGS.MOONMAW_DRAGONFLY = "月光龙蝇"
STRINGS.MOONMAW_GLASS = "不稳定的玻璃块"
STRINGS.MOONMAW_LAVAE = "玻璃岩浆虫"
STRINGS.MOONMAW_LAVAE_RING = STRINGS.MOONMAW_LAVAE
STRINGS.GLASS_SCALES = "启迪鳞片"
STRINGS.MOONGLASS_GEODE = "注能的玻璃碎片"
STRINGS.ARMOR_GLASSMAIL = "月鳞甲"
STRINGS.ARMOR_GLASSMAIL_SHARDS = "玻璃碎片"
STRINGS.MOONMAW_TRAP = STRINGS.ALTERGUARDIAN_PHASE3TRAP

STRINGS.LAVAE2 = STRINGS.LAVAE
STRINGS.BUSHCRAB = "灌木丛蟹"
STRINGS.ICEBOOMERANG = "冰冻回旋镖"
STRINGS.TOADLING = "蘑菇蟾蜍"
STRINGS.UNCOMPROMISING_TOAD = "多病青蛙"
STRINGS.DISEASECUREBOMB = "月油"
STRINGS.TOADLINGSPAWNER = "蟾蜍孢子"
-- STRINGS.NAMES.TOAD  = "Sickly Toad"
STRINGS.MONSTERSMALLMEAT = "小怪物肉"
STRINGS.COOKEDMONSTERSMALLMEAT = "烤小怪物肉"
STRINGS.MONSTERSMALLMEAT_DRIED = "小怪物肉干"
STRINGS.UM_MONSTEREGG = "怪物蛋"
STRINGS.UM_MONSTEREGG_COOKED = "熟怪物蛋"
STRINGS.VETERANSHRINE = "头骨洞窟"

STRINGS.WILSON_VETSKULL = "威尔逊的头骨"
STRINGS.WALTER_VETSKULL = "沃尔特的头骨"
STRINGS.WORTOX_VETSKULL = "沃拓克斯的头骨"
STRINGS.MAXWELL_VETSKULL = "麦斯威尔的头骨"
STRINGS.WILLOW_VETSKULL = "薇洛的头骨"
STRINGS.WARLY_VETSKULL = "沃利的头骨"
STRINGS.WINKY_VETSKULL = "温奇的头骨"
STRINGS.WICKERBOTTOM_VETSKULL = "薇克巴顿的头骨"
STRINGS.WIXIE_VETSKULL = "薇希的头骨"
STRINGS.WOODIE_VETSKULL = "伍迪的头骨"
STRINGS.WOLFGANG_VETSKULL = "沃尔夫冈的头骨"
STRINGS.WANDA_VETSKULL = "旺达的头骨"
STRINGS.WATHGRITHR_VETSKULL = "薇格弗德的头骨"
STRINGS.WES_VETSKULL = "韦斯的头骨"
STRINGS.WENDY_VETSKULL = "温蒂的头骨"

STRINGS.UM_SHADOW_WALTER = "沃尔特？"
STRINGS.UM_SHADOW_WORTOX = "沃拓克斯？"
STRINGS.UM_SHADOW_MAXWELL = "麦斯威尔？"
STRINGS.UM_SHADOW_WILLOW = "薇洛？"
STRINGS.UM_SHADOW_WARLY = "沃利？"
STRINGS.UM_SHADOW_WINKY = "温奇？"
STRINGS.UM_SHADOW_WICKERBOTTOM = "薇克巴顿？"
STRINGS.UM_SHADOW_WOODIE = "伍迪？"
STRINGS.UM_SHADOW_WOLFGANG = "沃尔夫冈？"
STRINGS.UM_SHADOW_WANDA = "旺达？"
STRINGS.UM_SHADOW_WATHGRITHR = "薇格弗德？"
STRINGS.UM_SHADOW_WES = "韦斯？"
STRINGS.UM_SHADOW_WENDY = "温蒂？"

STRINGS.UM_BOSS_SOUL = "暗影之魂"
STRINGS.UM_DARK_VESTIGES = "暗影残迹"
STRINGS.EXPLOSIVE_VETCURSE_SOUL = "爆裂灵魂"

STRINGS.UM_CHERRY_BEEQUEEN_SOUL = "樱桃蜂后灵魂"
STRINGS.UM_BEEQUEEN_SOUL = "蜂后灵魂"
STRINGS.UM_BEARGER_SOUL = "熊獾灵魂"
STRINGS.UM_DEERCLOPS_SOUL = "巨鹿灵魂"
STRINGS.UM_CRABKING_SOUL = "帝王蟹灵魂"
STRINGS.UM_MINOTAUR_SOUL = "远古守护者灵魂"
STRINGS.UM_DRAGONFLY_SOUL = "龙蝇灵魂"
STRINGS.UM_GOOSE_SOUL = "麋鹿鹅灵魂"
STRINGS.UM_HOODEDWIDOW_SOUL = "黑寡妇灵魂"
STRINGS.UM_KLAUS_SOUL = "克劳斯灵魂"
STRINGS.UM_FUELWEAVER_SOUL = "织影者灵魂"
STRINGS.UM_MALBATROSS_SOUL = "马尔巴洛斯灵魂"
STRINGS.UM_MOONMAW_SOUL = "月腹灵魂"

STRINGS.UM_RECORD_MENU = "永不妥协乐章"
STRINGS.UM_RECORD_WALTER = "跟我来，沃比！"
STRINGS.UM_RECORD_WIXIE = "叛逆顽童"
STRINGS.UM_RECORD_SHADOW_WIXIE = "幽暗本心"
STRINGS.UM_RECORD_HOODED_WIDOW = "恐蛛之音"
STRINGS.UM_RECORD_WATHOM = "心脏骤停！"
STRINGS.UM_RECORD_STRANGER = "神秘过客"
STRINGS.UM_RECORD_WINKY = "趣致小鼠"
STRINGS.UM_RECORD_MOONMAW = "飞蛾扑火"
STRINGS.UM_RECORD_TOT = "双生狂乱"

STRINGS.RATSKIN = "鼠皮"

STRINGS.PLAGUEMASK = "瘟疫面具"
SKINS.ms_hat_plaguemask_formal = "瘟疫面具"
SKINSDESC.ms_hat_plaguemask_formal = "一个在腐烂的世界中脱颖而出的精美面具。"

SKINS.wormwood_shadow = "堕落者" -- personal vendetta, bruh that shit aint 'triumphant'

STRINGS.TRAPDOOR = "不起眼的土丘"
STRINGS.SPIDER_TRAPDOOR = "地穴蜘蛛"
STRINGS.SPIDER_TRAPDOOR_HOODED = "黑寡妇"
STRINGS.MUTATOR_TRAPDOOR = "地穴变身涂鸦"
STRINGS.DECIDUOUS_ROOT = "活木树根"
STRINGS.LAVAESLIME = "岩浆虫黏液"
STRINGS.SALTPACK = "盐瓶3000"
STRINGS.SPOREPACK = "蟾蜍背包"
STRINGS.RAT_TAIL = "鼠尾"
STRINGS.SHROOM_SKIN_FRAGMENT = "蘑菇皮碎片"
STRINGS.AIR_CONDITIONER = "空调" -- <--
STRINGS.MINI_DREADEYE = "暗影之眼"
STRINGS.SHADOW_GOO = "暗影墨水"

STRINGS.ROCK_LICHEN = "大理石地衣"
STRINGS.SPRINGROCK1 = "岩石"
STRINGS.SPRINGROCK2 = "岩石"
STRINGS.SPRINGROCK3 = "岩石"

STRINGS.CAVE_ENTRANCE_MAGMABIOME = "岩石"
STRINGS.CAVE_ENTRANCE_OPEN_MAGMABIOME = "温暖洞穴"
STRINGS.CAVE_EXIT_MAGMABIOME = "湿热楼梯"
STRINGS.LAVA_POND_CAVE = "熔岩池"
STRINGS.MAGMAROCK1 = "岩石"
STRINGS.MAGMABONE = "骸骨"

STRINGS.BOULDER_CRAB = "岩石蟹"
STRINGS.BOULDER_CRAB_HOLE = "岩石蟹洞穴"
STRINGS.UM_HOTSPRING = "沸腾温泉"
STRINGS.VAMPIREBAT = "巨型蝙蝠"
STRINGS.WICKER_TENTACLE = "多病触手"
STRINGS.SKELETONMEAT = "长猪肉干"
STRINGS.ZASPBERRYPARFAIT = "电光浆果芭菲"
STRINGS.CARAPACECOOLER = "甲壳冷却器"
STRINGS.HONEY_LOG = "蜂蜜原木卷"
STRINGS.RNEGHOST = "游魂"
STRINGS.CHIMP = "猴子"
STRINGS.BUGZAPPER = "电蚊拍"
STRINGS.RICE1 = "稻米"
STRINGS.RICE2 = "稻米"
STRINGS.RICE_COOKED1 = "烤稻米"
STRINGS.RICE_COOKED2 = "烤稻米"
STRINGS.RICEPLANT1 = "水稻"
STRINGS.RICEPLANT2 = "水稻"
STRINGS.SEAFOODPAELLA = "海鲜饭"
STRINGS.SWILSON = "威尔逊？"
STRINGS.SWATHGRITHR = "薇格弗德？"
STRINGS.MOTHERGOOSE1 = "麋鹿鹅妈妈"
STRINGS.MOTHERGOOSE2 = "麋鹿鹅妈妈"
STRINGS.CRITTERLAB_REAL = "岩石巢穴"
STRINGS.CRITTERLAB_REAL_BROKEN = "破碎的岩石巢穴"
STRINGS.POLLENMITES = "花粉螨"
STRINGS.POLLENMITEDEN = "花粉螨巢穴"
STRINGS.WALRUS_CAMP_SUMMER = STRINGS.WALRUS_CAMP
STRINGS.SUNGLASSES = "太阳镜"
STRINGS.CHARLIEPHONOGRAPH_100 = "留声机"
STRINGS.STUMPLING = "松树树桩怪"
STRINGS.BIRCHLING = "桦树树桩怪"
STRINGS.LICELOAF1 = "米花糖"
STRINGS.LICELOAF1 = "米花糖"
STRINGS.MOON_TEAR = "月泪"
STRINGS.SHADOW_TELEPORTER = "暗影爪"
STRINGS.WAXWELL_PACT_TRADER = "契约之手"

STRINGS.SHADOW_CROWN = "暗影王冠"
STRINGS.UM_SHADOW_AXE = "幽暗斧"
STRINGS.CALIFORNIAKING = "加州辣汤"
STRINGS.TRAPDOORGRASS = "茂密草丛"
STRINGS.LUREPLAGUE_RAT = "腐败鼠"
STRINGS.SNAPPERTURTLE = "乌龟"
STRINGS.SNAPPERTURTLEBABY = "乌龟宝宝"
STRINGS.SNAPPERTURTLENEST = "乌龟巢穴"

STRINGS.CURSED_ANTLER = "诅咒鹿角"
SKINS.ms_twisted_antler = "扭曲鹿角"
SKINSDESC.ms_twisted_antler = "扭曲鹿角，给扭曲的人。"

STRINGS.UM_EXHUMER = "掘墓铲"
STRINGS.UM_WINGSUIT = "翼装服"
STRINGS.UM_MOONFLY_LANTERN = "月蝇提灯"

STRINGS.MARSH_GRASS = "沼泽灌木"
STRINGS.GIANT_TREE = "巨型红杉"
STRINGS.WEBBEDCREATURE = "茧"
STRINGS.WIDOWSGRASP = "寡妇之爪"
STRINGS.HOODEDWIDOW = "黑寡妇"
STRINGS.SILKSACK = "蛛丝背包"
STRINGS.SILKEN_BUNDLE = "蛛丝捆绑物资"


STRINGS.WEBBEDCREATURE_BUGGY = "虫茧"
STRINGS.WEBBEDCREATURE_GROSS = "怪诞虫茧"
STRINGS.WEBBEDCREATURE_HAIRY = "多毛虫茧"
STRINGS.WEBBEDCREATURE_HARD = "硬化虫茧"
STRINGS.WEBBEDCREATURE_LEATHER = "粗糙虫茧"
STRINGS.WEBBEDCREATURE_FEATHER = "轻软虫茧"
STRINGS.WEBBEDCREATURE_LEAFY = "带叶虫茧"
STRINGS.WEBBEDCREATURE_SCALY = "带鳞虫茧"
STRINGS.CHOMPER = "大嘴花"
STRINGS.BERNIEBOX = "玩具盒"
STRINGS.SNAPDRAGON = "金鱼草"
STRINGS.GIANT_BLUEBERRY = "爆汁蓝莓"
STRINGS.BLUEBERRYPLANT = "爆汁蓝莓植株"
STRINGS.BLUEBERRYFLOWER = "爆汁蓝莓花"
STRINGS.HOODEDTRAPDOOR = "活动石板"
STRINGS.HOODED_FERN = "高齿蕨"
STRINGS.FALLINGBEEHIVE = STRINGS.BEEHIVE
STRINGS.FRUITBAT = "果蝠"
STRINGS.PITCHERPLANT = "猪笼草"
STRINGS.GIANT_TREE_INFESTED = "被感染的红杉"
STRINGS.SNAPDRAGON_BUDDY_pale = "白色金鱼草"
STRINGS.SNAPDRAGON_BUDDY_orange = "橙色金鱼草"
STRINGS.SNAPDRAGON_BUDDY_red = "红色金鱼草"
STRINGS.SNAPDRAGON_BUDDY_purple = "紫色金鱼草"
STRINGS.SNAPDRAGON_BUDDY_pink = "粉色金鱼草"
STRINGS.SNAPDRAGON_BUDDY_green = "绿色金鱼草"
STRINGS.SNAPDRAGON_BUDDY_yellow = "黄色金鱼草"
STRINGS.PALE_VOMIT = "白色黏液"
STRINGS.ORANGE_VOMIT = "橙色黏液"
STRINGS.RED_VOMIT = "红色黏液"
STRINGS.PURPLE_VOMIT = "紫色黏液"
STRINGS.PINK_VOMIT = "粉色黏液"
STRINGS.GREEN_VOMIT = "绿色黏液"
STRINGS.YELLOW_VOMIT = "黄色黏液"
STRINGS.SNAPPLANT = "金鱼草植株"
STRINGS.WHISPERPOD = "耳语豆荚"
STRINGS.WHISPERPOD_NORMAL_GROUND = "耳语豆荚"
STRINGS.DEPLETED_HOODED_FERN = "大型蕨"
STRINGS.APHID = "蚜虫"
STRINGS.NYMPH = "若虫"
STRINGS.WIDOWSHEAD = "寡妇之颅"
STRINGS.CCTRINKET_DON = "撕破的书"
STRINGS.CCTRINKET_JAZZY = "生锈的萨克斯"
STRINGS.CCTRINKET_FREDDO = "破损的磁带"
STRINGS.CCTRINKET_NAMES = "必要标签"

STRINGS.BLUEBERRYPANCAKES = "爆汁蓝莓薄饼"
STRINGS.DEVILSFRUITCAKE = "恶魔水果蛋糕"
STRINGS.SIMPSALAD = "简单沙拉"
STRINGS.BEEFALOWINGS = "牛角派"
STRINGS.PINEPILE = "树枝堆"
STRINGS.HOODED_MUSHTREE_TALL = STRINGS.MUSHTREE_TALL
STRINGS.HOODED_MUSHTREE_MEDIUM = STRINGS.MUSHTREE_MEDIUM
STRINGS.HOODED_MUSHTREE_SMALL = STRINGS.MUSHTREE_SMALL
STRINGS.SCREECHER_TRINKET = "蝙蝠玩偶"
STRINGS.SNOWCONE = "冰沙"
STRINGS.CINNAMON_TREE = "肉桂树"
STRINGS.CINNAMON_TREE_BURNT = "肉桂树"
STRINGS.CINNAMON_TREE_STUMP = "肉桂树"
STRINGS.WATERMELON_LANTERN = "西瓜灯"
STRINGS.ANCIENT_TREPIDATION = "恐怖巨蛛"
STRINGS.ANCIENT_TREPIDATION_ARM = "巨蛛之爪"
STRINGS.STEEL_SWEATER = "钢制毛衣"
STRINGS.RNESKELETON = "骷髅士兵"

STRINGS.ANCIENT_AMULET_RED = "唤灵护符"
SKINS.ms_ancient_amulet_red_demoneye = "魔眼护符"
SKINSDESC.ms_ancient_amulet_red = "" -- TODO

STRINGS.RAT_WHIP = "绞尾鼠鞭"
STRINGS.KLAUS_AMULET = "无锁"
STRINGS.HOUND_LIGHTNING = "超级闪电"
STRINGS.LIGHTNINGHOUND = "闪电猎犬"
STRINGS.MAGMAHOUND = "熔岩青年座狼"
STRINGS.SPOREHOUND = "孢子猎犬"
STRINGS.GLACIALHOUND = "冰川青年座狼"
STRINGS.CRABCLAW = "诅咒蟹钳"
STRINGS.BIGHT = "超载奇械"
STRINGS.KNOOK = "自走噩兆"
STRINGS.ROSHIP = "啮合巨炮"
STRINGS.SNOTROAST = "象鼻大餐"
STRINGS.LICELOAF = "米花糖" -- For the cookbook

STRINGS.TURF_HOODEDMOSS = "连帽森林地皮"
STRINGS.TURF_ANCIENTHOODEDTURF = "远古连帽森林地皮"
STRINGS.TURF_UM_HOTSPRING_GRASS = "泥泞森林地皮"
STRINGS.TURF_UM_HOTSPRING_YELLOWROCK = "黄色岩石地皮"
STRINGS.TURF_UM_HOTSPRING_WHITEROCK = "白色岩石地皮"

STRINGS.DEERCLOPS_BARRIER = "冰墙"
STRINGS.PIGKING_PIGTORCH = STRINGS.PIGTORCH
STRINGS.UM_PAWN = "发条蟹兵"
STRINGS.UM_PAWN_NIGHTMARE = "损坏的发条蟹兵"
STRINGS.CAVE_ENTRANCE_SUNKDECID = STRINGS.CAVE_ENTRANCE
STRINGS.CAVE_ENTRANCE_OPEN_SUNKDECID = STRINGS.CAVE_ENTRANCE_OPEN
STRINGS.CAVE_EXIT_SUNKDECID = STRINGS.CAVE_EXIT
STRINGS.CAVE_ENTRANCE_MOON = STRINGS.CAVE_ENTRANCE
STRINGS.CAVE_ENTRANCE_OPEN_MOON = STRINGS.CAVE_ENTRANCE_OPEN
STRINGS.CAVE_EXIT_MOON = STRINGS.CAVE_EXIT
STRINGS.GORE_HORN_HAT = "犀牛帽"
STRINGS.SLOBBERLOBBER = "熔岩口器"
STRINGS.BEARGERCLAW = "诅咒熊爪"
STRINGS.LAVASPIT_SLOBBER = STRINGS.LAVASPIT
STRINGS.WOODPECKER = "啄木鸟"
STRINGS.UM_BEAR_TRAP = "利颚陷阱"
STRINGS.UM_BEAR_TRAP_OLD = "利颚陷阱"
STRINGS.MOTHERMOSSLING = STRINGS.MOSSLING
STRINGS.MOTHERMOOSEEGG1 = "金麋鹿蛋"
STRINGS.MOTHERMOOSEEGG2 = "金鹅蛋"
STRINGS.CORNCAN = "玉米罐头"
STRINGS.SKULLCHEST_CHILD = "骷髅箱"
STRINGS.SKULLCHEST = "骷髅箱"
STRINGS.GREENFOLIAGE = "森林蕨叶" -- Well, I guess I did this then...

STRINGS.FEATHER_FROCK = "羽毛长袍"
SKINS.ms_feather_frock_fancy = "乌鸦披风"
SKINSDESC.ms_feather_frock_fancy = "用最好的羽毛制成的华丽斗篷。"

STRINGS.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "捕兽夹"
STRINGS.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "黄金捕兽夹"
STRINGS.DRIFTWOODFISHINGROD = "浮木钓杆"

STRINGS.REDGEM_CRACKED = "破碎的红宝石"
STRINGS.BLUEGEM_CRACKED = "破碎的蓝宝石"
STRINGS.ORANGEGEM_CRACKED = "破碎的橙宝石"
STRINGS.GREENGEM_CRACKED = "破碎的绿宝石"
STRINGS.YELLOWGEM_CRACKED = "破碎的黄宝石"
STRINGS.PURPLEGEM_CRACKED = "破碎的紫宝石"
STRINGS.OPALPRECIOUSGEM_CRACKED = "破碎的彩虹宝石"
STRINGS.RED_MUSHED_ROOM = "红蘑菇糊糊"
STRINGS.GREEN_MUSHED_ROOM = "绿蘑菇糊糊"
STRINGS.BLUE_MUSHED_ROOM = "蓝蘑菇糊糊"

-- Stanton's Stash
STRINGS.STANTON_SHADOW_TONIC = "暗影气泡酒"
STRINGS.STANTON_SHADOW_TONIC2 = STRINGS.STANTON_SHADOW_TONIC
STRINGS.STANTON = "骷髅克里"
STRINGS.SKULLFLASK = "头骨酒瓶"
STRINGS.SKULLFLASK_EMPTY = "空头骨酒瓶"
-- Stanton's Stash

STRINGS.THEATERCORN = "玉米杯"
STRINGS.ARMORLAVAE = "友好的岩浆虫"
STRINGS.WIDOW_WEB_COMBAT = "蛛网粘液"

-- Blowgun stuff
STRINGS.UNCOMPROMISING_BLOWGUN = "吹箭筒" -- Lol
STRINGS.BLOWGUNAMMO_TOOTH = "飞镖"
STRINGS.BLOWGUNAMMO_FIRE = "火焰飞镖"
STRINGS.BLOWGUNAMMO_SLEEP = "催眠飞镖"
STRINGS.BLOWGUNAMMO_ELECTRIC = "雷电飞镖"

STRINGS.BOOK_RAIN_UM = "雨日手记"

STRINGS.RAIN_HORN = "唤雨海螺"
STRINGS.FLORAL_BANDAGE = "夏花绷带"
STRINGS.DORMANT_RAIN_HORN = "休眠海螺"

STRINGS.NIGHTCRAWLER = "梦游者"
STRINGS.UM_NIGHTCRAWLER = "暗影爬虫"
STRINGS.RNE_GRABBYSHADOWS = "暗影吊手"
STRINGS.NERVOUSTICK = "神经蜱"
STRINGS.NERVOUSTICKDEN = "虫群心脏"
STRINGS.FUELSEEKER = "燃料搜寻器"
STRINGS.MINDWEAVER = "心灵编织者"
STRINGS.UM_HECKLER = "斯皮茨女士"

STRINGS.RNEMUSHROOMBOMB = "爆菇"

STRINGS.HAT_BAGMASK = "纸袋"
STRINGS.HAT_BLACKCATMASK = "黑猫面具"
STRINGS.HAT_CLOWNMASK = "小丑面具"
STRINGS.HAT_WATHOMMASK = "怪物面具"
STRINGS.HAT_DEVILMASK = "红面恶魔面具"
STRINGS.HAT_FIENDMASK = "紫面恶魔面具"
STRINGS.HAT_GHOSTMASK = "橙眼鬼魂面具"
STRINGS.HAT_GLOBMASK = "绿水鬼面具"
STRINGS.HAT_HOCKEYMASK = "撕裂面具"
STRINGS.HAT_JOYOUSMASK = "大笑面具"
STRINGS.HAT_MERMMASK = "鱼人面具"
STRINGS.HAT_OOZEMASK = "紫水鬼面具"
STRINGS.HAT_ORANGECATMASK = "黄猫面具"
STRINGS.HAT_PHANTOMMASK = "紫眼鬼魂面具"
STRINGS.HAT_PIGMASK = "猪人面具"
STRINGS.HAT_PUMPGOREMASK = "南瓜面具"
STRINGS.HAT_REDSKULLMASK = "红骷髅面具"
STRINGS.HAT_SKULLMASK = "白骷髅面具"
STRINGS.HAT_SPECTREMASK = "青眼鬼魂面具"
STRINGS.HAT_WHITECATMASK = "白猫面具"
STRINGS.HAT_TECHNOMASK = "机械面具"
STRINGS.HAT_MANDRAKEMASK = "蔓草面具"
STRINGS.HAT_OPOSSUMMASK = "负鼠面具"
STRINGS.RNE_GOODIEBAG = "零食袋"
STRINGS.HAT_RATMASK = "老鼠面具"

STRINGS.OCULET = "双子护符"
STRINGS.OCULET_REZ = "激光眼宠物"
STRINGS.OCULET_SPAZ = "魔焰眼宠物"
STRINGS.WILLIAM = "威廉"

-- Under the Weather--
STRINGS.UNCOMPROMISING_HARPOON = "鱼叉"
STRINGS.UNCOMPROMISING_HARPOON_HEAVY = "重型鱼叉"
STRINGS.UNCOMPROMISING_HARPOONREEL = "卷轴"
STRINGS.UM_MAGNERANG = "磁力回旋镖"
STRINGS.UM_MAGNERANGREEL = "磁力回旋镖"
STRINGS.UNCOMPROMISING_FISHINGNET = "渔网"
STRINGS.UM_BEEGUN = "手持蜂巢"
STRINGS.UM_BEEGUN_CHERRY = "手持蜂巢"
STRINGS.BULLETBEE = "子弹蜂"
STRINGS.CHERRYBULLETBEE = "子弹蜂"
STRINGS.UM_BULLETBEE_PROJ = "子弹蜂"
STRINGS.UM_CHERRYBULLETBEE_PROJ = "子弹蜂"

STRINGS.WINONA_TOOLBOX = "器械箱"
STRINGS.OCEAN_SPEAKER = "破旧的扬声器" -- Kinda lame dunno what else though.
STRINGS.OCEAN_SPEAKER_TEASER = STRINGS.OCEAN_SPEAKER
STRINGS.SUNKENCHEST_ROYAL_RANDOM = "皇家沉底宝箱"

STRINGS.SUNKENCHEST_ROYAL_RED = "宝石镶嵌宝箱"
STRINGS.SUNKENCHEST_ROYAL_BLUE = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_PURPLE = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_GREEN = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_ORANGE = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_YELLOW = STRINGS.SUNKENCHEST_ROYAL_RED
STRINGS.SUNKENCHEST_ROYAL_RAINBOW = "绚丽的 " .. STRINGS.SUNKENCHEST_ROYAL_RED

STRINGS.SLUDGE = "海泥"
STRINGS.SLUDGE_OIL = "海泥提取物"
STRINGS.BOATPATCH_SLUDGE = "海泥补丁套件"
STRINGS.SLUDGESTACK = "海泥喷孔"
STRINGS.SLUDGE_SACK = "海泥包"

STRINGS.ARMOR_REED_UM = "芦苇甲"
STRINGS.ARMOR_SHARKSUIT_UM = "鲨甲"

STRINGS.ROCKJAWLEATHER = "鲨鱼皮"

STRINGS.LANTERN_ELECTRICAL = "电灯"
STRINGS.MINERHAT_ELECTRICAL = "电矿工帽"

STRINGS.POWERCELL = "蓄电池" -- 一次性电池

STRINGS.SEAROCK_RING = "海蚀柱"
STRINGS.RR_POWERLINE = "电力线"
STRINGS.EYEOFTERROR_MINI_ALLY = "无畏窥视者"
STRINGS.EYEOFTERROR_MINI_GROUNDED_ALLY = "恐怖的蛋"
STRINGS.STUFFED_PEEPER_POPPERS = "榴莲酿眼球"
STRINGS.UM_DEVILED_EGGS = "魔鬼蛋料理"
STRINGS.SIREN_BIRD_NEST = "筑巢的海蚀柱"
STRINGS.SIREN_BIRD_NEST_TEASER = STRINGS.SIREN_BIRD_NEST
STRINGS.SIREN_THRONE = "海妖王座"
STRINGS.SIREN_THRONE_TEASER = STRINGS.SIREN_THRONE
-- STRINGS.NAMES.UM_SIREN = "警笛"
STRINGS.WINONA_UPGRADEKIT_ELECTRICAL = "电能转换套件"
STRINGS.UM_SORREL = "酢浆草"

STRINGS.CRITTER_FIGGY = "小蚜虫"
STRINGS.CRITTER_FIGGY_BUILDER = "小蚜虫"

STRINGS.PORTABLEBOAT_ITEM = "气垫船套装"
STRINGS.PORTABLEBOAT_RIPCORD = "气垫船插头"

STRINGS.MASTUPGRADE_WINDTURBINE_ITEM = "风力涡轮灯台"

STRINGS.LUSH_ENTRANCE = "十分凶险的洞"
STRINGS.GIANT_TREE_BIRDNEST = "鸟巢"

STRINGS.CANNONBALL_SLUDGE_ITEM = "海泥炮弹"
STRINGS.CANNONBALL_SLUDGE = "海泥炮弹"
STRINGS.UM_COPPER_PIPE = "铜管"
STRINGS.STEERINGWHEEL_COPPER = "铜方向盘"
STRINGS.STEERINGWHEEL_COPPER_ITEM = "铜方向盘套装"
STRINGS.BOAT_BUMPER_SLUDGE = "海泥保险杠"
STRINGS.BOAT_BUMPER_SLUDGE_KIT = "海泥保险杠套装"
STRINGS.BOAT_BUMPER_COPPER = "铜保险杠"
STRINGS.BOAT_BUMPER_COPPER_KIT = "铜保险杠套装"
STRINGS.HERMIT_BUNDLE_LURES = "诱饵包"
STRINGS.LAVASPIT_SLUDGE = "燃烧的海泥池"

STRINGS.KELPSTACK = "海带海蚀柱"
STRINGS.MOSSSTACK = "苔藓海蚀柱"

STRINGS.SPECTER_SHIPWRECK = "废弃的沉船"
STRINGS.UM_DREAMCATCHER = "追梦人"
STRINGS.UM_BRINEISHMOSS = "盐水苔藓"
STRINGS.UM_COALESCED_NIGHTMARE = "合并梦魇"
STRINGS.BRINE_BALM = "盐晶药膏"
STRINGS.SLUDGE_CORK = "海泥塞"
STRINGS.UM_SPECTOPLASM = "光谱"
STRINGS.UM_SPECTER_AMULET = "幽灵护身符"
STRINGS.PHANTOM = "鬼魂" -- phantom like minecraft :-O
STRINGS.UMSS_GENERAL = "永不妥协开发工具"
STRINGS.UM_DEVCAPTURE = "开发捕获设备"
STRINGS.UM_BEEGUARD_SEEKER = "轰炸蜂"
STRINGS.UM_BEEGUARD_BLOCKER = "拦截蜂"
STRINGS.UM_BEEGUARD_SHOOTER = "子弹蜂"

STRINGS.UM_ORNAMENT_OPOSSUM = "负鼠装饰物"
STRINGS.UM_ORNAMENT_RAT = "老鼠装饰"

STRINGS.TRINKET_WATHOM1 = "破损的吸入器"

STRINGS.DEATHAMP = "心脏病发作"

STRINGS.CODEX_MANTRA = "旧·暗影秘典"
STRINGS.SHADOWVORTEX = "暗影漩涡"

STRINGS.UM_INKUBATOR = "远古孵化器"
STRINGS.UM_SCRAPPER = "远古拆解机"
STRINGS.UM_ASTRAL_PROJECTOR = "星界投射器"
STRINGS.UM_ASTRAL_PROJECTOR_TARGET = "星界接收器"

STRINGS.UM_MEAT_CUBE = "肉类立方块"
STRINGS.UM_MONSTER_CUBE = "怪物立方块"
STRINGS.UM_VEGGIE_CUBE = "蔬菜立方块"
STRINGS.UM_SUGAR_CUBE = "糖质立方块"
STRINGS.UM_ROUGHAGE_CUBE = "木质立方块"
STRINGS.UM_BLAND_CUBE = "无味立方块"

-- Ocupus Parts
STRINGS.UM_OCUPUS_EYE = "眼柄"
STRINGS.UM_OCUPUS_EYETACLE = "眼柄"
STRINGS.UM_OCUPUS_TENTACLE = "触手"
STRINGS.UM_OCUPUS_BEAK = "喙"

-- Ocupus Items
STRINGS.OCUPUS_TENTACLE = "多目章鱼触手"
STRINGS.OCUPUS_TENTACLE_EYE = "多目章鱼眼球"
STRINGS.OCUPUS_TENTACLE_COOKED = "熟触手"
STRINGS.OCUPUS_BEAK = "多目章鱼喙"
STRINGS.BEAKBASHER = "喙击者"
STRINGS.PLAUNT_MANNY = "汪汪警戒娃娃"

-- WIXIE & WALTER RELATED STRINGS

STRINGS.WIXIE_PIANO = "三角钢琴"
STRINGS.WIXIE_PIANO_CARD = "神秘纸张"
STRINGS.WIXIE_CLOCK = "落地摆钟"
STRINGS.WIXIE_CLOCKDANGLEY1 = "秒权重"
STRINGS.WIXIE_CLOCKDANGLEY2 = "分钟权重"
STRINGS.WIXIE_CLOCKDANGLEY3 = "小时权重"
STRINGS.WIXIE_WARDROBE = "华丽的衣橱"
STRINGS.CHARLES_T_HORSE = "破旧玩具"
STRINGS.THE_REAL_CHARLES_T_HORSE = "滑行手杖"
STRINGS.WOODEN_QUEEN_PIECE = "木制女王"
STRINGS.WIXIE_SHADOWCLONE = "暗影薇希"
STRINGS.SHADOW_WIXIE = "薇希"
STRINGS.WIXIE_SHADOW_CLONE = "暗影薇希"
STRINGS.SHADOW_WIXIE_HELPER = "暗影薇希"

STRINGS.SLINGSHOT_MATILDA = "浮木弹弓-玛蒂尔达"
STRINGS.SLINGSHOT_GNASHER = "活木弹弓-切齿"
STRINGS.SLINGSHOT_JESSIE = "绝望弹弓-杰西"
STRINGS.SLINGSHOT_CLAIRE = "光芒弹弓-克莱尔"

STRINGS.SLINGSHOTAMMO_LAZY = "替身弹药"
STRINGS.SLINGSHOTAMMO_SHADOW = "梦魇弹药"
STRINGS.SLINGSHOTAMMO_FIRECRACKERS = "鞭炮弹药"
STRINGS.SLINGSHOTAMMO_HONEY = "蜂蜜弹药"
STRINGS.SLINGSHOTAMMO_RUBBER = "橡皮弹药"
STRINGS.SLINGSHOTAMMO_TREMOR = "沙石弹药"
STRINGS.SLINGSHOTAMMO_MOONROCK = "月岩弹药"
STRINGS.SLINGSHOTAMMO_MOONGLASS = "月亮碎片弹药"
STRINGS.SLINGSHOTAMMO_SALT = "盐晶弹药"
STRINGS.SLINGSHOTAMMO_SLIME = "黏糊弹药"
STRINGS.SLINGSHOTAMMO_GOOP = "粘液弹药"
STRINGS.SLINGSHOTAMMO_FLARE = "爆燃弹药"

STRINGS.SLINGSHOTAMMO_INSANITY = "疯狂弹药"
STRINGS.SLINGSHOTAMMO_LUNARVINE = "新月弹药"

STRINGS.BAGOFMARBLES = "弹珠袋"

STRINGS.SLINGSHOTAMMO_LIMESTONE = "海泥弹药"
STRINGS.SLINGSHOTAMMO_TAR = "海泥弹药"
STRINGS.SLINGSHOTAMMO_OBSIDIAN = "黑曜石弹药"

STRINGS.PLACEHOLDER_INGREDIENT_IA_UM = "需要岛屿冒险或永不妥协！"
STRINGS.PLACEHOLDER_INGREDIENT_IA = "需要岛屿冒险！"

STRINGS.MEATRACK_HAT = "风干帽"
STRINGS.FISHMEAT_DRIED = "鱼干"
STRINGS.SMALLFISHMEAT_DRIED = "小鱼干"

STRINGS.WIXIEGUN =
"格洛克17（HD版中的贝雷塔92FS），也称为9mm手枪，是《半条命》及其扩展包中的一种武器。"

STRINGS.UM_MAXWELL_ARMOR_SANITY = "魔术师的暗夜甲"
STRINGS.UM_MAXWELL_NIGHTSWORD = "魔术师的暗夜剑"
STRINGS.PACT_ARMOR_SANITY = "暗夜契约甲"
STRINGS.PACT_SWORD_SANITY = "暗夜契约剑"
------------------------

STRINGS.WINONA_CATAPULT_ITEM = "拆除" .. STRINGS.WINONA_CATAPULT
STRINGS.WINONA_SPOTLIGHT_ITEM = "打包" .. STRINGS.WINONA_SPOTLIGHT
STRINGS.WINONA_BATTERY_LOW_ITEM = "分解" .. STRINGS.WINONA_BATTERY_LOW
STRINGS.WINONA_BATTERY_HIGH_ITEM = STRINGS.WINONA_BATTERY_HIGH .. "拆散"

STRINGS.STAFF_STARFALL = "星陨法杖"
STRINGS.STAFF_MOONFALL = "月陨法杖"
STRINGS.MOONFALL_PROJ = "流星"
STRINGS.HAT_CRAB = "蟹王冠"
STRINGS.HAT_CRAB_ICE = "严寒皇冠"
STRINGS.KALEIDOSCOPE = "万花筒"
STRINGS.MOONGLOW = "月光"
STRINGS.ARMOR_CRAB_MAXHP = "镶玉盔甲"
STRINGS.ARMOR_CRAB_REGEN = "治愈岩甲"
STRINGS.MOON_BEACON_KIT = "不活跃的月亮信标"
STRINGS.MOON_BEACON = "月亮信标"

STRINGS.MARA_BOSS1 = "《传说之下》中的Sans，来自热门系列《任天堂明星大乱斗》（以《我的世界》Steve为特色）[& Knuckles]"
STRINGS.MARA_BOSS1_BULLETS = "糟糕的时间"
STRINGS.UM_WITCH = "至尊女巫 · 灾厄"

-- Pyre Nettle stuff
STRINGS.UM_PYRE_NETTLES = "荨麻丛"
STRINGS.UM_SMOLDER_SPORE = "荨麻孢子"
STRINGS.UM_ARMOR_PYRE_NETTLES = "荨麻斗篷"
STRINGS.UM_BLOWDART_PYRE = "荨麻飞镖"

-- Mutation Extrapolation
STRINGS.UMDEBUFF_MOONBURN = "月光灼伤"
STRINGS.UMDEBUFF_MOONBURN_TESTINGSTICK = "魔法止痛棒"

-- Under the Weather Part 1
STRINGS.ALPHA_LIGHTNINGGOAT = "伏特头羊"
STRINGS.UM_TORNADO = "巨型龙卷风"
STRINGS.UM_WATERFALL = "瀑布"
STRINGS.PORTABLEBOAT = "气垫船套装"

STRINGS.UM_WINDTURBINE = "风力照明灯"
STRINGS.MASTUPGRADE_WINDTURBINE = "风力照明灯"

STRINGS.GARBAGEPATCHFLOTSAM = "风暴碎片"

STRINGS.PIGKING_PIGGUARD = STRINGS.PIGGUARD

STRINGS.UM_BOAT_ENGINE = "淤泥引擎"
STRINGS.SMOG = "窒息"

------------------------
-- Broiling Hills --
------------------------
STRINGS.SNAILDRAKE_EXPLOSION = "蜗龙爆炸"
STRINGS.SNAILDRAKE_HOLE = "裂缝"
STRINGS.SNAILDRAKE_MAGMA = "蜗龙"
STRINGS.SNAILDRAKE_SLIME = "蜗龙"
STRINGS.SNAILDRAKE_MAGMA_SLUDGE = "岩浆黏液"
STRINGS.SNAPALM = "爆燃黏液"
STRINGS.SNAILDRAKEHAT = "蜗龙角盔"
STRINGS.SNAILDRAKEBUCKET = "蜗龙盆"

------------------------
-- Magma Caves --
------------------------
STRINGS.MUSHTREE_SHADOW = "幽暗蘑菇"
STRINGS.GLOOMCAP = "幽暗蘑菇"
STRINGS.GLOOMCAP_COOKED = "熟幽暗蘑菇"
STRINGS.SPORE_SHADOW = "幽暗孢子"
STRINGS.VIPERWORM = "洞穴恶蛇"
STRINGS.VIPERLING = "蠕动暗影"
STRINGS.VIPERLINGFRIEND = "蠕动暗影"
STRINGS.VIPERFRUIT = "幽暗浆果"
STRINGS.VIPERFRUIT_LESSER = "小幽暗浆果"
STRINGS.VIPERJAM = "幽暗果酱"
STRINGS.VIPERFRUIT_PLANT = "不祥植物"
STRINGS.UM_GHOST_PEPPER = "褪色藤蔓"
STRINGS.UM_GHOST_PEPPER_ITEM = "幽灵辣椒"
------------------------
-- Rimeweed --
------------------------
STRINGS.RIMEWEED_MAIN = "尖刺霜草"
STRINGS.RIMEWEED_BARRIER = "霜草荆棘"
STRINGS.RIMEWEED_WHIP = "霜鞭"
STRINGS.UM_RIMEWEED_ITEMFLOWER = "霜花"
STRINGS.UM_RIMEWEED_ITEMVINE = "霜冻藤蔓"
STRINGS.UM_RIMEWEED_SPAGETT = "霜冻意面"
STRINGS.UM_RIMEWEED_TEQUILA = "冰镇龙舌兰"
STRINGS.UM_RIMEWEED_ICEPACK = "冰袋"
STRINGS.UM_BLOWDART_RIME = "霜镖"
STRINGS.UM_ARMOR_BRAMBLE_RIMEWEED = "霜冻外壳"
STRINGS.UM_HAT_RIME = "霜兽头盔"
STRINGS.UM_ICE_TAIL = "冰冻鼹鼠尾"

STRINGS.UM_DURIAN_CREAM_MARSHCAKE = "榴莲奶油软糖蛋糕"
STRINGS.UM_CHILES_EN_NOGADA = "三色酿椒"
STRINGS.UM_RICE_PUDDING = "米布丁"
STRINGS.UM_KEBAB = "无骨烤串"


STRINGS.UM_COOKPOT_WAGSTAFF = "锅-800"
STRINGS.UM_COOKPOT_WAGSTAFF_DISPLAY = "引人注目的显示器"
STRINGS.UM_COOKPOT_WAGSTAFF_LEVER = "简陋的杠杆"
STRINGS.UM_COOKPOT_WAGSTAFF_LEVER2 = "破旧的杠杆"

STRINGS.STAFF_TORNADO_LIGHTNING = "强化气象之痛"
STRINGS.RNEHOUND = "暗影猎犬"

STRINGS.JAWED_SCYTHE = "颚镰"
STRINGS.UM_ICE_SICLE = "冰镰"
STRINGS.SNAPPY_JAW = "利颚"
STRINGS.UM_BOATBOTTLE = "船瓶"
STRINGS.BOAT_ANCIENT_ITEM_BLUEPRINT = "远古船套件蓝图"
STRINGS.UM_BUTTERY_FLY = "黄油飞蝶"
STRINGS.UM_HAT_LEAFWING = "转瞬即逝的叶冠"
STRINGS.UM_LEAFWING = "叶翼"
STRINGS.UM_DETONATOR = "万能引爆器"

STRINGS.UM_BEE_MOON = "腐臭蜂"
STRINGS.UM_BEEHIVE_MOON = "腐臭蜂巢"
STRINGS.UM_MEATCOMB = "腐臭蜂巢"
STRINGS.UM_MEATHONEY = "腐臭蜂蜜"

STRINGS.FYRITEROCK = "黄铁矿矿簇"
STRINGS.UM_FYRITE = "黄铁矿"
STRINGS.UM_FYRE_BOMB = "高爆弹"
STRINGS.UM_MANNY = "普劳特·曼尼"

STRINGS.UM_HAT_BEE_MOON = "蜂帽"
STRINGS.UM_EYEBALM = "眼霜"
STRINGS.UM_BEEMINE_MOON = "腐臭蜂地雷"
STRINGS.UM_BEEMINE_MOON_ITEM = "腐臭蜂地雷"

STRINGS.UM_PLANT_HOTSPRINGS = "植物"
STRINGS.UM_PEPPERDRAGON_NEST = "椒龙巢"

STRINGS.UM_GHOST_FAJITA = "恐怖卷饼"
STRINGS.UM_BOOM_TART = "爆汁蓝莓挞"
STRINGS.UM_RIBOPOD = "肋荚虫"
STRINGS.UM_RIBOPODDEN = "骸骨堆"

STRINGS.UM_GEMOLOGYGEM_UNKNOWN = "奇异宝石"

STRINGS.UM_GEMOLOGYGEM_PREFIX = {
    "碎裂的",
    "微瑕的",
    "无暇的"
}

STRINGS.UM_GEMOLOGYBLUEGEM1 = "极地海蓝宝石"
STRINGS.UM_GEMOLOGYBLUEGEM2 = "冰鲜蓝宝石"
STRINGS.UM_GEMOLOGYREDGEM1 = "贪噬红宝石"
STRINGS.UM_GEMOLOGYREDGEM2 = "炽烈石榴石"
STRINGS.UM_GEMOLOGYPURPLEGEM1 = "狂怒萤石"
STRINGS.UM_GEMOLOGYPURPLEGEM2 = "奥术紫水晶"
STRINGS.UM_GEMOLOGYYELLOWGEM1 = "迅疾黄玉"
STRINGS.UM_GEMOLOGYYELLOWGEM2 = "静电琥珀"
STRINGS.UM_GEMOLOGYGREENGEM1 = "躁动橄榄石"
STRINGS.UM_GEMOLOGYGREENGEM2 = "混沌祖母绿"
STRINGS.UM_GEMOLOGYORANGEGEM1 = "惬意锆石"
STRINGS.UM_GEMOLOGYORANGEGEM2 = "珍藏黄水晶"
STRINGS.UM_GEMOLOGYPALEGEM1 = "绝世翡翠"
STRINGS.UM_GEMOLOGYPALEGEM2 = "坚钢钻石"
STRINGS.UM_GEMOLOGYFORGE = "宝石学锻造台"

STRINGS.GEMTOOL_PREFIX = {
    UM_GEMOLOGYGREENGEM1 = "躁动",
    UM_GEMOLOGYGREENGEM2 = "混沌",
    UM_GEMOLOGYYELLOWGEM1 = "迅疾",
    UM_GEMOLOGYYELLOWGEM2 = "静电",
    UM_GEMOLOGYPALEGEM1 = "绝世",
    UM_GEMOLOGYPALEGEM2 = "坚钢",
    UM_GEMOLOGYREDGEM1 = "贪噬红",
    UM_GEMOLOGYREDGEM2 = "炽烈",
    UM_GEMOLOGYPURPLEGEM1 = "狂怒",
    UM_GEMOLOGYPURPLEGEM2 = "奥术", 
    UM_GEMOLOGYORANGEGEM1 = "惬意",
    UM_GEMOLOGYORANGEGEM2 = "珍藏",
    UM_GEMOLOGYBLUEGEM1 = "极地",
    UM_GEMOLOGYBLUEGEM2 = "冰鲜",
}

STRINGS.WATHOM_CORPSE = "沃托姆的甲壳"

STRINGS.UM_SPONGEPLANT = "多孔海绵"
STRINGS.UM_SPONGEPLANT_ITEM = "多孔海绵块"
STRINGS.UM_SPONGE_CAKE = "多孔海绵蛋糕"

STRINGS.UM_MOSS = "连帽苔藓"

STRINGS.WATHGRITHR_SHIELD_DREADSTONE = "绝望石圆盾"
STRINGS.UM_FERN_FOX = "蕨狐"

STRINGS.UM_PEPPERDRAGON = "椒龙"
STRINGS.UM_PEPPERDRAGON_BLADDER = "储火袋"
STRINGS.UM_FLAMETHROWER = "爆焰喷射器"
STRINGS.UM_FIRECREAM = "防火霜"
STRINGS.UM_HAT_PEPPERDRAGON = "冷热逆转帽"

STRINGS.UM_GEMOLOGY_GEODE_RED = "红色菌类晶洞"
STRINGS.UM_GEMOLOGY_GEODE_GREEN = "绿色菌类晶洞"
STRINGS.UM_GEMOLOGY_GEODE_BLUE = "蓝色菌类晶洞"
STRINGS.UM_GEMOLOGY_GEODE_GUANO = "粪便晶洞"
STRINGS.UM_GEMOLOGY_GEODE_LOBSTER = "胚胎晶洞"
STRINGS.UM_GEMOLOGY_GEODE_GLASS = "玻璃晶洞"
STRINGS.UM_GEMOLOGY_GEODE_SLIME = "黏液晶洞"
STRINGS.UM_GEMOLOGY_GEODE_RUINS = "垃圾晶洞"


STRINGS.UM_BOOMBERRY_BOMB = "爆汁蓝莓炸弹"
STRINGS.UM_BOOMBERRYPIE = "爆汁蓝莓派"

STRINGS.UM_REDMUSHTREE_GEM = "石化蘑菇树"
STRINGS.UM_REDMUSHTREE_GEMLESS = "石化蘑菇树"
STRINGS.UM_GREENMUSHTREE_GEM = "石化蘑菇树"
STRINGS.UM_GREENMUSHTREE_GEMLESS = "石化蘑菇树"
STRINGS.UM_BLUEMUSHTREE_GEM = "石化蘑菇树"
STRINGS.UM_BLUEMUSHTREE_GEMLESS = "石化蘑菇树"

STRINGS.UM_GUANO_ROCK = "鸟粪石"
STRINGS.UM_ROCKLOBSTER_ROCK = "孵化石"
STRINGS.GLACIALHOUND_ICESPIKE = "冰刺"
STRINGS.UM_FEATHER_TOTEM = "羽毛图腾"
STRINGS.UM_MAGNIFIER = "宝石放大镜"