SKINS = GLOBAL.STRINGS.SKIN_NAMES
SKINSDESC = GLOBAL.STRINGS.SKIN_DESCRIPTIONS
NAMES = GLOBAL.STRINGS.NAMES
UI = GLOBAL.STRINGS.UI


--Re-names to existing items
NAMES.AMULET = "次级生命护身符"
NAMES.BEESWAX = "蜡"



-------------------------------------------------- Strings

NAMES.CREEPINGFEAR = "潜伏恐惧"
NAMES.DREADEYE = "恐惧之眼"

NAMES.UNCOMPROMISING_RAT = "老鼠" -- Maybe change the name with a pun with Robber or Raider, any idea ?
NAMES.UNCOMPROMISING_CAVERAT = "穴居鼠" -- The aggressive cousin
NAMES.UNCOMPROMISING_PACKRAT = "背包鼠" -- The hoarding cousin
NAMES.UNCOMPROMISING_RATHERD = "鼠群"
NAMES.UNCOMPROMISING_RATBURROW = "鼠穴"
NAMES.UNCOMPROMISING_WINKYBURROW = "温奇的鼠穴"
NAMES.UNCOMPROMISING_WINKYBURROW_MASTER = "温奇的鼠穴"
NAMES.UNCOMPROMISING_WINKYHOMEBURROW = "温奇的定居鼠穴"
NAMES.PIED_RAT = "花衣吹笛者"
NAMES.PIED_PIPER_FLUTE = "鼠笛"
NAMES.GASMASK = "鹅毛面具"
NAMES.WATER = "雨水"
NAMES.RAIN = "雨水"
NAMES.SPORECLOUD_TOAD = "孢子云"
NAMES.MOCK_DRAGONFLY = "时令龙蝇"
NAMES.UM_SAND = "沙子"
NAMES.UM_SANDHILL = "沙堆"
NAMES.SNOWPILE = "雪堆"
NAMES.SNOWGOGGLES = "猫眼护目镜"
NAMES.UM_SPIDERQUEENCORPSE = "蜘蛛女王尸体"
NAMES.RATPOISON = "毒果酱陷阱"
NAMES.RATPOISONBOTTLE = "毒果酱"
NAMES.LEECHSWARM = "花粉螨"
NAMES.LAITLEECH = "水蛭群"
NAMES.SHOCKWORM = "洞穴电鳗"


NAMES.ZASPBERRY = "电光浆果"
NAMES.ZASPBERRY_LESSER = "小电光浆果"
NAMES.ZASPBERRY_PLANT = "可疑植物"

NAMES.SNOWMONG = "雪怪"
NAMES.MINOTAUR_BOULDER = "远古石板"
NAMES.MINOTAUR_BOULDER_BIG = "巨型远古石板"
NAMES.MINOTAUR_ORGAN = "暗影心脏"
NAMES.MOCK_DRAGONFLY = "时令龙蝇"

NAMES.MOONMAW_DRAGONFLY = "月光龙蝇"
NAMES.MOONMAW_GLASS = "不稳定的玻璃块"
NAMES.MOONMAW_LAVAE = "玻璃岩浆虫"
NAMES.MOONMAW_LAVAE_RING = NAMES.MOONMAW_LAVAE
NAMES.GLASS_SCALES = "启迪鳞片"
NAMES.MOONGLASS_GEODE = "注能的玻璃碎片"
NAMES.ARMOR_GLASSMAIL = "月鳞甲"
NAMES.ARMOR_GLASSMAIL_SHARDS = "玻璃碎片"
NAMES.MOONMAW_TRAP = NAMES.ALTERGUARDIAN_PHASE3TRAP

NAMES.LAVAE2 = NAMES.LAVAE
NAMES.BUSHCRAB = "灌木丛蟹"
NAMES.ICEBOOMERANG = "冰冻回旋镖"
NAMES.TOADLING = "蘑菇蟾蜍"
NAMES.UNCOMPROMISING_TOAD = "多病青蛙"
NAMES.DISEASECUREBOMB = "月油"
NAMES.TOADLINGSPAWNER = "蟾蜍孢子"
-- NAMES.NAMES.TOAD  = "Sickly Toad"
NAMES.MONSTERSMALLMEAT = "小怪物肉"
NAMES.COOKEDMONSTERSMALLMEAT = "烤小怪物肉"
NAMES.MONSTERSMALLMEAT_DRIED = "小怪物肉干"
NAMES.UM_MONSTEREGG = "怪物蛋"
NAMES.UM_MONSTEREGG_COOKED = "熟怪物蛋"
NAMES.VETERANSHRINE = "头骨洞窟"

NAMES.WILSON_VETSKULL = "威尔逊的头骨"
NAMES.WALTER_VETSKULL = "沃尔特的头骨"
NAMES.WORTOX_VETSKULL = "沃拓克斯的头骨"
NAMES.MAXWELL_VETSKULL = "麦斯威尔的头骨"
NAMES.WILLOW_VETSKULL = "薇洛的头骨"
NAMES.WARLY_VETSKULL = "沃利的头骨"
NAMES.WINKY_VETSKULL = "温奇的头骨"
NAMES.WICKERBOTTOM_VETSKULL = "薇克巴顿的头骨"
NAMES.WIXIE_VETSKULL = "薇希的头骨"
NAMES.WOODIE_VETSKULL = "伍迪的头骨"
NAMES.WOLFGANG_VETSKULL = "沃尔夫冈的头骨"
NAMES.WANDA_VETSKULL = "旺达的头骨"
NAMES.WATHGRITHR_VETSKULL = "薇格弗德的头骨"
NAMES.WES_VETSKULL = "韦斯的头骨"
NAMES.WENDY_VETSKULL = "温蒂的头骨"

NAMES.UM_SHADOW_WALTER = "沃尔特？"
NAMES.UM_SHADOW_WORTOX = "沃拓克斯？"
NAMES.UM_SHADOW_MAXWELL = "麦斯威尔？"
NAMES.UM_SHADOW_WILLOW = "薇洛？"
NAMES.UM_SHADOW_WARLY = "沃利？"
NAMES.UM_SHADOW_WINKY = "温奇？"
NAMES.UM_SHADOW_WICKERBOTTOM = "薇克巴顿？"
NAMES.UM_SHADOW_WOODIE = "伍迪？"
NAMES.UM_SHADOW_WOLFGANG = "沃尔夫冈？"
NAMES.UM_SHADOW_WANDA = "旺达？"
NAMES.UM_SHADOW_WATHGRITHR = "薇格弗德？"
NAMES.UM_SHADOW_WES = "韦斯？"
NAMES.UM_SHADOW_WENDY = "温蒂？"

NAMES.UM_BOSS_SOUL = "暗影之魂"
NAMES.UM_DARK_VESTIGES = "暗影残迹"
NAMES.EXPLOSIVE_VETCURSE_SOUL = "爆裂灵魂"

NAMES.UM_CHERRY_BEEQUEEN_SOUL = "樱桃蜂后灵魂"
NAMES.UM_BEEQUEEN_SOUL = "蜂后灵魂"
NAMES.UM_BEARGER_SOUL = "熊獾灵魂"
NAMES.UM_DEERCLOPS_SOUL = "巨鹿灵魂"
NAMES.UM_CRABKING_SOUL = "帝王蟹灵魂"
NAMES.UM_MINOTAUR_SOUL = "远古守护者灵魂"
NAMES.UM_DRAGONFLY_SOUL = "龙蝇灵魂"
NAMES.UM_GOOSE_SOUL = "麋鹿鹅灵魂"
NAMES.UM_HOODEDWIDOW_SOUL = "黑寡妇灵魂"
NAMES.UM_KLAUS_SOUL = "克劳斯灵魂"
NAMES.UM_FUELWEAVER_SOUL = "远古织影者灵魂"
NAMES.UM_MALBATROSS_SOUL = "邪天翁灵魂"
NAMES.UM_MOONMAW_SOUL = "月亮龙蝇灵魂"

NAMES.UM_RECORD_MENU = "永不妥协乐章"
NAMES.UM_RECORD_WALTER = "跟我来，沃比！"
NAMES.UM_RECORD_WIXIE = "叛逆顽童"
NAMES.UM_RECORD_SHADOW_WIXIE = "幽暗本心"
NAMES.UM_RECORD_HOODED_WIDOW = "恐蛛之音"
NAMES.UM_RECORD_WATHOM = "心脏骤停！"
NAMES.UM_RECORD_STRANGER = "神秘过客"
NAMES.UM_RECORD_WINKY = "趣致小鼠"
NAMES.UM_RECORD_MOONMAW = "飞蛾扑火"
NAMES.UM_RECORD_TOT = "双生狂乱"

NAMES.RATSKIN = "鼠皮"

NAMES.PLAGUEMASK = "瘟疫面具"
SKINS.ms_hat_plaguemask_formal = "瘟疫面具"
SKINSDESC.ms_hat_plaguemask_formal = "一个在腐烂的世界中脱颖而出的精美面具。"

SKINS.wormwood_shadow = "堕落者" -- personal vendetta, bruh that shit aint 'triumphant'

NAMES.TRAPDOOR = "不起眼的土丘"
NAMES.SPIDER_TRAPDOOR = "地穴蜘蛛"
NAMES.SPIDER_TRAPDOOR_HOODED = "黑寡妇"
NAMES.MUTATOR_TRAPDOOR = "地穴变身涂鸦"
NAMES.DECIDUOUS_ROOT = "活木树根"
NAMES.LAVAESLIME = "岩浆虫黏液"
NAMES.SALTPACK = "盐瓶3000"
NAMES.SPOREPACK = "蟾蜍背包"
NAMES.UM_BACKPACK_AMULETUSE = "Amusement Pack"
NAMES.RAT_TAIL = "鼠尾"
NAMES.SHROOM_SKIN_FRAGMENT = "蘑菇皮碎片"
NAMES.AIR_CONDITIONER = "空调" -- <--
NAMES.MINI_DREADEYE = "暗影之眼"
NAMES.SHADOW_GOO = "暗影墨水"

NAMES.ROCK_LICHEN = "大理石地衣"
NAMES.SPRINGROCK1 = "岩石"
NAMES.SPRINGROCK2 = "岩石"
NAMES.SPRINGROCK3 = "岩石"

NAMES.CAVE_ENTRANCE_MAGMABIOME = "岩石"
NAMES.CAVE_ENTRANCE_OPEN_MAGMABIOME = "温暖洞穴"
NAMES.CAVE_EXIT_MAGMABIOME = "湿热楼梯"
NAMES.LAVA_POND_CAVE = "熔岩池"
NAMES.MAGMAROCK1 = "岩石"
NAMES.MAGMABONE = "骸骨"

NAMES.BOULDER_CRAB = "岩石蟹"
NAMES.BOULDER_CRAB_HOLE = "岩石蟹洞穴"
NAMES.UM_HOTSPRING = "沸腾温泉"
NAMES.VAMPIREBAT = "巨型蝙蝠"
NAMES.WICKER_TENTACLE = "多病触手"
NAMES.SKELETONMEAT = "长猪肉干"
NAMES.ZASPBERRYPARFAIT = "电光浆果芭菲"
NAMES.CARAPACECOOLER = "甲壳冷却器"
NAMES.HONEY_LOG = "蜂蜜原木卷"
NAMES.RNEGHOST = "游魂"
NAMES.CHIMP = "猴子"
NAMES.BUGZAPPER = "电蚊拍"
NAMES.RICE1 = "稻米"
NAMES.RICE2 = "稻米"
NAMES.RICE_COOKED1 = "烤稻米"
NAMES.RICE_COOKED2 = "烤稻米"
NAMES.RICEPLANT1 = "水稻"
NAMES.RICEPLANT2 = "水稻"
NAMES.SEAFOODPAELLA = "海鲜饭"
NAMES.SWILSON = "威尔逊？"
NAMES.SWATHGRITHR = "薇格弗德？"
NAMES.MOTHERGOOSE1 = "麋鹿鹅妈妈"
NAMES.MOTHERGOOSE2 = "麋鹿鹅妈妈"
NAMES.CRITTERLAB_REAL = "岩石巢穴"
NAMES.CRITTERLAB_REAL_BROKEN = "破碎的岩石巢穴"
NAMES.POLLENMITES = "花粉螨"
NAMES.POLLENMITEDEN = "花粉螨巢穴"
NAMES.WALRUS_CAMP_SUMMER = NAMES.WALRUS_CAMP
NAMES.SUNGLASSES = "太阳镜"
NAMES.CHARLIEPHONOGRAPH_100 = "留声机"
NAMES.STUMPLING = "松树树桩怪"
NAMES.BIRCHLING = "桦树树桩怪"
NAMES.LICELOAF1 = "米花糖"
NAMES.LICELOAF1 = "米花糖"
NAMES.MOON_TEAR = "月泪"
NAMES.SHADOW_TELEPORTER = "暗影爪"
NAMES.WAXWELL_PACT_TRADER = "契约之手"

NAMES.SHADOW_CROWN = "暗影王冠"
NAMES.UM_SHADOW_AXE = "幽暗斧"
NAMES.CALIFORNIAKING = "加州辣汤"
NAMES.TRAPDOORGRASS = "茂密草丛"
NAMES.LUREPLAGUE_RAT = "腐败鼠"
NAMES.SNAPPERTURTLE = "乌龟"
NAMES.SNAPPERTURTLEBABY = "乌龟宝宝"
NAMES.SNAPPERTURTLENEST = "乌龟巢穴"

NAMES.CURSED_ANTLER = "诅咒鹿角"
SKINS.ms_twisted_antler = "扭曲鹿角"
SKINSDESC.ms_twisted_antler = "扭曲鹿角，给扭曲的人。"

NAMES.CRYSTAL_CURSED_ANTLER = "Crystal Cursed Antler"

NAMES.UM_EXHUMER = "掘墓铲"
NAMES.UM_WINGSUIT = "翼装服"
NAMES.UM_MOONFLY_LANTERN = "月蝇提灯"

NAMES.MARSH_GRASS = "沼泽灌木"
NAMES.GIANT_TREE = "巨型红杉"
NAMES.WEBBEDCREATURE = "茧"
NAMES.WIDOWSGRASP = "寡妇之爪"
NAMES.HOODEDWIDOW = "黑寡妇"
NAMES.SILKSACK = "蛛丝背包"
NAMES.SILKEN_BUNDLE = "蛛丝捆绑物资"


NAMES.WEBBEDCREATURE_BUGGY = "虫茧"
NAMES.WEBBEDCREATURE_GROSS = "怪诞虫茧"
NAMES.WEBBEDCREATURE_HAIRY = "多毛虫茧"
NAMES.WEBBEDCREATURE_HARD = "硬化虫茧"
NAMES.WEBBEDCREATURE_LEATHER = "粗糙虫茧"
NAMES.WEBBEDCREATURE_FEATHER = "轻软虫茧"
NAMES.WEBBEDCREATURE_LEAFY = "带叶虫茧"

NAMES.GIANT_BLUEBERRY = "爆汁蓝莓"
NAMES.BLUEBERRYPLANT = "爆汁蓝莓植株"
NAMES.BLUEBERRYFLOWER = "爆汁蓝莓花"
NAMES.HOODEDTRAPDOOR = "活动石板"
NAMES.HOODED_FERN = "高齿蕨"
NAMES.FALLINGBEEHIVE = NAMES.BEEHIVE
NAMES.FRUITBAT = "果蝠"
NAMES.PITCHERPLANT = "猪笼草"

NAMES.DEPLETED_HOODED_FERN = "大型蕨"
NAMES.APHID = "蚜虫"
NAMES.NYMPH = "若虫"
NAMES.WIDOWSHEAD = "寡妇之颅"
NAMES.CCTRINKET_DON = "撕破的书"
NAMES.CCTRINKET_JAZZY = "生锈的萨克斯"
NAMES.CCTRINKET_FREDDO = "破损的磁带"
NAMES.CCTRINKET_NAMES = "必要标签"

NAMES.BLUEBERRYPANCAKES = "爆汁蓝莓薄饼"
NAMES.DEVILSFRUITCAKE = "恶魔水果蛋糕"
NAMES.SIMPSALAD = "简单沙拉"
NAMES.BEEFALOWINGS = "牛角派"
NAMES.PINEPILE = "树枝堆"
NAMES.HOODED_MUSHTREE_TALL = NAMES.MUSHTREE_TALL
NAMES.HOODED_MUSHTREE_MEDIUM = NAMES.MUSHTREE_MEDIUM
NAMES.HOODED_MUSHTREE_SMALL = NAMES.MUSHTREE_SMALL
NAMES.SCREECHER_TRINKET = "蝙蝠玩偶"
NAMES.SNOWCONE = "冰沙"
NAMES.CINNAMON_TREE = "肉桂树"
NAMES.CINNAMON_TREE_BURNT = "肉桂树"
NAMES.CINNAMON_TREE_STUMP = "肉桂树"
NAMES.WATERMELON_LANTERN = "西瓜灯"
NAMES.ANCIENT_TREPIDATION = "恐怖巨蛛"
NAMES.ANCIENT_TREPIDATION_ARM = "巨蛛之爪"
NAMES.STEEL_SWEATER = "钢制毛衣"
NAMES.RNESKELETON = "骷髅士兵"

NAMES.ANCIENT_AMULET_RED = "唤灵护符"
SKINS.ms_ancient_amulet_red_demoneye = "魔眼护符"
SKINSDESC.ms_ancient_amulet_red = "" -- TODO

NAMES.RAT_WHIP = "绞尾鼠鞭"
NAMES.KLAUS_AMULET = "无锁"
NAMES.HOUND_LIGHTNING = "超级闪电"
NAMES.LIGHTNINGHOUND = "闪电猎犬"
NAMES.MAGMAHOUND = "熔岩青年座狼"
NAMES.SPOREHOUND = "孢子猎犬"
NAMES.GLACIALHOUND = "冰川青年座狼"
NAMES.CRABCLAW = "诅咒蟹钳"
NAMES.BIGHT = "超载奇械"
NAMES.KNOOK = "自走噩兆"
NAMES.ROSHIP = "啮合巨炮"
NAMES.SNOTROAST = "象鼻大餐"
NAMES.LICELOAF = "米花糖" -- For the cookbook

NAMES.TURF_HOODEDMOSS = "连帽森林地皮"
NAMES.TURF_HOODEDFOLIAGE = "林下地皮"
NAMES.TURF_HOODEDFOLIAGE_DARK = "阴暗林下地皮"

NAMES.TURF_ANCIENTHOODEDTURF = "远古连帽地皮"
NAMES.TURF_UM_HOTSPRING_GRASS = "泥泞森林地皮"
NAMES.TURF_UM_HOTSPRING_YELLOWROCK = "黄色岩石地皮"
NAMES.TURF_UM_HOTSPRING_WHITEROCK = "白色岩石地皮"
NAMES.TURF_UM_MAGMA = "熔岩岩石地皮"
NAMES.TURF_MAGMA_GRASS = "火堆草地皮"

NAMES.DEERCLOPS_BARRIER = "冰墙"
NAMES.PIGKING_PIGTORCH = NAMES.PIGTORCH
NAMES.UM_PAWN = "发条蟹兵"
NAMES.UM_PAWN_NIGHTMARE = "损坏的发条蟹兵"
NAMES.CAVE_ENTRANCE_SUNKDECID = NAMES.CAVE_ENTRANCE
NAMES.CAVE_ENTRANCE_OPEN_SUNKDECID = NAMES.CAVE_ENTRANCE_OPEN
NAMES.CAVE_EXIT_SUNKDECID = NAMES.CAVE_EXIT
NAMES.CAVE_ENTRANCE_MOON = NAMES.CAVE_ENTRANCE
NAMES.CAVE_ENTRANCE_OPEN_MOON = NAMES.CAVE_ENTRANCE_OPEN
NAMES.CAVE_EXIT_MOON = NAMES.CAVE_EXIT
NAMES.GORE_HORN_HAT = "犀牛帽"
NAMES.SLOBBERLOBBER = "熔岩口器"
NAMES.BEARGERCLAW = "诅咒熊爪"
NAMES.UM_LAVASPIT_SLOBBER = NAMES.LAVASPIT
NAMES.WOODPECKER = "啄木鸟"
NAMES.UM_BEAR_TRAP = "利颚陷阱"
NAMES.UM_BEAR_TRAP_OLD = "利颚陷阱"
NAMES.MOTHERMOSSLING = NAMES.MOSSLING
NAMES.MOTHERMOOSEEGG1 = "金麋鹿蛋"
NAMES.MOTHERMOOSEEGG2 = "金鹅蛋"
NAMES.CORNCAN = "玉米罐头"
NAMES.SKULLCHEST_CHILD = "骷髅箱"
NAMES.SKULLCHEST = "骷髅箱"
NAMES.GREENFOLIAGE = "森林蕨叶" -- Well, I guess I did this then...

NAMES.FEATHER_FROCK = "羽毛长袍"
SKINS.ms_feATHER_FROCK_FANCY = "乌鸦披风"
SKINSDESC.ms_FEATHER_FROCK_FANCY = "用最好的羽毛制成的华丽斗篷。"

NAMES.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "捕兽夹"
NAMES.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "黄金捕兽夹"
NAMES.DRIFTWOODFISHINGROD = "浮木钓杆"

NAMES.REDGEM_CRACKED = "破碎的红宝石"
NAMES.BLUEGEM_CRACKED = "破碎的蓝宝石"
NAMES.ORANGEGEM_CRACKED = "破碎的橙宝石"
NAMES.GREENGEM_CRACKED = "破碎的绿宝石"
NAMES.YELLOWGEM_CRACKED = "破碎的黄宝石"
NAMES.PURPLEGEM_CRACKED = "破碎的紫宝石"
NAMES.OPALPRECIOUSGEM_CRACKED = "破碎的彩虹宝石"
NAMES.RED_MUSHED_ROOM = "红蘑菇糊糊"
NAMES.GREEN_MUSHED_ROOM = "绿蘑菇糊糊"
NAMES.BLUE_MUSHED_ROOM = "蓝蘑菇糊糊"

-- Stanton's Stash
NAMES.STANTON_SHADOW_TONIC = "暗影气泡酒"
NAMES.STANTON_SHADOW_TONIC2 = NAMES.STANTON_SHADOW_TONIC
NAMES.STANTON = "骷髅克里"
NAMES.SKULLFLASK = "头骨酒瓶"
NAMES.SKULLFLASK_EMPTY = "空头骨酒瓶"
-- Stanton's Stash

NAMES.THEATERCORN = "玉米杯"
NAMES.ARMORLAVAE = "友好的岩浆虫"
NAMES.WIDOW_WEB_COMBAT = "蛛网粘液"

NAMES.BOOK_RAIN_UM = "雨日手记"

NAMES.RAIN_HORN = "唤雨海螺"
NAMES.FLORAL_BANDAGE = "夏花绷带"
NAMES.DORMANT_RAIN_HORN = "休眠海螺"

NAMES.NIGHTCRAWLER = "梦游者"
NAMES.UM_NIGHTCRAWLER = "暗影爬虫"
NAMES.RNE_GRABBYSHADOWS = "暗影吊手"
NAMES.NERVOUSTICK = "神经蜱"
NAMES.NERVOUSTICKDEN = "虫群心脏"
NAMES.FUELSEEKER = "燃料搜寻器"
NAMES.MINDWEAVER = "心灵编织者"
NAMES.UM_HECKLER = "斯皮茨女士"

NAMES.RNEMUSHROOMBOMB = "爆菇"

NAMES.HAT_BAGMASK = "纸袋"
NAMES.HAT_BLACKCATMASK = "黑猫面具"
NAMES.HAT_CLOWNMASK = "小丑面具"
NAMES.HAT_WATHOMMASK = "怪物面具"
NAMES.HAT_DEVILMASK = "红面恶魔面具"
NAMES.HAT_FIENDMASK = "紫面恶魔面具"
NAMES.HAT_GHOSTMASK = "橙眼鬼魂面具"
NAMES.HAT_GLOBMASK = "绿水鬼面具"
NAMES.HAT_HOCKEYMASK = "撕裂面具"
NAMES.HAT_JOYOUSMASK = "大笑面具"
NAMES.HAT_MERMMASK = "鱼人面具"
NAMES.HAT_OOZEMASK = "紫水鬼面具"
NAMES.HAT_ORANGECATMASK = "黄猫面具"
NAMES.HAT_PHANTOMMASK = "紫眼鬼魂面具"
NAMES.HAT_PIGMASK = "猪人面具"
NAMES.HAT_PUMPGOREMASK = "南瓜面具"
NAMES.HAT_REDSKULLMASK = "红骷髅面具"
NAMES.HAT_SKULLMASK = "白骷髅面具"
NAMES.HAT_SPECTREMASK = "青眼鬼魂面具"
NAMES.HAT_WHITECATMASK = "白猫面具"
NAMES.HAT_TECHNOMASK = "机械面具"
NAMES.HAT_MANDRAKEMASK = "蔓草面具"
NAMES.HAT_OPOSSUMMASK = "负鼠面具"
NAMES.RNE_GOODIEBAG = "零食袋"
NAMES.HAT_RATMASK = "老鼠面具"

NAMES.OCULET = "双子护符"
NAMES.OCULET_REZ = "激光眼宠物"
NAMES.OCULET_SPAZ = "魔焰眼宠物"
NAMES.WILLIAM = "威廉"

-- Under the Weather--
NAMES.UNCOMPROMISING_HARPOON = "鱼叉"
NAMES.UNCOMPROMISING_HARPOON_HEAVY = "重型鱼叉"
NAMES.UNCOMPROMISING_HARPOONREEL = "卷轴"
NAMES.UM_MAGNERANG = "磁力回旋镖"
NAMES.UM_MAGNERANGREEL = "磁力回旋镖"
NAMES.UNCOMPROMISING_FISHINGNET = "渔网"
NAMES.UM_BEEGUN = "手持蜂巢"
NAMES.UM_BEEGUN_CHERRY = "手持蜂巢"
NAMES.BULLETBEE = "子弹蜂"
NAMES.CHERRYBULLETBEE = "子弹蜂"
NAMES.UM_BULLETBEE_PROJ = "子弹蜂"
NAMES.UM_CHERRYBULLETBEE_PROJ = "子弹蜂"

NAMES.WINONA_TOOLBOX = "器械箱"
NAMES.OCEAN_SPEAKER = "破旧的扬声器" -- Kinda lame dunno what else though.
NAMES.OCEAN_SPEAKER_TEASER = NAMES.OCEAN_SPEAKER
NAMES.SUNKENCHEST_ROYAL_RANDOM = "皇家沉底宝箱"

NAMES.SUNKENCHEST_ROYAL_RED = "宝石镶嵌宝箱"
NAMES.SUNKENCHEST_ROYAL_BLUE = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_PURPLE = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_GREEN = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_ORANGE = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_YELLOW = NAMES.SUNKENCHEST_ROYAL_RED
NAMES.SUNKENCHEST_ROYAL_RAINBOW = "绚丽的 " .. NAMES.SUNKENCHEST_ROYAL_RED

NAMES.SLUDGE = "海泥"
NAMES.SLUDGE_OIL = "海泥提取物"
NAMES.BOATPATCH_SLUDGE = "海泥补丁套件"
NAMES.SLUDGESTACK = "海泥喷孔"
NAMES.SLUDGE_SACK = "海泥包"

NAMES.ARMOR_REED_UM = "芦苇甲"
NAMES.ARMOR_SHARKSUIT_UM = "鲨甲"

NAMES.ROCKJAWLEATHER = "鲨鱼皮"

NAMES.LANTERN_ELECTRICAL = "电灯"
NAMES.MINERHAT_ELECTRICAL = "电矿工帽"

NAMES.POWERCELL = "蓄电池" -- 一次性电池

NAMES.SEAROCK_RING = "海蚀柱"
NAMES.RR_POWERLINE = "电力线"
NAMES.EYEOFTERROR_MINI_ALLY = "无畏窥视者"
NAMES.EYEOFTERROR_MINI_GROUNDED_ALLY = "恐怖的蛋"
NAMES.STUFFED_PEEPER_POPPERS = "榴莲酿眼球"
NAMES.UM_DEVILED_EGGS = "魔鬼蛋料理"
NAMES.SIREN_BIRD_NEST = "筑巢的海蚀柱"
NAMES.SIREN_BIRD_NEST_TEASER = NAMES.SIREN_BIRD_NEST
NAMES.SIREN_THRONE = "海妖王座"
NAMES.SIREN_THRONE_TEASER = NAMES.SIREN_THRONE
-- NAMES.NAMES.UM_SIREN = "警笛"
NAMES.WINONA_UPGRADEKIT_ELECTRICAL = "电能转换套件"
NAMES.UM_SORREL = "酢浆草"

NAMES.CRITTER_FIGGY = "小蚜虫"
NAMES.CRITTER_FIGGY_BUILDER = "小蚜虫"

NAMES.PORTABLEBOAT_ITEM = "气垫船套装"
NAMES.PORTABLEBOAT_RIPCORD = "气垫船插头"

NAMES.MASTUPGRADE_WINDTURBINE_ITEM = "风力涡轮灯台"

NAMES.LUSH_ENTRANCE = "十分凶险的洞"
NAMES.GIANT_TREE_BIRDNEST = "鸟巢"

NAMES.CANNONBALL_SLUDGE_ITEM = "海泥炮弹"
NAMES.CANNONBALL_SLUDGE = "海泥炮弹"
NAMES.UM_COPPER_PIPE = "铜管"
NAMES.STEERINGWHEEL_COPPER = "铜方向盘"
NAMES.STEERINGWHEEL_COPPER_ITEM = "铜方向盘套装"
NAMES.BOAT_BUMPER_SLUDGE = "海泥保险杠"
NAMES.BOAT_BUMPER_SLUDGE_KIT = "海泥保险杠套装"
NAMES.BOAT_BUMPER_COPPER = "铜保险杠"
NAMES.BOAT_BUMPER_COPPER_KIT = "铜保险杠套装"
NAMES.HERMIT_BUNDLE_LURES = "诱饵包"
NAMES.UM_LAVASPIT_SLUDGE = "燃烧的海泥池"

NAMES.KELPSTACK = "海带海蚀柱"
NAMES.MOSSSTACK = "苔藓海蚀柱"

NAMES.SPECTER_SHIPWRECK = "废弃的沉船"
NAMES.UM_DREAMCATCHER = "追梦人"
NAMES.UM_BRINEISHMOSS = "盐水苔藓"
NAMES.UM_COALESCED_NIGHTMARE = "合并梦魇"
NAMES.BRINE_BALM = "盐晶药膏"
NAMES.SLUDGE_CORK = "海泥塞"
NAMES.UM_SPECTOPLASM = "光谱"
NAMES.UM_SPECTER_AMULET = "幽灵护身符"
NAMES.PHANTOM = "鬼魂" -- phantom like minecraft :-O
NAMES.UMSS_GENERAL = "永不妥协开发工具"
NAMES.UM_DEVCAPTURE = "开发捕获设备"
NAMES.UM_BEEGUARD_SEEKER = "轰炸蜂"
NAMES.UM_BEEGUARD_BLOCKER = "拦截蜂"
NAMES.UM_BEEGUARD_SHOOTER = "子弹蜂"

NAMES.UM_ORNAMENT_OPOSSUM = "负鼠装饰物"
NAMES.UM_ORNAMENT_RAT = "老鼠装饰"

NAMES.TRINKET_WATHOM1 = "破损的吸入器"

NAMES.DEATHAMP = "心脏病发作"

NAMES.CODEX_MANTRA = "旧·暗影秘典"
NAMES.SHADOWVORTEX = "暗影漩涡"

NAMES.UM_INKUBATOR = "远古孵化器"
NAMES.UM_SCRAPPER = "远古拆解机"
NAMES.UM_ASTRAL_PROJECTOR = "星界投射器"
NAMES.UM_ASTRAL_PROJECTOR_TARGET = "星界接收器"

NAMES.UM_MEAT_CUBE = "肉类立方块"
NAMES.UM_MONSTER_CUBE = "怪物立方块"
NAMES.UM_VEGGIE_CUBE = "蔬菜立方块"
NAMES.UM_SUGAR_CUBE = "糖质立方块"
NAMES.UM_ROUGHAGE_CUBE = "木质立方块"
NAMES.UM_BLAND_CUBE = "无味立方块"

-- Ocupus Parts
NAMES.UM_OCUPUS_EYE = "眼柄"
NAMES.UM_OCUPUS_EYETACLE = "眼柄"
NAMES.UM_OCUPUS_TENTACLE = "触手"
NAMES.UM_OCUPUS_BEAK = "喙"

-- Ocupus Items
NAMES.OCUPUS_TENTACLE = "多目章鱼触手"
NAMES.OCUPUS_TENTACLE_EYE = "多目章鱼眼球"
NAMES.OCUPUS_TENTACLE_COOKED = "熟触手"
NAMES.OCUPUS_BEAK = "多目章鱼喙"
NAMES.BEAKBASHER = "喙击者"
NAMES.PLAUNT_MANNY = "汪汪警戒娃娃"

-- WIXIE & WALTER RELATED NAMES

NAMES.WIXIE_PIANO = "三角钢琴"
NAMES.WIXIE_PIANO_CARD = "神秘纸张"
NAMES.WIXIE_CLOCK = "落地摆钟"
NAMES.WIXIE_CLOCKDANGLEY1 = "秒权重"
NAMES.WIXIE_CLOCKDANGLEY2 = "分钟权重"
NAMES.WIXIE_CLOCKDANGLEY3 = "小时权重"
NAMES.WIXIE_WARDROBE = "华丽的衣橱"
NAMES.CHARLES_T_HORSE = "破旧玩具"
NAMES.THE_REAL_CHARLES_T_HORSE = "滑行手杖"
NAMES.WOODEN_QUEEN_PIECE = "木制女王"
NAMES.WIXIE_SHADOWCLONE = "暗影薇希"
NAMES.SHADOW_WIXIE = "薇希"
NAMES.WIXIE_SHADOW_CLONE = "暗影薇希"
NAMES.SHADOW_WIXIE_HELPER = "暗影薇希"

NAMES.SLINGSHOT_MATILDA = "浮木弹弓-玛蒂尔达"
NAMES.SLINGSHOT_GNASHER = "活木弹弓-切齿"
NAMES.SLINGSHOT_JESSIE = "绝望弹弓-杰西"
NAMES.SLINGSHOT_CLAIRE = "光芒弹弓-克莱尔"

NAMES.SLINGSHOTAMMO_LAZY = "替身弹药"
NAMES.SLINGSHOTAMMO_SHADOW = "梦魇弹药"
NAMES.SLINGSHOTAMMO_FIRECRACKERS = "鞭炮弹药"
NAMES.SLINGSHOTAMMO_HONEY = "蜂蜜弹药"
NAMES.SLINGSHOTAMMO_RUBBER = "橡皮弹药"
NAMES.SLINGSHOTAMMO_TREMOR = "沙石弹药"
NAMES.SLINGSHOTAMMO_MOONROCK = "月岩弹药"
NAMES.SLINGSHOTAMMO_MOONGLASS = "月亮碎片弹药"
NAMES.SLINGSHOTAMMO_SALT = "盐晶弹药"
NAMES.SLINGSHOTAMMO_SLIME = "黏糊弹药"
NAMES.SLINGSHOTAMMO_GOOP = "粘液弹药"
NAMES.SLINGSHOTAMMO_FLARE = "爆燃弹药"

NAMES.SLINGSHOTAMMO_INSANITY = "疯狂弹药"
NAMES.SLINGSHOTAMMO_LUNARVINE = "新月弹药"

NAMES.BAGOFMARBLES = "弹珠袋"

NAMES.SLINGSHOTAMMO_LIMESTONE = "海泥弹药"
NAMES.SLINGSHOTAMMO_TAR = "海泥弹药"
NAMES.SLINGSHOTAMMO_OBSIDIAN = "黑曜石弹药"

NAMES.PLACEHOLDER_INGREDIENT_IA_UM = "需要岛屿冒险或永不妥协！"
NAMES.PLACEHOLDER_INGREDIENT_IA = "需要岛屿冒险！"

NAMES.MEATRACK_HAT = "风干帽"
NAMES.FISHMEAT_DRIED = "鱼干"
NAMES.SMALLFISHMEAT_DRIED = "小鱼干"

NAMES.WIXIEGUN =
"格洛克17（HD版中的贝雷塔92FS），也称为9mm手枪，是《半条命》及其扩展包中的一种武器。"

NAMES.UM_MAXWELL_ARMOR_SANITY = "魔术师的暗夜甲"
NAMES.UM_MAXWELL_NIGHTSWORD = "魔术师的暗夜剑"
NAMES.PACT_ARMOR_SANITY = "暗夜契约甲"
NAMES.PACT_SWORD_SANITY = "暗夜契约剑"
------------------------

NAMES.WINONA_CATAPULT_ITEM = "拆除" .. NAMES.WINONA_CATAPULT
NAMES.WINONA_SPOTLIGHT_ITEM = "打包" .. NAMES.WINONA_SPOTLIGHT
NAMES.WINONA_BATTERY_LOW_ITEM = "分解" .. NAMES.WINONA_BATTERY_LOW
NAMES.WINONA_BATTERY_HIGH_ITEM = NAMES.WINONA_BATTERY_HIGH .. "拆散"

NAMES.STAFF_STARFALL = "星陨法杖"
NAMES.STAFF_MOONFALL = "月陨法杖"
NAMES.MOONFALL_PROJ = "流星"
NAMES.HAT_CRAB = "蟹王冠"
NAMES.HAT_CRAB_ICE = "严寒皇冠"
NAMES.KALEIDOSCOPE = "万花筒"
NAMES.MOONGLOW = "月光"
NAMES.ARMOR_CRAB_MAXHP = "镶玉盔甲"
NAMES.ARMOR_CRAB_REGEN = "治愈岩甲"
NAMES.MOON_BEACON_KIT = "不活跃的月亮信标"
NAMES.MOON_BEACON = "月亮信标"

NAMES.MARA_BOSS1 = "《传说之下》中的Sans，来自热门系列《任天堂明星大乱斗》（以《我的世界》Steve为特色）[& Knuckles]"
NAMES.MARA_BOSS1_BULLETS = "糟糕的时间"
NAMES.UM_WITCH = "至尊女巫 · 灾厄"

-- Pyre Nettle stuff
NAMES.UM_PYRE_NETTLES = "荨麻丛"
NAMES.UM_SMOLDER_SPORE = "荨麻孢子"
NAMES.UM_ARMOR_PYRE_NETTLES = "荨麻斗篷"
NAMES.UM_BLOWDART_PYRE = "荨麻飞镖"

-- Mutation Extrapolation
NAMES.UMDEBUFF_MOONBURN = "月光灼伤"
NAMES.UMDEBUFF_MOONBURN_TESTINGSTICK = "魔法止痛棒"

-- Under the Weather Part 1
NAMES.ALPHA_LIGHTNINGGOAT = "伏特头羊"
NAMES.UM_TORNADO = "巨型龙卷风"
NAMES.UM_WATERFALL = "瀑布"
NAMES.PORTABLEBOAT = "气垫船套装"

NAMES.UM_WINDTURBINE = "风力照明灯"
NAMES.MASTUPGRADE_WINDTURBINE = "风力照明灯"

NAMES.GARBAGEPATCHFLOTSAM = "风暴碎片"

NAMES.PIGKING_PIGGUARD = NAMES.PIGGUARD

NAMES.UM_BOAT_ENGINE = "淤泥引擎"
NAMES.SMOG = "窒息"

------------------------
-- Broiling Hills --
------------------------
NAMES.UM_SNAILDRAKE_EXPLOSION = "蜗龙爆炸"
NAMES.SNAILDRAKE_HOLE = "裂缝"
NAMES.SNAILDRAKE_MAGMA = "蜗龙"
NAMES.SNAILDRAKE_SLIME = "蜗龙"
NAMES.UM_SNAILDRAKE_MAGMA_SLUDGE = "岩浆黏液"
NAMES.SNAPALM = "爆燃黏液"
NAMES.SNAILDRAKEHAT = "蜗龙角盔"
NAMES.SNAILDRAKEBUCKET = "蜗龙盆"

------------------------
-- Magma Caves --
------------------------
NAMES.MUSHTREE_SHADOW = "幽暗蘑菇"
NAMES.GLOOMCAP = "幽暗蘑菇"
NAMES.GLOOMCAP_COOKED = "熟幽暗蘑菇"
NAMES.SPORE_SHADOW = "幽暗孢子"
NAMES.VIPERWORM = "洞穴恶蛇"
NAMES.VIPERLING = "蠕动暗影"
NAMES.VIPERLINGFRIEND = "蠕动暗影"
NAMES.VIPERFRUIT = "幽暗浆果"
NAMES.VIPERFRUIT_LESSER = "小幽暗浆果"
NAMES.VIPERJAM = "幽暗果酱"
NAMES.VIPERFRUIT_PLANT = "不祥植物"
NAMES.UM_GHOST_PEPPER = "褪色藤蔓"
NAMES.UM_GHOST_PEPPER_ITEM = "幽灵辣椒"
------------------------
-- Rimeweed --
------------------------
NAMES.RIMEWEED_MAIN = "尖刺霜草"
NAMES.RIMEWEED_BARRIER = "霜草荆棘"
NAMES.RIMEWEED_WHIP = "霜鞭"
NAMES.UM_RIMEWEED_ITEMFLOWER = "霜花"
NAMES.UM_RIMEWEED_ITEMVINE = "霜冻藤蔓"
NAMES.UM_RIMEWEED_SPAGETT = "霜冻意面"
NAMES.UM_RIMEWEED_TEQUILA = "冰镇龙舌兰"
NAMES.UM_RIMEWEED_ICEPACK = "冰袋"
NAMES.UM_BLOWDART_RIME = "霜镖"
NAMES.UM_ARMOR_BRAMBLE_RIMEWEED = "霜冻外壳"
NAMES.UM_HAT_RIME = "霜兽头盔"
NAMES.UM_ICE_TAIL = "冰冻鼹鼠尾"

NAMES.UM_DURIAN_CREAM_MARSHCAKE = "榴莲奶油软糖蛋糕"
NAMES.UM_CHILES_EN_NOGADA = "三色酿椒"
NAMES.UM_RICE_PUDDING = "米布丁"
NAMES.UM_KEBAB = "无骨烤串"


NAMES.UM_COOKPOT_WAGSTAFF = "锅-800"
NAMES.UM_COOKPOT_WAGSTAFF_DISPLAY = "引人注目的显示器"
NAMES.UM_COOKPOT_WAGSTAFF_LEVER = "简陋的杠杆"
NAMES.UM_COOKPOT_WAGSTAFF_LEVER2 = "破旧的杠杆"

NAMES.STAFF_TORNADO_LIGHTNING = "强化气象之痛"
NAMES.RNEHOUND = "暗影猎犬"

NAMES.JAWED_SCYTHE = "颚镰"
NAMES.UM_ICE_SICLE = "冰镰"
NAMES.SNAPPY_JAW = "利颚"
NAMES.UM_BOATBOTTLE = "船瓶"
NAMES.BOAT_ANCIENT_ITEM_BLUEPRINT = "远古船套件蓝图"
NAMES.UM_BUTTERY_FLY = "黄油蝴蝶"
NAMES.UM_HAT_LEAFWING = "转瞬即逝的叶冠"
NAMES.UM_LEAFWING = "叶翼"
NAMES.UM_DETONATOR = "万能引爆器"

NAMES.UM_BEE_MOON = "腐臭蜂"
NAMES.UM_BEEHIVE_MOON = "腐臭蜂巢"
NAMES.UM_MEATCOMB = "腐臭蜂巢"
NAMES.UM_MEATHONEY = "腐臭蜂蜜"

NAMES.FYRITEROCK = "黄铁矿矿簇"
NAMES.UM_FYRITE = "黄铁矿"
NAMES.UM_FYRE_BOMB = "高爆弹"
NAMES.UM_MANNY = "普劳特·曼尼"

NAMES.UM_HAT_BEE_MOON = "蜂帽"
NAMES.UM_EYEBALM = "眼霜"
NAMES.UM_BEEMINE_MOON = "腐臭蜂地雷"
NAMES.UM_BEEMINE_MOON_ITEM = "腐臭蜂地雷"

NAMES.UM_PLANT_HOTSPRINGS = "植物"
NAMES.UM_PEPPERDRAGON_NEST = "椒龙巢"

NAMES.UM_GHOST_FAJITA = "恐怖卷饼"
NAMES.UM_BOOM_TART = "爆汁蓝莓挞"
NAMES.UM_RIBOPOD = "肋荚虫"
NAMES.UM_RIBOPODDEN = "骸骨堆"

NAMES.UM_GEMOLOGYGEM_UNKNOWN = {
    DEFAULT = "奇异宝石",
    RED = "奇异红宝石",
    ORANGE = "奇异橙宝石",
    YELLOW = "奇异黄宝石",
    GREEN = "奇异绿宝石",
    BLUE = "奇异蓝宝石",
    PURPLE = "奇异紫宝石",
    PALE = "奇异彩虹宝石"
}


NAMES.UM_GEMOLOGYGEM_PREFIX = {
    "碎裂的",
    "微瑕的",
    "无暇的"
}

NAMES.UM_GEMOLOGYBLUEGEM1 = "极地海蓝宝石"
NAMES.UM_GEMOLOGYBLUEGEM2 = "冰鲜蓝宝石"
NAMES.UM_GEMOLOGYREDGEM1 = "贪噬红宝石"
NAMES.UM_GEMOLOGYREDGEM2 = "炽烈石榴石"
NAMES.UM_GEMOLOGYPURPLEGEM1 = "狂怒萤石"
NAMES.UM_GEMOLOGYPURPLEGEM2 = "奥术紫水晶"
NAMES.UM_GEMOLOGYYELLOWGEM1 = "迅疾黄玉"
NAMES.UM_GEMOLOGYYELLOWGEM2 = "静电琥珀"
NAMES.UM_GEMOLOGYGREENGEM1 = "躁动橄榄石"
NAMES.UM_GEMOLOGYGREENGEM2 = "混沌祖母绿"
NAMES.UM_GEMOLOGYORANGEGEM1 = "惬意锆石"
NAMES.UM_GEMOLOGYORANGEGEM2 = "珍藏黄水晶"
NAMES.UM_GEMOLOGYPALEGEM1 = "绝世翡翠"
NAMES.UM_GEMOLOGYPALEGEM2 = "坚钢钻石"
NAMES.UM_GEMOLOGYFORGE = "宝石学锻造台"

NAMES.GEMTOOL_PREFIX = {
    UM_GEMOLOGYGREENGEM1 = "躁动",
    UM_GEMOLOGYGREENGEM2 = "混沌",
    UM_GEMOLOGYYELLOWGEM1 = "迅疾",
    UM_GEMOLOGYYELLOWGEM2 = "静电",
    UM_GEMOLOGYPALEGEM1 = "绝世",
    UM_GEMOLOGYPALEGEM2 = "坚钢",
    UM_GEMOLOGYREDGEM1 = "贪噬红",
    UM_GEMOLOGYREDGEM2 = "炽烈",
    UM_GEMOLOGYPURPLEGEM1 = "狂怒",
    UM_GEMOLOGYPURPLEGEM2 = "奥术", 
    UM_GEMOLOGYORANGEGEM1 = "惬意",
    UM_GEMOLOGYORANGEGEM2 = "珍藏",
    UM_GEMOLOGYBLUEGEM1 = "极地",
    UM_GEMOLOGYBLUEGEM2 = "冰鲜",
}

NAMES.WATHOM_CORPSE = "沃托姆的甲壳"

NAMES.UM_SPONGEPLANT = "多孔海绵"
NAMES.UM_SPONGEPLANT_ITEM = "多孔海绵块"
NAMES.UM_SPONGE_CAKE = "多孔海绵蛋糕"

NAMES.UM_MOSS = "连帽苔藓"

NAMES.WATHGRITHR_SHIELD_DREADSTONE = "绝望石圆盾"
NAMES.UM_FERN_FOX = "蕨狐"
NAMES.UM_FERN_FOX_DEN = "狐穴"

NAMES.UM_PEPPERDRAGON = "椒龙"
NAMES.UM_PEPPERDRAGON_BLADDER = "储火袋"
NAMES.UM_FLAMETHROWER = "爆焰喷射器"
NAMES.UM_FIRECREAM = "防火霜"
NAMES.UM_HAT_PEPPERDRAGON = "冷热逆转帽"

NAMES.UM_GEMOLOGY_GEODE_RED = "红色菌类晶洞"
NAMES.UM_GEMOLOGY_GEODE_GREEN = "绿色菌类晶洞"
NAMES.UM_GEMOLOGY_GEODE_BLUE = "蓝色菌类晶洞"
NAMES.UM_GEMOLOGY_GEODE_GUANO = "粪便晶洞"
NAMES.UM_GEMOLOGY_GEODE_LOBSTER = "胚胎晶洞"
NAMES.UM_GEMOLOGY_GEODE_GLASS = "玻璃晶洞"
NAMES.UM_GEMOLOGY_GEODE_SLIME = "黏液晶洞"
NAMES.UM_GEMOLOGY_GEODE_RUINS = "垃圾晶洞"
NAMES.UM_GEMOLOGY_GEODE_VENT = "浮石晶洞"
NAMES.UM_GEMOLOGY_GEODE_SINK = "苔藓晶洞"

NAMES.UM_BOOMBERRY_BOMB = "爆汁蓝莓炸弹"
NAMES.UM_BOOMBERRYPIE = "爆汁蓝莓派"

NAMES.UM_REDMUSHTREE_GEM = "石化蘑菇树"
NAMES.UM_REDMUSHTREE_GEMLESS = "石化蘑菇树"
NAMES.UM_GREENMUSHTREE_GEM = "石化蘑菇树"
NAMES.UM_GREENMUSHTREE_GEMLESS = "石化蘑菇树"
NAMES.UM_BLUEMUSHTREE_GEM = "石化蘑菇树"
NAMES.UM_BLUEMUSHTREE_GEMLESS = "石化蘑菇树"

NAMES.UM_GUANO_ROCK = "粪化石矿簇"
NAMES.UM_GUANO_ROCK_GEMLESS = "粪化石矿簇"
NAMES.UM_SLIMESTONE_ROCK_GEMLESS = "滑石灰岩"
NAMES.UM_SLIMESTONE_ROCK = "滑石灰岩"
NAMES.UM_ROCKLOBSTER_ROCK = "孕育中的岩石"
NAMES.UM_SINKMOUND_ROCK = "不起眼的洞穴"
NAMES.UM_SINKMOUND_ROCK_GEMLESS = "不起眼的洞穴"
NAMES.GLACIALHOUND_ICESPIKE = "冰刺"
NAMES.UM_MOONGLASS_CEILING = "月玻璃钟乳石"
NAMES.UM_FEATHER_TOTEM = "羽毛神像"
NAMES.UM_GEMOLOGY_POUCH = "宝石袋"
NAMES.UM_MAGNIFIER = "远古宝石放大镜"
NAMES.UM_MAGNIFIER_PURPLEGEM = "宝石放大镜"
NAMES.UM_MAGNIFIER_OBSIDIAN = "宝石熔岩镜"
NAMES.UM_REEDS_LUNAR = "鬃毛芦苇"
NAMES.UM_STRANGE_RABBIT_ROCK = "奇异岩石"
NAMES.UM_GUANO_RAIN_PARTICLE = "新鲜粪堆"
NAMES.UM_HAT_NETTLEMASK = "荨麻面具"

NAMES.UM_TENTACLE_MOON = "巨型触手"
NAMES.UM_THULECITE_RAZOR = "铥矿剃刀"
NAMES.UM_TENTACLESPIKE_MOON = "触手尖刺"
NAMES.UM_TENTACLESPOT_MOON = "巨型触手皮"
NAMES.UM_BOMB_MOON = "跨巨型气体炸弹"
NAMES.UM_BACKPACK_AMULETUSE = "娱乐背包"
NAMES.UM_MUSHROOM_MOON = "月亮蘑菇"
NAMES.UM_POOFSHROOM = "噗芙蘑菇"





