-- Wilson's speech file
-- The strings here are also used when other characters are missing a line.
-- If you've added an object to the mod, this is where to add placeholder strings.
-- Keep things organized.
RECIPE_DESC = GLOBAL.STRINGS.RECIPE_DESC
-- Could this be moved to init_recipes without issue?
RECIPE_DESC.RAT_BURROW = "一窝烦人的小毛球。"

ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.GENERIC
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.GENERIC.ACTIONFAIL

-- [ Wilson Descriptions ]--

ANNOUNCE.DREADEYE_SPOOKED = "什-什么？"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "鬼魂解剖学无法得到心脏!"
ANNOUNCE.ANNOUNCE_WINONAGEN = "那不是我的事。"
ANNOUNCE.ANNOUNCE_RATRAID = "吱吱吱吱?"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "鼠鼠来了!"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "喂!把我的东西还来!"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"是雨滴！有腐蚀性!","呀,是酸雨!","我需要地方躲雨!",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "我们被真菌感染了!"
-- FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "刺...刺骨的严寒包......包围了我"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我感到...自己...变得更脆弱了..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "这下暖和多了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_VETCURSE = "真高兴这种状态离我而去了!"
ANNOUNCE.ANNOUNCE_RNEFOG = "我感到有人在对我暗中观察。"
-- FoodBuffs

-- CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "呃,感觉还不赖。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "我变得不像我自己了。"
DESCRIBE.CALIFORNIAKING = "这道菜看起来真恶心。"
-- CaliforniaKing

-- Content Creators
DESCRIBE.CCTRINKET_DON = "我只能认出 \"不要\" 和 \"指引\"这两个字."
DESCRIBE.CCTRINKET_JAZZY = "很有爵士乐的风格。"
DESCRIBE.CCTRINKET_FREDDO = "上面刻了一个 \"自由\" 的字."		
DESCRIBE.CCTRINKET_NAMES = "可能有人需要这个。"

-- Content Creators
DESCRIBE.UNCOMPROMISING_RAT = "它们这是在报复!"
DESCRIBE.UNCOMPROMISING_RATHERD = "这肯定通向老鼠们的老巢。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "这肯定通向老鼠们的老巢。"
DESCRIBE.UNCOMPROMISING_WINKYBURROW =
"这肯定通向老鼠们的老巢。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW =
"这肯定通向老鼠们的老巢。"

DESCRIBE.WINKY = {
    GENERIC = "你对几个实验感觉如何？",
    ATTACKER = "你知道你在咬谁！",
    MURDERER = "坏老鼠！!",
    REVIVER = "会是一个很棒的实验帮手!",
    GHOST = "我希望这不是我实验造成的",
    FIRESTARTER = "老鼠不应该用火！",
}
DESCRIBE.WATHOM = {
    GENERIC = "%s 似乎比他看起来更聪明。",
    ATTACKER = "%s 看起来很吓人！",
    MURDERER = "这个怪物要杀了我们所有人！",
    REVIVER = "我很高兴 %s 站在我这边！",
    GHOST = "这看起来不像是普通的鬼魂。 嗯，“正常”。",
    FIRESTARTER = "你是想喷火吗，%s？",
}
DESCRIBE.WIXIE = {
	GENERIC = "我认为 %s 不喜欢我。",
     	ATTACKER = "%s 是个恶霸！",
     	MURDERER = "她失去了道德束缚！",
     	REVIVER = "%s 的动机是个谜。",
     	GHOST = "我认为 %s 明白了她的意思。",
     	FIRESTARTER = "%s 是个威胁！",
}

DESCRIBE.RATPOISONBOTTLE =
"上面写着 \"不要喝下去,说的就是你, 韦伯。\""
DESCRIBE.RATPOISON = "杀人如麻的毒药!"

DESCRIBE.MONSTERSMALLMEAT = "小块的,有毒的肉。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "....这块肉还是 紫 色 的。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "真是快小恶魔的化身。"

DESCRIBE.UM_MONSTEREGG = "奇怪的蛋。"
DESCRIBE.UM_MONSTEREGG_COOKED = "我可一点都不想尝它！"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "这就是瘟疫的源头!"
DESCRIBE.TOADLING = "它肯定喜欢那些奇怪的树。"
DESCRIBE.UNCOMPROMISING_TOAD = "那只蛤蟆看起来病得厉害。"

DESCRIBE.GASMASK = "现在我可以自由地呼吸了。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "好恶心!"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿阿阿阿阿阿嚏!"
ANNOUNCE.ANNOUNCE_HAYFEVER = "我的鼻子......痒痒的。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "我再也不想体验把自己的眼睛挠肿的感觉了。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"这附近确实是升温。", "天呐,这家伙的叫声还在增大!",
	"我感到有些不好。",
}
ANNOUNCE.ANNOUNCE_ROOTING = "我被困住了!"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "刮起大风了.....。"

ANNOUNCE.SHADOWTALKER = {
    "无路可逃", "它们就在外面，注视着，永远如此",
    "这只是时间问题", "外面到底是哪年？",
    "只有黑暗", "这是永无止境的轮回", 
    "我在这里已经死过多少次了？", "我做了什么才应得此报？",
    "我真的能相信他们吗？"
}

-- StantonStuff
ANNOUNCE.STANTON_GREET = {
    "想和亡者喝一杯吗?", 
    "我们玩个小游戏,一起喝一杯怎么样?", "来和我痛饮吧。",
    "我来挑酒,你来解决。"
}
ANNOUNCE.STANTON_GIVE = {
    "你看起来很乐意,干杯。", "到你了。"
}
ANNOUNCE.STANTON_RESTOCK = {
    "还清醒吗?继续!", "再来一杯。"
}
ANNOUNCE.STANTON_RULES = {"我一次只喝一杯。"}
ANNOUNCE.STANTON_GLOAT = {"哈!我就知道你是个软柿子!", "哈! 你输了!"}

ANNOUNCE.STANTON_POET1 = {
    "六点至午夜,死神之手就要来了。"
}
ANNOUNCE.STANTON_POET2 = { "闭嘴,喝酒。"}
ANNOUNCE.STANTON_POET3 = { "和它的手做对的人永远也赢不了" }
ANNOUNCE.STANTON_POET4 = { "继续,与活死人共饮吧。" }
ANNOUNCE.STANTON_POET5 = { "与活死人共饮。" }

ANNOUNCE.STANTON_IMPATIENT = {
    "我的耐心有限。","我不会在这儿等你一整晚!"
}
ANNOUNCE.STANTON_SUPERIMPATIENT = {"我受够了,等待时间结束!"}
-- StantonStuff

ANNOUNCE.SHADOW_CROWN_CHALLENGE = "击败这个生物,得到你的奖品。"
ANNOUNCE.ANNOUNCE_OVER_EAT = {
	STUFFED = "我饱了",
	OVERSTUFFED = "嗝.....我真的不应该再继续进食了。",
}
ANNOUNCE.CURSED_ITEM_EQUIP = "嗷!我的手!"
DESCRIBE.VETSITEM = "我需要寻找一种黑暗力量来使用它！"
DESCRIBE.SCREECHER_TRINKET = "好极了,是我想要的。"
DESCRIBE.TRINKET_WATHOM1 = "无论这是什么，看起来都有点坏了"

DESCRIBE.UM_SAND = "一小堆沙子。"
DESCRIBE.UM_SANDHILL = "你最好离我远点。"
DESCRIBE.SNOWPILE = "如果让它堆积起来,会是个大问题。"
DESCRIBE.SNOWGOGGLES = "现在清晰多了。"

DESCRIBE.SNOWMONG = "抖抖虫!"
DESCRIBE.SHOCKWORM = "这只蠕虫是带电的!"
DESCRIBE.ZASPBERRY = "我能感觉到其中奔腾的电流。"
DESCRIBE.ZASPBERRYPARFAIT = "美味佳肴。"
DESCRIBE.ICEBOOMERANG = "寒气逼人。"

DESCRIBE.MINOTAUR_BOULDER = "这是一块很好的石头。"
DESCRIBE.MINOTAUR_BOULDER_BIG =
"科学表明,如果被它撞到,会很疼。应该吧。"
DESCRIBE.BUSHCRAB = "啊!这玩意儿在下面呆了多久?"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB =
"终于,月亮的变形特性终于有了实际用途。"
DESCRIBE.TOADLINGSPAWNER = "哦不。"
DESCRIBE.VETERANSHRINE = "我知道我在做什么...对吧?"
DESCRIBE.VET_SKULL = "一个好标本!"
DESCRIBE.UM_BOSS_SOUL = "身体越大,灵魂越大。这就是科学!"
DESCRIBE.UM_DARK_VESTIGES = "看看我戳它会发生什么..."
DESCRIBE.UM_VOXOLOPHONE = "收音机里又一个陌生人...能有多糟糕呢?"

DESCRIBE.UM_EXHUMER = "想象一下我能从真正的活骷髅那里获得多少数据!"
DESCRIBE.UM_WINGSUIT = "符合空气动力学!"
DESCRIBE.UM_MOONFLY_LANTERN = "它由魔法驱动。大量的魔法。"

DESCRIBE.WICKER_TENTACLE = "令人作呕的东西。"
DESCRIBE.HONEY_LOG = "我有一种奇怪的欲望想吃它。"

DESCRIBE.RAT_TAIL = "它散发着瘟疫的恶臭。"
DESCRIBE.PLAGUEMASK = "鸟喙里塞满的蘑菇闻起来很香。"
DESCRIBE.SALTPACK = "它能融化我周围的雪!"
DESCRIBE.SPOREPACK = "它又大又臭。"
DESCRIBE.SPIDER_TRAPDOOR = "啊!是伏击!"
DESCRIBE.TRAPDOOR = "这里一切正常。"
DESCRIBE.HOODEDTRAPDOOR = DESCRIBE.TRAPDOOR
DESCRIBE.SHROOM_SKIN_FRAGMENT =
"虽然很小,但臭气还是让人难以忍受。"
DESCRIBE.AIR_CONDITIONER = "闻起来很棒!"


DESCRIBE.SKELETONMEAT = "肉就是肉,我该在什么地方划定界限?"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "什么玩意儿这是--?!"
DESCRIBE.VAMPIREBAT = "这只更丑!!"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "我可以用几个月岩来把它修好。"
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP

-- Swampyness
DESCRIBE.RICEPLANT = "饭是钢。"
DESCRIBE.RICE = "它太硬了,无法入口。"
DESCRIBE.RICE_COOKED = "尝起来湿漉漉的。"
DESCRIBE.SEAFOODPAELLA = "清除鼻窦。"

DESCRIBE.STUMPLING = "它很小但是脾气很大!"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.BUGZAPPER = "现在我要让这些讨厌的害虫尝尝滋味!"
DESCRIBE.MOON_TEAR =
"我觉得月亮对它丢失的部分很伤心,我们应该保管好它。"
DESCRIBE.SHADOW_TELEPORTER = "嘿!我们离这块宝石远一点!"
DESCRIBE.POLLENMITEDEN = "科学说它很危险。"
DESCRIBE.POLLENMITES = "我可不愿意离它很近。"
DESCRIBE.SHADOW_CROWN = "我已经觉得更不安全了。"
DESCRIBE.UM_SHADOW_AXE = "它看起来异常熟悉。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.LICELOAF = "多么乏味。"
DESCRIBE.SUNGLASSES = "时尚,但是尺寸有些大。"
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "它是老鼠吗....哦不...呕。"
DESCRIBE.MARSH_GRASS = "都是灌木丛。"
DESCRIBE.CURSED_ANTLER = "强壮!可靠!"
DESCRIBE.BERNIEBOX = "里面有什么呢?如果我可以打开它就好了...."
DESCRIBE.HOODED_FERN = "这个蕨类植物长得相当大。"
DESCRIBE.HOODEDWIDOW = "那东西可以吃掉一个巨人!!"
DESCRIBE.GIANT_TREE = "它完全遮住了阳光。"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST
DESCRIBE.WIDOWSGRASP = "让我们打开这些茧吧!"
DESCRIBE.WEBBEDCREATURE = "看看里面是什么应该不会有事,对吧?"
ANNOUNCE.WEBBEDCREATURE = "只有蜘蛛才能撕破这么结实的蛛丝!"

DESCRIBE.SILKSACK = "我希望里面不是蜘蛛网。"
DESCRIBE.SILKEN_BUNDLE = "我们的物资被卡在里面了。"

DESCRIBE.SNAPDRAGON_BUDDY = "它看起来饿了。我也是。"
DESCRIBE.SNAPDRAGON = "看起来还不错。"
DESCRIBE.SNAPPLANT = "一小片家的感觉。"
DESCRIBE.WHISPERPOD = "让我们看看把它种在地里会发生什么。"
DESCRIBE.WHISPERPOD_NORMAL_GROUND = {
	GENERIC = "需要一些种子吗?",
	GROWING = "咕! 它长得太慢了!",
}
DESCRIBE.FRUITBAT = "啊, 还是很可怕!"
DESCRIBE.PITCHERPLANT = "它相当高。"
DESCRIBE.APHID = "一种可怕的害虫。"
DESCRIBE.NYMPH = "它正在将瘟疫传播到更多的树木上。"
DESCRIBE.GIANT_TREE_INFESTED = "看起来不太好。"
DESCRIBE.GIANT_BLUEBERRY = "这有点脏,我可以确定。"
DESCRIBE.BLUEBERRYPANCAKES = "香气扑鼻。"
DESCRIBE.DEVILSFRUITCAKE = "见鬼一样的好吃!"
DESCRIBE.SIMPSALAD = "这是一道非常清淡的菜。"
DESCRIBE.BEEFALOWINGS = "我确定皮弗娄牛不介意。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "永远也不能击倒我。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE =
"我的腿又开始变得脆弱了。"
DESCRIBE.WIDOWSHEAD = "这好像增强了我的视野。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "幽灵?"
DESCRIBE.SNOWCONE = "肯定是放了太多的冰导致的。"

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "它在搅乱我的思维！"
DESCRIBE.VIPERFRUIT = "我用科学的力量制造蛇！"
DESCRIBE.VIPERFRUIT_LESSER = DESCRIBE.VIPERFRUIT
DESCRIBE.VIPERJAM = "至少我现在有罐子了。"

DESCRIBE.BLUEBERRYPLANT = {
    READY = "它长得很大，也许我可以把它挖出来。",
    FROZE = "它被冻得结结实实的。",
    REGROWING = "这株植物挺过来了，它可能会重新长出来？"
}

DESCRIBE.ANTIHISTAMINE = "对治疗鼻塞很有用！"

DESCRIBE.HEATROCK_LEVEL = {
    TINY ="一块孤独的老岩石，坐在露天。",
    SMALL ="放在口袋里有点隔热。",
    MED ="我现在将其保持在一定程度的隔离状态。",
    LARGE ="现在它已经得到了很好的保护，免受恶劣天气的影响。",
    HUGE="它完全不受恶劣天气的影响！"
}

DESCRIBE.DURABILITY_LEVEL = {
    QUARTER = "它几乎快要碎了!",
    HALF = "里面有一些讨厌的孔洞。",
    THREEQUARTER = "可以使用一些缝合线。",
    FULL = "完好无损。",
}

ACTIONFAIL.READ.GENERIC = "似乎魔法在这种状态下不起作用。"
ACTIONFAIL.GIVE.NOTNIGHT = "我应该等到月亮出来。"

-- Xmas Update
DESCRIBE.MAGMAHOUND = "热狗!"
DESCRIBE.LIGHTNINGHOUND = "注意!那会刺痛你的!"
DESCRIBE.SPOREHOUND = "你这只病狗。"
DESCRIBE.GLACIALHOUND = "这只猎犬在冰川上。"
DESCRIBE.RNESKELETON = "它们诡异又可怕!"
DESCRIBE.RAT_WHIP = "规矩由我定。"
DESCRIBE.KLAUS_AMULET = "它的锁链里有寒冬之王!"
DESCRIBE.CRABCLAW = "嘿!里面有些宝石洞!" 
DESCRIBE.HAT_RATMASK = "我会亲自嗅出那些巢穴!" 

DESCRIBE.ORANGE_VOMIT = "哦,你真好..."
DESCRIBE.GREEN_VOMIT = "哦,你真好..."
DESCRIBE.RED_VOMIT = "哦,你真好..."
DESCRIBE.PINK_VOMIT = "哦,你真好..."
DESCRIBE.YELLOW_VOMIT = "哦,你真好..."
DESCRIBE.PURPLE_VOMIT = "哦,你真好..."
DESCRIBE.PALE_VOMIT = "哦,你真好..."

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = {
    GUARD = DESCRIBE.PIGMAN.GUARD,
    WEREPIG = DESCRIBE.PIGMAN.WEREPIG
}
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH

DESCRIBE.BIGHT = "它是活的!"
DESCRIBE.KNOOK = "我不喜欢那张巨口!"
DESCRIBE.ROSHIP = "多么恐怖!"

DESCRIBE.UM_PAWN = "当我靠近时声音变大了。"
DESCRIBE.UM_PAWN_NIGHTMARE = "我应该离它远一点。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "它和我的心脏连接在了一起!"
DESCRIBE.UM_BEAR_TRAP = "我应该尽量小心一些。"
DESCRIBE.UM_BEAR_TRAP_OLD = "哇!我应该尽量小心一些。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "别对我发脾气!"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "别对我发脾气!"
DESCRIBE.CORNCAN = "这些罐子是从哪来的?"
DESCRIBE.SKULLCHEST_CHILD = "要是能把我装进去就好了。"

DESCRIBE.SLOBBERLOBBER = "一个便携的岩浆发射器。"
DESCRIBE.GORE_HORN_HAT =
"我的头脑一直是最强大的武器... 是的,你明白了。"
DESCRIBE.BEARGERCLAW = "棍子和石头能敲断骨头。"
DESCRIBE.FEATHER_FROCK = "穿在身上舒适得像一张床!"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM ..
    "\n...这种形式几乎无法使用。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM ..
    "\n...这种形式几乎无法使用。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM ..
    "\n...这种形式几乎无法使用。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM ..
    "\n...这种形式几乎无法使用。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM ..
    "\n...这种形式几乎无法使用。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM ..
    "\n...这种形式几乎无法使用。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM ..
    "\n...这种形式几乎无法使用。"

DESCRIBE.RED_MUSHED_ROOM = "已经变成糊状的了。"
DESCRIBE.GREEN_MUSHED_ROOM = "已经变成糊状的了。"
DESCRIBE.BLUE_MUSHED_ROOM = "已经变成糊状的了。"

DESCRIBE.HEAT_SCALES_ARMOR = "要是能把我装进去就好了。"

-- StantonStuff
DESCRIBE.SKULLFLASK = "我们拿到了那个人的幸运瓶。"
DESCRIBE.SKULLFLASK_EMPTY = "我稍后再补货。"
DESCRIBE.STANTON_SHADOW_TONIC = "我不应该这样做..."
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "你想要一个喝酒的伙伴?呃..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "这是什么,这么可怕?"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "我..."
-- StantonStuff

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "我应该找到一些有趣的东西来看。"
DESCRIBE.DEERCLOPS_BARRIER = "我应当尽快挖出去!"

DESCRIBE.MOONMAW_DRAGONFLY = "吓哭我了!"
DESCRIBE.MOONMAW_LAVAE = "它们在保护它们的妈妈!"
DESCRIBE.SNAPPERTURTLE =
"这些东西不会咬你的手,对吧?"
DESCRIBE.SNAPPERTURTLEBABY =
"我想要一只作为宠物,但是我怕它咬掉我的手。"
DESCRIBE.SNAPPERTURTLENEST = "是的,那是一个巢穴。"
DESCRIBE.GLASS_SCALES = "我喜欢它发光的方式。"
DESCRIBE.MOONGLASS_GEODE = "它很重,不是真正的玻璃。"
DESCRIBE.ARMOR_GLASSMAIL = "伸手可及的任何东西都会被撕碎!"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "谢天谢地,我是掌控者。"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "科学使它不会头痛。"
DESCRIBE.SNOTROAST = "那东西绝不能靠近我的嘴巴。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我失去了食欲。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "我又开始感到饥饿了。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_BOOMBERRYATTACKS = "奇怪的果味。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_BOOMBERRYATTACKS = "这味道现在从我嘴里消失了。"
DESCRIBE.BOOK_RAIN_UM = "多谢，我已经了解水循环了。"
DESCRIBE.FLORAL_BANDAGE = "治愈开放性伤口并让它们保持芬芳。"
DESCRIBE.DORMANT_RAIN_HORN =
"看着它让我想起热带环境的画面。"
DESCRIBE.RAIN_HORN = "这对再次发生野火时会很有用。"
DESCRIBE.DRIFTWOODFISHINGROD = "它与海洋共鸣。"

ANNOUNCE.ANNOUNCE_NORATBURROWS = "听起来附近没有老鼠巢穴了。"
ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
    LEVEL_1 = "营地乱得像个老鼠窝。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
    LEVEL_1 = "营地里的的食物情况可能会引起不必要的注意。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
    LEVEL_1 = "老鼠似乎在旷野中进行繁衍,它们的源头在哪?",
}
DESCRIBE.PIED_RAT = "它一定是在领导鼠群!"
DESCRIBE.PIED_PIPER_FLUTE = "也许我可以自己领导一些老鼠?"
DESCRIBE.UNCOMPROMISING_PACKRAT = "嘿!它们带走了我们所有的贵重物品!"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "如果我淹死了，我就无法找回这个木筏！"

ACTIONFAIL.CHARGE_FROM = {
	NOT_ENOUGH_CHARGE = "我需要先恢复电源，然后才能这样做。",
	CHARGE_FULL = "当它已经充电时，这将不起作用。",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "多么令人震惊的结果！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "OW！ 多么令人震惊的结果！"

----UNDER THE WEATHER----
DESCRIBE.WINONA_TOOLBOX = "我的所有科学工具都有一个这样的工具。"
ACTIONFAIL.WINONATOOLBOX = "好吧，我从没说过这些是我的工具。"
DESCRIBE.WINONA_CATAPULT_ITEM = "我没有受过操作重型机械的训练。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "我没有受过操作重型机械的训练。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "我没有受过操作重型机械的训练。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "我没有受过操作重型机械的训练。"
DESCRIBE.POWERCELL = "这就像随身携带一个小电箱。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL =
"我当然知道这是怎么工作的！我自己也能做一个。"
DESCRIBE.MINERHAT_ELECTRICAL = "免提且由科学驱动！"
DESCRIBE.LANTERN_ELECTRICAL = "对灯笼的现代化改造。"
DESCRIBE.OCEAN_SPEAKER = "这看起来非常格格不入。" -- 真是个无聊的家伙。无聊的台词。

DESCRIBE.OCUPUS_BEAK = "我吃你好过你吃我好。"
DESCRIBE.OCUPUS_TENTACLE = "黏黏滑滑的"
DESCRIBE.OCUPUS_TENTACLE_EYE = "这里的每个人似乎都在看着我。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "看起来没那么糟糕……"
DESCRIBE.UM_OCUPUS_EYE = "我已经看过这个一千遍了，大怪物就在前面。"
DESCRIBE.UM_OCUPUS_EYETACLE = "寻找眼睛！"
DESCRIBE.UM_OCUPUS_TENTACLE = "它正试图让我们沉没，万岁。"
DESCRIBE.UM_OCUPUS_BEAK = "啊，看起来是奎肯的表弟。"
DESCRIBE.BEAKBASHER = "我把喙放在棍子上。现在怎么办？"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "它还活着！"

DESCRIBE.ARMOR_REED_UM = "戴上它我的脚仍然很轻盈。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "这让我感觉自己是头号掠食者。"
DESCRIBE.ROCKJAWLEATHER = "天气寒冷而且出奇的光滑。"

--DESCRIBE.UM_SIREN = "科学表明我们可以"帮助"彼此。"
-- 什么鬼的变种
--DESCRIBE.UM_SIREN = "科学表明她可能不是来自这里。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = "我觉得我还没能力照顾孩子！"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS = "我必须注意这些眼睛。"
DESCRIBE.UM_DEVILED_EGGS = "它们闻起来像是的味道。"
DESCRIBE.LUSH_ENTRANCE =
"看起来多么不祥的洞。"
DESCRIBE.CRITTER_FIGGY =
"嗯。我想我会称你为菲吉·牛顿·弗拉菲波顿十四世。"
DESCRIBE.GIANT_TREE_BIRDNEST = "这是个什么东西！"
ACTIONFAIL.UPGRADE.NOT_HARVESTED = "糟糕，我得先把它清理干净！"

DESCRIBE.SLUDGE = "它闻起来像鸡蛋，但看起来没有那么开胃。"
DESCRIBE.SLUDGE_OIL = "这样的东西曾经呆在我的实验室里。"
DESCRIBE.SLUDGE_SACK = "我希望它不会粘在我的背上。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM =
"它还是把事情搞砸了。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "它会反弹任何击中它的东西。"
DESCRIBE.BOAT_BUMPER_SLUDGE_KIT =
"一个更柔软的垫子，可以用来对付撞到我船的东西。"
DESCRIBE.BOATPATCH_SLUDGE = "另一种堵住漏洞的方法。"
DESCRIBE.UM_COPPER_PIPE = "金属管，难道来自一棵树？"
DESCRIBE.BRINE_BALM = "它能让伤口保持新鲜。这，这是不对的。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "里面有东西？"
DESCRIBE.UM_BEEGUN = "蜜蜂喜欢被大炮射出，对吗？"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE

DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "光是得到这个就太痛苦了。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "它是机械的，这意味着它更好。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "它更好，因为它是机械的。"
DESCRIBE.BOAT_BUMPER_COPPER =
"在它完成之前需要更多的打击。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "金属管相互粘在一起。"
DESCRIBE.UM_DREAMCATCHER =
"睡个好觉不再容易了，我希望这会有所帮助。"
DESCRIBE.UM_BRINEISHMOSS = "你不是我的苔藓！"
DESCRIBE.UM_COALESCED_NIGHTMARE = "那东西最好不要开始四处爬行。"
DESCRIBE.SLUDGE_CORK =
"它对船来说太大了。也许它可以塞点别的东西。"
DESCRIBE.SLUDGESTACK = "难闻的气味就是从那里来的吗？"
DESCRIBE.SPECTER_SHIPWRECK = "船失事了。" 

DESCRIBE.UNCOMPROMISING_HARPOON =
"从远处捅人从来没这么方便过"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "不像看起来那么重"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是交易。"
DESCRIBE.UM_MAGNERANG = "它会回来并带来一些东西。"
DESCRIBE.UM_MAGNERANGREEL = "科学很有吸引力。"
DESCRIBE.SIREN_THRONE =
"某事……或某人，似乎最近来过这里。"
DESCRIBE.LAVASPIT_SLUDGE = "哎呀，沸腾了！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "他们变成了一堵蜜不透蜂的墙！"

DESCRIBE.PORTABLEBOAT_ITEM = "科学将确定它是否漂浮。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "理论上它会产生光。"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "它会是一个很好的装饰吗？可能！"
DESCRIBE.UM_ORNAMENT_RAT = "老鼠没那么可怕！"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

-- WIXIE RELATED STRINGS
DESCRIBE.WIXIE_PIANO = "学习永远都不晚！"
DESCRIBE.WIXIE_CLOCK = "我们每天都做对两次。通常情况下。"
DESCRIBE.WIXIE_WARDROBE = "里面藏有黑暗的秘密。或者是...衣服"
DESCRIBE.CHARLES_T_HORSE = "这最好不要是骗人的。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "嘿嘿。"
DESCRIBE.SLINGSHOT_MATILDA = "她正在突破她的破窗记录。"
DESCRIBE.SLINGSHOT_GNASHER = "精确打击窗户。"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "肯定有滑倒的危险。"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,

    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,

    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "鱼腥味消失了。"
DESCRIBE.SMALLFISHMEAT_DRIED = "有点腥。"

DESCRIBE.WIXIEGUN = "科学走得太远"

ANNOUNCE.ATTACKED_CRABKING =
 "这壳太硬了！ 也许我应该改用船..."

DESCRIBE.MARA_BOSS1 = "呃..."
DESCRIBE.UM_WITCH = "添加了至尊灾厄。"
ANNOUNCE.GAS_DAMAGE = "咳！咳！"

-- Pyre Nettle stuff
DESCRIBE.UM_PYRE_NETTLES="一个新的标本！也许我应该仔细看看…"
DESCRIBE.UM_SMOLDER_SPORE="看起来有点摇晃！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN="我以为会发生什么？！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP="哦，它坏了！哦，它疯了！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES="植物不会怀疑任何事情！"
DESCRIBE.UM_BLOWDART_PYRE="这种感觉太棒了！"

-- Under the Weather Part 1
DESCRIBE.ALPHA_LIGHTNINGGOAT = "它会让我哀鸣！我是说，流血！"
DESCRIBE.UM_TORNADO = "抓紧你的帽子！"
DESCRIBE.UM_WATERFALL = "当你需要雨靴的时候在哪里？"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "周围没有龙卷风。"

DESCRIBE.UM_BOAT_ENGINE = {
    ON = "全速前进！",
    LOWFUEL = "油箱快空了。",
    OVERHEATING = "有点太热了！"
}
DESCRIBE.GARBAGEPATCHFLOTSAM = "一定是被那场龙卷风拖到这里来的！"

-- Broiling Hills
DESCRIBE.BOULDER_CRAB =
{
    GENERIC = "它不是石头！",
    NAKED = "我为它感到难过。",
}

DESCRIBE.BOULDER_CRAB_HOLE = "这是一个洞。"

DESCRIBE.UM_HOTSPRING = "它被熔岩加热。"

DESCRIBE.UM_PLANT_HOTSPRINGS = DESCRIBE.MARSH_PLANT --POND_ALGAE

DESCRIBE.ROCK_LICHEN =
{
    GENERIC = "它们喜欢潮湿的环境。",
    PICKED = "这个群体会重新生长。",
}

-- All things Snaildrake
DESCRIBE.SNAILDRAKE_MAGMA = "它们似乎有爆炸性的脾气。"
DESCRIBE.SNAILDRAKE_SLIME = DESCRIBE.SNAILDRAKE_MAGMA
DESCRIBE.SNAPALM = "我不确定拿着这个是否安全。"
DESCRIBE.SNAILDRAKEHAT = "它会弄乱我的发型。"
DESCRIBE.SNAILDRAKEBUCKET =
{
    GENERIC = "看起来可以装满。",
    WATER = "我打了一桶水。",
    LAVA = "烫手货。",
}
DESCRIBE.SNAILDRAKE_HOLE = "只是个洞。"

-- All things Rimeweed
DESCRIBE.RIMEWEED_MAIN = "那种杂草造成了这种藤蔓混乱。"
DESCRIBE.RIMEWEED_BARRIER = "看起来像一个带刺的冷锋。"

DESCRIBE.UM_RIMEWEED_ITEMVINE = "它带刺且触感冰冷。"
DESCRIBE.UM_RIMEWEED_ITEMFLOWER = "它出奇地耐寒。"

DESCRIBE.RIMEWEED_WHIP = "我会站在处理的一端。"

DESCRIBE.UM_RIMEWEED_TEQUILA = "天气太冷了享受不了。"
DESCRIBE.UM_RIMEWEED_SPAGETT = "脆脆的意大利面，不是我的首选。"

-- Lava Caves
DESCRIBE.MAGMAROCK1 = DESCRIBE.ROCKS
DESCRIBE.MAGMABONE = "我想知道虫子有没有碰到它。"

DESCRIBE.UM_COOKPOT_WAGSTAFF = {
    EMPTY = "你好，请勿坠毁",
    COOKING_LONG = DESCRIBE.COOKPOT.COOKING_LONG,
    COOKING_SHORT = DESCRIBE.COOKPOT.COOKING_SHORT,
    DONE = DESCRIBE.COOKPOT.DONE,
    BURNT = DESCRIBE.COOKPOT.BURNT,
}
DESCRIBE.UM_COOKPOT_WAGSTAFF_DISPLAY = "它显示某种食谱。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER = "也许我可以用这个做一些新实验。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER2 = "一遍又一遍地做同样的事情是非常科学的。"

DESCRIBE.UM_RICE_PUDDING = "一些普通的米饭布丁。"

DESCRIBE.UM_BOATBOTTLE = {
    FULL = "要么瓶子太小，要么船太大，因为我觉得船装不进去。",
    EMPTY = "如果我重新排列船上每个粒子，它还是同一条船吗?"
}

ANNOUNCE.ANNOUNCE_BUTTERFLY_SLIP = { "太滑了打不到。",
    "也许我应该等它停下来。",
    "它飞舞的时候我打不到。",
    "它休息时会更容易击中。",
    "如果它降落了可能更容易击中。" }

DESCRIBE.WATHGRITHR_SHIELD_DREADSTONE = "站在它身后，我无所畏惧！"

ANNOUNCE.ANNOUNCE_WEAPON_TOOWEAK_ICESHIELD = "我该用些热点话题来打破这层冰！"
DESCRIBE.UM_THULECITE_RAZOR = "铥矿剃刀！经典之作！"
DESCRIBE.UM_DURIAN_CREAM_MARSHCAKE = "这气味……具有统计学显著性。"
ANNOUNCE.ANNOUNCE_MARSHCAKE_BONUS = {
    SPRING = "新奇感肯定已被雨水冲刷殆尽。",
    SUMMER = "味道不错，但我本可以留到以后吃。",
    AUTUMN = "在这个季节品尝到的精致风味。",
    WINTER = "严冬中的一股热带异常气息！",
}
DESCRIBE.UM_BOOMBERRYPIE = "我对这个派喜爱至极。"
DESCRIBE.UM_CHILES_EN_NOGADA = "光是看着就让我垂涎欲滴！"