ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WALTER
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WALTER.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WALTER.ACTIONFAIL

--	[ 		Walter Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "嘿！别这样偷偷吓我！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "你需要我的帮助！还有你的身体..."
ANNOUNCE.ANNOUNCE_WINONAGEN = "我还没拿到‘把石头放进机器’的徽章呢。"
ANNOUNCE.ANNOUNCE_RATRAID = "听起来像是老鼠！"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "大家快把裤脚塞进袜子里！快！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "它们正在把我们的装备偷走！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "哎哟！这雨好刺痛！", "我以为‘一点水’不会伤害任何人！",
    "啊！我的皮肤！我需要避雨！"
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "我从没见过这样的蘑菇帽！"
-- FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = "叫我电击小子！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = "叫我电击侠！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "我有登山徽章，一点冷算不了什么！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我知道我不该这样做，但我还是做了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = "（叹气）看来我又只是沃尔特小子了..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = "（叹气）看来我又只是沃尔特小子了..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "我还是喜欢正常的温度。"
-- FoodBuffs

-- CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "我能应付得了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "沃...沃比？是你吗？"
DESCRIBE.CALIFORNIAKING = "我敢打赌沃托克斯吃不完这个！"
-- CaliforniaKing
DESCRIBE.FLORAL_BANDAGE = "这东西效果很强！"

ANNOUNCE.ANNOUNCE_RNEFOG = "哦哦哦哦，现在变得非常诡异了！"
DESCRIBE.UNCOMPROMISING_RAT = "我愿意分享，但它们似乎更喜欢直接抢走我们的东西。"
DESCRIBE.UNCOMPROMISING_RATHERD = "松树先锋从不头朝前进入鼠洞！"
DESCRIBE.UNCOMPROMISING_RATBURROW = "松树先锋从不头朝前进入鼠洞！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "哇！她挖洞的本事和沃比一样好！"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "她把所有东西都放在里面，希望她不介意分享。"

DESCRIBE.WINKY = {
    GENERIC = "哇！你是个狼人吗，%s？",
    ATTACKER = "嘿，不要咬人，%s！",
    MURDERER = "杀人鼠女的攻击！",
    REVIVER = "她是个好狼人！真是个大转折！",
    GHOST = "被狼人鬼魂缠身？这会是个很棒的故事！",
    FIRESTARTER = "我没想到你会生火！"
}
DESCRIBE.WATHOM = {
    GENERIC = "看，沃比！另一个会说话的怪物！",
    ATTACKER = "%s 很危险！",
    MURDERER = "跑，沃比！%s 变得狂野了！",
    REVIVER = "%s 是个好怪物！",
    GHOST = "哇！%s 有个很酷的鬼魂！",
    FIRESTARTER = "我知道你能听懂我说的话，%s！"
}
DESCRIBE.WIXIE = {
    GENERIC = "怎么了？你不想做朋友吗，%s？",
    ATTACKER = "暴力解决不了问题，%s！",
    MURDERER = "我觉得 %s 有问题！",
    REVIVER = "看，%s？帮助别人感觉很好！",
    GHOST = "松树先锋总是帮助需要帮助的人！即使他们很坏。",
    FIRESTARTER = "火不是开玩笑的，%s！请停止笑。"
}

DESCRIBE.RATPOISONBOTTLE = "如果没有其他选择..."
DESCRIBE.RATPOISON = "希望没有友好的生物误食..."

DESCRIBE.MONSTERSMALLMEAT = "对不起，沃比，看起来晚餐只有残羹剩饭..."
DESCRIBE.COOKEDMONSTERSMALLMEAT = "我尽力用现有的材料做了。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "沃比最喜欢的，只是小块的。"

DESCRIBE.UM_MONSTEREGG = "也许沃比会吃？希望她不介意壳..."
DESCRIBE.UM_MONSTEREGG_COOKED = "我希望能孵出一些酷东西。"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "我从没见过这样的蘑菇帽！"
DESCRIBE.TOADLING = "他能把我整个吞下...我还是保持距离吧。"

DESCRIBE.GASMASK = "臭味安全第一！"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "我觉得没有女王蜘蛛也能过得很好。"
ANNOUNCE.ANNOUNCE_SNEEZE = "啊啊啊嚏！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "我的过敏症又发作了！"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "回到正常的过敏水平。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
    "我觉得我们应该再复习一下火灾安全！",
    "地面变热了！", "保持冷静！"
}
ANNOUNCE.ANNOUNCE_ROOTING = "蔓延的藤蔓！我可以砍掉它们！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "我的直觉告诉我有暴风雪要来了！"
ANNOUNCE.SHADOWTALKER = {
    "我必须保护她", "我不应该这样做", "我不能放弃",
    "我很害怕"
}
ANNOUNCE.ANNOUNCE_OVER_EAT = {
    STUFFED = "松树先锋从不浪费食物，即使吃撑了...",
    OVERSTUFFED = "吃这么多食物是个坏主意！"
}
DESCRIBE.UM_SAND = "如果沙子重新出现，请嘲笑我忘记更改这个。"
DESCRIBE.UM_SANDHILL = "我不会把沙丘变成山。"
DESCRIBE.SNOWPILE = "清理这些时，铲子可以防止冻伤！"
DESCRIBE.SNOWGOGGLES = "它们有点大，但很暖和！"

DESCRIBE.SNOWMONG = "大挖洞的虫子和甲虫会反击大挖洞的虫子和猎犬--哇..."
DESCRIBE.SHOCKWORM = "不要碰它！它是一个活的电气危险！"
DESCRIBE.ZASPBERRY = "这个浆果有相当震撼的味道...呵呵。"
DESCRIBE.ZASPBERRYPARFAIT = "哦，甜点！"
DESCRIBE.ICEBOOMERANG = "不，沃比，不要捡这个！"
DESCRIBE.MINOTAUR_BOULDER = "小心滑坡！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "那个可能会伤到它！"
DESCRIBE.VETERANSHRINE = "我知道这是个坏主意，但我想进一步调查！"
DESCRIBE.VET_SKULL = "你怎么看，沃比？不死族？还是只是普通的死？"
DESCRIBE.UM_BOSS_SOUL = "你回来缠着我们了吗？酷！"
DESCRIBE.UM_DARK_VESTIGES = "我不知道这是什么，但很酷！"
DESCRIBE.UM_VOXOLOPHONE = "有任何恐怖故事给我吗？"

DESCRIBE.UM_EXHUMER = "哦！我有个完美的故事名字！‘被诅咒的掘墓人’的故事！"
DESCRIBE.UM_WINGSUIT = "我希望也能给你做一对，沃比！"
DESCRIBE.UM_MOONFLY_LANTERN = "你怎么看，沃比？外星魔法？"
DESCRIBE.PLAGUEMASK = "现在我可以和鸟类融为一体了！"
DESCRIBE.SPIDER_TRAPDOOR = "我告诉过你！"
DESCRIBE.TRAPDOOR = "小心，有些蜘蛛会用这些作为藏身之处！"
DESCRIBE.HOODEDTRAPDOOR = "记住那些蜘蛛！"
DESCRIBE.WICKER_TENTACLE = "我觉得它有毒，希望我能帮上忙..."
DESCRIBE.HONEY_LOG = "松树先锋知道不要尝试吃自己。"

DESCRIBE.BUSHCRAB = "完美的伪装！你真的骗到我了！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "一点自制的配方，来自大自然！"
DESCRIBE.RAT_TAIL = "我曾经见过一个女孩用这些做项链...我想我会放弃。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "我应该把这些缝在一起！"
DESCRIBE.AIR_CONDITIONER = "我们确定吸入蘑菇是个好主意吗？"
DESCRIBE.SPOREPACK = "只要有知识，任何东西都可以有用！"
DESCRIBE.SALTPACK = "这会处理雪堆，虽然我更喜欢自己动手！"

DESCRIBE.SKELETONMEAT = "我...我不喜欢关于人们在最绝望时的故事..."
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "哇！威尔逊，你怎么了？！"
DESCRIBE.VAMPIREBAT = "你一点也不像吸血鬼！"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "我们可以用一些月亮石建一个迷你动物收容所！"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "我曾是营地里最好的苍蝇拍。"

-- Swampyness
DESCRIBE.RICEPLANT = "肯定是另一个沼泽怪物！"
DESCRIBE.RICE = "在沼泽怪物的头发里找到的！"
DESCRIBE.RICE_COOKED = "看起来煮得不错。"
DESCRIBE.SEAFOODPAELLA = "我用各种沼泽里的东西做的！"
DESCRIBE.LICELOAF = "看起来像口粮！"
DESCRIBE.SUNGLASSES = "不错！"

DESCRIBE.STUMPLING = "哇！你看到了吗，沃比？"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "离家很远，对吧？沃比和我会陪着你！"
DESCRIBE.SHADOW_CROWN = "皇冠？松树先锋必须保持谦虚！"
DESCRIBE.UM_SHADOW_AXE = "我觉得有人在模仿我。"
DESCRIBE.POLLENMITEDEN = "这些小家伙传播得很快！"
DESCRIBE.POLLENMITES = "光是看着它们我的眼睛就开始流泪。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "当你习惯了额外的眼睛，它们其实挺可爱的。"
DESCRIBE.MARSH_GRASS = "我们可以躲在后面，我猜？"
DESCRIBE.CURSED_ANTLER = "一场值得讲述的战斗的纪念品！"
DESCRIBE.BERNIEBOX = "那是威洛的，我怕碰它会发生什么..."
DESCRIBE.HOODED_FERN = "叶子这么大，我们可以用它来收集雨水。"
DESCRIBE.HOODEDWIDOW = "哇！那可以吃掉任何东西！"
DESCRIBE.GIANT_TREE = "一棵红杉树！你可以从几英里外看到它！"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST
DESCRIBE.WIDOWSGRASP = "沃比，去拿！"

DESCRIBE.SILKSACK = "我想知道里面有没有小蜘蛛。"
DESCRIBE.SILKEN_BUNDLE = "我们的物资被困在里面了。"

DESCRIBE.WEBBEDCREATURE = "哦，我想知道里面有什么！"
ANNOUNCE.WEBBEDCREATURE = "我怎么让她帮我解开这个？"
DESCRIBE.SNAPDRAGON_BUDDY = "小心沃比！那些植物看起来很饿！"
DESCRIBE.SNAPDRAGON = "我从没见过这样的东西！"
DESCRIBE.SNAPPLANT = "它们真的很吸引人！"
DESCRIBE.WHISPERPOD = "我觉得它需要一些土壤！"
DESCRIBE.WHISPERPOD_NORMAL_GROUND = {
    GENERIC = "我觉得它需要一些种子！有吗，沃比？",
    GROWING = "我希望植物能像你一样快长大，沃比。"
}
DESCRIBE.FRUITBAT = "也许我们运气好，它会把我变成水果！"
DESCRIBE.PITCHERPLANT = "里面有什么在动吗？"
DESCRIBE.APHID = "它毛茸茸的！"
DESCRIBE.NYMPH = "我想知道它们在做什么？"
DESCRIBE.GIANT_TREE_INFESTED = "快出来！"
DESCRIBE.GIANT_BLUEBERRY = "幸好松树先锋的制服是防污的！"
DESCRIBE.BLUEBERRYPANCAKES = "啊，甜美的食物！"
DESCRIBE.DEVILSFRUITCAKE = "对不起，沃比，巧克力对狗不好！"
DESCRIBE.SIMPSALAD = "松树先锋总是吃他的...呃...紫色的东西！"
DESCRIBE.BEEFALOWINGS = "好久没吃热翅了！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我站稳了！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "我又失去平衡了！"
DESCRIBE.WIDOWSHEAD = "别担心沃比，是我！"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "我听说过南瓜头，但从没听说过瓜头！"

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "我想知道它是怎么做的！"
DESCRIBE.VIPERFRUIT = "我一直想要一条宠物蛇！"
DESCRIBE.VIPERFRUIT_LESSER = DESCRIBE.VIPERFRUIT
DESCRIBE.VIPERJAM = "我希望能有一些花生酱和果酱。"

DESCRIBE.BLUEBERRYPLANT = {
    READY = "哇！这里的一切都很大！",
    FROZE = "它冻住了，真酷！",
    REGROWING = "它会回来，对吧？"
}

DESCRIBE.ANTIHISTAMINE = "它会防止我的过敏症发作！"
ANNOUNCE.CURSED_ITEM_EQUIP = "哎哟！急救箱在哪里！"
DESCRIBE.VETSITEM = "需要更多的诅咒吗？希望如此！"
DESCRIBE.SCREECHER_TRINKET = "我们的童子军领队告诉我们要远离这样的符号。"
ACTIONFAIL.GIVE.NOTNIGHT = "我觉得月亮的力量在月亮在场时效果最好。"

DESCRIBE.MAGMAHOUND = "你不应该玩火！"
DESCRIBE.LIGHTNINGHOUND = "这不是普通的闪电，这是高级闪电！"
DESCRIBE.SPOREHOUND = "离开沃比！他可能有传染病！"
DESCRIBE.GLACIALHOUND = "酷朋友，沃比！"
DESCRIBE.RNESKELETON = "你好！是什么故事让你变成这样的？"
DESCRIBE.RAT_WHIP = "有创意！...呃。"
DESCRIBE.KLAUS_AMULET = "山羊的力量！"
DESCRIBE.CRABCLAW = "他留下了他的爪子！"
DESCRIBE.HAT_RATMASK = "小心，这里来了鼠人！"

DESCRIBE.ORANGE_VOMIT = "谢谢你分享你的消化液？"
DESCRIBE.GREEN_VOMIT = "谢谢你分享你的消化液？"
DESCRIBE.RED_VOMIT = "谢谢你分享你的消化液？"
DESCRIBE.PINK_VOMIT = "谢谢你分享你的消化液？"
DESCRIBE.YELLOW_VOMIT = "谢谢你分享你的消化液？"
DESCRIBE.PURPLE_VOMIT = "谢谢你分享你的消化液？"
DESCRIBE.PALE_VOMIT = "谢谢你分享你的消化液？"

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = {
    GUARD = DESCRIBE.PIGMAN.GUARD,
    WEREPIG = DESCRIBE.PIGMAN.WEREPIG
}
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH

DESCRIBE.BIGHT = "你在漏水！你真的应该修好它。"
DESCRIBE.KNOOK = "它真的很吓人！"
DESCRIBE.ROSHIP = "哇，你真吓人！你能停止射击我了吗？"

DESCRIBE.UM_PAWN = "不要靠得太近，沃比。"
DESCRIBE.UM_PAWN_NIGHTMARE = "不要靠得太近，沃比。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "我还是想避免受伤。"
DESCRIBE.UM_BEAR_TRAP = "通常这些是用来对付，呃，熊的。"
DESCRIBE.UM_BEAR_TRAP_OLD = "谁把他们的装备留在这里了？"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "通常这些是用来对付，呃，熊的。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "通常这些是用来对付，呃，熊的。"
DESCRIBE.CORNCAN = "哦，玉米！"
DESCRIBE.SKULLCHEST_CHILD = "沃托克斯曾经从里面跳出来！"

DESCRIBE.SLOBBERLOBBER = "营地里不准吐痰！"
DESCRIBE.GORE_HORN_HAT = "像犀牛一样思考，像犀牛一样撞东西！"
DESCRIBE.BEARGERCLAW = "大自然的设计。"
DESCRIBE.FEATHER_FROCK = "我一直想知道变成鸟是什么感觉！"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM .. "\n它全都刻上了！"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM .. "\n它全都刻上了！"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM .. "\n它全都刻上了！"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM .. "\n它全都刻上了！"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM .. "\n它全都刻上了！"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM .. "\n它全都刻上了！"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM .. "\n它全都刻上了！"

DESCRIBE.RED_MUSHED_ROOM = "我不确定它被捣碎后会不会更好。"
DESCRIBE.GREEN_MUSHED_ROOM = "我不确定它被捣碎后会不会更好。"
DESCRIBE.BLUE_MUSHED_ROOM = "我不确定它被捣碎后会不会更好。"

DESCRIBE.SHADOW_TELEPORTER = "好奇！"

-- StantonStuff
DESCRIBE.SKULLFLASK = "酷！"
DESCRIBE.SKULLFLASK_EMPTY = "没有了！"
DESCRIBE.STANTON_SHADOW_TONIC = "我不应该..."
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "哦，对不起，先生，但我不允许喝酒！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "嗯，它什么也没做。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = ""
-- StantonStuff

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "这会和一些娱乐活动一起很好。"
DESCRIBE.DEERCLOPS_BARRIER = "有些冰看起来更弱。"

DESCRIBE.MOONMAW_DRAGONFLY = "看看那些锋利的边缘！"
DESCRIBE.MOONMAW_LAVAE = "非常锋利，非常快！"
DESCRIBE.SNAPPERTURTLE = "看！一只咬人的乌龟！这些家伙可以轻易咬掉你的手指！"
DESCRIBE.SNAPPERTURTLEBABY = "不要低估那些下巴-沃比不！"
DESCRIBE.SNAPPERTURTLENEST = "看起来它们在这里筑巢！"
DESCRIBE.GLASS_SCALES = "我从没见过这样的东西！"
DESCRIBE.MOONGLASS_GEODE = "它不像玻璃那样反光。它一定是石头！"
DESCRIBE.ARMOR_GLASSMAIL = "我无懈可击！"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "不，沃比，退后！"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE
DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "我以前在徒步旅行时到处都能看到它们！"
DESCRIBE.SNOTROAST = "你想要这个吗，沃比？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我觉得我要吐了..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "呃...我感觉好多了。"
DESCRIBE.BOOK_RAIN_UM = "让我想起过去的一次露营旅行。"
DESCRIBE.DORMANT_RAIN_HORN = "如果你把它放在耳边，你可以听到海洋的声音！"
DESCRIBE.RAIN_HORN = "这可能在天气热的时候有用。"
DESCRIBE.DRIFTWOODFISHINGROD = "鱼似乎喜欢它。"

ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
    LEVEL_1 = "如果把东西留在地上，所有的东西可能会被偷走！"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
    LEVEL_1 = "松树先锋应该保持食物新鲜并妥善存放！"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
    LEVEL_1 = "闻到了吗，沃比？那里有一堆老鼠！"
}

DESCRIBE.PIED_RAT = "小声点，你可能会伤到沃比的耳朵！"
DESCRIBE.PIED_PIPER_FLUTE = "沃比不想让我吹这个。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "哇，他可能是个很棒的松树先锋！"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "我最好在这个东西爆炸前找到坚实的地面！"

ACTIONFAIL.CHARGE_FROM = {
    NOT_ENOUGH_CHARGE = "需要换一对新电池吗？",
    CHARGE_FULL = "它已经充满电了。"
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "哇！我觉得我差点被电到了。"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "哇！我觉得我差点被电到了。"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "我想知道里面有什么小工具和装置。"
ACTIONFAIL.WINONATOOLBOX = "我还没有这个徽章。"
DESCRIBE.WINONA_CATAPULT_ITEM_UM = "机器不在松树先锋的课程中。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM_UM = "机器不在松树先锋的课程中。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM_UM = "机器不在松树先锋的课程中。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM_UM = "机器不在松树先锋的课程中。"
DESCRIBE.POWERCELL = "这安全吗？"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "它在供电时会更有用。"
DESCRIBE.MINERHAT_ELECTRICAL = "不要咬这个小电箱，好吗，女孩？它可能会伤到你！"
DESCRIBE.LANTERN_ELECTRICAL = "可靠的光源是任何露营旅行的必需品！"
DESCRIBE.OCEAN_SPEAKER = "我想知道沃比能不能听到它的频率。"
-- DESCRIBE.UM_SIREN = "哇！！一个真正的海怪！！"

DESCRIBE.OCUPUS_BEAK = "克拉肯的嘴！"
DESCRIBE.OCUPUS_TENTACLE = "呃，沃比，你要这个吗？"
DESCRIBE.OCUPUS_TENTACLE_EYE = "它还在四处张望。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "至少现在可以接受了，我想。"
DESCRIBE.UM_OCUPUS_EYE = "有人在找东西咬。"
DESCRIBE.UM_OCUPUS_EYETACLE = "我们的唯一希望就是去攻击那些！"
DESCRIBE.UM_OCUPUS_TENTACLE = "我们不是你的食物！"
DESCRIBE.UM_OCUPUS_BEAK = "克拉肯出现了！"
DESCRIBE.BEAKBASHER = "这会打破更多的东西，不是吗，沃比？"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "我们做了什么，沃比？"

DESCRIBE.ARMOR_REED_UM = "它可能会帮助我融入环境。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "我不需要帮助游泳！"
DESCRIBE.ROCKJAWLEATHER = "哇，真正的鲨鱼皮。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = "我用友好的眼睛看到了...我看到了..."
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS = "如果我闭上眼睛吞下去，也许味道会更好！"
DESCRIBE.UM_DEVILED_EGGS = "味道很糟糕！明白了吗？...你明白了。"
DESCRIBE.LUSH_ENTRANCE = "我不确定我现在想不想下去，沃比..."
DESCRIBE.CRITTER_FIGGY = "沃比想和你玩，菲吉！"
DESCRIBE.GIANT_TREE_BIRDNEST = "沃比，别碰那些蛋！" -- 沃比你这个婊子不要吃蛋
ACTIONFAIL.UPGRADE.NOT_HARVESTED = "始终保持设备清洁整齐！"

DESCRIBE.SLUDGE = "一团臭臭的东西？"
DESCRIBE.SLUDGE_OIL = "这是一些油腻的油。"
DESCRIBE.SLUDGE_SACK = "它会保管我不想被偷的东西！"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "也许这就是固体火的样子。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "它让我想起了橡皮筏！"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "安全第一！"
DESCRIBE.BOATPATCH_SLUDGE = "最好的洞是堵住的洞。"
DESCRIBE.UM_COPPER_PIPE = "金属加工不在我的训练范围内..."
DESCRIBE.BRINE_BALM = "也许我应该坚持用绷带。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "哦，里面有虫子吗？"
DESCRIBE.UM_BEEGUN = "保持敌人近在咫尺，对吧？" -- 请让沃尔特装备这个时每分钟失去20点理智，我觉得这会是一个很酷的特色
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "得到这个真是个麻烦。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "未来就是现在！"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "我更喜欢一个漂亮的木制方向盘。"
DESCRIBE.BOAT_BUMPER_COPPER = "这会让我们安全！"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "加强周边防护！"
DESCRIBE.UM_DREAMCATCHER = "我读过这些！希望它们有效..."
DESCRIBE.UM_BRINEISHMOSS = "它看起来像毛毛虫。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "这是我的噩梦的样子吗？真的没那么吓人。"
DESCRIBE.SLUDGE_CORK = "一个超大浴缸的塞子！"
DESCRIBE.SLUDGESTACK = "那是什么东西？我不认识..."
DESCRIBE.SPECTER_SHIPWRECK = "希望它是闹鬼的！"

DESCRIBE.UNCOMPROMISING_HARPOON = "从远处刺东西从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是真正的卷轴。"
DESCRIBE.UM_MAGNERANG = "它总能找到回来的路！"
DESCRIBE.UM_MAGNERANGREEL = "我们确定它不会引发森林火灾吗？"
DESCRIBE.SIREN_THRONE = "看，沃比！一块石头！" -- 傻孩子。
DESCRIBE.LAVASPIT_SLUDGE = "小心，沃比！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "没关系，我本来也不打算靠得太近！"

DESCRIBE.PORTABLEBOAT_ITEM = "我学会了用树枝和绳子做筏子，但不是这个！"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "这就是自然的力量！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "我喜欢这些小家伙！希望我们北方有更多..."
DESCRIBE.UM_ORNAMENT_RAT = "独自一人，小家伙？"

DESCRIBE.TRINKET_WATHOM1 = "这是...宝藏？我想？是吗？？"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

-- WIXIE RELATED STRINGS

DESCRIBE.WIXIE_PIANO = "钢琴课不在我的训练范围内！"
DESCRIBE.WIXIE_CLOCK = "可惜它坏了，滴答作响的钟增加了恐怖故事的紧张感！"
DESCRIBE.WIXIE_WARDROBE = "让我想起了我听过的一个广播剧，‘走廊尽头的鬼衣橱’，它讲的是-"
DESCRIBE.CHARLES_T_HORSE = "你觉得它被诅咒了吗，沃比？"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "我不能被看到玩孩子的玩具！"
DESCRIBE.SLINGSHOT_MATILDA = "三发？那是三只眼睛！"
DESCRIBE.SLINGSHOT_GNASHER = "有人可能会用这个射中他们的眼睛！"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "我想不出这些有什么实际用途。"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,

    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,

    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT
}
DESCRIBE.FISHMEAT_DRIED = "这是个很棒的小吃，如果你不介意味道的话！"
DESCRIBE.SMALLFISHMEAT_DRIED = "一口大小的营养小吃！"

DESCRIBE.WIXIEGUN = "这不是松树先锋批准的！"

DESCRIBE.MARA_BOSS1 = "它活了！！"
ANNOUNCE.GAS_DAMAGE = "咳！咳！" --TODO

-- Pyre Nettle stuff
DESCRIBE.UM_PYRE_NETTLES = "好吧，那绝对是有毒的。"
DESCRIBE.UM_SMOLDER_SPORE = "也许我们可以仔细看看..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "啊！！那不是可食用的！！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "火！火！！绝对不是我的错！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "工艺真是惊人！就像叶子从未分开过一样！"
DESCRIBE.UM_BLOWDART_PYRE = "我要没收这些。"

-- Under the Weather Part 1
DESCRIBE.ALPHA_LIGHTNINGGOAT = "小心沃比！这只山羊看起来很凶！"
DESCRIBE.UM_TORNADO = "钉住我们的装备！蹲下掩护！跑啊！！"
DESCRIBE.UM_WATERFALL = "我喜欢一个好的瀑布！"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有龙卷风，我能感觉到！"

DESCRIBE.UM_BOAT_ENGINE = {
    ON = "请写一些引语",
    LOWFUEL = "请写一些引语",
    OVERHEATING = "请写一些引语"
}

-- Broiling Hills
DESCRIBE.BOULDER_CRAB = {
    GENERIC = "这不是一块石头！",
    NAKED = "我为它感到难过。",
}

DESCRIBE.BOULDER_CRAB_HOLE = "这是一个洞。"

DESCRIBE.UM_HOTSPRING = "它是由熔岩加热的。"

DESCRIBE.UM_PLANT_HOTSPRINGS = DESCRIBE.MARSH_PLANT --POND_ALGAE

DESCRIBE.ROCK_LICHEN = {
    GENERIC = "它们喜欢潮湿。",
    PICKED = "菌落会随着时间重新生长。",
}

-- All things Snaildrake
DESCRIBE.SNAILDRAKE_MAGMA = "它们似乎有爆炸的性格。"
DESCRIBE.SNAILDRAKE_SLIME = DESCRIBE.SNAILDRAKE_MAGMA
DESCRIBE.SNAPALM = "我不确定拿着这个是否安全。"
DESCRIBE.SNAILDRAKEHAT = "它会弄乱我的头发。"
DESCRIBE.SNAILDRAKEBUCKET = {
    GENERIC = "看起来可以装满。",
    WATER = "我已经取了一桶水。",
    LAVA = "热东西。",
}
DESCRIBE.SNAILDRAKE_HOLE = "只是一个洞。"

-- All things Rimeweed
DESCRIBE.RIMEWEED_MAIN = "那杂草正在制造这种藤蔓混乱。"
DESCRIBE.RIMEWEED_BARRIER = "看起来像一个刺冷锋。"

DESCRIBE.UM_RIMEWEED_ITEMVINE = "它摸起来又刺又冷。"
DESCRIBE.UM_RIMEWEED_ITEMFLOWER = "它出奇的坚韧。"

DESCRIBE.RIMEWEED_WHIP = "我会站在它的处理端。"

DESCRIBE.UM_RIMEWEED_TEQUILA = "太冷了，无法享受。"
DESCRIBE.UM_RIMEWEED_SPAGETT = "脆脆的意大利面，不是我的首选。"

-- Lava Caves
DESCRIBE.MAGMAROCK1 = DESCRIBE.ROCKS
DESCRIBE.MAGMABONE = "我想知道虫子是否吃了它。"

DESCRIBE.UM_COOKPOT_WAGSTAFF = {
    EMPTY = "嘿，瓦格，你在煮那个水晶吗？",
    COOKING_LONG = DESCRIBE.COOKPOT.COOKING_LONG,
    COOKING_SHORT = DESCRIBE.COOKPOT.COOKING_SHORT,
    DONE = DESCRIBE.COOKPOT.DONE,
    BURNT = DESCRIBE.COOKPOT.BURNT,
}
DESCRIBE.UM_COOKPOT_WAGSTAFF_DISPLAY = "嗯...多么有趣的展示。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER = "给我另一个尝试新食谱的机会。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER2 = "这个食谱会保持这样。"

DESCRIBE.UM_RICE_PUDDING = "它有巧克力味吗？"

DESCRIBE.UM_BOATBOTTLE = {
    FULL = "我们去找一艘船放进去吧！",
    EMPTY = "记住，沃比，只有在紧急情况下才打破它。"
}

ANNOUNCE.ANNOUNCE_BUTTERFLY_SLIP = {
    "当它们忙的时候抓住它们要容易得多。",
    "我知道不要试图抓住还在飞的蝴蝶。",
    "看，沃比，这次我抓到了！哎呀，也许没有。",
    "来吧，我通常很擅长这个！下次我得偷偷靠近它。",
    "它降落时我会抓住它。这次肯定行！"
}

DESCRIBE.WATHOM_CORPSE = "看，沃比！他还在呼吸！"

DESCRIBE.WATHGRITHR_SHIELD_DREADSTONE = "盾牌没有什么可怕的！"
ANNOUNCE.ANNOUNCE_WEAPON_TOOWEAK_ICESHIELD = "作家们，请在这里写一些聪明的话。\n提到你需要火或其他东西，我不知道"
