ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WANDA
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WANDA.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WANDA.ACTIONFAIL

--	[ 		Wanda Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "这可不是平常那些烦人的家伙..."
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "什么。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "我还没时间学习这些东西。"
ANNOUNCE.ANNOUNCE_RATRAID = "去烦别人吧！"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "为什么偏偏是现在？！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "那些都是重要的材料！我觉得是..."
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "这雨在腐蚀时间流！", "啊！好疼！",
    "这雨除了麻烦什么都不是！"
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "有什么不祥的东西在蠢蠢欲动。"
-- FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "呼...希望值得这么做！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "现在已经无法回头了..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "啊，终于恢复正常了。"
ANNOUNCE.ANNOUNCE_RNEFOG = "有什么东西在那里...某种新事物..."
-- FoodBuffs

-- CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "哦，真是麻烦..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "这段经历将永远困扰着我的时间线。"
DESCRIBE.CALIFORNIAKING = "在任何时间线里我都不会觉得这东西有吸引力。"
-- CaliforniaKing

DESCRIBE.UNCOMPROMISING_RAT = "嘘！离这儿远点！"
DESCRIBE.UNCOMPROMISING_RATHERD = "它们是怎么找到时间这么快繁殖的？"
DESCRIBE.UNCOMPROMISING_RATBURROW = "你们是把我的钟藏在这里了吗？"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "这东西造得不够持久。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "至少这个还在帮忙。虽然我宁愿不冒这个险。"

DESCRIBE.WINKY = {
    GENERIC = "我想这个时间线出了点问题。",
    ATTACKER = "你在干什么，%s？",
    MURDERER = "够了！我会把你送回你来的洞里，%s！",
    REVIVER = "谢谢你，%s，但我还是会盯着你。",
    GHOST = "也许这样更好。",
    FIRESTARTER = "她在她的路上留下了毁灭！"
}
DESCRIBE.WATHOM = {
    GENERIC = "%s 是过去的遗物。",
    ATTACKER = "%s 在制造麻烦。",
    MURDERER = "你会希望你能收回它，%s！",
    REVIVER = "%s 似乎对我有计划！",
    GHOST = "被影子影响了，%s？别担心，我会很快把你带回来！",
    FIRESTARTER = "%s 正以不同的方式处理问题。"
}
DESCRIBE.WIXIE = {
    GENERIC = "%s 让我想从这个时间线跳出去。",
    ATTACKER = "尊重点，%s！",
    MURDERER = "暴力的年轻人是这里的一个问题！",
    REVIVER = "你的目的是什么，%s？",
    GHOST = "我想我会慢慢把你带回来，%s。",
    FIRESTARTER = "她太鲁莽了！"
}

DESCRIBE.RATPOISONBOTTLE = "很抱歉必须这样做。"
DESCRIBE.RATPOISON = "你们的时间到了，小家伙们..."

DESCRIBE.MONSTERSMALLMEAT = "一口大小的毒药。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "这看起来仍然没有吸引力。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "希望经过这么长时间后它变得更好了。"

DESCRIBE.UM_MONSTEREGG = "给它足够的时间，它可能会变成某种异形。"
DESCRIBE.UM_MONSTEREGG_COOKED = "我无法判断它是否更好了。"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "最糟糕的情况。"
DESCRIBE.TOADLING = "后代？这...是新的。"

DESCRIBE.GASMASK = "啊，这将是一个清新的新造型！"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "只是时间问题，某些更糟糕的事情会发生..."
ANNOUNCE.ANNOUNCE_SNEEZE = "阿嚏！我的天啊！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "过敏...我害怕这一年中的这个时候。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "啊，清新的空气...终于！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
    "看来这头狮子学会了一些新把戏！",
    "麻烦事越来越多了！", "大家小心脚下！"
}
ANNOUNCE.ANNOUNCE_ROOTING = "倒带，倒带！！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "风越来越大了，我想暴风雪要来了！"
ANNOUNCE.SHADOWTALKER = {
    "滴答，滴答，滴答，滴答", "时间在流逝...",
    "我只是需要更多的时间", "它们都在我周围"
}
ANNOUNCE.ANNOUNCE_OVER_EAT = {
    STUFFED = "wacky's inflation fantasy has taken over",
    OVERSTUFFED = "BRAPPING"
}
-- DESCRIBE.UM_SAND = "Lots of tiny, tiny stones."
-- DESCRIBE.UM_SANDHILL = "The sand has formed a small pile."
DESCRIBE.SNOWPILE = "是时候清理了！"
DESCRIBE.SNOWGOGGLES = "我的未来变得更加清晰了。"

DESCRIBE.SNOWMONG = "也许那些堆积物确实值得我的时间！"
DESCRIBE.SHOCKWORM = "这是一个新把戏！"
DESCRIBE.ZASPBERRY = "如果非要我说的话，不如一个发条浆果。"
DESCRIBE.ZASPBERRYPARFAIT = "一种让嘴巴发麻的甜点！"
DESCRIBE.ICEBOOMERANG = "如果我用得不对，它可能会把我冻住。"
DESCRIBE.MINOTAUR_BOULDER = "停下！你可能会把整个地方埋了！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "哦，你正在制造一个巨大的混乱！"
DESCRIBE.VETERANSHRINE = "哦，我对此有一种不好的预感..."
DESCRIBE.VET_SKULL = "这个人的时钟早已停止。"
DESCRIBE.UM_BOSS_SOUL = "里面有某种东西在徘徊。"
DESCRIBE.UM_DARK_VESTIGES = "它在不断移动..."
DESCRIBE.UM_VOXOLOPHONE = "我无法判断它是什么时候制造的，也无法判断是谁制造的..."

DESCRIBE.UM_EXHUMER = "我想某些东西*确实*可以将死亡的时钟倒转。"
DESCRIBE.UM_WINGSUIT = "早起的鸟儿有虫吃，或者他们是这么说的。"
DESCRIBE.UM_MOONFLY_LANTERN = "非常方便。"

DESCRIBE.RAT_TAIL = "它就...直接掉下来了！"
DESCRIBE.PLAGUEMASK = "它看起来太滑稽了！我必须试试！"
DESCRIBE.SPIDER_TRAPDOOR = "它整天都在等着有人经过吗？"
DESCRIBE.TRAPDOOR = "一个更不显眼的巨石。"
DESCRIBE.HOODEDTRAPDOOR = "那块石头有点问题，我只是记不起来了..."
DESCRIBE.WICKER_TENTACLE = "它看起来比我记得的更糟糕。"
DESCRIBE.HONEY_LOG = "那是...甜的。"

DESCRIBE.BUSHCRAB = "啊！你什么时候到这儿的？！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "逆转疾病。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "一个整体的一部分。"
DESCRIBE.AIR_CONDITIONER = "为什么我会想把蘑菇喷到空气中？"
DESCRIBE.SPOREPACK = "它会把孢子传播到所有东西上。恶心！"
DESCRIBE.SALTPACK = "节省铲雪的时间。"



DESCRIBE.SKELETONMEAT = "有点令人不安，但将来可能有用。"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "影子已经抓住了你！"
DESCRIBE.VAMPIREBAT = "离我远点！我的头发绝对装不下你这么大的东西！"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "也许一块月岩可以修复它。"
DESCRIBE.CHARLIEPHONOGRAPH_100 = "我以前听过这个曲子吗？"
DESCRIBE.BUGZAPPER = "有助于防止虫子进入我的头发。"

-- Swampyness
DESCRIBE.RICEPLANT = "有趣，我以前没见过这些..."
DESCRIBE.RICE = "单独煮可能是浪费时间。"
DESCRIBE.RICE_COOKED = "我应该听从自己的建议。"
DESCRIBE.SEAFOODPAELLA = "它的气味清理了我的鼻子。"
DESCRIBE.LICELOAF = "不算是巨大的浪费时间，我想。"
DESCRIBE.SUNGLASSES = "是时候换一副新眼镜了。"

DESCRIBE.STUMPLING = "试图节省时间反而咬了我一口！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "这是什么时候掉下来的？"
DESCRIBE.SHADOW_TELEPORTER = "哦，你真是诱人..."
DESCRIBE.POLLENMITEDEN = "它们会在不久的时间内繁殖。"
DESCRIBE.POLLENMITES = "别想在我的头发里筑巢！"
DESCRIBE.SHADOW_CROWN = "它让我感到如此...特权。"
DESCRIBE.UM_SHADOW_AXE = "对同时在多个地方的一个初步解决方案。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "哦，真是麻烦，你怎么了？"
DESCRIBE.MARSH_GRASS = "我以为这些东西已经随着时间消失了。"
DESCRIBE.CURSED_ANTLER = "对我的口味来说是相当粗糙的工具。"
DESCRIBE.BERNIEBOX = "这是一个我会留给微洛的谜团。" -- unused, unedited
DESCRIBE.HOODED_FERN = "对蕨类植物的新尝试。"
DESCRIBE.HOODEDWIDOW = "麻烦，她太大了！"
DESCRIBE.GIANT_TREE = "它们有相当长的时间生长。"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST

DESCRIBE.WIDOWSGRASP = "可能会松开那些茧。"

DESCRIBE.SILKSACK = "里面的一些丝绸可以压缩我们的物资。"
DESCRIBE.SILKEN_BUNDLE = "粘稠地保存以便高效运输。"

DESCRIBE.WEBBEDCREATURE = "我猜是为了以后保存。"
ANNOUNCE.WEBBEDCREATURE = "我需要更合适的东西，否则我只是浪费时间。"
DESCRIBE.SNAPDRAGON_BUDDY = "我自己的时间节省者！"
DESCRIBE.SNAPDRAGON = "我觉得你不是这里的。"
DESCRIBE.SNAPPLANT = "多么美丽，难怪金鱼草被它吸引了！"
DESCRIBE.WHISPERPOD = "更多的园艺？真是麻烦..."
DESCRIBE.WHISPERPOD_NORMAL_GROUND = {
    GENERIC = "还需要什么？一些种子，也许？",
    GROWING = "没关系，慢慢来。"
}
DESCRIBE.FRUITBAT = "一个厌倦了被束缚的浆果。"
DESCRIBE.PITCHERPLANT = "它超出了我的掌握。"
DESCRIBE.APHID = "它们的寿命如此短暂，却浪费在吃叶子上..."
DESCRIBE.NYMPH = "给它足够的时间成熟并成长为一个领导者。"
DESCRIBE.GIANT_TREE_INFESTED = "它是变老了，还是有其他事情在发生？"
DESCRIBE.GIANT_BLUEBERRY = "解除武装，可以吃了。"
DESCRIBE.BLUEBERRYPANCAKES = "糖浆花了一些甜蜜的时间，但每一秒都值得。"
DESCRIBE.DEVILSFRUITCAKE = "看起来像一生的糖分。"
DESCRIBE.SIMPSALAD = "这是一个可怕的浪费时间。"
DESCRIBE.BEEFALOWINGS = "我不知道，这看起来对我的胃来说太重了。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "你不会把我击倒，哪怕一百万年！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "一百万年可能是夸张了。"
DESCRIBE.WIDOWSHEAD = "戴上这样的东西真是太阴沉了。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = DESCRIBE.PUMPKIN_LANTERN

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "它被燃料影响了。"
DESCRIBE.VIPERFRUIT = "尝起来像影子。"
DESCRIBE.VIPERFRUIT_LESSER = DESCRIBE.VIPERFRUIT
DESCRIBE.VIPERJAM = "我很想直接从罐子里吃。"

DESCRIBE.BLUEBERRYPLANT = {
    READY = "小心点...",
    FROZE = "它的时钟停止了。",
    REGROWING = "给它时间，它会回来。"
}

DESCRIBE.ANTIHISTAMINE = "可能会提供一些过敏保护，暂时的。"
ANNOUNCE.CURSED_ITEM_EQUIP = "啊！它不适合未被诅咒的手。"
DESCRIBE.VETSITEM = "它不适合未被诅咒的手。"
DESCRIBE.SCREECHER_TRINKET = "它来自另一个时间线。"
ACTIONFAIL.GIVE.NOTNIGHT = "需要月亮出来。"

DESCRIBE.MAGMAHOUND = "别对我流口水！"
DESCRIBE.LIGHTNINGHOUND = "你无法控制闪电！别试了！"
DESCRIBE.SPOREHOUND = "哦，真是麻烦，蘑菇也感染了猎犬。"
DESCRIBE.GLACIALHOUND = "如此威胁的外表。"
DESCRIBE.RNESKELETON = "你已经逗留得太久了。"
DESCRIBE.RAT_WHIP = "一个将我的食物变成战斗的鞭子。"
DESCRIBE.KLAUS_AMULET = "双倍时间！"
DESCRIBE.CRABCLAW = "将宝石变成力量，就像它的前身一样。"
DESCRIBE.HAT_RATMASK = "哈！一个老鼠面具？我怎么能抗拒不戴它呢？"

DESCRIBE.ORANGE_VOMIT = "恶心！"
DESCRIBE.GREEN_VOMIT = "恶心！"
DESCRIBE.RED_VOMIT = "恶心！"
DESCRIBE.PINK_VOMIT = "恶心！"
DESCRIBE.YELLOW_VOMIT = "恶心！"
DESCRIBE.PURPLE_VOMIT = "恶心！"
DESCRIBE.PALE_VOMIT = "恶心！"

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = {
    GUARD = DESCRIBE.PIGMAN.GUARD,
    WEREPIG = DESCRIBE.PIGMAN.WEREPIG
}
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH

DESCRIBE.BIGHT = "哦，那是相当可怕的展示！"
DESCRIBE.KNOOK = "它远远超出了挽救的范围，并渴望鲜血！"
DESCRIBE.ROSHIP = "只是时间问题，我就会被镀锌了！"

DESCRIBE.UM_PAWN = "小心，它是一个行走的闹钟。"
DESCRIBE.UM_PAWN_NIGHTMARE = "小心，它是一个滴答作响的定时炸弹。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "它在我活着的时候不会帮到我。"
DESCRIBE.UM_BEAR_TRAP = "我不喜欢被困在一个地方。"
DESCRIBE.UM_BEAR_TRAP_OLD = "我不喜欢被困在一个地方。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "一个让敌人困住的好方法。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "一个陷阱，但 somehow 更加诱人走进去。"
DESCRIBE.CORNCAN = "罐头充当了一个时间泡泡，保护里面的东西。"
DESCRIBE.SKULLCHEST_CHILD = "里面的东西可以在多个时间点存在。"

DESCRIBE.SLOBBERLOBBER = "一种野蛮的方式将任何东西变成灰烬。"
DESCRIBE.GORE_HORN_HAT = "它将影子变成速度！"
DESCRIBE.BEARGERCLAW = "我真的有时间挖整个地球吗？"
DESCRIBE.FEATHER_FROCK = "时间飞逝，我也会飞！"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM ..
    "\n...它的切割是错误的！只有蟹爪可以引导它的力量。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM ..
    "\n...它的切割是错误的！只有蟹爪可以引导它的力量。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM ..
    "\n...它的切割是错误的！只有蟹爪可以引导它的力量。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM ..
    "\n...它的切割是错误的！只有蟹爪可以引导它的力量。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM ..
    "\n...它的切割是错误的！只有蟹爪可以引导它的力量。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM ..
    "\n...它的切割是错误的！只有蟹爪可以引导它的力量。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM ..
    "\n...它的切割是错误的！只有蟹爪可以引导它的力量。"

DESCRIBE.RED_MUSHED_ROOM = "恶心..."
DESCRIBE.GREEN_MUSHED_ROOM = "恶心..."
DESCRIBE.BLUE_MUSHED_ROOM = "恶心..."

-- StantonStuff
DESCRIBE.SKULLFLASK = "让我免于恐惧。"
DESCRIBE.SKULLFLASK_EMPTY = "它正在重新填充，只需给它时间。"
DESCRIBE.STANTON_SHADOW_TONIC = "喝这个不会有好结果..."
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "我不喜欢你兜售的东西！"
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "我感到...摆脱了我的担忧。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "虽然持续的时间不长，但感觉很好。"
-- StantonStuff

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "如果我们有一些电影来搭配它就好了。"
DESCRIBE.DEERCLOPS_BARRIER = "让我出去！我没有时间和你打架！"

DESCRIBE.MOONMAW_DRAGONFLY = "哦，我今天真的没想到会遇到天体虫子！"
DESCRIBE.MOONMAW_LAVAE = "我会把你打碎成碎片！"
DESCRIBE.SNAPPERTURTLE = "它自然会比我活得更久。"
DESCRIBE.SNAPPERTURTLEBABY = "时间是宝贵的。听我的建议，明智地使用它。"
DESCRIBE.SNAPPERTURTLENEST = "一个潮湿的乌龟巢穴。"
DESCRIBE.GLASS_SCALES = "闪耀且相当锋利。"
DESCRIBE.MOONGLASS_GEODE = "充能玻璃一旦分解就不会持续很久。"
DESCRIBE.ARMOR_GLASSMAIL = "我自己对武器化玻璃的尝试。"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "它们旋转得比我能制造的任何时钟都快！"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "做他们所做的事情需要耐心。"
DESCRIBE.SNOTROAST = "这对我来说是一个相当新的低点。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我不再感到饥饿，至少暂时是这样。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "我想我的胃正在恢复到正常的节奏。"
DESCRIBE.BOOK_RAIN_UM = "它篡改了本地云的时间流。"
DESCRIBE.FLORAL_BANDAGE = "我没有时间去摆弄那个。"
DESCRIBE.DORMANT_RAIN_HORN = "它不起作用？我会试着尽快修好它！"
DESCRIBE.RAIN_HORN = "它在被拉过时间流时变形了。"
DESCRIBE.DRIFTWOODFISHINGROD = "一种更稳定的钓鱼方式。"

ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
    LEVEL_1 = "真是一团糟！没有时间耽搁，赶紧清理！"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
    LEVEL_1 = "我们的食物已经过了保质期。我担心它正在吸引害虫！"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
    LEVEL_1 = "外面有一堆老鼠。它们很快就会冒险到这里来！"
}

DESCRIBE.PIED_RAT = "如果不是一只老鼠在演奏那首曲子，我可能会值得花时间坐下来听。"
DESCRIBE.PIED_PIPER_FLUTE = "我担心那支笛子去过哪里。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "我的小玩意儿！我还需要那些！"

ACTIONFAIL.CHARGE_FROM = {
    NOT_ENOUGH_CHARGE = "坐在这里等待是没有意义的。",
    CHARGE_FULL = "它不需要重新充电！"
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "显然，建造者没有时间让它安全！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "它甚至没有正确绝缘！"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "我随身携带我需要的一切。"
ACTIONFAIL.WINONATOOLBOX = "好像我需要从那里拿什么东西。"
DESCRIBE.WINONA_CATAPULT_ITEM_UM = "它运行在现代技术上，不幸的是。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM_UM = "没有那种电气嗡嗡声会好得多。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM_UM = "我对电子产品不太感兴趣。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM_UM = "我对电子产品不太感兴趣。"
DESCRIBE.POWERCELL = "有了发条，你就不需要这些东西了！"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "给我的设备增加了一个恼人的嗡嗡声。"
DESCRIBE.MINERHAT_ELECTRICAL = "它得到了改进，但现在太亮了。"
DESCRIBE.LANTERN_ELECTRICAL = "再亮一点，我的眼睛就会直接烧掉！"
DESCRIBE.OCEAN_SPEAKER = "我记得这些！我不太...记得它们的作用..."
-- DESCRIBE.UM_SIREN = "哦，真是麻烦！又是你。"

DESCRIBE.OCUPUS_BEAK = "无论这是什么，我现在拥有它了。"
DESCRIBE.OCUPUS_TENTACLE = "别碰。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "这就是一直盯着的后果。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "闻起来像绝望。"
DESCRIBE.UM_OCUPUS_EYE = "如果我过去那里，我可能会有点糟糕的时间。"
DESCRIBE.UM_OCUPUS_EYETACLE = "当我们消灭那些眼睛时，它让我们走了。"
DESCRIBE.UM_OCUPUS_TENTACLE = "别碰。"
DESCRIBE.UM_OCUPUS_BEAK = "我没想到会有这个。"
DESCRIBE.BEAKBASHER = "一个初步的应用，目前可以。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "它会看到未来，确定麻烦何时到来。"
DESCRIBE.ARMOR_REED_UM = "有助于处理我工作的潮湿部分。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "一种相当有趣的保护方式。"
DESCRIBE.ROCKJAWLEATHER = "它们能以这种皮肤游得这么快让我感到惊讶。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = "这些不是我以为会得到的新眼睛。"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = "它需要时间休息。"

DESCRIBE.STUFFED_PEEPER_POPPERS = "连食物都在看着我。"
DESCRIBE.UM_DEVILED_EGGS = "一百年都不行。"
DESCRIBE.LUSH_ENTRANCE = "我应该稍后探索这个。或者更早。"
DESCRIBE.CRITTER_FIGGY = "你是一个小小的跨时间线的宇宙恐怖，你知道吗？"
DESCRIBE.GIANT_TREE_BIRDNEST = "什么，你是蛋？"
ACTIONFAIL.UPGRADE.NOT_HARVESTED = "我的清洁工具在哪里？"

DESCRIBE.SLUDGE = "多么粘稠。"
DESCRIBE.SLUDGE_OIL = "也许我可以用这个来润滑我的齿轮。"
DESCRIBE.SLUDGE_SACK = "把我的手表放进去只会把它们弄脏。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "粗糙只让它更危险。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "这应该能让东西漂浮起来。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "它应该给船更多的时间漂浮。"
DESCRIBE.BOATPATCH_SLUDGE = "把它放进一个洞里然后忘掉它。"
DESCRIBE.UM_COPPER_PIPE = "它已经老化和生锈了。"
DESCRIBE.BRINE_BALM = "不，谢谢，时间治愈一切创伤。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = "用这种方式捕鱼效率更高。"
DESCRIBE.UM_AMBER = "很久以前有东西被困在里面。"
DESCRIBE.UM_BEEGUN = "多么奇怪，一把射出蜜蜂的枪！"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "它来自另一个时间线，你是怎么进入这个的？"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "它可以持续一个世纪。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "我们需要一些东西来首先操控。"
DESCRIBE.BOAT_BUMPER_COPPER = "这应该能持续足够长的时间。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "现在我们只需要一艘船来保护。"
DESCRIBE.UM_DREAMCATCHER = "它也能捕捉噩梦吗？"
DESCRIBE.UM_BRINEISHMOSS = "苔藓，它到处生长。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "我怀疑这会长时间地包含它们。"
DESCRIBE.SLUDGE_CORK = "这应该能加快处理那些污泥的速度。"
DESCRIBE.SLUDGESTACK = "那污泥随着时间的推移磨损了岩石。"
DESCRIBE.SPECTER_SHIPWRECK = "一切最终都会毁灭。"

DESCRIBE.UNCOMPROMISING_HARPOON = "从远处刺东西从未如此容易。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它看起来并不像它看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是真正的卷轴。"
DESCRIBE.UM_MAGNERANG = "磁铁不是我的专长。"
DESCRIBE.UM_MAGNERANGREEL = "它看起来不稳定。"
DESCRIBE.SIREN_THRONE = "哦，看！一块石头！无论如何。"
DESCRIBE.LAVASPIT_SLUDGE = "我没有时间在热煤上跳舞！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "正面攻击那些会浪费时间。"

DESCRIBE.PORTABLEBOAT_ITEM = "这艘船肯定会有一个短暂的寿命。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "我们走得越快，它就越亮！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "可惜它们的寿命很短。"
DESCRIBE.UM_ORNAMENT_RAT = "别让它进入我的钟表！"

DESCRIBE.TRINKET_WATHOM1 = "哦，那真是浪费时间。"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

-- WIXIE RELATED STRINGS

DESCRIBE.WIXIE_PIANO = "我们有一辈子的时间来学习！"
DESCRIBE.WIXIE_CLOCK = "我打不开它，所以我无法修复它！"
DESCRIBE.WIXIE_WARDROBE = "等等，这东西在这里多久了？"
DESCRIBE.CHARLES_T_HORSE = "它已经被时间遗忘了。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "没有一个齿轮在视线中。"
DESCRIBE.SLINGSHOT_MATILDA = "三是幸运数字。"
DESCRIBE.SLINGSHOT_GNASHER = "这个玩具在正确的时间窗口下可能会有奇效。"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "我欣赏它们设计的复杂性。"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,

    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,

    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT
}
DESCRIBE.FISHMEAT_DRIED = "时间已经消除了气味，但它会改善味道吗？"
DESCRIBE.SMALLFISHMEAT_DRIED = "我很惊讶它没有枯萎。"

DESCRIBE.WIXIEGUN = "这不是正确的时间线！"

DESCRIBE.MARA_BOSS1 = "好吧。又一个时间线消失了。"
ANNOUNCE.GAS_DAMAGE = "啊！时间流在这里很浑浊！"

-- Pyre Nettle stuff
DESCRIBE.UM_PYRE_NETTLES = "大量收集可能会节省一些时间...如果我不被这些该死的东西刺到的话。"
DESCRIBE.UM_SMOLDER_SPORE = "如果我不耽搁的话，我可以溜过去。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "该死！如果它们没有那么好吃就好了！！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "啊！我错过了时间窗口！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "我最好还是保持距离。"
DESCRIBE.UM_BLOWDART_PYRE = "哦，真是浪费..."

-- Under the Weather Part 1
DESCRIBE.ALPHA_LIGHTNINGGOAT = "它通过年龄获得了智慧。和质量。"
DESCRIBE.UM_TORNADO = "一个摇摇晃晃的...有风的...东西！"
DESCRIBE.UM_WATERFALL = "时间冲刷掉了一切。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "还没有龙卷风，至少在这个时间线里..."

DESCRIBE.UM_BOAT_ENGINE = {
    ON = "PLEASE WRITE QUOTES",
    LOWFUEL = "PLEASE WRITE QUOTES",
    OVERHEATING = "PLEASE WRITE QUOTES"
}

-- Broiling Hills
DESCRIBE.BOULDER_CRAB =
{
    GENERIC = "这不是一块石头！",
    NAKED = "我为它感到遗憾。",
}

DESCRIBE.BOULDER_CRAB_HOLE = "这是一个洞。"

DESCRIBE.UM_HOTSPRING = "它是由熔岩加热的。"

DESCRIBE.UM_PLANT_HOTSPRINGS = DESCRIBE.MARSH_PLANT --POND_ALGAE

DESCRIBE.ROCK_LICHEN =
{
    GENERIC = "它们喜欢潮湿的环境。",
    PICKED = "殖民地会随着时间重新生长。",
}

-- All things Snaildrake
DESCRIBE.SNAILDRAKE_MAGMA = "它们似乎有一种爆炸性的性格。"
DESCRIBE.SNAILDRAKE_SLIME = DESCRIBE.SNAILDRAKE_MAGMA
DESCRIBE.SNAPALM = "我不确定拿着这个是否安全。"
DESCRIBE.SNAILDRAKEHAT = "它会弄乱我的头发。"
DESCRIBE.SNAILDRAKEBUCKET =
{
    GENERIC = "看起来可以装满。",
    WATER = "我取了一桶水。",
    LAVA = "热的东西。",
}
DESCRIBE.SNAILDRAKE_HOLE = "这只是一个洞。"

-- All things Rimeweed
DESCRIBE.RIMEWEED_MAIN = "那杂草正在制造这种藤蔓般的混乱。"
DESCRIBE.RIMEWEED_BARRIER = "看起来像一个刺刺的冷锋。"

DESCRIBE.UM_RIMEWEED_ITEMVINE = "它摸起来又刺又冷。"
DESCRIBE.UM_RIMEWEED_ITEMFLOWER = "它出奇地耐寒。"

DESCRIBE.RIMEWEED_WHIP = "我会站在它的处理端。"

DESCRIBE.UM_RIMEWEED_TEQUILA = "它太冷了，无法享受。"
DESCRIBE.UM_RIMEWEED_SPAGETT = "脆脆的意大利面，不是我的首选。"

-- Lava Caves
DESCRIBE.MAGMAROCK1 = DESCRIBE.ROCKS
DESCRIBE.MAGMABONE = "我想知道虫子是否吃掉了它。"

DESCRIBE.UM_COOKPOT_WAGSTAFF = {
    EMPTY = "我没有时间去干涉他的疯狂。",
    COOKING_LONG = DESCRIBE.COOKPOT.COOKING_LONG,
    COOKING_SHORT = DESCRIBE.COOKPOT.COOKING_SHORT,
    DONE = DESCRIBE.COOKPOT.DONE,
    BURNT = DESCRIBE.COOKPOT.BURNT,
}
DESCRIBE.UM_COOKPOT_WAGSTAFF_DISPLAY = "不幸的是，它没有告诉我需要多长时间才能煮熟。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER = "可以用来给一个好的风。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER2 = "通过简单的拨动重置时间线的这一部分。"

DESCRIBE.UM_RICE_PUDDING = "别再叫我布丁了。"

DESCRIBE.UM_BOATBOTTLE = {
    FULL = "一种简单的方法，用我的手表组织我的船。",
    EMPTY = "我希望我能记住这是哪艘船，我应该开始标记这些。"
}

ANNOUNCE.ANNOUNCE_BUTTERFLY_SLIP = {"我记得这更容易...",
    "等待一个机会是否值得我的时间？",
    "嗯。我的时机不对。我应该等它静止。",
    "哦，真是麻烦，我真的必须等它休息吗？",
    "如果它着陆了，可能会更容易击中它。"}

DESCRIBE.WATHOM_CORPSE = "时间，瓦托姆？真的又到那个时间了吗？"

DESCRIBE.WATHGRITHR_SHIELD_DREADSTONE = "目前它保护得很好。"
ANNOUNCE.ANNOUNCE_WEAPON_TOOWEAK_ICESHIELD = "哦，真是麻烦，有人应该给你加热！"