ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WATHGRITHR
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WATHGRITHR.ACTIONFAIL

--	[ 		Wigfrid Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "别再耍花招了！面对我！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "战友！我们必须去你的尸体那里！"
ANNOUNCE.ANNOUNCE_WINONAGEN = "这种事最好交给那位机械少女。"
ANNOUNCE.ANNOUNCE_RATRAID = "有吱吱作响的东西靠近了。"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "保护圣物！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "那些卑鄙之徒带着我们的战利品逃走了！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "苍穹降下暴怒之雨！",
    "灼烧的雨滴，如利刃划过肌肤！",
    "弗雷尔的怒火倾泻而下！"
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "一场瘟疫从冥府深处涌出！"
-- FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = "惧吾之电能威力！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION =
"雷霆之神赐福于我！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好好冷冷冷"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "何神降祸于我？"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了"
-- FoodBuffs

-- CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "战士能做到！...能吗？"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "我恢复理智了。"
DESCRIBE.CALIFORNIAKING = "杯中之挑战？"
-- CaliforniaKing
DESCRIBE.FLORAL_BANDAGE = "鲜花与蜂蜜为伤者带来生机！"

ANNOUNCE.ANNOUNCE_RNEFOG = "战士需要保持警惕！"
DESCRIBE.UNCOMPROMISING_RAT = "瘟疫降临于我们两家！"
DESCRIBE.UNCOMPROMISING_RATHERD = "小野兽的巢穴！"
DESCRIBE.UNCOMPROMISING_RATBURROW = "小野兽的巢穴！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW =
"货物以拉塔托斯克之速运送。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW =
"野兽的巢穴，以及其中的宝藏。"

DESCRIBE.WINKY = {
    GENERIC = "人类大小的老鼠！这必是凶兆！",
    ATTACKER = "别用你的牙齿咬我！",
    MURDERER = "%s会给我们带来瘟疫！",
    REVIVER = "也许我判断得太快了！",
    GHOST = "野兽已被杀死，但它的灵魂仍在。",
    FIRESTARTER = "降瘟疫于我们的作物和房屋！"
}
DESCRIBE.WATHOM = {
    GENERIC = "愿有朝一日我们在战场上相遇，%s！",
    ATTACKER = "拿起武器，%s！",
    MURDERER = "我会将你绳之以法！",
    REVIVER = "我们或可成为朋友，%s！",
    GHOST = "又一野兽被杀死了！",
    FIRESTARTER = "有那样的爪子，为何还要玩火？"
}
DESCRIBE.WIXIE = {
    GENERIC = "%s是洛基的化身！",
    ATTACKER = "别在远处战斗，%s！",
    MURDERER = "你还太小，不该成为杀手！",
    REVIVER = "你想进一步嘲弄我吗，%s？",
    GHOST = "这个小恶魔被杀死了！",
    FIRESTARTER = "又在耍你的把戏，洛基？"
}

DESCRIBE.RATPOISONBOTTLE = "我的宝藏，是诱饵。我的怒火，是陷阱。"
DESCRIBE.RATPOISON = "出来吧小掠夺者，面对末日的审判！"

DESCRIBE.MONSTERSMALLMEAT = "微小邪恶之肉。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "我可以享用这不祥之物吗？"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "吾之阴暗口粮。"

DESCRIBE.UM_MONSTEREGG = "邪恶意图之蛋！"
DESCRIBE.UM_MONSTEREGG_COOKED = "我杀死了野兽。"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD =
"让我们从根部铲除这瘟疫！"
DESCRIBE.TOADLING = "腐败的邪恶守卫！"

DESCRIBE.GASMASK = "毒气无法吞噬我！！"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "又一次胜利！"
ANNOUNCE.ANNOUNCE_SNEEZE = "啊啊啊...嚏！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "我的鼻孔痒得难受！"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "烟雾散去了！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
    "冥府之怒降临于我们！", "诸神黄昏已至！", "野兽咆哮如雷！"
}
ANNOUNCE.ANNOUNCE_OVER_EAT = {
    STUFFED = "光荣的盛宴！",
    OVERSTUFFED = "无论如何努力，我都无法让自己再感到饥饿！"
}
ANNOUNCE.ANNOUNCE_ROOTING = "卑鄙的把戏！光荣地战斗！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "狂风愈加猛烈！"
ANNOUNCE.SHADOWTALKER = {
    "她已不在", "这就是我的归属", "我不想回去"
}
DESCRIBE.UM_SAND = "你是一种很干净的泥土。"
DESCRIBE.UM_SANDHILL = "我不会小题大做。"
DESCRIBE.SNOWPILE = "斯卡蒂不会对此感到满意。"
DESCRIBE.SNOWGOGGLES = "我们将与暴风雪本身战斗！"

DESCRIBE.SNOWMONG = "走开，邪恶的雪怪！"
DESCRIBE.SHOCKWORM = "凶猛的反击！"
DESCRIBE.ZASPBERRY = "索尔的力量真能被野果所蕴含？"
DESCRIBE.ZASPBERRYPARFAIT = "汝之敌人将在我的力量前颤抖。"
DESCRIBE.ICEBOOMERANG = "无人能逃脱我的长矛！"
DESCRIBE.MINOTAUR_BOULDER = "肮脏的诡计！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "让野兽把头撞向这块石头！"
DESCRIBE.VETERANSHRINE = "没有挑战能难倒我！"
DESCRIBE.VET_SKULL = "我接受你的挑战，恶魔！"
DESCRIBE.UM_BOSS_SOUL = "我最终的奖赏！"
DESCRIBE.UM_DARK_VESTIGES = "不怎么算战利品。"
DESCRIBE.UM_VOXOLOPHONE = "毫无疑问是冥界的把戏！"

DESCRIBE.UM_EXHUMER = "从冥界撕裂而出，我命令你的灵魂！"
DESCRIBE.UM_WINGSUIT = "我将像真正的瓦尔基里一样翱翔天际！"
DESCRIBE.UM_MOONFLY_LANTERN = "如天空中的彗星，拖着炽热的尾迹！"

DESCRIBE.PLAGUEMASK = "我是对抗瘟疫的战士！"
DESCRIBE.SPIDER_TRAPDOOR = "我自己的战术，被用来对付我！"
DESCRIBE.TRAPDOOR = "这里什么也没有。"
DESCRIBE.HOODEDTRAPDOOR = "那里什么也没有。"
DESCRIBE.WICKER_TENTACLE = "中毒的敌人毫无挑战性！"
DESCRIBE.HONEY_LOG =
"树木之肉...是哪个骗子干的好事？"

DESCRIBE.BUSHCRAB = "野性的遭遇！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "对抗瘟疫的武器！"
DESCRIBE.RAT_TAIL = "盗窃毫无荣誉可言！"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "小小的胜利战利品！"
DESCRIBE.AIR_CONDITIONER = "它能抵御空气中的威胁！"
DESCRIBE.SPOREPACK = "它掩盖了我的气味！"
DESCRIBE.SALTPACK = "它能清理战场！"


DESCRIBE.SKELETONMEAT = "战争的...战利品..."
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "一个挑战者！"
DESCRIBE.VAMPIREBAT = "个头越大，摔得越重！"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN =
"用一些月岩，我们可以为小生物打造完美的堡垒！"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "这不是配得上女武神的武器！"
-- Swampyness
DESCRIBE.RICEPLANT = "简单的植物，但长在水里。"
DESCRIBE.RICE = "即便我能吃，我也不会吃！"
DESCRIBE.RICE_COOKED = "我拒绝！"
DESCRIBE.SEAFOODPAELLA = "沼泽战士的奖赏！"

DESCRIBE.STUMPLING = "小小的愤怒林地精灵！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "这里有强大的力量！神秘的力量..."
DESCRIBE.SHADOW_TELEPORTER = "让我们击倒它，夺取它的宝藏！"
DESCRIBE.POLLENMITEDEN = "虫子的瓦尔哈拉。"
DESCRIBE.POLLENMITES = "别来侵扰我，虫子！"
DESCRIBE.SHADOW_CROWN = "我将敏捷地闪避！"
DESCRIBE.UM_SHADOW_AXE = "这武器的持有者拥有一支军队！"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.LICELOAF = "把它扔回沼泽水里！"
DESCRIBE.SUNGLASSES = "敌人再也不能用阳光对付我了！"
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "新的瘟疫到来！"
DESCRIBE.MARSH_GRASS = "是一丛灌木！"
DESCRIBE.CURSED_ANTLER = "华丽的武器！"
DESCRIBE.BERNIEBOX = "我不需要玩具！"
DESCRIBE.HOODED_FERN = "野兽可能潜伏在灌木丛中！"
DESCRIBE.HOODEDWIDOW = "我...我不害怕！"
DESCRIBE.GIANT_TREE = "我肯定站在世界之树尤格德拉希尔面前！"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST

DESCRIBE.WIDOWSGRASP = "通往我战利品的钥匙！"
DESCRIBE.SILKSACK = "这将成为我收藏的绝佳补充。"
DESCRIBE.SILKEN_BUNDLE = "为史诗储存的粘性物资。"

DESCRIBE.WEBBEDCREATURE = "我看到了战利品！"
ANNOUNCE.WEBBEDCREATURE = "太硬了！蜘蛛有钥匙！"
DESCRIBE.SNAPDRAGON_BUDDY = "这不是战士！"
DESCRIBE.SNAPDRAGON = "这是蔬菜——我的死敌！"
DESCRIBE.SNAPPLANT = "它们有强大的纽带！"
DESCRIBE.WHISPERPOD = "园艺不是战士的任务！"
DESCRIBE.WHISPERPOD_NORMAL_GROUND = {
    GENERIC = "也许种子会派上用场。",
    GROWING = "我是盾女，不是农民！"
}
DESCRIBE.FRUITBAT = "不是肉！"
DESCRIBE.PITCHERPLANT = "一株植物！"
DESCRIBE.APHID = "来战斗吧，虫子！"
DESCRIBE.NYMPH = "更多虫子！"
DESCRIBE.GIANT_TREE_INFESTED = "瘟疫降临其上。"
DESCRIBE.GIANT_BLUEBERRY = "我不会被诱惑！"
DESCRIBE.BLUEBERRYPANCAKES = "我会抵抗！"
DESCRIBE.DEVILSFRUITCAKE = "你无法诱惑我，冥府！"
DESCRIBE.SIMPSALAD = "这就是我吃肉的原因！"
DESCRIBE.BEEFALOWINGS = "我们为这头皮弗娄牛的荣誉而歌唱！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我不会被击退！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE =
"我失去了与皮弗娄牛的联系。"
DESCRIBE.WIDOWSHEAD = "我敌人的头颅就在我面前！"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "你想战斗吗，西瓜头？"

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "一条以懦夫方式战斗的蛇！"
DESCRIBE.VIPERFRUIT = "来自洛基本人的水果！"
DESCRIBE.VIPERFRUIT_LESSER = DESCRIBE.VIPERFRUIT
DESCRIBE.VIPERJAM = "仍然粘稠恶心，但被封存了。"

DESCRIBE.BLUEBERRYPLANT = {
    READY = "会反击的水果？令人尊敬。",
    FROZE = "它不能再反击了。",
    REGROWING = "光荣。仍然不是肉。"
}

DESCRIBE.ANTIHISTAMINE = "它将保护我的鼻子！"
ANNOUNCE.CURSED_ITEM_EQUIP = "这工具会反击！"
DESCRIBE.VETSITEM = "我必须进一步挑战自己才能使用它！"
DESCRIBE.SCREECHER_TRINKET = "毫无疑问是被诅咒的符号！"
ACTIONFAIL.GIVE.NOTNIGHT = "天空中的伟大月亮将赋予它力量。"

DESCRIBE.MAGMAHOUND = "它从远处战斗，你这懦夫！"
DESCRIBE.LIGHTNINGHOUND = "索尔的仆从？我做了什么惹怒了他？"
DESCRIBE.SPOREHOUND = "芬里尔的后裔，被扭曲得面目全非。"
DESCRIBE.GLACIALHOUND = "冰冻的外皮！"
DESCRIBE.RNESKELETON =
"倒下的战士！如果你想再次倒下就举起武器！"
DESCRIBE.RAT_WHIP = "你的鞭打刺痛，是令人畏惧的武器！"
DESCRIBE.KLAUS_AMULET = "战士之锁！"
DESCRIBE.CRABCLAW = "可以用珠宝装饰的华丽武器！"
DESCRIBE.HAT_RATMASK = "让我想起剧院里的面具。"

DESCRIBE.ORANGE_VOMIT = "...不。"
DESCRIBE.GREEN_VOMIT = "...不。"
DESCRIBE.RED_VOMIT = "...不。"
DESCRIBE.PINK_VOMIT = "...不。"
DESCRIBE.YELLOW_VOMIT = "...不。"
DESCRIBE.PURPLE_VOMIT = "...不。"
DESCRIBE.PALE_VOMIT = "...不。"

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = {
    GUARD = DESCRIBE.PIGMAN.GUARD,
    WEREPIG = DESCRIBE.PIGMAN.WEREPIG
}

DESCRIBE.BIGHT = "这些战士不会接受失败！"
DESCRIBE.KNOOK = "两个战士融合在一起！"
DESCRIBE.ROSHIP = "它们以懦夫的方式战斗。"

DESCRIBE.UM_PAWN = "躲在同伴身后的懦夫。"
DESCRIBE.UM_PAWN_NIGHTMARE = "躲在同伴身后的懦夫。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "我的灵魂属于战争！"
DESCRIBE.UM_BEAR_TRAP = "解除陷阱很容易。"
DESCRIBE.UM_BEAR_TRAP_OLD = "解除陷阱很容易。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "狡猾的武器！"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "狡猾的武器！"
DESCRIBE.CORNCAN = "能在航行中存活的食物！"
DESCRIBE.SKULLCHEST_CHILD = "诸神守护着我的战利品。"

DESCRIBE.SLOBBERLOBBER = "我向敌人吐口水。"
DESCRIBE.GORE_HORN_HAT = "蛮力胜过一切！"
DESCRIBE.BEARGERCLAW = "强大野兽的力量现在是我的了。"
DESCRIBE.FEATHER_FROCK = "肮脏的羽毛外衣！"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM .. "\n仅为战斗而塑！"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM .. "\n仅为战斗而塑！"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM .. "\n仅为战斗而塑！"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM .. "\n仅为战斗而塑！"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM .. "\n仅为战斗而塑！"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM .. "\n仅为战斗而塑！"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM ..
    "\n仅为战斗而塑！"

DESCRIBE.RED_MUSHED_ROOM = "捣碎又压扁！"
DESCRIBE.GREEN_MUSHED_ROOM = "捣碎又压扁！"
DESCRIBE.BLUE_MUSHED_ROOM = "捣碎又压扁！"

-- StantonStuff
DESCRIBE.SKULLFLASK = "战前的荣耀蜜酒！为强大干杯！"
DESCRIBE.SKULLFLASK_EMPTY = "空瓶子，会被重新装满的！"
DESCRIBE.STANTON_SHADOW_TONIC = "这是奇怪的蜜酒..."
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "哈！你不知道你在和谁打赌！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "我什么都不怕！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "女武神永不退缩。"
-- StantonStuff

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "给观众的食物，不是给战士的。"
DESCRIBE.DEERCLOPS_BARRIER = "攻击脆弱的路障！"

DESCRIBE.MOONMAW_DRAGONFLY = "重赛！"
DESCRIBE.MOONMAW_LAVAE = "它们动作的灵巧几乎能与我匹敌！"
DESCRIBE.SNAPPERTURTLE = "当心你惹恼了谁，否则你的盾牌就是我的！"
DESCRIBE.SNAPPERTURTLEBABY = "它还没有战斗的精神。"
DESCRIBE.SNAPPERTURTLENEST = "野兽的领地。"
DESCRIBE.GLASS_SCALES = "我才是这片土地真正的战士。"
DESCRIBE.MOONGLASS_GEODE = "可以坐在上面的宝座，俯瞰我丰厚的战利品！"
DESCRIBE.ARMOR_GLASSMAIL = "巨大的力量，愿你降临于我胸前。"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "诸神眷顾我！"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "你的喙不是我长矛的对手！"
DESCRIBE.SNOTROAST = "浪费战争战利品。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我感觉不舒服..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "我的胃恢复了力量！"
DESCRIBE.BOOK_RAIN_UM = "让战场湿润的典籍。"
DESCRIBE.DORMANT_RAIN_HORN = "来自海洋之王的奇怪恩惠。"
DESCRIBE.RAIN_HORN = "召唤倾盆大雨的号角。"
DESCRIBE.DRIFTWOODFISHINGROD = "鱼类惧怕我。"

ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
    LEVEL_1 = "无人看守的战利品会吸引盗贼！"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
    LEVEL_1 = "我们家里传来恶臭。"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
    LEVEL_1 = "一大群邪恶恶毒的害虫聚集了！"
}

DESCRIBE.PIED_RAT = "我会击败你，指挥官！"
DESCRIBE.PIED_PIPER_FLUTE = "我可以演奏的歌曲！"
DESCRIBE.UNCOMPROMISING_PACKRAT = "懦夫，别跑！"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK =
"我们共存亡，我忠诚的船只！"

ACTIONFAIL.CHARGE_FROM = {
    NOT_ENOUGH_CHARGE = "它处于休眠状态。",
    CHARGE_FULL = "它已经拥有强大的力量！"
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "我获得了索尔的祝福！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "索尔惩罚我的笨拙！"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "不需要，我拥有战斗所需的所有工具。"
ACTIONFAIL.WINONATOOLBOX = "再来一次！它没有战争工具！"
DESCRIBE.WINONA_CATAPULT_ITEM_UM = "邪恶的装置！"
DESCRIBE.WINONA_SPOTLIGHT_ITEM_UM = "邪恶的装置！"
DESCRIBE.WINONA_BATTERY_LOW_ITEM_UM = "邪恶的装置！"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM_UM = "邪恶的装置！"
DESCRIBE.POWERCELL = "她把索尔的力量装进了盒子里。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL =
"伟大的工匠，请赐福我的装备，让它享受索尔的力量！"
DESCRIBE.MINERHAT_ELECTRICAL = "工匠再次将我们从黑暗的邪恶之手中守护！"
DESCRIBE.LANTERN_ELECTRICAL = "闪电的力量将黑暗拒之门外！"
DESCRIBE.OCEAN_SPEAKER = "它回响着不适合战斗的歌曲！"
-- DESCRIBE.UM_SIREN = "终于遇到了一位值得的对手，我们的战斗将成为传奇！"

DESCRIBE.OCUPUS_BEAK = "我更喜欢吃掉它。"
DESCRIBE.OCUPUS_TENTACLE = "今天我不会被拉入深渊。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "以眼还眼！"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "我看到食物，我就吃它！"
DESCRIBE.UM_OCUPUS_EYE = "阴暗的战斗者在等待。"
DESCRIBE.UM_OCUPUS_EYETACLE = "是时候瞄准眼睛了！"
DESCRIBE.UM_OCUPUS_TENTACLE = "来自深渊的挑战者回应了！"
DESCRIBE.UM_OCUPUS_BEAK = "不公平！你的表现不符合角色设定。"
DESCRIBE.BEAKBASHER = "用咸水深渊锻造的完美战锤。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "它会通知我挑战者的到来！"

DESCRIBE.ARMOR_REED_UM = "紧急保护。不会持续太久。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "凶猛海洋战士的盔甲。"
DESCRIBE.ROCKJAWLEATHER = "来自深海的战利品。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = "你以奥丁之眼的力量战斗！"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS =
"英勇敌人的遗骸，带着厌恶观看！"
DESCRIBE.UM_DEVILED_EGGS = "我孵化了纯粹的邪恶！"
DESCRIBE.LUSH_ENTRANCE = "我没时间挖掘，有狩猎要进行！"
DESCRIBE.CRITTER_FIGGY = "瘟疫诞生的战士！"
DESCRIBE.GIANT_TREE_BIRDNEST = "许多强大战士的起点！"

DESCRIBE.SLUDGE = "来自冥府的邪恶脓液！"
DESCRIBE.SLUDGE_OIL = "它被浓缩成纯粹的精华。"
DESCRIBE.SLUDGE_SACK = "不适是一个小代价。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "硫磺之球！"
DESCRIBE.BOAT_BUMPER_SLUDGE = "它将承受任何打击。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "我船只的柔软盔甲。"
DESCRIBE.BOATPATCH_SLUDGE = "洞，再也不见。"
DESCRIBE.UM_COPPER_PIPE = "铁匠的材料。"
DESCRIBE.BRINE_BALM = "我的体质将战胜一切。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "树脂之壳。"
DESCRIBE.UM_BEEGUN = "蜜蜂齐射！"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "我们大厅的宝藏！"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER =
"我的船只将从各个攻击角度得到保护。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM =
"坚固，但需要一艘船来掌舵。"
DESCRIBE.BOAT_BUMPER_COPPER = "抵挡海浪的板甲。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "汝之船只的板甲。"
DESCRIBE.UM_DREAMCATCHER = "我只梦见战斗中的光荣死亡！"
DESCRIBE.UM_BRINEISHMOSS = "潮湿的苔藓。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "恐惧的显现！"
DESCRIBE.SLUDGE_CORK = "这将阻挡脓液。"
DESCRIBE.SLUDGESTACK = "脓液从冥府的血管中喷涌而出！"
DESCRIBE.SPECTER_SHIPWRECK = "被海洋卷走，任其腐朽。"

DESCRIBE.UNCOMPROMISING_HARPOON =
"从远处刺穿东西从未如此容易。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它看起来没那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是真正的卷轴。"
DESCRIBE.UM_MAGNERANG =
"一种武器，会附着在敌人的盔甲上，让他们沉重。"
DESCRIBE.UM_MAGNERANGREEL = "它让我的敌人保持距离。"
DESCRIBE.SIREN_THRONE = "业余的宝座。"
DESCRIBE.LAVASPIT_SLUDGE = "冥府之火！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "君主采取了防御姿态！"

DESCRIBE.PORTABLEBOAT_ITEM = "这艘船不适合战斗！"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "赐予我光明，尼约德！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "醒来，邪恶的野兽！"
DESCRIBE.UM_ORNAMENT_RAT = "你在我之下，小家伙！"

DESCRIBE.TRINKET_WATHOM1 = "这是什么乐器？"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

-- WIXIE RELATED STRINGS

DESCRIBE.WIXIE_PIANO = "我将谱写一曲配得上我伟大的交响乐！"
DESCRIBE.WIXIE_CLOCK = "时间不等人！哦，等等..."
DESCRIBE.WIXIE_WARDROBE = "里面藏着什么？负重的野兽？"
DESCRIBE.CHARLES_T_HORSE = "这匹马很久以前就去了瓦尔哈拉。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "里面有小士兵吗？"
DESCRIBE.SLINGSHOT_MATILDA = "光荣地战斗，否则不战！"
DESCRIBE.SLINGSHOT_GNASHER = "小家伙在玩弄黑暗魔法！"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "这是什么肮脏的诡计？"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,

    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,

    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT
}
DESCRIBE.FISHMEAT_DRIED = "我可以吃一天！"
DESCRIBE.SMALLFISHMEAT_DRIED = "勉强算一份零食！"

DESCRIBE.WIXIEGUN = "这种现代战争让我害怕。"

DESCRIBE.MARA_BOSS1 = "好！！与我战斗吧，恶魔！！"
ANNOUNCE.GAS_DAMAGE = "啊！咳咳！不能...呼吸！"

-- Pyre Nettle stuff
DESCRIBE.UM_PYRE_NETTLES = "勇敢的外表，却是懦弱的形式！"
DESCRIBE.UM_SMOLDER_SPORE = "它因力量而颤抖。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "冥府之火！！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "冥府之火！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "它将抵挡火焰植物最猛烈的愤怒。"
DESCRIBE.UM_BLOWDART_PYRE = "我宁愿身处火焰和硫磺之中！"

-- Under the Weather Part 1
DESCRIBE.ALPHA_LIGHTNINGGOAT = "你想挑战我吗，冥府野兽？"
DESCRIBE.UM_TORNADO = "与我战斗，风！"
DESCRIBE.UM_WATERFALL = "你不能淹没我！"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "我们摆脱了埃俄罗斯的风。"

DESCRIBE.UM_BOAT_ENGINE = {
    ON = "请写引文",
    LOWFUEL = "请写引文",
    OVERHEATING = "请写引文"
}

-- Broiling Hills
DESCRIBE.BOULDER_CRAB =
{
    GENERIC = "它不是石头！",
    NAKED = "我为它感到遗憾。",
}

DESCRIBE.BOULDER_CRAB_HOLE = "是个洞。"

DESCRIBE.UM_HOTSPRING = "被熔岩加热。"

DESCRIBE.UM_PLANT_HOTSPRINGS = "温泉植物。"

DESCRIBE.ROCK_LICHEN =
{
    GENERIC = "它们喜欢潮湿。",
    PICKED = "菌落会及时重新生长。",
}

-- All things Snaildrake
DESCRIBE.SNAILDRAKE_MAGMA = "它们似乎脾气暴躁。"
DESCRIBE.SNAILDRAKE_SLIME = DESCRIBE.SNAILDRAKE_MAGMA
DESCRIBE.SNAPALM = "我不确定拿着这个是否安全。"
DESCRIBE.SNAILDRAKEHAT = "它会弄乱我的头发。"
DESCRIBE.SNAILDRAKEBUCKET =
{
    GENERIC = "看起来可以装满。",
    WATER = "我取了一蜗牛的水。",
    LAVA = "热辣的东西。",
}
DESCRIBE.SNAILDRAKE_HOLE = "只是一个洞。"

-- All things Rimeweed
DESCRIBE.RIMEWEED_MAIN = "那株杂草正在制造这些藤蔓混乱。"
DESCRIBE.RIMEWEED_BARRIER = "看起来像一道多刺的冷锋。"

DESCRIBE.UM_RIMEWEED_ITEMVINE = "摸起来又刺又冷。"
DESCRIBE.UM_RIMEWEED_ITEMFLOWER = "它出奇地顽强。"

DESCRIBE.RIMEWEED_WHIP = "我会站在挥打的一端。"

DESCRIBE.UM_RIMEWEED_TEQUILA = "太冷了，无法享用。"
DESCRIBE.UM_RIMEWEED_SPAGETT = "脆脆的意大利面，不是我的首选。"

-- Lava Caves
DESCRIBE.MAGMAROCK1 = DESCRIBE.ROCKS
DESCRIBE.MAGMABONE = "我想知道虫子有没有吃它。"

DESCRIBE.UM_COOKPOT_WAGSTAFF = {
    EMPTY = "铁嘴在徘徊，等待被喂食。",
    COOKING_LONG = DESCRIBE.COOKPOT.COOKING_LONG,
    COOKING_SHORT = DESCRIBE.COOKPOT.COOKING_SHORT,
    DONE = DESCRIBE.COOKPOT.DONE,
    BURNT = DESCRIBE.COOKPOT.BURNT,
}
DESCRIBE.UM_COOKPOT_WAGSTAFF_DISPLAY = "若想饕餮，必先克服试炼。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER =  "装置的缺失部分。它们在战斗中分离了吗？"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER2 = "它应该能做点什么。"

DESCRIBE.UM_RICE_PUDDING = "邪恶的甜米糊。"

DESCRIBE.UM_BOATBOTTLE = {
    FULL = "用于展示最值得的船只。",
    EMPTY = "随时可以使用的船只！"
}

ANNOUNCE.ANNOUNCE_BUTTERFLY_SLIP = {"所有这些追逐，为了什么？",
    "我不擅长对付空中敌人。",
    "真正的战士不会把日子花在与昆虫战斗上。",
    "这个世界有那么多怪物，我为什么要屈尊于此？",
    "没人会讲述杀死蝴蝶的女武神的故事。"}

DESCRIBE.WATHOM_CORPSE = "我怀疑终场尚未到来！"

DESCRIBE.WATHGRITHR_SHIELD_DREADSTONE = "保护我的身体但不保护我的心灵。"
ANNOUNCE.ANNOUNCE_WEAPON_TOOWEAK_ICESHIELD = "你的软弱会在激战中暴露！"
