ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WAXWELL
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WAXWELL.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WAXWELL.ACTIONFAIL

--	[ 		Maxwell Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "查理？不……是别的什么……"
    ANNOUNCE.ANNOUNCE_HARDCORE_RES = "我必须把这颗心交给他们腐烂的尸体。"
    ANNOUNCE.ANNOUNCE_WINONAGEN = "我更像一个 \"魔法和黑暗艺术家\" 。"
    ANNOUNCE.ANNOUNCE_RATRAID = "哦，不。"
    ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "...来吧，查理，这真的有必要吗？"
    -- Yes. Enjoy.
    ANNOUNCE.ANNOUNCE_RATRAID_OVER = "你怎么敢？回来！"
    ANNOUNCE.ANNOUNCE_ACIDRAIN = {
        "哇！雨正在灼烧我！",
        "我的西装！它烧毁了！",
        "我在融化！融化了！！",
    }
    ANNOUNCE.ANNOUNCE_TOADSTOOLED = "邪恶的孢子！"
	--FoodBuffs
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我随时都有可能死亡！"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了。"
	--FoodBuffs
	
	--CaliforniaKing
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "那可能是个坏主意。"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "我想我更喜欢王位而不是这玩意儿..."
	DESCRIBE.CALIFORNIAKING = "这是什么肮脏的汞合金？"
	--CaliforniaKing
	
	ANNOUNCE.ANNOUNCE_RNEFOG = "不只是查理在外面，是吗？"
    DESCRIBE.UNCOMPROMISING_RAT = "肮脏的害虫！"
    DESCRIBE.UNCOMPROMISING_RATHERD = "我不记得允许你这个害虫在我的世界定居。"
    DESCRIBE.UNCOMPROMISING_RATBURROW = "我不记得允许你这个害虫在我的世界定居。"
    DESCRIBE.UNCOMPROMISING_WINKYBURROW = "我不记得允许你这个害虫在我的世界定居。"
    DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "我不记得允许你这个害虫在我的世界定居。"
	
	DESCRIBE.WINKY =
        {
            GENERIC = "我没有把他们带到这里，当然也不是我造就她！",
            ATTACKER = "把你的脏爪子从我身边拿开！",
            MURDERER = "她闻到了死亡的味道。",
            REVIVER = "很高兴还活着，但尽量不要碰我的西装！",
            GHOST = "在她活着的时候就死了。像肮脏、发臭的老鼠一样。",
            FIRESTARTER = "为什么这里的所有生物都必须惹麻烦？",
        }
	DESCRIBE.WATHOM =
        {
GENERIC = "这不是我最自豪的实验之一。",
             ATTACKER = "你失去了控制，%s。",
             MURDERER = "这就是你报答我的方式，%s?",
             REVIVER = "我就知道你会有你的用处，%s。",
             GHOST = "奇怪，它们在地表下显现。",
             FIRESTARTER = "我没想到你会是一个点火器，%s。",
        }
	DESCRIBE.WIXIE =
        {
GENERIC = "我希望你不是在收集流浪狗，查理。",
             ATTACKER = "立即停止暴力，%s！",
             MURDERER = "我不再理解孩子了。",
             REVIVER = "我会留意你的，%s。",
             GHOST = "终于，安静下来了。",
             FIRESTARTER = "%s 变得可以预测了。",
        }
		
    DESCRIBE.RATPOISONBOTTLE = "呃...我暂时记得红色的是什么。"
    DESCRIBE.RATPOISON = "一个可以阻止害虫的小东西。"

    DESCRIBE.MONSTERSMALLMEAT = "远离最低等的害虫。"
    DESCRIBE.COOKEDMONSTERSMALLMEAT = "多么令人不快的前景..."
    DESCRIBE.MONSTERSMALLMEAT_DRIED = "我的牙齿太老了，不适合这个。"

    DESCRIBE.UM_MONSTEREGG = "里面藏着什么恶魔?"
    DESCRIBE.UM_MONSTEREGG_COOKED = "很明显，蛋黄和毛茸茸的蛋清."

    DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "它似乎正在使用孢子污染空气。"
    DESCRIBE.TOADLING = "它们被某种真菌蜂巢思维所取代。"
	
	DESCRIBE.GASMASK = "这可以清除烟汽"
	DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
	DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
	DESCRIBE.SPIDERQUEENCORPSE = "它在等待什么吗？"
	ANNOUNCE.ANNOUNCE_SNEEZE = "阿阿阿...啾！"
	ANNOUNCE.ANNOUNCE_HAYFEVER = "呃，过敏。"
	ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "噢... 我又能呼吸了。"
	ANNOUNCE.ANNOUNCE_FIREFALL = {
		"永远没有片刻的宁静。",
		"卑劣的脏东西正在努力破坏。",
		"那可能不太好。",
	}
	ANNOUNCE.ANNOUNCE_ROOTING = "它的根抓住了我！"
	ANNOUNCE.ANNOUNCE_SNOWSTORM = "风正在增强，这里出了点问题。"
	ANNOUNCE.SHADOWTALKER = {
        "查理  我很抱歉",
        "他们不会让我们走的",
        "不要原谅我",
    }
	ANNOUNCE.ANNOUNCE_OVER_EAT =
	{
		STUFFED = "我能说什么？我是个贪吃的国王。",
		OVERSTUFFED = "暴食是一种罪过，我的罪已经够多了！",
    }
	DESCRIBE.UM_SAND = "岩石被彻底击碎，再也无法辨认。"
	DESCRIBE.UM_SANDHILL = "一小堆黄沙。"
	DESCRIBE.SNOWPILE = "在它进入我的靴子前把它弄走。"
	DESCRIBE.SNOWGOGGLES = "..."
	
	DESCRIBE.SNOWMONG = "它看起来很联盟。"
	DESCRIBE.SHOCKWORM = "我绝对没有创造这一只！"
	 -- ...
	DESCRIBE.ZASPBERRY = "我不喜欢野生浆果，不管有没有魔法。"
	DESCRIBE.ZASPBERRYPARFAIT = "它看起来和它尝起来一样好。"
	DESCRIBE.ICEBOOMERANG = "魔法很棒，不是吗？"
	DESCRIBE.MINOTAUR_BOULDER = "这个地方的状况比我想象的糟糕得多。"
	DESCRIBE.MINOTAUR_BOULDER_BIG = "也许我们可利用它来达到我们的优势？"
	DESCRIBE.SNOWBALL_THROWABLE = "一点也不适合，你对此有什么不明白的？"
	DESCRIBE.VETERANSHRINE = "我已经遇到了与燃料有关的问题，还有什么其他的问题吗？"
	DESCRIBE.RAT_TAIL = "哎呀，恶心！"
	DESCRIBE.PLAGUEMASK = "喙看起来很可笑。"
	DESCRIBE.SPIDER_TRAPDOOR = "哦，太好了，它们变得更聪明了。"
	DESCRIBE.TRAPDOOR = "这里有些不对劲，我能感觉到。"
	DESCRIBE.HOODEDTRAPDOOR = "那些伏击蜘蛛也在这里，不是吗。"
	DESCRIBE.WICKER_TENTACLE = "他们已经从他们的存在位面被撕裂了。"
	DESCRIBE.HONEY_LOG = "...我什么都没得到。"

	DESCRIBE.BUSHCRAB = "我猜他们终于孵化了。"
	DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
	DESCRIBE.DISEASECUREBOMB = "我榨干了那块石头上的每一滴油。"
	DESCRIBE.SHROOM_SKIN_FRAGMENT = "它很麻烦，但现在是我的了。"
	DESCRIBE.AIR_CONDITIONER = "现在这是一台我可以习惯的机器！"
	DESCRIBE.SPOREPACK = "这太恶心了！我不在乎它有多大！"
	DESCRIBE.SALTPACK = "我不适合做家务。"
	
	DESCRIBE.UM_SCORPION = "你不会蜇我的。"
	DESCRIBE.SCORPIONCARAPACE = "呃，最好是把它留给猎犬。"
	DESCRIBE.SCORPIONCARAPACECOOKED = "烹饪并不能治愈这块肉里的质地。"
	DESCRIBE.HARDSHELLTACOS = "好吧，这确实变得更好了。"
	
	DESCRIBE.SKELETONMEAT = "我情愿死！"
	DESCRIBE.CHIMP = DESCRIBE.MONKEY
	DESCRIBE.SWILSON = "我... 我以为我杀了你！"
	DESCRIBE.VAMPIREBAT = "我记得你是... 与众不同的。"
	DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
	DESCRIBE.CRITTERLAB_REAL_BROKEN = "有了月岩，我就可以养出一些肮脏的生物。"
	DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
	DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
	DESCRIBE.BUGZAPPER = "很普通，但它可以把虫子拒之门外。"		
	--Swampyness
	DESCRIBE.RICEPLANT = "这些以前不在这里..."
	DESCRIBE.RICE = "我会在它上面折断我的牙齿！"
	DESCRIBE.RICE_COOKED = "我想这会更好。"
	DESCRIBE.SEAFOODPAELLA = "一顿美餐！" 
	
	DESCRIBE.STUMPLING = "他们令人反感！"
	DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
	DESCRIBE.MOON_TEAR = "另一个 \"月亮\" 的礼物。"
	DESCRIBE.SHADOW_TELEPORTER = "哦，拜托。我一看就知道了。"
	DESCRIBE.POLLENMITEDEN = "呃，虫群的家。"
    DESCRIBE.POLLENMITES = "可怕的虫群。"
    DESCRIBE.SHADOW_CROWN = "黑暗带来强大的力量，但会让你的身体变得脆弱，我应该知道。"
    DESCRIBE.RNEGHOST = DESCRIBE.GHOST
	DESCRIBE.LICELOAF = "平淡无奇。"
	DESCRIBE.SUNGLASSES = "这不是我的风格。"
	DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
	DESCRIBE.LUREPLAGUE_RAT = "这不对，眼球草，长在了老鼠身上？这是你做的吗查理？"
	DESCRIBE.MARSH_GRASS = "我应该让他们进来的，这地方真的很单调。"
	DESCRIBE.CURSED_ANTLER = "你希望我带着这个？！"
	DESCRIBE.BERNIEBOX = "其中有强大的力量。"
	DESCRIBE.HOODED_FERN = "无趣。"
	DESCRIBE.HOODEDWIDOW = "我想离她远点。"
	DESCRIBE.GIANT_TREE = "这棵树异常地大。"
	DESCRIBE.WIDOWSGRASP = "我的西装上沾到了血！"
	DESCRIBE.WEBBEDCREATURE = "里面可能有尸体。"
	ANNOUNCE.WEBBEDCREATURE = "只有蜘蛛可以打开它，呃。"
	DESCRIBE.SNAPDRAGON_BUDDY = "如果我喂它，它会消失吗？"
	DESCRIBE.SNAPDRAGON = "我没有和你争吵，目前为止。"
	DESCRIBE.SNAPPLANT = "你看起来很眼熟。"
	DESCRIBE.WHISPERPOD = "好极了，更肮脏的工作。"
	DESCRIBE.WHISPERPOD_NORMAL_GROUND =
	{
		GENERIC = "它需要更多？这些东西如何自行繁殖？",
		GROWING = "它在生长。",
	}
	DESCRIBE.FRUITBAT = "更丑了！"
	DESCRIBE.PITCHERPLANT = "这是一株植物，但长得很高。"
	DESCRIBE.APHID = "我不喜欢你。"
DESCRIBE.NYMPH = "它正在寻找更多的树木。"
	DESCRIBE.GIANT_TREE_INFESTED = "这里到处都是害虫。"
	DESCRIBE.GIANT_BLUEBERRY = "这会变得一团糟，唉。"
	DESCRIBE.STEAMEDHAMS = "它们显然是烤过的。"
	DESCRIBE.BLUEBERRYPANCAKES = "简直是一团糟。"
	DESCRIBE.SIMPSALAD = "不过是一点粗粮。"
DESCRIBE.DEVILSFRUITCAKE = "由黑魔法制成的蛋糕。 或者黑巧克力。"
	DESCRIBE.BEEFALOWINGS = "发情的牛。"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我可能很单薄，但你不能撼动我！"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "我失去了立足点。"
	DESCRIBE.WIDOWSHEAD = "看起来皮质仍然是半功能性的。"
	DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
	DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
	DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
	DESCRIBE.WATERMELON_LANTERN = "为什么打招呼，卡特丽娜女士。"
	
		--Viperstuff Quotes
	DESCRIBE.VIPERWORM = "这只被燃料烧坏了。"
	DESCRIBE.VIPERFRUIT = "我想，更多是为了军队。"
	DESCRIBE.VIPERJAM = "目前为止，我的好手套是安全的。"
	
	
	DESCRIBE.BLUEBERRYPLANT =         
		{
            READY = "如果它在这套衣服上爆裂，我会杀了某些东西。",
			FROZE = "它已经被冻结了，很好。",
			REGROWING = "它会长得更多。",
		}
	DESCRIBE.BERNIE_INACTIVE =
        {
            BROKEN = "它以前经历过一些好日子。",
            GENERIC = "这让我有点怀旧。",
            ASHLEY_BROKEN = "它以前经历过一些好日子。",
            ASHLEY = "这让我有点怀旧。",
        }
	
	DESCRIBE.BERNIE_ACTIVE =
        {
            GENERIC = "我在这里看到了什么？",
            ASHLEY = "我在这里看到了什么？",
        }
	DESCRIBE.BERNIE_BIG =
        {
            GENERIC = "真是令人不安。",
            ASHLEY = "真是令人不安。",
        }
	DESCRIBE.ANTIHISTAMINE = "它有助于抑制过敏。"
    ANNOUNCE.CURSED_ITEM_EQUIP = "我好像不能触碰它！"
    DESCRIBE.VETSITEM = "他们用花哨的东西诱惑我们，我们应该利用黑暗的力量吗？"
	DESCRIBE.SCREECHER_TRINKET = "它来自很远的地方。"
	
	ANNOUNCE.ANNOUNCE_NOSANITY = "我头疼得厉害！"
	ANNOUNCE.ANNOUNCE_NOHEALTH = "我的身体太虚弱了！"
	ANNOUNCE.ANNOUNCE_NOFUEL = "我需要一些噩梦燃料。"
	ACTIONFAIL.GIVE = {NOTNIGHT = "也许我们应该在月亮出来的时候再试一次？"}

	DESCRIBE.MAGMAHOUND = "我很嫉妒，我应该让红猎犬变成这样的。"
	DESCRIBE.LIGHTNINGHOUND = "我怎么没想到？啧。"
	DESCRIBE.SPOREHOUND = "哼，看起来那只生病的蟾蜍改善了他们。"
	DESCRIBE.GLACIALHOUND = "我应该让蓝色猎犬变成这样的！"
	DESCRIBE.RNESKELETON = "回来报仇？如果必须的话，我会再次杀了你。"
	DESCRIBE.RAT_WHIP = "多好的方法。"
	DESCRIBE.KLAUS_AMULET = "强大而美妙的魔法！"
	DESCRIBE.CRABCLAW = "我一看到宝石洞就知道了。" 
	DESCRIBE.HAT_RATMASK = "我必须做这个肮脏的工作吗？" 

	DESCRIBE.ORANGE_VOMIT = "这是生命！"
	DESCRIBE.GREEN_VOMIT = "这是生命！"
	DESCRIBE.RED_VOMIT = "这是生命！"
	DESCRIBE.PINK_VOMIT = "这是生命！"
	DESCRIBE.YELLOW_VOMIT = "这是生命！"
	DESCRIBE.PURPLE_VOMIT = "这是生命！"
	DESCRIBE.PALE_VOMIT = "这是生命！"
	
	DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
	DESCRIBE.PIGKING_PIGGUARD = 
	{
	GUARD = DESCRIBE.PIGMAN.GUARD,
	WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
	}
	DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH

	DESCRIBE.BIGHT = "他完蛋了！"
	DESCRIBE.KNOOK = "他的动作更是个混蛋！"
	DESCRIBE.ROSHIP = "你的脸现在看起来更糟了！"
	
	DESCRIBE.UM_PAWN = "这些正在走动的东西怎么样？我还以为我把它们弃置了？"
	DESCRIBE.UM_PAWN_NIGHTMARE = "这是最初的设计..."

	DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
	DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
	DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
	-- Blowgun stuff
	DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
	DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
	DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
	DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
	DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
	
	DESCRIBE.ANCIENT_AMULET_RED = "我认为他们不再需要灵魂了。"
	DESCRIBE.UM_BEAR_TRAP = "我从来没有教过他们这样做。"
	DESCRIBE.UM_BEAR_TRAP_OLD = "好极了，他们变得更聪明了。"
	DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "比狗牙陷阱要好。"
	DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "比狗牙陷阱要好。"
	DESCRIBE.CORNCAN = "里面大概有玉米。"
	DESCRIBE.SKULLCHEST_CHILD = "它将物品保存在本地口袋维度中。"
	
	DESCRIBE.SLOBBERLOBBER = "它全部的力量又回到了我的手里。"
	DESCRIBE.GORE_HORN_HAT = "穿这个让我感觉不太好。"
	DESCRIBE.BEARGERCLAW = "我很乐意弄脏别人的手。"
	DESCRIBE.FEATHER_FROCK = "羽毛油脂会沾满我的西装。"
	
	DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n现在无法正常运行。"
	DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n现在无法正常运行。"
	DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n现在无法正常运行。"
	DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n现在无法正常运行。"
	DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n现在无法正常运行。"
	DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n现在无法正常运行。"
	DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n现在无法正常运行。"
	
	DESCRIBE.RED_MUSHED_ROOM = "我已经把它捣成糊状了。"
	DESCRIBE.GREEN_MUSHED_ROOM = "我已经把它捣成糊状了。"
	DESCRIBE.BLUE_MUSHED_ROOM = "我已经把它捣成糊状了。"
	
	--StantonStuff
	DESCRIBE.SKULLFLASK = "令人印象深刻的混合物。"
	DESCRIBE.SKULLFLASK_EMPTY = "瓶子似乎也被施了魔法，太棒了。"
	DESCRIBE.STANTON_SHADOW_TONIC = "噩梦燃料鸡尾酒？拜托，我可以做一整晚！"
	DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
	DESCRIBE.STANTON = "你是谁？我杀了你吗？"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "还有一种安慰效果，就像蛋奶酒一样。"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "我想要更多饮品。"
	--StantonStuff
	
	DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
	DESCRIBE.THEATERCORN = "唤起旧时的记忆。"
	DESCRIBE.DEERCLOPS_BARRIER = "她使用魔法的效率越来越高！我很自豪！"
	

	DESCRIBE.MOONMAW_DRAGONFLY = "哦！我甚至不能看向你！"
	DESCRIBE.MOONMAW_LAVAE = "我的最爱：有我整个身体大小的尖刺。"
	DESCRIBE.SNAPPERTURTLE = "敢骂我就杀了你。"
	DESCRIBE.SNAPPERTURTLEBABY = "不要以为你的年龄可以成为你行为的借口，先生。"
	DESCRIBE.SNAPPERTURTLENEST = "一定来自海洋，我以前从未在岛上见过它们。"
	DESCRIBE.GLASS_SCALES = "我还是不习惯月光类型的魔法。"
	DESCRIBE.MOONGLASS_GEODE = "一团月亮能量的集中体，我可以使用它。"
	DESCRIBE.ARMOR_GLASSMAIL = "我不会很快死去的！"
	DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "如果你不怕死，尽管靠近点。"
	DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
	DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
	DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

	DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR
	
	DESCRIBE.WOODPECKER = "红鸟进化得相当快。"
	DESCRIBE.SNOTROAST = "你不可能是认真的吧。"
	ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我们永远不会谈论这个。"
	ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
	DESCRIBE.BOOK_RAIN_UM = "我们也在篡改月亮魔法，是吗？"
	DESCRIBE.FLORAL_BANDAGE = "甜绷带。"
	DESCRIBE.DORMANT_RAIN_HORN = "一个能够引导一些魔法能量的贝壳。"
	DESCRIBE.RAIN_HORN = "那个持有甲壳的人对魔法的了角比她领导的要多..."
	DESCRIBE.DRIFTWOODFISHINGROD = "浮木一定让它变得更能吸引鱼类了。"

	    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
        LEVEL_1 = "哼，老鼠肯定在渴望我们的物品。",
    }
    ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
        LEVEL_1 = "那些老鼠会被那些消极处理过的食物所吸引。",
    }
    ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
        LEVEL_1 = "阴险的害虫，它们聚焦起来围攻我们的小小村落。",
    }

	DESCRIBE.PIED_RAT = "那件破衣服，毁了！"
	DESCRIBE.PIED_PIPER_FLUTE = "我不会碰那个，更不用说把它放在我的嘴上。"
	DESCRIBE.UNCOMPROMISING_PACKRAT = "认为你很聪明，是吗？"
	
	ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "如果我淹死了，我会把你抛在脑后。"
	
	ACTIONFAIL.CHARGE_FROM =
	{
		NOT_ENOUGH_CHARGE = "没电了，可惜了。",
		CHARGE_FULL = "那将是矫枉过正",
	}
	ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "迫不及待地去充电"
	ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "那是智慧！"
	
	----UNDER THE WEATHER----
	
	DESCRIBE.WINONA_TOOLBOX = "我不会拖着它到处乱跑。"
	ACTIONFAIL.WINONATOOLBOX = "如果我进不去怎么帮忙？"
	DESCRIBE.WINONA_CATAPULT_ITEM = "有时候我会想念我的发条装置。"
	DESCRIBE.WINONA_SPOTLIGHT_ITEM = "有时候我会想念我的发条装置。"
	DESCRIBE.WINONA_BATTERY_LOW_ITEM = "有时候我会想念我的发条装置。"
	DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "有时候我会想念我的发条装置。"
	DESCRIBE.POWERCELL = "."
	DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "她满脑子都是好主意。"
	DESCRIBE.MINERHAT_ELECTRICAL = "我想这解决了萤火虫问题。"
	DESCRIBE.OCEAN_SPEAKER = "你知道，我曾经是国王。在这里，我无法认出我在这些可怜的水域中找到的一半东西。"
	--DESCRIBE.UM_SIREN = "多么怪诞。然而有点诱人....."

	DESCRIBE.OCUPUS_BEAK = ""
	DESCRIBE.OCUPUS_TENTACLE = "墨黑色，可能尝起来也像墨水。"
	DESCRIBE.OCUPUS_TENTACLE_EYE = "我不确定眼睛是让它变得更少还是更可口。"
	DESCRIBE.OCUPUS_TENTACLE_COOKED = "至少现在烤得很好。"

	DESCRIBE.ARMOR_REED_UM = "至少它能让我的西装保持干净。"
	DESCRIBE.ARMOR_SHARKSUIT_UM = "我真的需要穿用鱼做的衣服吗？"
	DESCRIBE.ROCKJAWLEATHER = "它已经开始臭了。"

	DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
	DESCRIBE.STUFFED_PEEPER_POPPERS = "我已经没胃口了。"
	DESCRIBE.UM_DEVILED_EGGS = "我接触到的所有东西似乎都是这个样子。"
	DESCRIBE.LUSH_ENTRANCE = "哼，我知道最好不要去不该戳鼻子的地方。"
	DESCRIBE.CRITTER_FIGGY = "下颚脱了衣服，伙计。"
	DESCRIBE.GIANT_TREE_BIRDNEST = "它只是乞求被踩在脚下。"

	    DESCRIBE.SLUDGE = "恶心的粘液，它粘在任何东西上。"
	DESCRIBE.SLUDGE_OIL = "至少它现在被控制住了。"
	    DESCRIBE.SLUDGE_SACK = "你想想这很不合常理。"
	DESCRIBE.CANNONBALL_SLUDGE_ITEM = "我们现在正试图模仿希腊火，是吗。"
	DESCRIBE.BOAT_BUMPER_SLUDGE = "那应该让我的船远离我。 出于一个原因，或另一个"
	
	DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "至少这个混蛋不会对我产生影响。"
	    DESCRIBE.BOATPATCH_SLUDGE = "最好留在那个洞里。"
	    DESCRIBE.UM_COPPER_PIPE = "你认为他们是从哪里来的？"
	    DESCRIBE.BRINE_BALM = "不要在我的伤口上撒盐。"
	    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
	DESCRIBE.UM_AMBER = "我什至不知道里面有什么。"
	DESCRIBE.UM_BEEGUN = "我很欣赏头韵。"
	DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
	DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
	DESCRIBE.SUNKENCHEST_ROYAL = "得到这个让我感到非常痛苦。"
	DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
	DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
	DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
	DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
	DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
	DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
	DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "我的船转了一圈又一圈。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "它需要一艘船来旋转。"
DESCRIBE.BOAT_BUMPER_COPPER = "这是坚固的东西。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "这将使船保持完整。"
DESCRIBE.UM_DREAMCATCHER = "这里没有梦，只有噩梦。"
DESCRIBE.UM_BRINEISHMOSS = "苔藓不太值得注意。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "灾难的根源。"
DESCRIBE.SLUDGE_CORK = "我到底要用这个塞什么，一个水槽孔？"
DESCRIBE.SLUDGESTACK = "其他人可以收获它。"
DESCRIBE.SPECTER_SHIPWRECK =
"不会是第一个尝试通过海上逃跑的人。"

	DESCRIBE.UNCOMPROMISING_HARPOON = "远距离刺伤从未如此简单。"
	DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
	DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
	DESCRIBE.UM_MAGNERANG = "我不认为这会扔得很远。"
	DESCRIBE.UM_MAGNERANGREEL = "有趣的磁铁是……"
	DESCRIBE.SIREN_THRONE = "有什么东西敢侵犯我的水域？！"
	DESCRIBE.LAVASPIT_SLUDGE = "这是玷污西装的最快方法。"

	DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
	DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
	DESCRIBE.UM_BEEGUARD_BLOCKER = "我们必须想办法绕过它们。"

	DESCRIBE.PORTABLEBOAT_ITEM = "我不会用我的生命来信任它。"
	DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "我们再次利用了大自然。"

	DESCRIBE.UM_ORNAMENT_OPOSSUM = "它没有死，它只是一种表演。我想。"
	DESCRIBE.UM_ORNAMENT_RAT = "走开，卑鄙的东西！"

	DESCRIBE.TRINKET_WATHOM1 = "难怪他心脏病发作了。"

	DESCRIBE.CODEX_MANTRA = "我很抱歉查理。"
	
	-- WIXIE RELATED STRINGS
	
	DESCRIBE.WIXIE_PIANO = "这是怎么到这里来的？"
	DESCRIBE.WIXIE_CLOCK = "很遗憾它不能正常工作。"
	DESCRIBE.WIXIE_WARDROBE = "这是某种单向传送门......"
	DESCRIBE.CHARLES_T_HORSE = "他们收回了它。"
	DESCRIBE.THE_REAL_CHARLES_T_HORSE = "真古怪。"
	DESCRIBE.SLINGSHOT_MATILDA = "考虑到使用的材料，它非常坚固。"
	DESCRIBE.SLINGSHOT_GNASHER = "多么恶心的笑话。"

	DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_THULECITE
	DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_THULECITE
	DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
	DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
	DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
	DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_THULECITE
	DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_THULECITE
	DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_THULECITE
	DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
	DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
	DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
		
	DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
	DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
	DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_THULECITE

	DESCRIBE.BAGOFMARBLES = "我没有时间玩幼稚的游戏。"

	DESCRIBE.MEATRACK_HAT = {
            GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
            DRYING = DESCRIBE.MEATRACK.DRYING,
            DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
            DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
            DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
	}
	DESCRIBE.FISHMEAT_DRIED = "它比普通肉干更柔软。"
	DESCRIBE.SMALLFISHMEAT_DRIED = "它比普通肉干更柔软，而且更小。"

	DESCRIBE.WIXIEGUN = "这是什么魔法？！"

DESCRIBE.MARA_BOSS1 = "*嘘*"
ANNOUNCE.GAS_DAMAGE = "咳咳!咳咳!"

-- 火炭荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "看来他们适应得不错。好啊。" 
DESCRIBE.UM_SMOLDER_SPORE = "那个植物的孢子？多么奇特。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "啊，对。真是个惊喜。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "我想这是我自找的。"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "对我的口味来说有点冒险，但它应该能阻止荨麻的出现。"
DESCRIBE.UM_BLOWDART_PYRE = "无论我把它们指向什么，它们都会带来彻底的危险......"

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "你最好不要威胁我。"
DESCRIBE.UM_TORNADO = "印章是个意外，我发誓！"
DESCRIBE.UM_WATERFALL = "没有缓和的大雨。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "我们暂时没有任何龙卷风了。"
