ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WEBBER
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WEBBER.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WEBBER.ACTIONFAIL

--	[ 		Webber Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "哎呀！这吓到我们了......"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "Wilson 先生说幽灵不是这样工作的。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "父亲告诉我不要玩机械。"
ANNOUNCE.ANNOUNCE_RATRAID = "那是什么声音？朋友们？"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "哇，它出来玩了！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "嘿，等一下！我们来玩捉人吧！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"噢！痛！",
"雨，雨，走开！",
"嗷！我们的皮毛被烧焦了！",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "蘑菇，蘑菇！"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我-我们很抱歉！我们很害怕！哇！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了。"
--FoodBuffs
	
--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "我们做到了！我们完成了.... 那个.."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "发生什么事了？"
DESCRIBE.CALIFORNIAKING = "我们肯定吃得更糟。"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "什-什么声音？ 我们很害怕！"
DESCRIBE.UNCOMPROMISING_RAT = "好皮毛！"
DESCRIBE.UNCOMPROMISING_RATHERD = "它在看着我们！嘿你好，小家伙！"
DESCRIBE.UNCOMPROMISING_RATBURROW = "它在看着我们！嘿你好，小家伙！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "它在看着我们！嘿你好，小家伙！"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "它在看着我们！嘿你好，小家伙！"
	
DESCRIBE.WINKY =
{
    GENERIC = "有点像我们！",
    ATTACKER = "你给我们带来了坏名声",
    MURDERER = "我保证，我不像她那样刻薄！",
    REVIVER = "谢谢！我知道我们可以成为朋友！",
    GHOST = "哦 不！我们应该帮助她！",
    FIRESTARTER = "小心不要烧焦你的皮毛！另外，不要烧我们的东西...",
}
DESCRIBE.WATHOM =
{
GENERIC = "我希望 %s 和我们有更多共同点！",
     ATTACKER = "没有人喜欢恶霸，%s。",
     MURDERER = "%s 可能是个怪物！",
     REVIVER = "你心地善良，%s！",
     GHOST = "好奇怪的鬼！",
     FIRESTARTER = "别玩火，%s。",
}
DESCRIBE.WIXIE =
{
GENERIC = "嗨 %s！想玩吗？...不？",
     ATTACKER = "别再刻薄了，%s!",
     MURDERER = "你做得太过分了，%!",
     REVIVER = "谢谢你，%!",
     GHOST = "哦，可怜的 %s！",
     FIRESTARTER = "你的弓有点烧焦了，%s。",
}
		
DESCRIBE.RATPOISONBOTTLE = "温蒂真的很喜欢这东西！想知道它是什么味道的..."
DESCRIBE.RATPOISON = "哎呀！ 都撒了！"

DESCRIBE.MONSTERSMALLMEAT = "我们宁愿不要考虑太多。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "它会让我们渡过难关。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "它真的很耐嚼。"

DESCRIBE.UM_MONSTEREGG = "一个鸡蛋？ 也许它会孵化一个朋友。"
DESCRIBE.UM_MONSTEREGG_COOKED = "就像爸爸以前做的那样..."

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "讨厌的雨是从那里来的吗？"
DESCRIBE.TOADLING = "那是一只奇怪的青蛙。"
	
DESCRIBE.GASMASK = "现在我们不会咳嗽得那么厉害了。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "噢不！你还好吗？"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿...阿阿阿阿阿阿啾！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "我们一定是过敏了。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "哇！我想我们的过敏症已经消失了！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"我... 我们不喜欢那样的声音！",
	"地面变得格外刺痛！",
	"小心！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "我们卡住了！救命！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "听起来像是一场风暴！让我们为下雪天做好准备吧。"
ANNOUNCE.SHADOWTALKER = {
"我是怪物",
"我永远也不能回家",
"我想回家",
}
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "我们真的吃饱了。",
	OVERSTUFFED = "我们希望我们有第三个胃！",
}
DESCRIBE.UM_SAND = "很高兴在我们的脚下感受到它。"
DESCRIBE.UM_SANDHILL = "希望我们有一个水桶和一把铲子。"
DESCRIBE.SNOWPILE = "我希望这是玩耍的好时机..."
DESCRIBE.SNOWGOGGLES = "我们既不是猫眼也不是昆虫眼。"
	
DESCRIBE.SNOWMONG = "4只眼睛？！ 绝对不是我们的朋友！"
DESCRIBE.SHOCKWORM = "古怪的皮褶生物！"
DESCRIBE.ZASPBERRY = "精力充沛。"
DESCRIBE.ZASPBERRYPARFAIT = "我们以前从来没有吃过这个，看起来很好吃。"
DESCRIBE.ICEBOOMERANG = "Brrrr, 我们靠近了就感觉很冷！"
DESCRIBE.MINOTAUR_BOULDER = "希望我们的天花板朋友没事！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "来吧，大个子，冲过来！"
DESCRIBE.SNOWBALL_THROWABLE = "噢！噢！ 谁想打雪仗？"
DESCRIBE.VETERANSHRINE = "它在看着我们！！"
DESCRIBE.RAT_TAIL = "它看起来像我们的皮毛！但更臭。"
DESCRIBE.PLAGUEMASK = "它看起来像一只鸡！"
DESCRIBE.SPIDER_TRAPDOOR = "我们不在乎你没有头发，你仍然是我们的朋友！"
DESCRIBE.TRAPDOOR = "我们聪明的朋友建造了这些石板！"
DESCRIBE.HOODEDTRAPDOOR = "我们聪明的朋友一定在附近！"
DESCRIBE.WICKER_TENTACLE = "我认为这是晕船或者晕车。"
DESCRIBE.HONEY_LOG = "太好了！它让我们... 更甜？"

DESCRIBE.BUSHCRAB = "不是我们的朋友！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "它会粘住并弄脏我们的皮毛。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "一块漆黑的小东西，让我们想到了... 我们！"
DESCRIBE.AIR_CONDITIONER = "这让我们的肺部感觉都很好！"
DESCRIBE.SPOREPACK = "穿上它以后我们需要做个泡泡浴！"
DESCRIBE.SALTPACK = "不过，我们有点想在雪地里玩耍。"
	
DESCRIBE.UM_SCORPION = "你好，蝎子朋友。"
DESCRIBE.SCORPIONCARAPACE = "比平时更脆一点。"
DESCRIBE.SCORPIONCARAPACECOOKED = "还不错。"
DESCRIBE.HARDSHELLTACOS = "我还想再吃一个！"
	
DESCRIBE.SKELETONMEAT = "我以前从来没有见过我自己的皮肤... 永远！"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "不，停下来，威尔逊！是我们呀！"
DESCRIBE.VAMPIREBAT = "好怪物！"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "月岩会成为一些小动物的新家！"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "这是做什么的？哎哟！"	
--Swampyness
DESCRIBE.RICEPLANT = "我们应该划船去拿它！"
DESCRIBE.RICE = "现在吃有点太干了！"
DESCRIBE.RICE_COOKED = "我们想和别的东西一起吃！"
DESCRIBE.SEAFOODPAELLA = "它有助于排干我们的鼻孔。"

DESCRIBE.STUMPLING = "这是什么东西？"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "它会弄湿我们的皮毛，让我们把它存放在安全的地方。"
DESCRIBE.SHADOW_TELEPORTER = "你要送我礼物吗？"
DESCRIBE.POLLENMITEDEN = "蜘蛛不是昆虫！"
DESCRIBE.POLLENMITES = "别咬我们，小家伙！"
DESCRIBE.SHADOW_CROWN = "啊哇呜哇乌龟，啊哇呜哇野兔..."
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.LICELOAF = "吃起来没有滋味。"
DESCRIBE.SUNGLASSES = "如果我们闭上大部分眼睛，它就会起作用了。"
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "嘿，伙计，漂亮的眼睛！"
DESCRIBE.MARSH_GRASS = "灌木丛。"
DESCRIBE.CURSED_ANTLER = "哇，看看它有多大！"
DESCRIBE.BERNIEBOX = "我想打开它，但它不是我们的东西。"
DESCRIBE.HOODED_FERN = "苔藓和绿叶。"
DESCRIBE.HOODEDWIDOW = "我们也是蜘蛛！！你为什么要攻击我们？！"
DESCRIBE.GIANT_TREE = "它可能非常古老。"
DESCRIBE.WIDOWSGRASP = "对不起..."
DESCRIBE.WEBBEDCREATURE = "哦！ 我们的朋友会为我们储存礼物吗？"
ANNOUNCE.WEBBEDCREATURE = "我们需要更大的手，来自更大的蜘蛛！"
DESCRIBE.SNAPDRAGON_BUDDY = "天呐！我们很高兴他们不吃肉！"
DESCRIBE.SNAPDRAGON = "看起来很漂亮！"
DESCRIBE.SNAPPLANT = "最好的花蕾，明白了吗？"
DESCRIBE.WHISPERPOD = "我们把它种下去吧！"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "让我们尝试在其中种植一些东西！",
	GROWING = "已经完成了吗？",
}
DESCRIBE.FRUITBAT = "这是我们最喜欢的颜色！"
DESCRIBE.PITCHERPLANT = "如果我们能像其他蜘蛛一样攀爬，我们就可以到达那里。"
DESCRIBE.APHID = "不是蜘蛛！"
DESCRIBE.NYMPH = "这种东西也会飞吗？"
DESCRIBE.GIANT_TREE_INFESTED = "它看起来很恶心。"
DESCRIBE.GIANT_BLUEBERRY = "到处都是汁水！"
DESCRIBE.STEAMEDHAMS = "这只是一个汉堡。"
DESCRIBE.DEVILSFRUITCAKE = "希望我们不会肚子痛..."
DESCRIBE.BLUEBERRYPANCAKES = "真的很甜！"
DESCRIBE.SIMPSALAD = "我们需要的不仅仅是这个。"
DESCRIBE.BEEFALOWINGS = "我们喜欢蝙蝠翅膀的嘎吱声！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我们没有被推得踉踉跄跄！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "状态结束了。"
DESCRIBE.WIDOWSHEAD = "我们本来可以成为朋友的...."
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "以前从来没有用西瓜试过这个！"
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "我们不喜欢他的长相！"
DESCRIBE.VIPERFRUIT = "它让我们想起了草莓。"
DESCRIBE.VIPERJAM = "不再有黏糊糊的触碰了。"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "它很大！我们不可能用我们的手臂把它拉出来！",
		FROZE = "我们可以看到里面的浆果！哦...",
		REGROWING = "爆炸一定很累。",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "一切都毁了。",
    GENERIC = "一只泰迪熊。",
    ASHLEY_BROKEN = "一切都毁了。",
    ASHLEY = "一只毛绒小猫。",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "那只泰迪熊在动！",
    ASHLEY = "那只小猫在动！",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "既毛骨悚然又很可爱！！",
    ASHLEY = "既毛骨悚然又很可爱！！",
}
DESCRIBE.ANTIHISTAMINE = "它可以阻止我们打喷嚏！我们不知道为什么，但确实如此！"
ANNOUNCE.CURSED_ITEM_EQUIP = "哎呀！"
DESCRIBE.VETSITEM = "我们的手还没有受到足够的诅咒！"
DESCRIBE.SCREECHER_TRINKET = "我们不喜欢它。"
ACTIONFAIL.GIVE = {NOTNIGHT = "我认为它在睡觉？但是，在白天？"}

DESCRIBE.MAGMAHOUND = "哎呀，他吐了！"
DESCRIBE.LIGHTNINGHOUND = "哎哟哎哟哎哟！ 我们的脚丫子！"
DESCRIBE.SPOREHOUND = "一只生病的愤怒小狗！"
DESCRIBE.GLACIALHOUND = "光是看着它，我们都要冻僵了！"
DESCRIBE.RNESKELETON = "哦，你好！你想要点什么吗？"
DESCRIBE.RAT_WHIP = "它很臭。我们宁愿用别的东西。"
DESCRIBE.KLAUS_AMULET = "我们一直很顽皮..."
DESCRIBE.CRABCLAW = "晃来晃去真是太有趣了！芜湖！" 
DESCRIBE.HAT_RATMASK = "我们喜欢寻宝！" 

DESCRIBE.ORANGE_VOMIT = "哈哈, 呕。"
DESCRIBE.GREEN_VOMIT = "哈哈, 呕。"
DESCRIBE.RED_VOMIT = "哈哈, 呕。"
DESCRIBE.PINK_VOMIT = "哈哈, 呕。"
DESCRIBE.YELLOW_VOMIT = "哈哈, 呕。"
DESCRIBE.PURPLE_VOMIT = "哈哈, 呕。"
DESCRIBE.PALE_VOMIT = "哈哈, 呕。"
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "我们很抱歉没有修复你！"
DESCRIBE.KNOOK = "我们认为我们应该离它远点。"
DESCRIBE.ROSHIP = "你是我们最不喜欢的！"
	
DESCRIBE.UM_PAWN = "听起来像我的旧闹钟！"
DESCRIBE.UM_PAWN_NIGHTMARE = "听起来像我的旧闹钟！"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH		
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
	
DESCRIBE.ANCIENT_AMULET_RED = "我们两个都有空间吗？"
DESCRIBE.UM_BEAR_TRAP = "哎呀！"
DESCRIBE.UM_BEAR_TRAP_OLD = "哎呀！"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "哎哟。 我们更喜欢织网。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "哎哟。 我们更喜欢织网。 "
DESCRIBE.CORNCAN = "妈妈从来不允许我触摸开罐器，她说我会把手指切开。"
DESCRIBE.SKULLCHEST_CHILD = "我们可以伸手去拥抱另一边的人吗？"
	
DESCRIBE.SLOBBERLOBBER = "随地吐痰是粗鲁的！"
DESCRIBE.GORE_HORN_HAT = "噢！ 别碰尖的那一头！噢..."
DESCRIBE.BEARGERCLAW = "太棒了！哈哈！"
DESCRIBE.FEATHER_FROCK = "我感觉自己像个王子！不，是个国王！"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n我觉得我把它弄坏了。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n我觉得我把它弄坏了。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n我觉得我把它弄坏了。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n我觉得我把它弄坏了。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n我觉得我把它弄坏了。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n我觉得我把它弄坏了。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n我觉得我把它弄坏了。"
	
DESCRIBE.RED_MUSHED_ROOM = "压扁！"
DESCRIBE.GREEN_MUSHED_ROOM = "压扁！"
DESCRIBE.BLUE_MUSHED_ROOM = "压扁！"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "我不认为我被允许拥有这个..."
DESCRIBE.SKULLFLASK_EMPTY = "里面什么都没了。"
DESCRIBE.STANTON_SHADOW_TONIC = "如果妈妈看到我这样做，会杀了我的..."
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "你有点... 令人毛骨悚然..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "我们的皮肤和皮毛感觉更舒服了！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "一切都变得更可怕了！"
--StantonStuff
	
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "我们喜欢在吃东西的时候看其他人打架。"
DESCRIBE.DEERCLOPS_BARRIER = "我们认为我们应该通过薄弱地区进行开采。"
	

DESCRIBE.MOONMAW_DRAGONFLY = "哎呀！他们看起来疯掉了！！"
DESCRIBE.MOONMAW_LAVAE = "我们不需要另一个点进入我们之间！"
DESCRIBE.SNAPPERTURTLE = "他很可爱，有点！"
DESCRIBE.SNAPPERTURTLEBABY = "一脚就能把它打翻。"
DESCRIBE.SNAPPERTURTLENEST = "有东西睡在这里，是吗？"
DESCRIBE.GLASS_SCALES = "这太酷了！！"
DESCRIBE.MOONGLASS_GEODE = "我们可以把它当作夜灯吗？"
DESCRIBE.ARMOR_GLASSMAIL = "看着我，可怕的怪物龙！ 哇啊哇啊哇啊！"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "这让我们有点害怕！"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = "这次我尝试了一些不同的东西！"
	
DESCRIBE.WOODPECKER = "我们喜欢你的喙！"
DESCRIBE.SNOTROAST = "呕！这么多鼻涕！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "吃鼻涕并不是一件好事.."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN_UM = "我们想在雨中玩耍，而不是阅读它。"
DESCRIBE.FLORAL_BANDAGE = "我们有时喜欢舔它。"
DESCRIBE.DORMANT_RAIN_HORN = "这对我们来说很熟悉。"
DESCRIBE.RAIN_HORN = "我们的记忆一定是混乱了，我们认为这有什么不同。"
DESCRIBE.DRIFTWOODFISHINGROD = "我们可以用它抓住好多鱼。"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "我们或许应该清理我们的玩具。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "我们的食物气味很重。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "外面有东西在吱吱作响。",
}

DESCRIBE.PIED_RAT = "我们可以戴一下你的帽子吗？"
DESCRIBE.PIED_PIPER_FLUTE = "我们一直想学习如何演奏。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "不错的背包！"
	
ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "木筏不会下沉，但我们会！"

ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "我们做对了吗？",
	CHARGE_FULL = "已经充满电了。",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "我认为我们做得对！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "啊！ 我们认为这是不对的。"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "我们可以把它做成玩具盒吗？"
ACTIONFAIL.WINONATOOLBOX = "我们应该尊重。"
DESCRIBE.WINONA_CATAPULT_ITEM = "我不想失去一只手臂！"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "我不想失去一只手臂！"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "我不想失去一只手臂！"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "我不想失去一只手臂！"
DESCRIBE.POWERCELL = "那是块大电池。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "让我们放入的所有东西都装在电池上！"
DESCRIBE.MINERHAT_ELECTRICAL = "现在我们也可以充电了。"
DESCRIBE.OCEAN_SPEAKER = "我想靠近一点，但他似乎很疲倦。"
--DESCRIBE.UM_SIREN = "她的歌让我们头晕目眩..."

     DESCRIBE.OCUPUS_BEAK = ""
DESCRIBE.OCUPUS_TENTACLE = "我们会和你握手，但它，好吧......"
DESCRIBE.OCUPUS_TENTACLE_EYE = "我的天，你的眼睛真大。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "脆脆的，但还是软软的。"
DESCRIBE.UM_OCUPUS_EYE = "我们已经习惯了很多只眼睛，这些眼睛之间的距离有点远。"
DESCRIBE.UM_OCUPUS_EYETACLE = "如果我们蒙蔽了他们，大人物可能会放我们走。"
DESCRIBE.UM_OCUPUS_TENTACLE = "它又大又疯狂又糟糕。"
DESCRIBE.UM_OCUPUS_BEAK = "是的，它想吃掉我们。"
DESCRIBE.BEAKBASHER = "即使是最平凡的东西也可以派上用场。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "我们试图让这棵树看起来像一只大蜘蛛。我认为这不起作用。"

DESCRIBE.ARMOR_REED_UM = "我们几乎感觉不到它在我们身上。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "穿上它我们感觉更可怕了。"
DESCRIBE.ROCKJAWLEATHER = "好漂亮的鳍。"
	
DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
DESCRIBE.STUFFED_PEEPER_POPPERS = "我认为我们可能走得太远了。"
DESCRIBE.UM_DEVILED_EGGS = "我们喜欢这些！"
DESCRIBE.LUSH_ENTRANCE = "我不确定我想去那里……但他想去！"
DESCRIBE.CRITTER_FIGGY = "耶！！一个新的虫友！"
DESCRIBE.GIANT_TREE_BIRDNEST = "他说他认为我们的巢穴更安全。"
	
DESCRIBE.SLUDGE = "我们不希望它沾到我们的皮毛上。"
DESCRIBE.SLUDGE_OIL = "洒出来可不好。我们不应该碰它。"
    DESCRIBE.SLUDGE_SACK = "我们不喜欢背上的感觉。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "一块会走的石头，咔BOM！"
DESCRIBE.BOAT_BUMPER_SLUDGE = "这个颠簸的保险杠可以保证船的安全。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "它会撞到东西。"
    DESCRIBE.BOATPATCH_SLUDGE = "这是任何洞的完美尺寸。"
    DESCRIBE.UM_COPPER_PIPE = "我们可以看穿它并假装它是一个望远镜。"
    DESCRIBE.BRINE_BALM = "很痛，但对我们有好处。"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "很难看到，但里面有东西。"
DESCRIBE.UM_BEEGUN = "这似乎是错误的。"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "耶！一个精美的宝箱！"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "我们可能会因为这些转弯而晕船。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "它将帮助我们转动我们的船。"
DESCRIBE.BOAT_BUMPER_COPPER = ""
DESCRIBE.BOAT_BUMPER_COPPER_KIT = ""
DESCRIBE.UM_DREAMCATCHER = "晚安。"
DESCRIBE.UM_BRINEISHMOSS = "感觉就像湿毛皮。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "它们不是我们的想法。"
DESCRIBE.SLUDGE_CORK = "我们可以用这个堵住很大的洞。"
DESCRIBE.SLUDGESTACK = "我们认为这对我们的皮毛没有好处。"
DESCRIBE.SPECTER_SHIPWRECK = "里面有人吗？"

DESCRIBE.UNCOMPROMISING_HARPOON = "远距离刺伤从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
DESCRIBE.UM_MAGNERANG = "爸爸的抽屉里不是有一些吗？"
DESCRIBE.UM_MAGNERANGREEL = "我们喜欢这些颜色！"
DESCRIBE.SIREN_THRONE = "没人在。"
DESCRIBE.LAVASPIT_SLUDGE = "啊，它烧焦了我的皮毛！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "哇！让我们穿过你们这些卑鄙的东西！"

DESCRIBE.PORTABLEBOAT_ITEM = "它不会加入我们的黑暗深处。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "无限循环。"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "哦不！你还好吗？" 
DESCRIBE.UM_ORNAMENT_RAT= "我们找到你了，你这鬼鬼祟祟的东西！" 

DESCRIBE.TRINKET_WATHOM1 = "我们要退款！！"
	
DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "它仍然很难弹奏，即使有八只手臂！"
DESCRIBE.WIXIE_CLOCK = "噢，这不是布谷鸟钟。"
DESCRIBE.WIXIE_WARDROBE = "看起来很可怕！"
DESCRIBE.CHARLES_T_HORSE = "噢，可怜的玩具！"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "头晕，小马！"
DESCRIBE.SLINGSHOT_MATILDA = "我不认为她想让我们玩这个。"
DESCRIBE.SLINGSHOT_GNASHER = "它在告诉我犯罪！不，谢谢，弹弓！"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_THULECITE

DESCRIBE.BAGOFMARBLES = "哦，我喜欢漂亮的漩涡！"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "我不确定那行得通！"
DESCRIBE.SMALLFISHMEAT_DRIED = "有点腥味！"

DESCRIBE.WIXIEGUN = "我们不应该玩这个！"

DESCRIBE.MARA_BOSS1 = "噢！好极了!"
ANNOUNCE.GAS_DAMAGE = "Khoff. Khak. Khak."

-- 火炭荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "这个看起来不怎么样！"
DESCRIBE.UM_SMOLDER_SPORE = "它和其他的不一样..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "啊！我们的毛皮着火了！！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "啊！我们的毛皮着火了！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "它戳穿了我们的皮毛。痒痒的。"
DESCRIBE.UM_BLOWDART_PYRE = "它可能会伤害我们的朋友..."

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "家乡的山羊都没有这么暴躁..."
DESCRIBE.UM_TORNADO = "我讨厌龙卷风..."
DESCRIBE.UM_WATERFALL = "溅起的水花！"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "幸好周围没有龙卷风！"
