ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WENDY
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WENDY.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WENDY.ACTIONFAIL

--	[ 		Wendy Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "呀！别玩这种把戏..."
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "要是这么简单就好了..."
ANNOUNCE.ANNOUNCE_WINONAGEN = "我可能会把它搞砸，像其他一切一样..."
ANNOUNCE.ANNOUNCE_RATRAID = "哦，太棒了。"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "害虫和瘟疫！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "嘿！那些是我的负担！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "他们的血肉将会凋零...", "雨水正在侵蚀我的身体...",
    "这是大自然的惩罚..."
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "来自大地深处的诅咒！"
-- FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "太...太冷了"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我被诅咒了..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好些了"
-- FoodBuffs

-- CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING =
"我觉得我会后悔的。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "说实话，那并不算太糟。"
DESCRIBE.CALIFORNIAKING = "我还剩下什么可失去的？"
-- CaliforniaKing

ANNOUNCE.ANNOUNCE_RNEFOG = "死亡从黑暗中凝视着我。"
DESCRIBE.UNCOMPROMISING_RAT =
"邪恶的恶魔被锻造来摧毁虚荣的支柱。"
DESCRIBE.UNCOMPROMISING_RATHERD = "盗贼巢穴的唯一入口。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "盗贼巢穴的唯一入口。"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "通往无处，也通往处处。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "一个悲惨而肮脏的家。"

DESCRIBE.WINKY = {
    GENERIC = "趁你还活着，好好生活，%s。",
    ATTACKER = "也许伤害他人是她的天性。",
    MURDERER = "又一个怪物，又一个杀手。",
    REVIVER = "%s，你珍惜我的生命吗？还是只是出于本能？",
    GHOST = "她短暂的生命结束了。",
    FIRESTARTER = "燃烧东西无法重新点燃内心的火焰。"
}
DESCRIBE.WATHOM = {
    GENERIC = "从大地中，野兽降临了。",
    ATTACKER = "%s，野兽的命运不就是伤害他人吗？",
    MURDERER = "下一个带走我吧。",
    REVIVER = "再次复活，等待着未来的死亡。",
    GHOST = "也许是比亡灵更黑暗的力量？",
    FIRESTARTER = "他所过之处，只有毁灭。"
}
DESCRIBE.WIXIE = {
    GENERIC = "棍棒和石头打断了我的骨头。%s永远不会伤害我。",
    ATTACKER = "算了，%s完全有能力伤害别人。",
    MURDERER = "谋杀，%s？又一个年轻人堕落了。",
    REVIVER = "%s，把敌人留在身边？",
    GHOST = "%s让我想起了阿比盖尔。",
    FIRESTARTER = "%s采取焦土策略。"
}

DESCRIBE.RATPOISONBOTTLE = "有这样的想法..."
DESCRIBE.RATPOISON =
"即使我参与其中，这个世界也会把我拖回来..."

DESCRIBE.MONSTERSMALLMEAT = "一小口，浓缩痛苦的黑暗之井..."
DESCRIBE.COOKEDMONSTERSMALLMEAT =
"小小的，充满痛苦，准备好被这个世界吞噬..."
DESCRIBE.MONSTERSMALLMEAT_DRIED =
"它身上的重负减轻了一些，但它永远无法真正摆脱本性..."

DESCRIBE.UM_MONSTEREGG = "我感觉它里面有邪恶。"
DESCRIBE.UM_MONSTEREGG_COOKED = "我摧毁了邪恶。"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD =
"一种寄生的存在，以大地为食。"
DESCRIBE.TOADLING = "它们对同类非常忠诚..."

DESCRIBE.GASMASK = "它能过滤空气，但过滤不了绝望。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "一个不可避免的结局。"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿嚏！阿嚏！ sniff。"
ANNOUNCE.ANNOUNCE_HAYFEVER = "呃，连我的鼻窦都在受苦。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF =
"我的鼻窦通畅了，但痛苦仍在继续。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
    "那些哭声很熟悉。", "我希望这是个迅速的结局。",
    "有些人只想看着世界燃烧。"
}
ANNOUNCE.ANNOUNCE_ROOTING = "你无法永远束缚我。"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "一旦风暴来袭，寒冷的死亡就在等待着我们。"
ANNOUNCE.SHADOWTALKER = {
    "她再也不会回来了", "我帮不了她", "这是我的错"
}
ANNOUNCE.ANNOUNCE_OVER_EAT = {
    STUFFED = "贪婪与暴食。",
    OVERSTUFFED = "纯粹的暴食。我感到羞愧。"
}
DESCRIBE.UM_SAND = "我想知道沙子是否知道自己的微不足道？"
DESCRIBE.UM_SANDHILL = "这看起来是暂时的。"
DESCRIBE.SNOWPILE = "寒冷的死亡在等待着我们。"
DESCRIBE.SNOWGOGGLES = "就像雪中的眼泪。"

DESCRIBE.SNOWMONG = "只是另一个残酷的玩笑。"
DESCRIBE.SHOCKWORM = "黑暗中的光芒。"
DESCRIBE.ZASPBERRY =
"也许它会给我的生活带来一些光明。可能不会。"
DESCRIBE.ZASPBERRYPARFAIT = "麻木。"
DESCRIBE.ICEBOOMERANG = "从蛆虫尾巴上撕下来的。"
DESCRIBE.MINOTAUR_BOULDER = "我们又一次勉强躲过了死亡。"
DESCRIBE.MINOTAUR_BOULDER_BIG = "鲁莽将是那生物的毁灭。"
DESCRIBE.VETERANSHRINE = "我已经习惯了痛苦。"
DESCRIBE.VET_SKULL = "我们被剥夺了这种必然性。"
DESCRIBE.UM_BOSS_SOUL = "一颗被腐蚀的灵魂。"
DESCRIBE.UM_DARK_VESTIGES = "这就是剩下的全部吗？"
DESCRIBE.UM_VOXOLOPHONE = "你会把我引向另一条黑暗的道路吗？"

DESCRIBE.UM_EXHUMER = "死亡只是开始。"
DESCRIBE.UM_WINGSUIT = "即使是飞行也无法让我摆脱这个地方。"
DESCRIBE.UM_MOONFLY_LANTERN = "黑暗中的另一盏灯。多么不幸。"

DESCRIBE.RAT_TAIL = "它包含着死亡的侍从。"
DESCRIBE.PLAGUEMASK = "就像乌鸦一样，瘟疫医生被死亡所吸引。"
DESCRIBE.SPIDER_TRAPDOOR = "我是猎物，还是它是？"
DESCRIBE.TRAPDOOR = "一座山丘，死于此处。"
DESCRIBE.HOODEDTRAPDOOR = "一块哭泣的石头。"
DESCRIBE.WICKER_TENTACLE = "这个快到生命的尽头了。"
DESCRIBE.HONEY_LOG = "如果必须的话，我会吃掉它的肉来生存。"

DESCRIBE.BUSHCRAB = "大自然母亲的另一个残酷玩笑。"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "我希望我能把阿比盖尔从死亡中带回来。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "一把从骨头上撕下的肉。"
DESCRIBE.AIR_CONDITIONER = "怡人的香气给人虚假的希望。"
DESCRIBE.SPOREPACK = "它散发着恶臭，就像其他一切一样。"
DESCRIBE.SALTPACK =
"It deals with menial chores. My other problems remain unsolved."



DESCRIBE.SKELETONMEAT = "以肉换肉..."
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "一名行刑者从黑暗中走出。"
DESCRIBE.VAMPIREBAT = "它设法比同伴活得更久。"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN =
"我可以用一些月岩来交些新朋友。"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "另一个简单的工具。"
-- Swampyness
DESCRIBE.RICEPLANT = "一份奖赏。高于水坟。"
DESCRIBE.RICE = "需要烹饪。"
DESCRIBE.RICE_COOKED = "这应该够了...暂时。"
DESCRIBE.SEAFOODPAELLA = "它清理了我的鼻子，但很快又被堵上了。"
DESCRIBE.LICELOAF = "缺乏味道。"

DESCRIBE.STUMPLING = "一个木头小妖精。"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "看来月亮也知道悲伤。"
DESCRIBE.SHADOW_TELEPORTER = "你不能永远抓住那东西。"
DESCRIBE.POLLENMITEDEN = "它们在构建自己的厄运。"
DESCRIBE.POLLENMITES = "就像生活一样，它们一点一点地消耗你。"
DESCRIBE.SHADOW_CROWN =
"这就是老年人感受到的青春吗？精力充沛，却又脆弱？"
DESCRIBE.UM_SHADOW_AXE = "过去的幽灵似乎仍附着其上。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.SUNGLASSES = " 好极了，现在世界又暗了一层。"
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "真正的恶魔被锻造来击垮我！"
DESCRIBE.MARSH_GRASS = "我对这个没什么好说的。"
DESCRIBE.CURSED_ANTLER = "生命没有磨损它。我羡慕它。"
DESCRIBE.BERNIEBOX = "玩具是给孩子们的。"
DESCRIBE.HOODED_FERN = "绿色而无聊，像大多数植物一样。"
DESCRIBE.HOODEDWIDOW = "她可以一口吃掉我。"
DESCRIBE.GIANT_TREE = "古老的，充满生机。"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST

DESCRIBE.WIDOWSGRASP = "它本可以轻易刺穿我的胸膛。我希望它做到了。"
DESCRIBE.SILKSACK = "用来携带沉重而怪异的负担。"
DESCRIBE.SILKEN_BUNDLE = "无论里面是什么，现在都粘粘的。"

DESCRIBE.WEBBEDCREATURE = "如果我犯了错误，那可能就是我其中之一。"
ANNOUNCE.WEBBEDCREATURE = "解开这个需要蜘蛛的触碰..."
DESCRIBE.SNAPDRAGON_BUDDY = "为食物而活，像其他一切一样。"
DESCRIBE.SNAPDRAGON = "我看过的花更漂亮。"
DESCRIBE.SNAPPLANT = "这两个有着几乎不可分离的纽带。"
DESCRIBE.WHISPERPOD = "它不会自己成长。"
DESCRIBE.WHISPERPOD_NORMAL_GROUND = {
    GENERIC = "它需要别的东西才能成长。",
    GROWING = "继续成长。我会等的。"
}
DESCRIBE.FRUITBAT = "什么？！"
DESCRIBE.PITCHERPLANT = "遥不可及..."
DESCRIBE.APHID = "它们困扰着树木。"
DESCRIBE.NYMPH = "瘟疫正在蔓延。"
DESCRIBE.GIANT_TREE_INFESTED = "它在与死亡抗争。"
DESCRIBE.GIANT_BLUEBERRY = "它会在我的嘴里爆炸吗？"
DESCRIBE.BLUEBERRYPANCAKES = "味觉爆炸。"
DESCRIBE.DEVILSFRUITCAKE = "别诱惑疼痛的牙齿。"
DESCRIBE.SIMPSALAD = "这不是斋戒的时候。"
DESCRIBE.BEEFALOWINGS = "你想试试吗，阿比盖尔？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我的立场不会动摇。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "我的立场正在动摇。"
DESCRIBE.WIDOWSHEAD = "这次，深渊将凝视着我。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "你一点也不吓人。"

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "幻象只会让人偏离现实。"
DESCRIBE.VIPERFRUIT = "我们的友谊只是幻象。"
DESCRIBE.VIPERFRUIT_LESSER = DESCRIBE.VIPERFRUIT
DESCRIBE.VIPERJAM = "不完美的色彩混合。"

DESCRIBE.BLUEBERRYPLANT = {
    READY = "吃它会造成混乱，就像我做的其他一切一样。",
    FROZE = "遥不可及，就像阿比盖尔。",
    REGROWING = "哦，它还在那儿。"
}

DESCRIBE.ANTIHISTAMINE = "我想这能清理堵塞的鼻窦。"
ANNOUNCE.CURSED_ITEM_EQUIP = "触摸时会灼烧。"
DESCRIBE.VETSITEM = "它相信我的双手是纯洁无瑕的。"
DESCRIBE.SCREECHER_TRINKET = "死亡的恶臭在此徘徊。"
ACTIONFAIL.GIVE.NOTNIGHT = "它在等待夜幕降临。"

DESCRIBE.MAGMAHOUND = "它向被诅咒者降下地狱之雨。"
DESCRIBE.LIGHTNINGHOUND = "来自上方的死亡！"
DESCRIBE.SPOREHOUND = "一个不幸的野兽。"
DESCRIBE.GLACIALHOUND = "它冻结的心仍在跳动。"
DESCRIBE.RNESKELETON = "收割者来接我了吗？你花了多长时间？"
DESCRIBE.RAT_WHIP = "多么屈辱。"
DESCRIBE.KLAUS_AMULET = "另一把锁。"
DESCRIBE.CRABCLAW = "轻轻一剪就能切断肢体。"
DESCRIBE.HAT_RATMASK = "我能闻到几英里外的害虫味。"

DESCRIBE.ORANGE_VOMIT = "如同人生。"
DESCRIBE.GREEN_VOMIT = "如同人生。"
DESCRIBE.RED_VOMIT = "如同人生。"
DESCRIBE.PINK_VOMIT = "如同人生。"
DESCRIBE.YELLOW_VOMIT = "如同人生。"
DESCRIBE.PURPLE_VOMIT = "如同人生。"
DESCRIBE.PALE_VOMIT = "如同人生。"

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = {
    GUARD = DESCRIBE.PIGMAN.GUARD,
    WEREPIG = DESCRIBE.PIGMAN.WEREPIG
}

DESCRIBE.BIGHT = "它生活在痛苦中。"
DESCRIBE.KNOOK = "对它来说每一秒的生命都是折磨。"
DESCRIBE.ROSHIP = "多么悲惨的存在。"

DESCRIBE.UM_PAWN = "一生无尽的巡逻。"
DESCRIBE.UM_PAWN_NIGHTMARE = "它有一个暴力的结局。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "它会把我灵魂的剩余部分聚集在一起。"
DESCRIBE.UM_BEAR_TRAP = "野兽的下颚在每个角落等待着攻击。"
DESCRIBE.UM_BEAR_TRAP_OLD =
"野兽的下颚在每个角落等待着攻击。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "一种残忍、不人道的工具。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "一种残忍、不人道的工具。"
DESCRIBE.CORNCAN = "看起来像是玉米。"
DESCRIBE.SKULLCHEST_CHILD =
"我能够触及另一个层面，但我仍然无法触及阿比盖尔..."

DESCRIBE.SLOBBERLOBBER = "大自然令人作呕。"
DESCRIBE.GORE_HORN_HAT = "大自然的匕首。"
DESCRIBE.BEARGERCLAW = "我的眼睛进了灰尘。这次是真的。"
DESCRIBE.FEATHER_FROCK = "死去并被拔掉羽毛。"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM .. "\n我毁掉了魔法。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM .. "\n我毁掉了魔法。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM .. "\n我毁掉了魔法。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM .. "\n我毁掉了魔法。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM .. "\n我毁掉了魔法。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM .. "\n我毁掉了魔法。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM ..
    "\n我毁掉了魔法。"

DESCRIBE.RED_MUSHED_ROOM = "它的希望和梦想被粉碎了。"
DESCRIBE.GREEN_MUSHED_ROOM = "它的希望和梦想被粉碎了。"
DESCRIBE.BLUE_MUSHED_ROOM = "它的希望和梦想被粉碎了。"

-- StantonStuff
DESCRIBE.SKULLFLASK = "它帮助我应对。"
DESCRIBE.SKULLFLASK_EMPTY = "请回来..."
DESCRIBE.STANTON_SHADOW_TONIC = "黑色的恶心东西。"
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "我对你没兴趣。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "一切都...更好了..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "我的头脑正在清醒。呃。"
-- StantonStuff

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "我希望我能和阿比盖尔分享。"
DESCRIBE.DEERCLOPS_BARRIER = "这些中有一些有裂缝。"

DESCRIBE.MOONMAW_DRAGONFLY =
"我在它身上看到了自己.. 反射中，我能看到我的倒影。"
DESCRIBE.MOONMAW_LAVAE = "匕首瞄准我的心！"
DESCRIBE.SNAPPERTURTLE = "我希望有时能躲在壳里。"
DESCRIBE.SNAPPERTURTLEBABY = "我可以让你翻过来然后你就死了。"
DESCRIBE.SNAPPERTURTLENEST = "哦，喜悦。"
DESCRIBE.GLASS_SCALES = "腐败的鳞片。"
DESCRIBE.MOONGLASS_GEODE =
"能腐蚀邪恶野兽的东西，肯定也能腐蚀人类？"
DESCRIBE.ARMOR_GLASSMAIL = "我周围的一切都在死去。"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "一次失误我就会失去自己的肢体。"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "要是那喙更锋利就好了..."
DESCRIBE.SNOTROAST = "我永远不会这么堕落。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我真的跌到了谷底。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "我再也尝不出那恶毒的味道了。"
DESCRIBE.BOOK_RAIN_UM = "它让周围的世界反映我的观点。"
DESCRIBE.FLORAL_BANDAGE = "可以治愈破碎的心，但治不好破碎的心智。"
DESCRIBE.DORMANT_RAIN_HORN = "我记得这个。"
DESCRIBE.RAIN_HORN = "它让周围的世界反映我的观点。"
DESCRIBE.DRIFTWOODFISHINGROD =
"大海只是让它变得更好，它想要鱼消失。"

ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
    LEVEL_1 = "如果我们不关心自己的财物，它们就会溜走。"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
    LEVEL_1 = "我们的营地散发着死亡的味道，害虫们都注意到了。"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
    LEVEL_1 = "啮齿动物正在某处集结进攻。"
}

DESCRIBE.PIED_RAT = "多么可怕的声音。"
DESCRIBE.PIED_PIPER_FLUTE = "充满了那野兽的唾液。"
DESCRIBE.UNCOMPROMISING_PACKRAT =
"你的背包不会帮你承担世界的重担。"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "这个木筏即将抛弃我让我溺水。"

ACTIONFAIL.CHARGE_FROM = {
    NOT_ENOUGH_CHARGE = "里面没有生命力。",
    CHARGE_FULL = "电池已经满了。"
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "它本可以电死我。"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED =
"它本可以电死我。我希望它做到了。"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "如果空了就没有用了。"
ACTIONFAIL.WINONATOOLBOX = "不是我的东西不能拿。"
DESCRIBE.WINONA_CATAPULT_ITEM_UM = "我对无生命的机器不感兴趣。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM_UM = "我对无生命的机器不感兴趣。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM_UM = "我对无生命的机器不感兴趣。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM_UM = "我对无生命的机器不感兴趣。"
DESCRIBE.POWERCELL = "它为电子设备提供能量。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL =
"也许这就是人类的未来？"
DESCRIBE.MINERHAT_ELECTRICAL = "光就是光，我有什么好抱怨的？"
DESCRIBE.LANTERN_ELECTRICAL = "更亮的灯光带来更深的阴影。"
DESCRIBE.OCEAN_SPEAKER =
"它坏了，里面空空的。只播放忧郁的曲调。"
-- DESCRIBE.UM_SIREN = "She manipulates her pawns through song. A very potentent ability..."

DESCRIBE.OCUPUS_BEAK = "这有什么用呢？"
DESCRIBE.OCUPUS_TENTACLE = "它想把我拉入深渊。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "也许应该把它扔回去。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "一根精心烹饪的触须。"
DESCRIBE.UM_OCUPUS_EYE = "看起来像是深渊的观察者。"
DESCRIBE.UM_OCUPUS_EYETACLE = "深渊正在凝视着我们。如果不想加入它们，我们应该摧毁它。"
DESCRIBE.UM_OCUPUS_TENTACLE = "它试图把我们拖下去。"
DESCRIBE.UM_OCUPUS_BEAK = "我需要捂住耳朵。"
DESCRIBE.BEAKBASHER = "一个由深渊生物创造的毁灭者。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "曼德拉草可能复活了，但它没有生命。"

DESCRIBE.ARMOR_REED_UM = DESCRIBE.ARMORGRASS
DESCRIBE.ARMOR_SHARKSUIT_UM =
"总有更高层次的捕食者。"
DESCRIBE.ROCKJAWLEATHER = "即使是它们的皮肤也会反击。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = "于是，死亡带来了新的生命。"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS =
"它们凝视着我嘴里的无尽黑暗。"
DESCRIBE.UM_DEVILED_EGGS = "父辈的罪恶。"
DESCRIBE.LUSH_ENTRANCE = "我只能想象下面潜伏着什么恐怖。"
DESCRIBE.CRITTER_FIGGY = "它空洞的眼睛直视着我..."
DESCRIBE.GIANT_TREE_BIRDNEST =
"它们还未孵化，世界却已残酷地将它们抛向捕食者。"

DESCRIBE.SLUDGE = "海洋的邪恶混合物。"
DESCRIBE.SLUDGE_OIL = "一杯死亡之饮。"
DESCRIBE.SLUDGE_SACK = "一个湿漉漉的袋子。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "愿另一端的人快速解脱。"
DESCRIBE.BOAT_BUMPER_SLUDGE =
"这只会延缓不可避免的事情。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "这只会延缓不可避免的事情。"
DESCRIBE.BOATPATCH_SLUDGE = "暂时保护我们免受大海的残酷。"
DESCRIBE.UM_COPPER_PIPE = "空心的。"
DESCRIBE.BRINE_BALM = "用痛苦来抚平我的伤口。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "永远被封存。"
DESCRIBE.UM_BEEGUN = "千刀万剐的死亡。"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "为了得到这个真是费尽周折。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER = "现在我可以转动这艘船了。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM =
"它可以转动整艘船，如果我有的话。"
DESCRIBE.BOAT_BUMPER_COPPER = "这会持续更久，但不会永远。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "这会持续更久，但不会永远。"
DESCRIBE.UM_DREAMCATCHER = "哦，去捕捉一个梦吧。"
DESCRIBE.UM_BRINEISHMOSS = "悲伤的苔藓。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "持续折磨的梦境。"
DESCRIBE.SLUDGE_CORK = "用来堵住海洋的粘稠泪水。"
DESCRIBE.SLUDGESTACK = "从咸水深处升起的泪水。"
DESCRIBE.SPECTER_SHIPWRECK = "被遗弃在海洋中腐烂。"

DESCRIBE.UNCOMPROMISING_HARPOON =
"从远处刺击东西从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它看起来没那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是真正的交易。"
DESCRIBE.UM_MAGNERANG = "我不擅长让东西靠近。"
DESCRIBE.UM_MAGNERANGREEL = "我也有分离焦虑。"
DESCRIBE.SIREN_THRONE = "一个统治无尽虚无的王座。"
DESCRIBE.LAVASPIT_SLUDGE = "一个诱人的方式，在火焰中结束。"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "它们是我们应该避免的战斗..."

DESCRIBE.PORTABLEBOAT_ITEM = "它不会和我们一起沉入浑浊的深渊。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "一个无尽的循环。"

DESCRIBE.UM_ORNAMENT_OPOSSUM =
"它真的死了吗，还是只是在装死？你怎么看，阿比盖尔？"
DESCRIBE.UM_ORNAMENT_RAT = "老鼠的寿命很短。"

DESCRIBE.TRINKET_WATHOM1 = "破碎且毫无价值。就像...算了。"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

-- WIXIE RELATED STRINGS

DESCRIBE.WIXIE_PIANO = "我只会弹悲伤的曲子。对不起..."
DESCRIBE.WIXIE_CLOCK = "它看起来已经见过它的制造者了。"
DESCRIBE.WIXIE_WARDROBE = "里面可能藏着黑暗的秘密。"
DESCRIBE.CHARLES_T_HORSE = "失去的纯真..."
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "它可能会给别人带来快乐。"
DESCRIBE.SLINGSHOT_MATILDA = "我想她想要一个妹妹。"
DESCRIBE.SLINGSHOT_GNASHER = "她和阿比盖尔可能会成为好朋友..."

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_THULECITE

DESCRIBE.BAGOFMARBLES = "明亮而愉快。我讨厌它。"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,

    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,

    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT
}
DESCRIBE.FISHMEAT_DRIED = "死了，干了，美味。"
DESCRIBE.SMALLFISHMEAT_DRIED = "你几乎看不出它曾经是一条鱼。"

DESCRIBE.WIXIEGUN = "冷酷的钢铁。"

DESCRIBE.MARA_BOSS1 = "终于。"
ANNOUNCE.GAS_DAMAGE = "咳。我完了！"

-- Pyre Nettle stuff
DESCRIBE.UM_PYRE_NETTLES = "一旦习惯了，毒素也没那么糟糕。"
DESCRIBE.UM_SMOLDER_SPORE = "再靠近一点..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "让我们赶紧结束吧。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "也许如果我注意了，它就不会这样结束..."
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "生活中痛苦的提醒。"
DESCRIBE.UM_BLOWDART_PYRE = "从远处送来的死亡。"

-- Under the Weather Part 1
DESCRIBE.ALPHA_LIGHTNINGGOAT = "保护好你自己，否则你会失去它们..."
DESCRIBE.UM_TORNADO = "没有地方像家一样..."
DESCRIBE.UM_WATERFALL = "洗去我们的泪水。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有龙卷风来给我们带来痛苦。"

DESCRIBE.UM_BOAT_ENGINE = {
    ON = "请写一些引人注目的描述。",
    LOWFUEL = "请写一些引人注目的描述。",
    OVERHEATING = "请写一些引人注目的描述。"
}

-- Broiling Hills
DESCRIBE.BOULDER_CRAB =
{
    GENERIC = "这不是一块石头！",
    NAKED = "我为它感到难过。",
}

DESCRIBE.BOULDER_CRAB_HOLE = "这是一个洞。"

DESCRIBE.UM_HOTSPRING = "它被熔岩加热。"

DESCRIBE.UM_PLANT_HOTSPRINGS = DESCRIBE.MARSH_PLANT --POND_ALGAE

DESCRIBE.ROCK_LICHEN =
{
    GENERIC = "它们喜欢潮湿。",
    PICKED = "殖民地会在时间中重生。",
}

-- All things Snaildrake
DESCRIBE.SNAILDRAKE_MAGMA = "它们似乎有爆炸性的性格。"
DESCRIBE.SNAILDRAKE_SLIME = DESCRIBE.SNAILDRAKE_MAGMA
DESCRIBE.SNAPALM = "我不确定拿着这个是否安全。"
DESCRIBE.SNAILDRAKEHAT = "它会弄乱我的头发。"
DESCRIBE.SNAILDRAKEBUCKET =
{
    GENERIC = "看起来可以装满。",
    WATER = "我已经取了一桶水。",
    LAVA = "热东西。",
}
DESCRIBE.SNAILDRAKE_HOLE = "只是一个洞。"

-- All things Rimeweed
DESCRIBE.RIMEWEED_MAIN = "那杂草在制造这种藤蔓混乱。"
DESCRIBE.RIMEWEED_BARRIER = "看起来像是一个刺冷的前线。"

DESCRIBE.UM_RIMEWEED_ITEMVINE = "它触感刺痛且冰冷。"
DESCRIBE.UM_RIMEWEED_ITEMFLOWER = "它出奇的坚韧。"

DESCRIBE.RIMEWEED_WHIP = "我会站在它的处理端。"

DESCRIBE.UM_RIMEWEED_TEQUILA = "太冷了，无法享受。"
DESCRIBE.UM_RIMEWEED_SPAGETT = "脆脆的意大利面，不是我的首选。"

-- Lava Caves
DESCRIBE.MAGMAROCK1 = DESCRIBE.ROCKS
DESCRIBE.MAGMABONE = "我想知道虫子是否吃了它。"

DESCRIBE.UM_COOKPOT_WAGSTAFF = {
    EMPTY = "一切都变了。",
    COOKING_LONG = DESCRIBE.COOKPOT.COOKING_LONG,
    COOKING_SHORT = DESCRIBE.COOKPOT.COOKING_SHORT,
    DONE = DESCRIBE.COOKPOT.DONE,
    BURNT = DESCRIBE.COOKPOT.BURNT,
}
DESCRIBE.UM_COOKPOT_WAGSTAFF_DISPLAY = "一份阴暗的成分清单。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER = "离开这一切。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER2 = "没有什么能永远保持不变。"

DESCRIBE.UM_RICE_PUDDING = "这至少有味道。"

DESCRIBE.UM_BOATBOTTLE = {
    FULL = "在我指尖上移动整艘船的力量。",
    EMPTY = "暂时从它曾经航行的地方移除。"
}

ANNOUNCE.ANNOUNCE_BUTTERFLY_SLIP = {"你无法从死亡的掌握中溜走。",
    "如果我抓不到你，死亡迟早会抓到你。",
    --"也许阿比盖尔可以试试。",
    "飞行只能带你到这么远。",
    "最好等它降落。"}
	
DESCRIBE.WATHOM_CORPSE = "再次崛起，让你再次感受到死亡的刺痛。"

DESCRIBE.WATHGRITHR_SHIELD_DREADSTONE = "坚硬而冰冷，像这个世界。"
ANNOUNCE.ANNOUNCE_WEAPON_TOOWEAK_ICESHIELD = "请写一些聪明的描述。\n提到你需要火或其他东西。"
