ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WES
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WES.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WES.ACTIONFAIL

--	[ 		Wes Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "..."
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "...!"
ANNOUNCE.ANNOUNCE_WINONAGEN = "..."
ANNOUNCE.ANNOUNCE_RATRAID = "..."
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "!"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "..."
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "...", "!", "..."
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "..."

ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = "...!"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = "...!"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = "..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = "..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "..."

ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "..."
DESCRIBE.CALIFORNIAKING = "..."