ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WILLOW
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WILLOW.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WILLOW.ACTIONFAIL

--	[ 		Willow Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "伯尼！帮帮我！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "等等，我该把这东西放在哪里？"
ANNOUNCE.ANNOUNCE_WINONAGEN = "呃，我不想手上沾上油脂！"
ANNOUNCE.ANNOUNCE_RATRAID = "我真的不喜欢那种声音......"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "呃，为什么一定是老鼠？！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "嘿，我的东西！回到这里！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"哦，哦，哦！",
"雨水不应该燃烧！",
"哇！ 疼痛的感觉是相互的，水！",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "哇！就是这样！"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "伯尼，救我！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了。"
--FoodBuffs

--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "哈 哈 哈！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "我还想再吃一次！"
DESCRIBE.CALIFORNIAKING = "如果它着火了会更好。"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "H-hello?"
DESCRIBE.UNCOMPROMISING_RAT = "离伯尼远点！"
DESCRIBE.UNCOMPROMISING_RATHERD = "哎呀，我们能把它砸碎吗？"
DESCRIBE.UNCOMPROMISING_RATBURROW = "哎呀，我们能把它砸碎吗？"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "哎呀，我们能把它砸碎吗？"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "哎呀，我们能把它砸碎吗？"
	
DESCRIBE.WINKY =
{
    GENERIC = "咦噢!一只巨大的老鼠！",
    ATTACKER = "别咬我的脚后跟！",
    MURDERER = "你永远拿不走我的东西",
    REVIVER = "如果我找到任何奶酪，欢迎共同享用!",
    GHOST = "我曾经养过一只宠物鼠。不知道她是不是也变成了鬼？",
    FIRESTARTER = "你对老鼠来说还不错!",
}
DESCRIBE.WATHOM =
{
GENERIC = "你会用那样的嘴让苍蝇进来！",
     ATTACKER = "冷静下来，%s!",
     MURDERER = "又一头愤怒的凶残野兽！",
     REVIVER = "你会再次用那口气杀了我！",
     GHOST = "%s 看起来更像幽灵！",
     FIRESTARTER = "一个烧东西的怪物？我希望我不是在照镜子。",
}
DESCRIBE.WIXIE =
{
GENERIC = "我也没有朋友，但这不是因为我是个混蛋！",
     ATTACKER = "别再用石头砸人了，你这个混蛋！",
     MURDERER = "%s 疯了！",
     REVIVER = "别表现得像你的朋友，%s！",
     GHOST = "这就是你欺负人的下场，%s!",
     FIRESTARTER = "你也喜欢烧东西？也许我们可以成为朋友！",
}
		
DESCRIBE.RATPOISONBOTTLE = "是的，它会解决那些恶心的小混蛋！"
DESCRIBE.RATPOISON = "来来来，吃掉它吃掉它..."

DESCRIBE.MONSTERSMALLMEAT = "它来自毛茸茸的小怪物..."
DESCRIBE.COOKEDMONSTERSMALLMEAT = "我不认为我能把所有的头发都烧掉..."
DESCRIBE.MONSTERSMALLMEAT_DRIED = "现在它又脏又旧。"

DESCRIBE.UM_MONSTEREGG = "它闻起来像死亡！来自某只鸟!"
DESCRIBE.UM_MONSTEREGG_COOKED = "紫色的东西在动吗?!"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "呕！烧掉它！"
DESCRIBE.TOADLING = "好恶心！看起来就黏糊糊的。"
	
DESCRIBE.GASMASK = "停止咳嗽。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "烧掉它！烧掉它！呜呜呜！"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿嚏！！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "我的鼻窦在燃烧。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "闻一闻，我现在感觉好多了！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "我觉得暴风雪要来了，我讨厌冬天。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"是的！燃烧！",
	"我想看到这个世界燃烧！",
	"是的！来自大地的火焰！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "哦，你真的想被烧掉？"
ANNOUNCE.SHADOWTALKER = {
"火焰是我唯一的安慰",
"我把一切都燃尽了",
"灰烬，灰烬……",
}
	
DESCRIBE.UM_BEAR_TRAP = "我不会上当的！"
DESCRIBE.UM_BEAR_TRAP_OLD = "哪个混蛋把它丢在这里了？"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "看！鲨鱼的牙齿！"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "看！闪闪发光的鲨鱼牙齿！"
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "第二顿太诱人了。",
	OVERSTUFFED = "我真的不该吃第三顿！",
}
DESCRIBE.UM_SAND = "重要的是，这是沙子。"
DESCRIBE.UM_SANDHILL = "哦，看！是一堆沙子。"
DESCRIBE.SNOWPILE = "火似乎异常无效。"
DESCRIBE.SNOWGOGGLES = "现在我可以看到世界的反面正在燃烧。"
	
DESCRIBE.SNOWMONG = "融化那些混蛋！"
DESCRIBE.SHOCKWORM = "满身褶皱。"
DESCRIBE.ZASPBERRY = "我不会浪费任何莓子。"
DESCRIBE.ZASPBERRYPARFAIT = "我舔的时候舌头会发麻。"
DESCRIBE.ICEBOOMERANG = "我的意思是，我觉得我们可以使用它。"
DESCRIBE.MINOTAUR_BOULDER = "注意一下这东西的落点！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "过来，笨蛋！ 自己撞上来吧！"
DESCRIBE.SNOWBALL_THROWABLE = 
"呃，雪很无聊！让我们扔火球吧！"
DESCRIBE.VETERANSHRINE = "呕，它被黏液覆盖了。"
DESCRIBE.VET_SKULL = "唉，可怜的……不管你是谁！"
DESCRIBE.UM_BOSS_SOUL = "恐怖！"
DESCRIBE.UM_DARK_VESTIGES = "这是某种散发着恶臭的令人毛骨悚然的胶水！"
DESCRIBE.UM_VOXOLOPHONE = "我们真的在听广播里的另一个怪物吗？"

DESCRIBE.UM_EXHUMER = "让我成为一支无意识骷髅大军！"
DESCRIBE.UM_WINGSUIT = "我要飞向太阳！"
DESCRIBE.UM_MOONFLY_LANTERN = "紧随其后的是火光……"

DESCRIBE.RAT_TAIL = "恶心..."
DESCRIBE.PLAGUEMASK = "我像一只凤凰！"
DESCRIBE.SPIDER_TRAPDOOR = "我更喜欢你在岩石下面。"
DESCRIBE.TRAPDOOR = "这只是块石头。"
DESCRIBE.HOODEDTRAPDOOR = DESCRIBE.TRAPDOOR 
DESCRIBE.WICKER_TENTACLE = "现在它们看起来特别恶心！"
DESCRIBE.HONEY_LOG = "你毁了它！这柴火没用！"

DESCRIBE.BUSHCRAB = "应该把它烧掉... 就应该把它烧掉！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "我宁愿烧掉有病的植物。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "要么直接把它烧掉，要么从来就不曾拥有过。"
DESCRIBE.AIR_CONDITIONER = "它能喷火吗？"
DESCRIBE.SPOREPACK = "气味是火无法处理的！"
DESCRIBE.SALTPACK = "我仍然讨厌冬天。"
	
DESCRIBE.UM_SCORPION = "呃，恶心！"
DESCRIBE.SCORPIONCARAPACE = "需要大量的火来解决这玩意。"
DESCRIBE.SCORPIONCARAPACECOOKED = "难以置信，火还不够大..."
DESCRIBE.HARDSHELLTACOS = "这个还不错。"
	
DESCRIBE.SKELETONMEAT = "我要吐了..."
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "威-威尔逊？"
DESCRIBE.VAMPIREBAT = "哦，你真令人毛骨悚然。"
DESCRIBE.LUREPLAGUE_RAT = "离我远点！"
				
--Swampyness
DESCRIBE.RICEPLANT = "只是一些潮湿的植物。"
DESCRIBE.RICE = "需要先烧一下。"
DESCRIBE.RICE_COOKED = "这样会更好。"
DESCRIBE.SEAFOODPAELLA = "吃完这个我应该会停止打喷嚏。"
DESCRIBE.LICELOAF = "应该放久一点，味道会更好。"
DESCRIBE.SUNGLASSES = "我可以用它看一整天的太阳！"
	
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "我可以用一些月岩建造一个迷你寄养家庭。"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "我更喜欢火而不是电，除非是带电的火！"
DESCRIBE.STUMPLING = "你绝对是易燃物！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "把它收起来！它在为所有事情哭泣！"
DESCRIBE.SHADOW_TELEPORTER = "哦！给我！"
DESCRIBE.POLLENMITEDEN = "很起来很易燃，非常易燃。"
DESCRIBE.POLLENMITES = "是的！它们应该很容易燃烧！"
DESCRIBE.SHADOW_CROWN = "戴上它真让我不舒服。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.MARSH_GRASS = "它会烧起来吗？"	
DESCRIBE.CURSED_ANTLER = "它永远不会离开我，除非我主动抛弃它。"
DESCRIBE.BERNIEBOX = "我喜欢保留外包装。"
DESCRIBE.HOODED_FERN = "我真的不理解为什么不应该烧掉它？"
DESCRIBE.HOODEDWIDOW = "我不会接近它的！"
DESCRIBE.GIANT_TREE = "那是一棵大树。"
DESCRIBE.WIDOWSGRASP = "呃，我不想抓住它！"
DESCRIBE.WEBBEDCREATURE = "为什么不让我烧了它们？"
ANNOUNCE.WEBBEDCREATURE = "我没法做到！我需要那个蜘蛛的爪子！"
DESCRIBE.SNAPDRAGON_BUDDY = "这食物是我的，你不能吃。"
DESCRIBE.SNAPDRAGON = "我想知道你是否会比大多数人烧得更亮。"
DESCRIBE.SNAPPLANT = "这个大个子非常喜欢那些愚蠢的植物。"
DESCRIBE.WHISPERPOD = "糟糕，把它插在地上就好了。"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "我觉得它想要什么东西。",
	GROWING = "快点长，你个愚蠢的植物！",
}
DESCRIBE.FRUITBAT = "如果它静止不动，我就会把它烧掉。"
DESCRIBE.PITCHERPLANT = "如果它在低处，我会把它烧掉。"
DESCRIBE.APHID = "你的绒毛会成为很好的火种。"
DESCRIBE.NYMPH = "您的蜡几乎不需要任何热量即可融化。"
DESCRIBE.GIANT_TREE_INFESTED = "把昆虫烧掉！"
DESCRIBE.GIANT_BLUEBERRY = "我的牙被卡住了！"
DESCRIBE.STEAMEDHAMS = "这是一个火腿三明治。"
DESCRIBE.BLUEBERRYPANCAKES = "噢噢噢噢！我迫不及待想吃掉你！"
DESCRIBE.SIMPSALAD = "我看到的只是潜在的火灾风险。"
DESCRIBE.BEEFALOWINGS = "如果它真的着火了会更热。"
DESCRIBE.DEVILSFRUITCAKE = "真是罪恶的甜蜜啊！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我不会再被推动了！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "呃，噢, 又被推来推去了！"
DESCRIBE.WIDOWSHEAD = "再也没有蒙面寡妇了！"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "继续燃烧吧，西瓜头。"
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "来吧，伯尼！来做点事吧！"
DESCRIBE.VIPERFRUIT = "它们现在和我们一起了，伯尼。"
DESCRIBE.VIPERJAM = "嘿，所有的粘性都包含在内！"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "嗯，不要介意我这样做！",
		FROZE = "天呐，它被冻在里面了！",
		REGROWING = "很有趣。",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "我需要修复伯尼。",
    GENERIC = "我的儿时伙伴 - 伯尼！",
    ASHLEY_BROKEN = "我需要修复Ashley。",
    ASHLEY = "我的儿时伙伴 - Ashley!",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "伯尼，救命！",
    ASHLEY = "Ashley，救命！",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "伯尼，抓住它们！！",
    ASHLEY = "ASHLEY，抓住它们！！",
}
		
ANNOUNCE.ANNOUNCE_UNCOMP_LIGHTFIRE =
{
	"嘻嘻！",
	"好耶！",
	"哎呀！",
	"我放了一把火！",
	"烧吧！",
	"我控制不了自己！",
}
DESCRIBE.ANTIHISTAMINE = "它会清理我的鼻涕。"
ANNOUNCE.CURSED_ITEM_EQUIP = "嗷！ 这就是被烧着的感觉吗？"
DESCRIBE.VETSITEM = "那是什么？ 你要我诅咒自己吗？ 如果你这么说..."
DESCRIBE.SCREECHER_TRINKET = "我... 我认为我不应该烧掉它。"
ACTIONFAIL.GIVE = {NOTNIGHT = "我会尽量等到晚上，嗯。"}

DESCRIBE.MAGMAHOUND = "是的！用火给我洗澡！"
DESCRIBE.LIGHTNINGHOUND = "闪电只是在燃烧，一点也不好玩！"
DESCRIBE.SPOREHOUND = "我不在乎你生病了，你还是个混蛋。"
DESCRIBE.GLACIALHOUND = "又一只冷狗？为什么你不能着火？"
DESCRIBE.RNESKELETON = "天呐，骷髅！！"
DESCRIBE.RAT_WHIP = "把它挥来挥去实在是太累了..."
DESCRIBE.KLAUS_AMULET = "哎呀，太重了！我应该穿这个？！"
DESCRIBE.CRABCLAW = "哈哈，重击！" 
DESCRIBE.HAT_RATMASK = "哎呀，我都能闻到它们的味道！" 

DESCRIBE.ORANGE_VOMIT = "哟呜呜呜!"
DESCRIBE.GREEN_VOMIT = "哟呜呜呜!"
DESCRIBE.RED_VOMIT = "哟呜呜呜!"
DESCRIBE.PINK_VOMIT = "哟呜呜呜!"
DESCRIBE.YELLOW_VOMIT = "哟呜呜呜!"
DESCRIBE.PURPLE_VOMIT = "哟呜呜呜!"
DESCRIBE.PALE_VOMIT = "哟呜呜呜!"
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "这匹马没死！"
DESCRIBE.KNOOK = "这个主教没死！"
DESCRIBE.ROSHIP = "你的脸真丑。"
	
DESCRIBE.UM_PAWN = "哔哔声太烦了！"
DESCRIBE.UM_PAWN_NIGHTMARE = "哔哔声太烦了！"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH		
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
DESCRIBE.CORNCAN = "可能是我见过的最无聊的东西之一。"
DESCRIBE.SKULLCHEST_CHILD = "可惜烧了一个以后，其他的也不能跟着一起烧掉。"
	
DESCRIBE.ANCIENT_AMULET_RED = "我希望我的灵魂留在我的身体里，谢谢。"
DESCRIBE.SLOBBERLOBBER = "我最喜欢的两件事，合二为一！"
DESCRIBE.GORE_HORN_HAT = "冲！冲！冲！"
DESCRIBE.BEARGERCLAW = "也许我可以用这个挖到地心。"
DESCRIBE.FEATHER_FROCK = "我是凤凰！听我叫！"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n我没有破坏它！我让它变得更好！"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n我没有破坏它！我让它变得更好！"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n我没有破坏它！我让它变得更好！"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n我没有破坏它！我让它变得更好！"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n我没有破坏它！我让它变得更好！"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n我没有破坏它！我让它变得更好！"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n我没有破坏它！我让它变得更好！"
	
DESCRIBE.RED_MUSHED_ROOM = "非常... 非常黏糊！"
DESCRIBE.GREEN_MUSHED_ROOM = "我不喜欢它，所以我把它压扁了！"
DESCRIBE.BLUE_MUSHED_ROOM = "我不喜欢它，所以我把它压扁了！"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "如果再热一点就更好了。"
DESCRIBE.SKULLFLASK_EMPTY = "一滴也没有了。"
DESCRIBE.STANTON_SHADOW_TONIC = "恶心！"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "酷酷的骷髅！ 它想要什么呢？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "我什么都不怕！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "我浑身起了鸡皮疙瘩..."
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "我宁愿把它烧掉，或者至少我可以边吃边看东西烧焦。"
DESCRIBE.DEERCLOPS_BARRIER = "你为什么烧不起来！" 
	
--Stuff for Canis to check

DESCRIBE.MOONMAW_DRAGONFLY = "你为什么存在？！" 
DESCRIBE.MOONMAW_LAVAE = "哦废物，哦废物，哦废物废物废物！"
DESCRIBE.SNAPPERTURTLE = "我更喜欢这些乌龟而不是金属乌龟。"
DESCRIBE.SNAPPERTURTLEBABY = "可爱，我猜。"
DESCRIBE.SNAPPERTURTLENEST = "你知道我要说什么..."
DESCRIBE.GLASS_SCALES = "蓝色火焰很漂亮..."
DESCRIBE.MOONGLASS_GEODE = "我们差点死掉，得到的只是一块愚蠢的石头？"
DESCRIBE.ARMOR_GLASSMAIL = "我更喜欢非月亮版本。"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "看到它们这样旋转让我头晕目眩！"
--Stuff for Canis to check
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR
	
DESCRIBE.WOODPECKER = "哈！它看起来烧焦了一半！"
DESCRIBE.SNOTROAST = "呕呕呕！ 我不想看它！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我需要烧掉我的嘴。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN = "我讨厌这本书。"
DESCRIBE.FLORAL_BANDAGE = "这太恶心了。"
DESCRIBE.DORMANT_RAIN_HORN = "烧不起来，不敢兴趣。"
DESCRIBE.RAIN_HORN = "我要退款。"
DESCRIBE.DRIFTWOODFISHINGROD = "这个比另一个好在哪里？"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "我们的基地太乱了，我们可以烧掉一些吗？",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "我们的食物闻起来很糟糕！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "外面有很多恶心的老鼠。",
}

DESCRIBE.PIED_RAT = "哇！他很臭！"
DESCRIBE.PIED_PIPER_FLUTE = "我先把它放在火上。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "让伯尼远离那个背包！"
	
ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "我的救生筏快要变成求死筏了！"

ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "出来了",
	CHARGE_FULL = "已经充满了!",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "哈，不能让我震惊！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "哦！ 不是我想的那样。"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "我必须随身携带所有东西吗？"
ACTIONFAIL.WINONATOOLBOX = "嘿，至少让我走个高峰。"
DESCRIBE.WINONA_CATAPULT_ITEM = "愚蠢的机器！"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "愚蠢的机器！"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "愚蠢的机器！"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "愚蠢的机器！"
DESCRIBE.POWERCELL = "是的，是的，它很好，但它燃烧得有多好。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "我们希望不会发生电气火灾，对吧？"
DESCRIBE.MINERHAT_ELECTRICAL = "为什么我不能用火来激活它！"
DESCRIBE.OCEAN_SPEAKER = "这台笨重的大机器在外面干什么？"
--DESCRIBE.UM_SIREN = "Oh yeah!? I can blow bubbles twice as big! Watch!"
	
--DESCRIBE.OCUPUS_BEAK = ""
DESCRIBE.OCUPUS_TENTACLE = "我并没有深陷其中。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "我不喜欢被我的食物盯上。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "那看起来还是有弹性的。"

DESCRIBE.ARMOR_REED_UM = "制作起来很有趣，是时候烧掉它了。"
DESCRIBE.ARMOR_SHARKSUIT_UM = ""
DESCRIBE.ROCKJAWLEATHER = "我不想要粗鱼皮。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
DESCRIBE.STUFFED_PEEPER_POPPERS = "哇，他们正看着我！"
DESCRIBE.UM_DEVILED_EGGS = "糟糕！我讨厌流蛋！"
DESCRIBE.LUSH_ENTRANCE = "哦，我敢打赌那里有各种各样的东西要烧掉！"
DESCRIBE.CRITTER_FIGGY = "哇！这么蓬松，我才不会在你身上烧一根头发！"
DESCRIBE.GIANT_TREE_BIRDNEST = "想想如果我点燃巢穴，鸡蛋会炸吗？"

    DESCRIBE.SLUDGE = "烧掉这些恶心的东西很容易。"
DESCRIBE.SLUDGE_OIL = "闻起来像是生火的好方法。"
    DESCRIBE.SLUDGE_SACK = "人类已知的最粗劣的背包。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "一块美丽的燃烧破坏。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "好吧，最好是让我的船免于沉没。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "烧掉它会更好。"
    DESCRIBE.BOATPATCH_SLUDGE = "呃，船会臭的！"
    DESCRIBE.UM_COPPER_PIPE = "这些根本不会燃烧。"
    DESCRIBE.BRINE_BALM = "另一种燃烧方式，我可以习惯这个。"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "漂亮。"
DESCRIBE.UM_BEEGUN = "每个人都有蜜蜂！"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "财富超出了我最疯狂的梦想。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "现在整条船都在旋转！"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "我还需要其中之一。"
DESCRIBE.BOAT_BUMPER_COPPER = 
"这是否意味着我也可以撞上很多我想要的东西？"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "所以，我猜这一定很强大。"
DESCRIBE.UM_DREAMCATCHER = "你能捕捉到我所有的噩梦吗？"
DESCRIBE.UM_BRINEISHMOSS = "又湿又恶心。"
DESCRIBE.UM_COALESCED_NIGHTMARE = 
"我什至不想去想它是从哪里来的。"
DESCRIBE.SLUDGE_CORK = "至少现在我可以堵住那些淤泥了！"
DESCRIBE.SLUDGESTACK = "来吧，看着它燃烧不是很有趣吗？"
DESCRIBE.SPECTER_SHIPWRECK = "它在水中，但看起来足够可燃。"

DESCRIBE.UNCOMPROMISING_HARPOON = 
"远距离刺伤从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
DESCRIBE.UM_MAGNERANG = "嘿，这曲折错了。"
DESCRIBE.UM_MAGNERANGREEL = "是的！让他们原地不动！"
DESCRIBE.SIREN_THRONE = "呃，谁愿意坐在一块又臭又臭的石头上？"
DESCRIBE.LAVASPIT_SLUDGE = "哈！这东西太棒了！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "那个混蛋让我远离！"

DESCRIBE.PORTABLEBOAT_ITEM = "防火船？全部上船！"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "它没有熊熊烈火的舒适光芒。"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "哦，是个小天使！"
DESCRIBE.UM_ORNAMENT_RAT = "我讨厌老鼠！ 哦，是假的吗？ 我仍然讨厌它！"

DESCRIBE.TRINKET_WATHOM1 = "哇！！这毫无价值。"
	
DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "土豆和糖蜜！"
DESCRIBE.WIXIE_CLOCK = "这是火钟！每天每小时！"
DESCRIBE.WIXIE_WARDROBE = "我讨厌不易燃的木头！"
DESCRIBE.CHARLES_T_HORSE = 
"我无法让自己燃烧它...因为它不会燃烧！"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "我已经有伯尼了！"
DESCRIBE.SLINGSHOT_MATILDA = "更多射击！"
DESCRIBE.SLINGSHOT_GNASHER = "它是红色的吗？"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = "Yes!! Now were talking!!"
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_THULECITE

DESCRIBE.BAGOFMARBLES = "一团小火焰被困在里面，等着出来！"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "呃，还是油腻的。"
DESCRIBE.SMALLFISHMEAT_DRIED = "还是寿司吗？"

DESCRIBE.WIXIEGUN = "是的！！暴力！！！"

DESCRIBE.MARA_BOSS1 = ""
ANNOUNCE.GAS_DAMAGE = "咳。咳。这就像没有火的烟。" --在我们实施鼠气时改变这一点。

-- 火焰荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "哦，真漂亮！但它可以更漂亮..."
ANNOUNCE.ANNOUNCE_FIRENETTLE_TOXIN = {
"好了，带来了热量！",
"事情正在升温！",
"这才像话！",
"嘿，这还挺舒服的。",
"我开始觉得心里暖洋洋的。",
"我的血管里有火! 呃，是真的吗？",
"嘿，其实这很好。"
}
DESCRIBE.UM_SMOLDER_SPORE = "啊，你不是一个有潜力的小球吗？"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "辣！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "哎呀!"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "感受燃烧！"
DESCRIBE.UM_BLOWDART_PYRE = "那是我的主意! 不客气。"

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "我喜欢你的颜色！"
DESCRIBE.UM_TORNADO = "这将会扑灭我所有的火！"
DESCRIBE.UM_WATERFALL = "唉！我来到这里是为了逃避所有的水。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "周围没有龙卷风。"
