ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WILSON
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WILSON.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WILSON.ACTIONFAIL

--	[ 		Wilson Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "我的灵魂正在被拉扯！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "这是不科学的！"
ANNOUNCE.ANNOUNCE_WINONAGEN = "让我们看看这台机器能做什么！"
ANNOUNCE.ANNOUNCE_RATRAID = "老鼠！"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "它们来了！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "我的研究材料！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "这雨有腐蚀性！", "啊！它刺痛我的皮肤！",
    "我需要找个避雨的地方！"
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "蘑菇！都是蘑菇！"

ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = "我感觉浑身充满了能量！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = "闪电的力量在我体内流动！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "这是为了科学！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "一个有趣的实验..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = "我的能量耗尽了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = "电荷已经耗尽。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "这和我预期的一样。"

ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "这应该很有趣！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "啊...我的头..."
DESCRIBE.CALIFORNIAKING = "科学的奇迹！"

DESCRIBE.UNCOMPROMISING_RAT = "真讨厌的小害虫！"
DESCRIBE.UNCOMPROMISING_RATHERD = "需要进行更多的研究。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "那里面有什么东西在动！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "一个奇特的地下洞穴。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "比普通的巢穴更加精致。"

DESCRIBE.WINKY = {
    GENERIC = "你好啊，%s！",
    ATTACKER = "%s看起来有点暴躁！",
    MURDERER = "科学警告我要小心你，%s！",
    REVIVER = "%s似乎很懂科学！",
    GHOST = "看来需要进行一些亡灵科学了。",
    FIRESTARTER = "火并不总是最好的解决方案！"
}
DESCRIBE.WATHOM = {
    GENERIC = "令人着迷的生物！",
    ATTACKER = "%s的行为需要更多研究！",
    MURDERER = "这个实验已经失控了！",
    REVIVER = "%s展现出了惊人的智慧！",
    GHOST = "又一个待解决的科学难题。",
    FIRESTARTER = "这不是正确的实验方法！"
}
DESCRIBE.WIXIE = {
    GENERIC = "你好，%s。让我们保持科学的态度！",
    ATTACKER = "%s似乎对科学有些敌意！",
    MURDERER = "这违背了科学道德！",
    REVIVER = "也许%s也有科学家的潜质！",
    GHOST = "看来我们需要做一些复活实验。",
    FIRESTARTER = "这不是负责任的科学态度！"
}

DESCRIBE.RATPOISONBOTTLE = "一个危险的化学实验。"
DESCRIBE.RATPOISON = "致命的化学配方。"

DESCRIBE.MONSTERSMALLMEAT = "这肉的分子结构很奇怪。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "烹饪改变了它的化学成分。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "脱水处理完成。"

DESCRIBE.UM_MONSTEREGG = "我想知道里面的DNA结构。"
DESCRIBE.UM_MONSTEREGG_COOKED = "蛋白质被高温改变了。"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "一个巨大的真菌样本！"
DESCRIBE.TOADLING = "它们似乎受到某种真菌的影响。"

DESCRIBE.GASMASK = "防止有害气体的必要装备。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "值得研究的标本。"
ANNOUNCE.ANNOUNCE_SNEEZE = "啊嚏！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "我的鼻子对空气中的某些粒子产生了过敏反应。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "过敏反应终于停止了。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
    "火山爆发的前兆！", "需要紧急避难！",
    "这里变得太热了！"
}
ANNOUNCE.ANNOUNCE_ROOTING = "我被束缚住了！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "大气压力在急剧变化！"
ANNOUNCE.SHADOWTALKER = {
    "我必须保持理性", "科学会给出答案",
    "这不符合逻辑", "保持冷静"
}
ANNOUNCE.ANNOUNCE_OVER_EAT = {
    STUFFED = "我的胃已经达到了极限。",
    OVERSTUFFED = "这违背了基本的营养学原理！"
}