local require = GLOBAL.require
GLOBAL.STRINGS.CHARACTERS.WINKY = require ("winky_speech")

ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WINKY
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WINKY.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WINKY.ACTIONFAIL

--	[ 		Winky Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "哇！那是什么？！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "啊！这颗心是我的，不是你的。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "没用的机器"
ANNOUNCE.ANNOUNCE_RATRAID = "我能听到我的家人们。"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "拿走一切！啊哈哈！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "嘿，我的家人！他们拿走了我的宝藏！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
	"我的皮毛正在融化！",
	"啊啊雨有烧焦的味道！",
	"必须躲避这讨厌的雨！吱吱！",
}
ANNOUNCE.ANNOUNCE_TOADSTOOL = "有人切奶酪了吗？"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "斯斯嘶....真冷...."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "不！！！黑暗不能拥有我！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "我的-又感觉我的手指到了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_VETCURSE = "邪恶的存在消失了......"
ANNOUNCE.ANNOUNCE_RNEFOG = "谁在那儿！"
--FoodBuffs

--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "感觉啊哈哈哈哈。嗡嗡声。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "啊,我不觉得烦了。"
DESCRIBE.CALIFORNIAKING = "哦哦哦,这杯饮料不错。"
--CaliforniaKing

--Content Creators
DESCRIBE.CCTRINKET_DON = "我只能辨认出 \"吱吱\" 和 嗯。。。 \"吱吱\"。"
DESCRIBE.CCTRINKET_JAZZY = "看起来很活泼。"
DESCRIBE.CCTRINKET_FREDDO = "上面刻有愚蠢的划痕。"
--Content Creators

DESCRIBE.UNCOMPROMISING_RAT = "你好,家人。"
DESCRIBE.UNCOMPROMISING_RATHERD = "我们都联系在一起了。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "我们都联系在一起了。"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "有很多通往家的隧道。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "我美丽的家！"

DESCRIBE.WINKY =
{
	GENERIC = "我认识你吗？",
	ATTACKER = "%s,让你的蠢爪子离我远点！",
	MURDERER = "%s 我在你的皮毛上看到了血！",
	REVIVER = "我想我们现在是一家人了。",
	GHOST = "你看起来很眼熟,你是我的族群的一部分吗？",
	FIRESTARTER = "我能闻到你皮毛上的灰味,你这个笨蛋。",
}

DESCRIBE.WIXIE =
{
	GENERIC = "你为什么长着我这样的牙齿？你不是我的家人。",
	ATTACKER = "别再向我扔你那愚蠢的鹅卵石了！",
	MURDERER = "我现在要向你扔石头,%s！",
	REVIVER = "我猜你很好。",
	GHOST = "你是不是被小石子噎住了？",
	FIRESTARTER = "你现在也在烧东西！？停止！",
}
DESCRIBE.WATHOM =
{
	GENERIC = "你是龙虾人！你记得我,不是吗？",
	ATTACKER = "我和我的家人都知道你是个杀手！",
	MURDERER = "他正在进行大屠杀,我必须逃走！",
	REVIVER = "我不知道你除了杀人还能做别的事。",
	GHOST = "咦,谁杀了你？",
	FIRESTARTER = "%s,你不太擅长烧东西,所以停下来。",
}

DESCRIBE.RATPOISONBOTTLE = "呸！你想杀了我吗？"
DESCRIBE.RATPOISON = "呸！你想杀了我吗？"

DESCRIBE.MONSTERSMALLMEAT = "一小块多汁的肉。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "味道不错。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "你必须咀嚼很多才能把味道弄出来。"
DESCRIBE.UM_MONSTEREGG = ""
DESCRIBE.UM_MONSTEREGG_COOKED = ""

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "那个！融化的雨水就是从那里来的！"
DESCRIBE.TOADLING = "别挡我的路。"
DESCRIBE.UNCOMPROMISING_TOAD = "现在闻起来很有趣。"

DESCRIBE.GASMASK = "它很闷,我闻不到它的味道。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "她坐在那里。等着......"
ANNOUNCE.ANNOUNCE_SNEEZE = "啊啊,湫!!!!"
ANNOUNCE.ANNOUNCE_HAYFEVER = "我的鼻子感觉..痒。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "最后,我不想再用爪子把我的鼻子掰下来了。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"我的皮毛着火了吗？还是我？",
	"有什么东西闻起来像燃烧的老鼠！",
	"我被这种炎热弄得油腻了。",
}
ANNOUNCE.ANNOUNCE_ROOTING = "我卡住了！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "我听到风的呼啸。"
ANNOUNCE.SHADOWTALKER = {
	"你永远不会报复。",
	"你一无所有。",
	"",
}

ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "我的肚子好大！吱吱！",
	OVERSTUFFED = "我太大太圆了！",
}
ANNOUNCE.CURSED_ITEM_EQUIP = "嘎嘎！"
DESCRIBE.VETSITEM = "它低声说,它要我和那个白痴说话！"
DESCRIBE.SCREECHER_TRINKET = "小洋娃娃。"

DESCRIBE.UM_SAND = "粉尘。"
DESCRIBE.UM_SANDHILL = "尘土飞扬。"
DESCRIBE.SNOWPILE = "雪山。"
DESCRIBE.SNOWGOGGLES = "吸嘴。"

DESCRIBE.SNOWMONG = "雪海豹。"
DESCRIBE.SHOCKWORM = "我能从这里闻到你的黏液。"
DESCRIBE.ZASPBERRY = "这个肯定有点活泼吧。"
DESCRIBE.ZASPBERRYPARFAIT = "它让我的皮毛直立起来。"
DESCRIBE.ICEBOOMERANG = "差点卡到我的舌头上了。"

DESCRIBE.MINOTAUR_BOULDER = "岩石。"
DESCRIBE.MINOTAUR_BOULDER_BIG = "岩石,但更大。"
DESCRIBE.BUSHCRAB = "把你的浆果给我！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "一袋岩油。"
DESCRIBE.TOADLINGSPAWNER = "闻起来很臭。"
DESCRIBE.VETERANSHRINE = "你为什么要说......"
DESCRIBE.VET_SKULL = "愚蠢的头，连啃都不好！"
DESCRIBE.UM_BOSS_SOUL = "不能吃。有什么意义？"
DESCRIBE.UM_DARK_VESTIGES = "有嚼劲，味道很糟糕！"
DESCRIBE.UM_VOXOLOPHONE = "愚蠢的盒子试图跟我说话。"

DESCRIBE.UM_EXHUMER = "肮脏的骨头，不值得咀嚼。"
DESCRIBE.UM_WINGSUIT = "现在我可以像那些肮脏的鸟一样飞翔了！"
DESCRIBE.UM_MOONFLY_LANTERN = "我的收藏中又一件闪亮的东西。"

DESCRIBE.WICKER_TENTACLE = "绿色且更粘稠。"
DESCRIBE.HONEY_LOG = "又脆又甜，像甲虫一样。"

DESCRIBE.RAT_TAIL = "有什么问题吗？我们时不时都会死。"
DESCRIBE.PLAGUEMASK ="为什么我想闻好闻的味道。"
DESCRIBE.SALTPACK ="啊啊，我想它吸引了我的眼球！"
DESCRIBE.SPOREPACK =
"我们做了一点法丁，我们做了一点法丁，是的。"
DESCRIBE.SNOWBALL_THROWABLE = "哈哈，我希望我能早点拥有拇指。"
DESCRIBE.SPIDER_TRAPDOOR = "滚回你那丑陋的洞里去。"
DESCRIBE.TRAPDOOR ="更平坦、更糟糕的岩石。"
DESCRIBE.HOODEDTRAPDOOR = DESCRIBE.TRAPDOOR
DESCRIBE.SHROOM_SKIN_FRAGMENT = "嗯,有点孢子味。"
DESCRIBE.AIR_CONDITIONER = "这味道太难闻了！我不喜欢这种香味。"

DESCRIBE.UM_SCORPION = "粉碎它。"
DESCRIBE.SCORPIONCARAPACE = "味道很有趣。"
DESCRIBE.SCORPIONCARAPACECOOKED = "没那么糟糕,真的。"
DESCRIBE.HARDSHELLTACOS = "嗯,好脆。"

DESCRIBE.SKELETONMEAT = "肉丝"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "你又是哪一个？"
DESCRIBE.VAMPIREBAT = "比我更丑陋的更丑陋的东西,看起来不像我。"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "我应该就这样离开。"
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP

--Swampyness
DESCRIBE.RICEPLANT = "松脆的小东西。"
DESCRIBE.RICE = "松脆的小东西。"
DESCRIBE.RICE_COOKED = "哦,你应该煮它们。"
DESCRIBE.SEAFOODPAELLA = "鱼菜。"

DESCRIBE.STUMPLING = "用锤子砸碎它！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.BUGZAPPER = "吝啬鬼。"
DESCRIBE.MOON_TEAR = "眼泪的味道不是很咸。"
DESCRIBE.SHADOW_TELEPORTER = "也许它不会注意到我拿走了宝石。"
DESCRIBE.POLLENMITEDEN = "一个小吃店,里面全是多汁的虫子。"
DESCRIBE.POLLENMITES = "要是有一种吃它们的好方法就好了。"
DESCRIBE.SHADOW_CROWN = "它至少和我的皮毛相配。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.LICELOAF = "我留着以后用。"
DESCRIBE.SUNGLASSES = "黑眼圈。"
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "嘿！你怎么了？"
DESCRIBE.MARSH_GRASS = "嘘嘘嘘,安静点......"
DESCRIBE.CURSED_ANTLER = "重击头哈哈哈。"
DESCRIBE.BERNIEBOX = "我可以用牙齿打开的盒子。"
DESCRIBE.HOODED_FERN = "它是绿色的。"
DESCRIBE.HOODEDWIDOW = "啊！谁邀请你的！"
DESCRIBE.GIANT_TREE = "我应该爬上去吃掉上面的小鸟。"
DESCRIBE.WIDOWSGRASP = "哈哈,我的私人牙签。"
DESCRIBE.WEBBEDCREATURE = ""
ANNOUNCE.WEBBEDCREATURE = "当我试图撕开它时,我总是卡住！"
DESCRIBE.SNAPDRAGON_BUDDY = "它看起来很饿,我也很饿。"
DESCRIBE.SNAPDRAGON = "一些野生根兽。"
DESCRIBE.SNAPPLANT = "他们之间的关系非常活跃。"
DESCRIBE.WHISPERPOD = "嗯？我没有听到这个团块发出任何低语。"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "嗯,做点什么。",
	GROWING = "根来了！",
}
DESCRIBE.FRUITBAT = "我希望你不会像地面上的那样爆炸。"
DESCRIBE.PITCHERPLANT = "必须爬上去我才能闻到甜味。"
DESCRIBE.APHID = "离开这里,这里现在是老鼠之地。"
DESCRIBE.NYMPH = "你正在玩一场失败的游戏，试图超越我！"
DESCRIBE.GIANT_TREE_INFESTED = "一定长满了虫子。"
DESCRIBE.GIANT_BLUEBERRY = "我现在要把它放进嘴里。"
DESCRIBE.STEAMEDHAMS = "这些蒸火腿与肉丝丁的非常相似。"
DESCRIBE.BLUEBERRYPANCAKES = "这种自制的蓝色粘液非常令人满意。"
DESCRIBE.SIMPSALAD = "这是叶子。"
DESCRIBE.BEEFALOWINGS = "我不确定我是否也吃角。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "哈哈！我是无敌的！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "哦哦..我的身体现在好痛.."
ANNOUNCE.WIDOWSHEAD = "没有这个我的眼睛很好。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "你为什么要这么做。"
DESCRIBE.SNOWCONE = "为什么会有人吃雪。"

--Viperstuff 语录
DESCRIBE.VIPERWORM = "滚出我的脑袋,滚出去！"
DESCRIBE.VIPERFRUIT = "多汁的,充满甜味。"
DESCRIBE.VIPERJAM = "粘稠的粘液,好东西。"

DESCRIBE.BLUEBERRYPLANT =
{
	READY = "我应该把我的爪子挖进去。",
	FROZE = "又硬又冷。",
	REGROWING = "也许用我的爪子是个坏主意。",
}
DESCRIBE.BERNIE_INACTIVE =
{
	BROKEN = "他死了。",
	GENERIC = "闻起来像那个燃烧的女孩。",
	ASHLEY_BROKEN = "她死了。",
	ASHLEY = "闻起来像那个燃烧的女孩。",
}

DESCRIBE.BERNIE_ACTIVE =
{
	GENERIC = "你是个吉特巴。",
	ASHLEY = "你是个吉特巴。",
}
DESCRIBE.BERNIE_BIG =
{
	GENERIC = "他现在是个大畜生了！",
	ASHLEY = "他现在是个大畜生了！",
}
DESCRIBE.ANTIHISTAMINE = "我的鼻子不会再痒了！"

DESCRIBE.HEATROCK_LEVEL =
{
	TINY = "一块孤独的老石头,坐在空旷的地方。",
	SMALL = "放在我的口袋里有点暖和。",
	MED = "我现在让它有点暖和。",
	LARGE = "它现在受到了很好的保护,不受温度的影响。",
	HUGE = "它完美地抵御了这些自然！",
}

DESCRIBE.DURABILITY_LEVEL =
{
	QUARTER = "臭破布现在。",
	HALF = "它变得很臭,很糟糕。",
	THREEQUARTER = "它开始闻起来更香了。",
	FULL = "这很好。",
}

ACTIONFAIL.READ =
{
	GENERIC = "我当然知道我在做什么。",
}
ACTIONFAIL.GIVE = { NOTNIGHT = "也许如果我用力打它,它会起作用吗？" }

RECIPE_DESC = GLOBAL.STRINGS.RECIPE_DESC

RECIPE_DESC.RAT_BURROW = "带回家。"

-- Xmas Update
DESCRIBE.MAGMAHOUND = "崎岖不平的岩石。"
DESCRIBE.LIGHTNINGHOUND = "我想是像玉米一样的黄色。"
DESCRIBE.SPOREHOUND = "到别处去散养。"
DESCRIBE.GLACIALHOUND = "它有冰骨吗。"
DESCRIBE.RNESKELETON = "你走路怎么样？"
DESCRIBE.RAT_WHIP = "我希望我的尾巴能像这样敲打。"
DESCRIBE.KLAUS_AMULET = "就像宝石项链,不太漂亮。"
DESCRIBE.CRABCLAW = "笨蛋俱乐部。"
DESCRIBE.HAT_RATMASK = "人类就是这么说的,奉承。"

DESCRIBE.ORANGE_VOMIT = "粘液糊。味道很苦。"
DESCRIBE.GREEN_VOMIT = "粘液糊。非常酸。"
DESCRIBE.RED_VOMIT = "粘液糊。味道很苦。"
DESCRIBE.PINK_VOMIT = "粘液糊。味道很酸。"
DESCRIBE.YELLOW_VOMIT = "黏糊糊的。味道很苦。"
DESCRIBE.PURPLE_VOMIT = "粘液糊。非常酸。"
DESCRIBE.PALE_VOMIT = "粘液糊。味道很淡。"

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD =
{
	GUARD = DESCRIBE.PIGMAN.GUARD,
	WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH

DESCRIBE.BIGHT = "这个丑陋的杂乱嘈杂的东西是什么？"
DESCRIBE.KNOOK = "可怕的嘈杂声,烦死了！！！..."
DESCRIBE.ROSHIP = "滚开你这个丑陋的笨蛋！"

DESCRIBE.UM_PAWN = "这很烦人。"
DESCRIBE.UM_PAWN_NIGHTMARE = "至少这个可以闭嘴！"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = ""
DESCRIBE.UM_BEAR_TRAP = "也许我应该朝它扔石头。"
DESCRIBE.UM_BEAR_TRAP_OLD = "铁锈很好吃。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "我应该用铁锈覆盖它。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "我应该用铁锈覆盖它。"
DESCRIBE.CORNCAN = "打开它！我闻到了里面的味道。"
DESCRIBE.SKULLCHEST_CHILD = "里面非常安静......"

DESCRIBE.SLOBBERLOBBER = "恶心的肉馅东西。"
DESCRIBE.GORE_HORN_HAT = "离我远点！闪闪。"
DESCRIBE.BEARGERCLAW = "新指甲,很漂亮。"
DESCRIBE.FEATHER_FROCK = "布满灰尘的丑鸟斗篷。"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM .. "\n变形的珠宝。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM .. "\n变形的珠宝。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM .. "\n变形的珠宝。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM .. "\n变形的珠宝。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM .. "\n变形的宝石。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM .. "\n变形的珠宝。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM .. "\n变形的珠宝。"

DESCRIBE.RED_MUSHED_ROOM = "是的,一些黏糊糊的东西"
DESCRIBE.GREEN_MUSHED_ROOM = "是的,一些黏糊糊的东西"
DESCRIBE.BLUE_MUSHED_ROOM = "是的,一些黏糊糊的东西"

DESCRIBE.HEAT_SCALES_ARMOR = "要是我能装进去就好了。"

--StantonStuff
DESCRIBE.SKULLFLASK = "饮用骨头。"
DESCRIBE.SKULLFLASK_EMPTY = "什么？没有了？"
DESCRIBE.STANTON_SHADOW_TONIC = "黏糊糊的黑色饮料"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "你还活着。欢迎回来？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "终于,没有什么能阻止我了！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "哦。"
--StantonStuff

--Night Terror Masks
DESCRIBE.HAT_BAGMASK = "这太蠢了。"
DESCRIBE.HAT_BLACKCATMASK = "我可以用它来欺骗那些愚蠢的猫！"
DESCRIBE.HAT_CLOWNMASK = "我不理解这个。"
DESCRIBE.HAT_WATHOMMASK = "我见过这个吃龙虾的人一次,他说话很耳语。"
DESCRIBE.HAT_DEVILMASK = "它为什么对我吐舌头！"
DESCRIBE.HAT_FIENDMASK = "它为什么对我吐舌头！"
DESCRIBE.HAT_GHOSTMASK = "我见过更可怕的东西......"
DESCRIBE.HAT_GLOBMASK = "这是假的粘液。"
DESCRIBE.HAT_HOCKEYMASK = "上面有很多洞。"
DESCRIBE.HAT_JOYOUSMASK = "哈哈,我觉得很兴奋。"
DESCRIBE.HAT_MERMMASK = "气味在哪里？这是最好的部分。"
DESCRIBE.HAT_OOZEMASK = "这是假的粘液。"
DESCRIBE.HAT_ORANGECATMASK = "我可以用它来欺骗那些愚蠢的猫！"
DESCRIBE.HAT_PHANTOMMASK = "我见过更可怕的东西......"
DESCRIBE.HAT_PIGMASK = "哈哈哈,真丑！"
DESCRIBE.HAT_PUMPGOREMASK = "你为什么老是给他们脸。"
DESCRIBE.HAT_REDSKULLMASK = "这不是真骨头,但我还是会嚼它的。"
DESCRIBE.HAT_SKULLMASK = "这不是真骨头,但我还是会嚼它的。"
DESCRIBE.HAT_SPECTREMASK = "我见过更可怕的东西......"
DESCRIBE.HAT_WHITECATMASK = "我可以用它来欺骗那些愚蠢的猫"
DESCRIBE.HAT_TECHNOMASK = "这不是真的,所以我更喜欢它。"
DESCRIBE.HAT_MANDRAKEMASK = "这是一张非常奇怪的脸。"
DESCRIBE.HAT_OPOSSUMMASK = "这是一只老鼠,但错了。"
DESCRIBE.RNE_GOODIEBAG = "是的,里面所有的东西都是我应得的。"

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "呵呵,边吃边笑很有趣,哈哈哈！"
DESCRIBE.DEERCLOPS_BARRIER = "我被困住了！不！"


DESCRIBE.MOONMAW_DRAGONFLY = "啊啊啊！！你是什么东西！"
DESCRIBE.MOONMAW_LAVAE = "旋转,旋转。旋转..."
DESCRIBE.SNAPPERTURTLE = "嗯,我不在,别理我。"
DESCRIBE.SNAPPERTURTLEBABY = "我会把它捡起来扔掉！"
DESCRIBE.SNAPPERTURTLENEST = "我不喜欢靠近水的巢穴,所以那不是我的。"
DESCRIBE.GLASS_SCALES = "我喜欢它亮起来的样子！"
DESCRIBE.MOONGLASS_GEODE = "充满光明。"
DESCRIBE.ARMOR_GLASSMAIL = "我是玻璃杀手！"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "切切切切,切片。"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "你为什么要敲你的头,笨蛋。"
DESCRIBE.SNOTROAST = "充满美味的鼻涕。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "啊,是的,太饱了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "我希望我现在能吃点东西。"
DESCRIBE.BOOK_RAIN_UM = "多云,有可能下雨。"
DESCRIBE.FLORAL_BANDAGE = "我应该吃掉它。"
DESCRIBE.DORMANT_RAIN_HORN = "它是咸的。"
DESCRIBE.RAIN_HORN = "全是云吗？"
DESCRIBE.DRIFTWOODFISHINGROD = "为什么他们更喜欢这个？"

ANNOUNCE.ANNOUNCE_NORATBURROWS = "这里很寂寞。"


ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
	LEVEL_1 = "开始有家的感觉了！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
	LEVEL_1 = "开始有家的味道了！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
	LEVEL_1 = "啊哈哈,更多朋友来了！",
}

DESCRIBE.PIED_RAT = "给我那个,你玩错了。"
DESCRIBE.PIED_PIPER_FLUTE = "我喜欢演奏歌曲！"
DESCRIBE.UNCOMPROMISING_PACKRAT = "我教他们穿那个。"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "不！我不想弄湿我的皮毛！"

ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "愚蠢的机器坏了！",
	CHARGE_FULL = "工作！哦等等,它已满。",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "你的也是我的。"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "吱吱！！！"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "让我看看里面有什么。"
ACTIONFAIL.WINONATOOLBOX = "我告诉你这是我的！我的！"
DESCRIBE.WINONA_CATAPULT_ITEM = "有趣的小机器！"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "有趣的小机器！"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "有趣的小机器！"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "有趣的小机器！"
DESCRIBE.POWERCELL = "我觉得我应该好好想想这个。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "带电线的东西可以放在其他东西上。"
DESCRIBE.MINERHAT_ELECTRICAL = "现在都连接好了。"
DESCRIBE.OCEAN_SPEAKER = "大声可怕的东西。"
--DESCRIBE.UM_SIREN = "我觉得你有鱼腥味。"

DESCRIBE.OCUPUS_BEAK = "一些笨拙的东西,我认为它是一张嘴。但它现在是我的了。"
DESCRIBE.OCUPUS_TENTACLE = "它很有弹性而且很好吃！"
DESCRIBE.OCUPUS_TENTACLE_EYE = "哈,眼睛有嚼劲,我以为它会很粘。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "我喜欢咀嚼它。"

DESCRIBE.ARMOR_REED_UM = "它是绑在一起的。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "穿上它并没有让我感觉更安全,只是又冷又怪。"
DESCRIBE.ROCKJAWLEATHER = "摸起来又冷又凹凸不平。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
DESCRIBE.STUFFED_PEEPER_POPPERS = "我喜欢这些粘糊糊的小东西！"
DESCRIBE.UM_DEVILED_EGGS = "美味的鸡蛋,它们闻起来很香！"
DESCRIBE.LUSH_ENTRANCE = "又一个洞。实际上我以前没见过这个。"
DESCRIBE.CRITTER_FIGGY = "我不喜欢小甲虫跟着我。"
DESCRIBE.GIANT_TREE_BIRDNEST = "它们似乎是来找我的！"

DESCRIBE.SLUDGE = "我喜欢它有一种有趣的香味。"
DESCRIBE.SLUDGE_OIL = "香味最浓。太浓了,我不喜欢！"
DESCRIBE.SLUDGE_SACK = "黏糊糊的背带,这是我的风格。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "污泥,现在是一块石头。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "是的,非常好。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "我的船闻起来会很有趣。"
DESCRIBE.BOATPATCH_SLUDGE = "我想要它,但我不想要船洞。"
DESCRIBE.UM_COPPER_PIPE = "舔这个非常好吃。"
DESCRIBE.BRINE_BALM = "我不是为了帮助自己而伤害自己。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = "我现在可以用这个偷走我想要的一切。"
DESCRIBE.UM_AMBER = "这是一颗宝石吗？"
DESCRIBE.UM_BEEGUN = "它们现在是我的蜜蜂了！我不想射杀它们！"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "我需要更多的老鼠把它带回我的洞里。"
DESCRIBE.STEERINGWHEEL_COPPER = "是的,继续旋转,一直旋转......"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "它很像机器。"
DESCRIBE.BOAT_BUMPER_COPPER = "你撞我？我撞你！"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "非常结实！"
DESCRIBE.UM_DREAMCATCHER = "把我的梦想还给我。它是我的！"
DESCRIBE.UM_BRINEISHMOSS = "我已经吃够了苔藓,知道它的味道如何。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "我不想……这个……"
DESCRIBE.SLUDGE_CORK = "我不喜欢堵洞。"
DESCRIBE.SLUDGESTACK = "哦新气味！"
DESCRIBE.SPECTER_SHIPWRECK = "哈哈！有人撞坏了他们的船！"

DESCRIBE.UNCOMPROMISING_HARPOON = "我为什么要扔掉它？现在这是我的了。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "我为什么要扔掉它？现在这是我的了。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = ""
DESCRIBE.UM_MAGNERANG = "我为什么要扔掉它？现在这是我的了。"
DESCRIBE.UM_MAGNERANGREEL = "它想拿东西？"
DESCRIBE.SIREN_THRONE = "我认为这是一个座位？上面那些东西是什么,我想要它们。"
DESCRIBE.LAVASPIT_SLUDGE = "太热了！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "让我过去！"

DESCRIBE.PORTABLEBOAT_ITEM = "我想咬它的洞。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "是的,我喜欢旋转。"

DESCRIBE.WIXIE_PIANO = "我喜欢轻敲和敲击琴键所以它会发出声音。"
DESCRIBE.WIXIE_CLOCK = "我没有弄坏它！"
DESCRIBE.WIXIE_WARDROBE = "里面是什么？给我看看！"
DESCRIBE.CHARLES_T_HORSE = "油腻而耐嚼。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "某种咀嚼棒？"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "*嘶嘶声！*你不是真的！"
DESCRIBE.UM_ORNAMENT_RAT = "你们是假家庭！"

DESCRIBE.TRINKET_WATHOM1 = "哦！那就是它去的地方。"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

DESCRIBE.MARA_BOSS1 = "逃跑时间!!"
ANNOUNCE.GAS_DAMAGE = "咳咳! 咳咳!"

-- 荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "味道像血。愚蠢的植物。"
DESCRIBE.UM_SMOLDER_SPORE = "嘶! 远离..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "帮助我，你们这些傻瓜! 它攻击了我！！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "啊! 我持有的团块正在燃烧！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "愚蠢的尖锐垃圾。"
DESCRIBE.UM_BLOWDART_PYRE = "哦不。不去想它了。不要再想了。请不要。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "啊! 我的抱团！！"

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "没有足够的空间容纳我们两个人！"
DESCRIBE.UM_TORNADO = "愚蠢的风又来报仇了！"
DESCRIBE.UM_WATERFALL = "我经常洗澡。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有愚蠢的龙卷风来偷我的东西。"
