ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WINONA
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WINONA.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WINONA.ACTIONFAIL

--	[ 		Winona Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "我-是你吗，查理？"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "没有尸体？那不会太有建设性。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "即使它很小，请......把你的错误报告放在我的 Discord 服务器上！"
ANNOUNCE.ANNOUNCE_RATRAID = "噢，老鼠。"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "他们来了！抓住他们！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "嘿，他们带着我的装备跑了！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"这场雨快要把我点燃了！",
"这东西会烧穿我的衣服！还有我！",
"我需要离开这场雨！",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "有东西在下面堆积！"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "这不是我最聪明的想法之一。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了。"
--FoodBuffs
	
--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "哇！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "哇，最好不要再这么做了。"
DESCRIBE.CALIFORNIAKING = "这到底是什么？"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "浓雾滚滚而来。你在做什么，查理？"
DESCRIBE.UNCOMPROMISING_RAT = "那是我希望不再看到的家的一部分。"
DESCRIBE.UNCOMPROMISING_RATHERD = "看来我找到了你的小秘密！"
DESCRIBE.UNCOMPROMISING_RATBURROW = "看来我找到了你的小秘密！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "看来我找到了你的小秘密！"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "看来我找到了你的小秘密！"
	
DESCRIBE.WINKY =
{
    GENERIC = "请远离我的机器!",
    ATTACKER = "别让她咬我！",
    MURDERER = "我们需要杀虫剂来照顾她!",
    REVIVER = "谢谢你的帮助，你这个淘气的东西！",
    GHOST = "家里的老工厂一定有数百只老鼠出没！",
    FIRESTARTER = "你在嚼电线吗？你是不是起火了？!",
}
DESCRIBE.WATHOM =
{
GENERIC = "当我看到一个复制品时，我知道它是一个复制品。",
     ATTACKER = "%s 咬人多过吠叫！",
     MURDERER = "%s 正在横冲直撞！",
     REVIVER = "你比我最初想的要多，%s！",
     GHOST = "我认为这个幽灵有缺陷！",
     FIRESTARTER = "&s 想要破坏我们所有的东西！",
}
DESCRIBE.WIXIE =
{
GENERIC = "%s 让我想起了她这个年纪的自己。抱歉，Charlie...",
     ATTACKER = "停止你的粗暴行为，%s!",
     MURDERER = "你这个小威胁！",
     REVIVER = "欺负黄金之心，是吧？",
     GHOST = "来来去去。",
     FIRESTARTER = "诉诸纵火，你这个小恶魔？！",
}
		
DESCRIBE.RATPOISONBOTTLE = "Darn, this stuff woulda put Red Squill to shame.该死，这东西会让红海棠蒙羞。"
DESCRIBE.RATPOISON = "很高兴不用担心我们的东西上到处都是老鼠。"

DESCRIBE.MONSTERSMALLMEAT = "不太清楚为什么我想要这个..."
DESCRIBE.COOKEDMONSTERSMALLMEAT = "烹饪这样的东西能做成食物吗？"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "老的，悲伤的，愤怒的肉。"

DESCRIBE.UM_MONSTEREGG = "奇怪颜色的鸡蛋..."
DESCRIBE.UM_MONSTEREGG_COOKED = "里面有一些壳，还有毛发."

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "那可不好，我们需要从源头上切断它！"
DESCRIBE.TOADLING = "好吧，这一只是有态度的。"
	
DESCRIBE.GASMASK = "适合采矿作业的设备。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "我们真的需要保留它吗？"	
ANNOUNCE.ANNOUNCE_SNEEZE = "阿嚏！噢！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "有什么东西在我的鼻子里跳舞！"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "我的鼻子终于得到了安宁！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "暴风雪要来了，最好蹲下。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"在尖叫声中，雨水想要融化一切。",
	"天呐！让它冷却下来！",
	"穿上你的防火安全靴！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "我被抓住了！"
ANNOUNCE.SHADOWTALKER = {
"她还记得我吗？",
"她 走 了",
"我 想 她",
}
ANNOUNCE.ANNOUNCE_OVER_EAT ={
	STUFFED = "我吃饱了，我们开始工作吧！",
	OVERSTUFFED = "我的胃已经填满了！",
}
DESCRIBE.UM_SAND = "我只能把它分解到这种程度。"
DESCRIBE.UM_SANDHILL = "我通常把清理工作留给看门人。"
DESCRIBE.SNOWPILE = "早点铲掉它，迟则生变。"
DESCRIBE.SNOWGOGGLES = "冬季的工具。"

DESCRIBE.SNOWMONG = 
"这就是传说中的冰雪鼹鼠之一吗？"
DESCRIBE.SHOCKWORM = "如果我见过，那就是安全隐患！"
DESCRIBE.ZASPBERRY = "不妨尝尝。"
DESCRIBE.ZASPBERRYPARFAIT = "这会让我的脚步振作起来。"
DESCRIBE.ICEBOOMERANG = "非常方便的工具，不是吗？"
DESCRIBE.MINOTAUR_BOULDER = "安全帽，各位！安全第一！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "试试这个，你个大笨牛。"
DESCRIBE.VETERANSHRINE = "这看起来不像是查理在做的事。"
DESCRIBE.VET_SKULL = "一些可怜的家伙结束了生命。"
DESCRIBE.UM_BOSS_SOUL = "不能放手，是吧？"
DESCRIBE.UM_DARK_VESTIGES = "某种奇怪的胶水？"
DESCRIBE.UM_VOXOLOPHONE = "结构很熟悉。这是老板做的吗？"

DESCRIBE.UM_EXHUMER = "工人们如果死了就不需要午休了！"
DESCRIBE.UM_WINGSUIT = "飞行是一项艰苦的工作！"
DESCRIBE.UM_MOONFLY_LANTERN = "魔法力量。整洁。"

DESCRIBE.SNOWBALL_THROWABLE = "也许我可以把它装进弹射器？嗯，不。"
DESCRIBE.RAT_TAIL = "是的，我不想带着它到处走。"
DESCRIBE.PLAGUEMASK = "你必须小心，不要让喙撞到任何东西。"
DESCRIBE.SPIDER_TRAPDOOR = "我可能不得不窃取那个“活板门”的想法。"
DESCRIBE.TRAPDOOR = "我什么也没看到。"
DESCRIBE.HOODEDTRAPDOOR = DESCRIBE.TRAPDOOR 
DESCRIBE.WICKER_TENTACLE = "看起来有某种制造缺陷。"
DESCRIBE.HONEY_LOG = "看起来它是从零食工厂生产的。"

DESCRIBE.BUSHCRAB = "危险的植物！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "我们会让这些植物像上油的机器一样工作！"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "为什么所有蟾蜍都有难闻的恶臭？"
DESCRIBE.AIR_CONDITIONER = "我可以拿这个设计做点什么..."
DESCRIBE.SPOREPACK = "哇, 这气味像是迎面一拳。"
DESCRIBE.SALTPACK = "我早该想到这个的！"
	
DESCRIBE.UM_SCORPION = "我不想看到毒刺的业务结局！"
DESCRIBE.SCORPIONCARAPACE = "我确信我能找到别的东西吃。"
DESCRIBE.SCORPIONCARAPACECOOKED = "附近一定有更好吃的东西..."
DESCRIBE.HARDSHELLTACOS = "吃下去发出很好听的嘎吱声。"
	
DESCRIBE.SKELETONMEAT = "这是个糟糕的主意。"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "哇！ 他的斧子是真的！"
DESCRIBE.VAMPIREBAT = "它可能更老，但看起来和其他人一样生气！"
					
--Swampyness
DESCRIBE.RICEPLANT = "我需要建造一些东西来采摘它。"
DESCRIBE.RICE = "最好不要生吃。"
DESCRIBE.RICE_COOKED = "一小口就吃掉了。"
DESCRIBE.SEAFOODPAELLA = "有点难闻。"
DESCRIBE.LICELOAF = "它可以保存一段时间，直到我需要它。"
DESCRIBE.SUNGLASSES = "它不能替代安全护目镜。"
	
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "我可以修复那个巢穴，月岩可以成为一个很好的基地。"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "此模型的最佳专利。"
DESCRIBE.STUMPLING = "树桩也有眼睛！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "我认为它出现了漏洞。也许我可以稍后修复它。"
DESCRIBE.SHADOW_TELEPORTER = "查理，这是什么？"
DESCRIBE.POLLENMITEDEN = "是的，这可能需要拆解。"
DESCRIBE.POLLENMITES = "庭院工作的严重危机。"
DESCRIBE.SHADOW_CROWN = "让我浑身起鸡皮疙瘩，但至少我移动得更快了。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "当你的眼睛少点的时候，我会更喜欢你。"
DESCRIBE.MARSH_GRASS = "看呐，灌木丛！"
DESCRIBE.CURSED_ANTLER = "它永远不会打在你身上。"
DESCRIBE.BERNIEBOX = "如果不是工具，我就不感兴趣。"
DESCRIBE.HOODED_FERN = "有什么东西在纤维里里沙沙作响吗？ "
DESCRIBE.HOODEDWIDOW = "我会，呃，留在这里。"
DESCRIBE.GIANT_TREE = "我们不能轻易地砍倒这棵树。"
DESCRIBE.WIDOWSGRASP = "我们现在可以打开这些茧了！"
DESCRIBE.WEBBEDCREATURE = "嗯，我想打开它！"
ANNOUNCE.WEBBEDCREATURE = "是的，不，我们不是靠自己来打破茧的。"
DESCRIBE.SNAPDRAGON_BUDDY = "它们的胃口很大！"
DESCRIBE.SNAPDRAGON = "为什么这里的东西都长得很巨大？"
DESCRIBE.SNAPPLANT = "大本营，嗯？"
DESCRIBE.WHISPERPOD = "让我们动手吧。"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "它少了一块，用来生长的，也许吧？",
	GROWING = "它在努力长大。",
}
DESCRIBE.FRUITBAT = "我其实不介意这个。"
DESCRIBE.FRUITBAT = "飞行的... 水果？"
DESCRIBE.PITCHERPLANT = "它只是种植物。"
DESCRIBE.APHID = "只是另一种害虫。"
DESCRIBE.NYMPH = "感染的原因。"
DESCRIBE.GIANT_TREE_INFESTED = "这似乎是虫子的来源。"
DESCRIBE.GIANT_BLUEBERRY = "它装满了液体！"
DESCRIBE.STEAMEDHAMS = "很明显是烤的。"
DESCRIBE.BLUEBERRYPANCAKES = "虽然很乱，但值得。"
DESCRIBE.SIMPSALAD = "它只是一些粗饲料。"
DESCRIBE.BEEFALOWINGS = "里面有些好吃的。"
DESCRIBE.DEVILSFRUITCAKE = "那是一块坚固的蛋糕。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我感觉比平时更强壮了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "回到工作。"
DESCRIBE.WIDOWSHEAD = "为什么这种情况不断发生！"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = DESCRIBE.PUMPKIN_LANTERN
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "别以为你能欺骗我！"
DESCRIBE.VIPERFRUIT = "很高兴有人帮忙。"
DESCRIBE.VIPERJAM = "混合得很好。"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "会弄得一团糟，但还有什么新东西？",
		FROZE = "现在只是一块冰。",
		REGROWING = "那一定是根。",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "他有点像是待修缮的房子。",
    GENERIC = "这个小家伙深受喜爱。",
    ASHLEY_BROKEN = "她有点像是待修缮的房子。",
    ASHLEY = "这个小家伙深受喜爱。",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "他是发条吗？我可以看看里面吗？",
    ASHLEY = "她是发条吗？我可以看看里面吗？",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "那个女孩知道如何表演。",
    ASHLEY = "那个女孩知道如何表演。",
}
DESCRIBE.ANTIHISTAMINE = "它可以帮助我的肺部保持清洁。"
ANNOUNCE.CURSED_ITEM_EQUIP = "看起来安全手套还不够！"
DESCRIBE.VETSITEM = "我会接受任何讨价还价来使用这样的工具！"
DESCRIBE.SCREECHER_TRINKET = "除了令人毛骨悚然之外，它还有什么实际用途？"
ACTIONFAIL.GIVE = {NOTNIGHT = "这是一只夜猫子。"}

DESCRIBE.MAGMAHOUND = "连呼吸都带着热气。"
DESCRIBE.LIGHTNINGHOUND = "一个行走的发电机！"
DESCRIBE.SPOREHOUND = "我很惊讶它还活着。"
DESCRIBE.GLACIALHOUND = "又一个蓝色的？原来那个还不够吗？"
DESCRIBE.RNESKELETON = "有人回来了。"
DESCRIBE.RAT_WHIP = "光是气味就可以吓跑人。"
DESCRIBE.KLAUS_AMULET = "是时候超频了！"
DESCRIBE.CRABCLAW = "我有把宝石粘在东西上的诀窍，不是吗？" 
DESCRIBE.HAT_RATMASK = "我们去寻找它们的行动基地。" 

DESCRIBE.ORANGE_VOMIT = "谢谢。"
DESCRIBE.GREEN_VOMIT = "谢谢。"
DESCRIBE.RED_VOMIT = "谢谢。"
DESCRIBE.PINK_VOMIT = "谢谢。"
DESCRIBE.YELLOW_VOMIT = "谢谢。"
DESCRIBE.PURPLE_VOMIT = "谢谢。"
DESCRIBE.PALE_VOMIT = "谢谢。"
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "里面全是松散的电线。"
DESCRIBE.KNOOK = "它们看起来不太舒服。"
DESCRIBE.ROSHIP = "我很惊讶它竟然能正常工作。"
	
DESCRIBE.UM_PAWN = "我想我会离它远点。"
DESCRIBE.UM_PAWN_NIGHTMARE = "我想我会离它远点。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH		
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
	
DESCRIBE.ANCIENT_AMULET_RED = "我希望它有实际的用途。"
DESCRIBE.UM_BEAR_TRAP = "手艺很好，我想知道他们是如何获得制作它的材料的。"
DESCRIBE.UM_BEAR_TRAP_OLD = "手艺很好，虽然有点生锈。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "一个简单而有效的机制。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "一个简单而有效的机制。"
DESCRIBE.CORNCAN = "等待对话的玉米穗。"
DESCRIBE.SKULLCHEST_CHILD = "通过适当的协调，我可以从任何地方得到任何东西。"
	
DESCRIBE.SLOBBERLOBBER = "我在原来的世界里已经消灭了几个，把查理恶心坏了。"
DESCRIBE.GORE_HORN_HAT = "拆迁队来了！"
DESCRIBE.BEARGERCLAW = "老实说，我更喜欢人造工具。"
DESCRIBE.FEATHER_FROCK = "对我来说还是太花哨了。"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n它不能在我的设备中使用了。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n它不能在我的设备中使用了。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n它不能在我的设备中使用了。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n它不能在我的设备中使用了。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n它不能在我的设备中使用了。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n它不能在我的设备中使用了。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n它不能在我的设备中使用了。"
	
DESCRIBE.RED_MUSHED_ROOM = "它出于某种目的已被磨成糊状。"
DESCRIBE.GREEN_MUSHED_ROOM = "它出于某种目的已被磨成糊状。"
DESCRIBE.BLUE_MUSHED_ROOM = "它出于某种目的已被磨成糊状。"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "不要在工作场所醉酒，我就对它没意见。"
DESCRIBE.SKULLFLASK_EMPTY = "什么都没有。"
DESCRIBE.STANTON_SHADOW_TONIC = "我不能这样做，我正在上工呢。"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "喝酒游戏，嗯？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "脑汁！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "我的脑子现在更乱了！"
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "一团糟，但是很适合看表演的时候享用。"
DESCRIBE.DEERCLOPS_BARRIER = "必须从这里逃走！"
	
--Stuff for Canis to check
DESCRIBE.MOONMAW_DRAGONFLY = "不。"
DESCRIBE.MOONMAW_LAVAE = "这可能会产生很大的动能。"
DESCRIBE.SNAPPERTURTLE = "必须在它的外壳上贴一张 \"手部请远离活动部位\" 的贴纸。"
DESCRIBE.SNAPPERTURTLEBABY = "它会变大！"
DESCRIBE.SNAPPERTURTLENEST = "它们的聚会场所。"
DESCRIBE.GLASS_SCALES = "它的光很漂亮！"
DESCRIBE.MOONGLASS_GEODE = "想像一下对某事嗤之以鼻，哈。可能不应该这样。"
DESCRIBE.ARMOR_GLASSMAIL = "我们在这个世界真的进步了，是吧？"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "它们同步移动，作为更大的机器的一部分。"
--Stuff for Canis to check
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE
	
DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "一个勤奋的工人，我尊重它们。"
DESCRIBE.SNOTROAST = "现在它是一个loogie!"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "强大的填充，就是这样！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN_UM = "我不怕下雨！"
DESCRIBE.FLORAL_BANDAGE = "我喜欢甜美的气味，掩盖了工厂的霉味。"
DESCRIBE.DORMANT_RAIN_HORN = "只是一个海螺壳。"
DESCRIBE.RAIN_HORN = "在炎热的夏天吹奏。"
DESCRIBE.DRIFTWOODFISHINGROD = "能让工作更轻松就是最好的事。"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "混乱的工作环境，老板会不高兴的。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "最好把旧的食物扔掉，把好东西藏起来。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "哪里来的吱吱声？",
}

DESCRIBE.PIED_RAT = "一定是那些老鼠的头儿。"
DESCRIBE.PIED_PIPER_FLUTE = "我从不都不是最好的领导者。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "我认为我们已经找到了目标。"

	
ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "快收拾东西了，我正在下沉！"

ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "没有电了！",
	CHARGE_FULL = "充满电了！",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "有插座."
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "下次最好戴上手套！"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "没有它就不会离开家。"
ACTIONFAIL.WINONATOOLBOX = "哈？谁把我关在外面了！"
DESCRIBE.WINONA_CATAPULT_ITEM = "一点便携保护。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "谁需要聚光灯？"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "我只是希望它不要那么重！"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "那些魔法都没有让它变轻。"
DESCRIBE.POWERCELL = "小的聪明才智和努力工作大有帮助。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "我从头开始设计它。"
DESCRIBE.MINERHAT_ELECTRICAL = "稍加修修补补就大不一样了。"
DESCRIBE.OCEAN_SPEAKER = "现在如果我能看到它的内部……"
	--DESCRIBE.UM_SIREN = "Heh, she certainly knows how to run her workplace."
	
DESCRIBE.OCUPUS_BEAK = "有很好的光泽感。"
DESCRIBE.OCUPUS_TENTACLE = "" -- 它会在你的食道上蠕动。
DESCRIBE.OCUPUS_TENTACLE_EYE = "没有一只可以吃眼睛。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "现在闻起来好多了。"

DESCRIBE.ARMOR_REED_UM = DESCRIBE.ARMORGRASS
DESCRIBE.ARMOR_SHARKSUIT_UM = ""
DESCRIBE.ROCKJAWLEATHER = "看起来他失去了一点皮肤。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
DESCRIBE.STUFFED_PEEPER_POPPERS = "这感觉像是食物中毒的好方法。"
DESCRIBE.UM_DEVILED_EGGS = "他们在冰箱后面坐得太久了。"
DESCRIBE.LUSH_ENTRANCE = "我吸取了教训，在不祥的门口闲逛。"
DESCRIBE.CRITTER_FIGGY = "当我看到他们时，我就知道他们很努力！"
DESCRIBE.GIANT_TREE_BIRDNEST = "哈！我印象深刻的是那些贝壳并没有从那年秋天裂开。"

    DESCRIBE.SLUDGE = "非常恶心，但可能值得。"
DESCRIBE.SLUDGE_OIL = "归根结底，燃料就是燃料。"
    DESCRIBE.SLUDGE_SACK = "现在全是黏糊糊的，可能不是最好的存储空间。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "不想成为这个接收端。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "看起来足够安全。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "我有点担心把它放在我的船上。"
    DESCRIBE.BOATPATCH_SLUDGE = "最好也敲进去。"
    DESCRIBE.UM_COPPER_PIPE = "没想到会在这里找到这些。"
    DESCRIBE.BRINE_BALM = "物有所值。"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "不确定这是什么石头。"
    DESCRIBE.UM_BEEGUN = "蜜蜂一直很狡猾。但这是另一回事。"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "哦哦，我们现在是不是很喜欢！"
DESCRIBE.STEERINGWHEEL_COPPER = "继续转弯，漂亮而平稳。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "真正的好作品。"
DESCRIBE.BOAT_BUMPER_COPPER = "要花很多时间才能解决这个问题。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "花了一些时间来使用它。"
DESCRIBE.UM_DREAMCATCHER = "没时间做白日梦。"
DESCRIBE.UM_BRINEISHMOSS = "嗯嗯，苔藓没事。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "这是在我的脑袋里吗？"
DESCRIBE.SLUDGE_CORK = "它应该能帮我堵住那些淤泥。"
DESCRIBE.SLUDGESTACK = "可能值得一看。"
DESCRIBE.SPECTER_SHIPWRECK = "我看到了一些糟糕的工艺。"

DESCRIBE.UNCOMPROMISING_HARPOON = "远距离刺伤从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
DESCRIBE.UM_MAGNERANG = "沉重，就像在马蹄铁上折腾一样。"
DESCRIBE.UM_MAGNERANGREEL = "我喜欢这些东西！"
DESCRIBE.SIREN_THRONE = "哇哦，又一块石头。"
DESCRIBE.LAVASPIT_SLUDGE = "工厂又起火了！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "对于一群蜜蜂来说，它们肯定知道如何筑墙。"

DESCRIBE.PORTABLEBOAT_ITEM = "小船很懦弱！"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "强风造出强光！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "这种小动物爱叫多于咬。"
DESCRIBE.UM_ORNAMENT_RAT = "不要在我转身时咬东西！"

DESCRIBE.TRINKET_WATHOM1 = "这一切都是为了一堆垃圾......"
	
DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "这正合查理的胃口。"
--我不能像该死的影子一样弹钢琴。 他妈的！
DESCRIBE.WIXIE_CLOCK = "坏了是吧？如果它是钢制的就不会发生了！"
DESCRIBE.WIXIE_WARDROBE = "一周中的任何一天给我一个钢制储物柜。"
DESCRIBE.CHARLES_T_HORSE = "不要让我修理它，我不是木工。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "什么样的孩子会想要这个？"
DESCRIBE.SLINGSHOT_MATILDA = "这东西是怎么连在一起的？"
DESCRIBE.SLINGSHOT_GNASHER = "那东西就是麻烦。"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "哈。接下来他们会想出什么？"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "一个很好的工作女孩的零食。"
DESCRIBE.SMALLFISHMEAT_DRIED = "可以用更多这些......"

DESCRIBE.WIXIEGUN = "这就是制造业的未来吗？可惜了。"

DESCRIBE.MARA_BOSS1 = "我的天，这到底是什么东西"
ANNOUNCE.GAS_DAMAGE = "这里就像一个熔炉! 咳！"

-- 燃烧的荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "也许我应该贴上一些危险胶带。"
DESCRIBE.UM_SMOLDER_SPORE = "小心，那东西看起来要爆炸了！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "这不是一个值得怀旧的东西！！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "这不是一个值得怀旧的东西！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "这真的符合规范吗？"
DESCRIBE.UM_BLOWDART_PYRE = "我有点为另一端的人感到难过..."

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "这是个斗士！"
DESCRIBE.UM_TORNADO = "我的建筑没有经过大风认证！"
DESCRIBE.UM_WATERFALL = "当你需要时，哪里有沙袋？"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "看来我们已经远离了所有龙卷风。"
