ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WOODIE
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WOODIE.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WOODIE.ACTIONFAIL

--	[ 			Woodie Descriptions			]	--

ANNOUNCE.DREADEYE_SPOOKED = "谁在那儿？现身！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "没有身体也没什么用，嗯？"
ANNOUNCE.ANNOUNCE_WINONAGEN = "我不太热衷于维护电动引擎。"
ANNOUNCE.ANNOUNCE_RATRAID = "那是某种邪恶的声音。"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "快，抓住原木！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "Luce'！坚持住！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"我们得离开这场吓人的雨！",
"露-露西？! 你身上有一滴雨！",
"别担心露西, 我抓紧你了。",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "哇-- 哦! 看呐露西, 有新东西要砍！"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "又一个诅咒？我会把它们扔在一起。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了。"
--FoodBuffs
	
--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "让我们再次起程..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "露- 露西，是你吗？"
DESCRIBE.CALIFORNIAKING = "最好不是我想的那样。"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "我不确定这个..."
DESCRIBE.UNCOMPROMISING_RAT = "更多害虫来偷我的工具包！"
DESCRIBE.UNCOMPROMISING_RATHERD = "这就是害虫的居所！"
DESCRIBE.UNCOMPROMISING_RATBURROW = "这就是害虫的居所！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "这就是害虫的居所！"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "这就是害虫的居所！"
	
DESCRIBE.WINKY =
{
    GENERIC = "你是不是像我一样被诅咒了",
    ATTACKER = "这里唯一啃原木的就是我!",
    MURDERER = "守口如瓶!",
    REVIVER = "我喜欢这些小动物！",
    GHOST = "拯救林地动物！",
    FIRESTARTER = "老鼠不过是麻烦！",
}
DESCRIBE.WATHOM =
{
GENERIC = "我希望你不会造成任何麻烦，%s。",
     ATTACKER = "我在树林里见过更可怕的东西。",
     MURDERER = "%s 是致命的之一。",
     REVIVER = "我们这些森林生物需要团结一致，嗯 %s？",
     GHOST = "你每天都会看到一些新东西，嗯 %s？",
     FIRESTARTER = "%s 不太关心环境。",
}
DESCRIBE.WIXIE =
{
GENERIC = "离我和露西远点，你这个小威胁！",
     ATTACKER = "别再朝我扔石头了！",
     MURDERER = "%s 的行为相当刻薄！",
     REVIVER = "我想我可以原谅你，%s。",
     GHOST = "%s 还有灵魂，嗯？",
     FIRESTARTER = "我不介意侮辱，但点燃火焰越界了！",
}
		
DESCRIBE.RATPOISONBOTTLE = "让人大饱眼福的林中肠道炸弹！"
DESCRIBE.RATPOISON = "为小怪物下一次的到访准备一些东西..."

DESCRIBE.MONSTERSMALLMEAT = "如果它更大点可能会有用..."
DESCRIBE.COOKEDMONSTERSMALLMEAT = "那不是加拿大犹太食物。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "那不是加拿大犹太食物。"

DESCRIBE.UM_MONSTEREGG = "不会有好结果的.."
DESCRIBE.UM_MONSTEREGG_COOKED = "我觉得它还活着..."

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "那个蘑菇正在杀死我的树！"
DESCRIBE.TOADLING = "下车吧，你个混蛋。"
	
DESCRIBE.GASMASK = "让我的肺部保持清洁。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "那是眼睛酸痛的景象，是吧？"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿嚏！ 原谅我，对不起。"
ANNOUNCE.ANNOUNCE_HAYFEVER = "你像我一样过敏吗，露西？"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "哦！清洁空气回来了！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"冷静点，蠢货！",
	"火来了，拯救树木！",
	"这与加拿大的天气完全不同！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "你醒了，露西！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "暴风雪正在酝酿中，别担心露西，我们可以坚持住的。"
ANNOUNCE.SHADOWTALKER = {
"他们不相信我",
"他们认为我疯了",
"我只剩下她了",
}
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "感觉就像我的第一个感恩节。",
	OVERSTUFFED = "我吃撑了！",
}
DESCRIBE.UM_SAND = "沙沙的。"
DESCRIBE.UM_SANDHILL = "一大堆沙子。"
DESCRIBE.SNOWPILE = "你称之为被雪覆盖？"
DESCRIBE.SNOWGOGGLES = "现在我感觉回到了故乡。"
	
DESCRIBE.SNOWMONG = "在土里的大虫子！"
DESCRIBE.SHOCKWORM = "那条虫子像北极光一样亮了起来！"
DESCRIBE.ZASPBERRY = "蓝莓不是真正的浆果。"
DESCRIBE.ZASPBERRYPARFAIT = "给你一种静电附着力，就像你在地毯上持续摩擦你的脚之后一样。"
DESCRIBE.ICEBOOMERANG = "这就是加拿大，是吧？"
DESCRIBE.MINOTAUR_BOULDER = "它造成了严重的伤害。"
DESCRIBE.MINOTAUR_BOULDER_BIG = "毁掉这个！"
DESCRIBE.SNOWBALL_THROWABLE = "我是雪仗专家！"
DESCRIBE.VETERANSHRINE = "它让我起了鸡皮疙瘩，是吧？"
DESCRIBE.VET_SKULL = "真可惜，嗯？"
DESCRIBE.UM_BOSS_SOUL = "陷入困境，嗯？"
DESCRIBE.UM_DARK_VESTIGES = "不应该弄乱这些东西。"
DESCRIBE.UM_VOXOLOPHONE = "另一个收音机，嗯？"

DESCRIBE.UM_EXHUMER = "超出我们理解范围的恐怖，嗯？"
DESCRIBE.UM_WINGSUIT = "犯规。"
DESCRIBE.UM_MOONFLY_LANTERN = "为了那些寒冷的黑夜，嗯？"

DESCRIBE.RAT_TAIL = "我不想吸入那种气味，嗯？"
DESCRIBE.PLAGUEMASK ="阻止坏空气进入，让好空气进入，嗯？"
DESCRIBE.SPIDER_TRAPDOOR = "它们没有头发看起来更恶心。"
DESCRIBE.TRAPDOOR = "草丛里有什么东西吗？"
DESCRIBE.HOODEDTRAPDOOR = "很熟悉，是吧？"
DESCRIBE.WICKER_TENTACLE = "看起来有点绿，是吧？"
DESCRIBE.HONEY_LOG = "我已经... 有一段时间没有味觉了。"

DESCRIBE.BUSHCRAB = "在淡水里捕猎。"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "当月亮开始帮我忙的时候。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "就像一些有味道的肉干... 不，我收回我的话。"
DESCRIBE.AIR_CONDITIONER = "这是一种很好的气味变化，是吧？"
DESCRIBE.SPOREPACK = "这会冒犯鼻孔。"
DESCRIBE.SALTPACK = "这个包在加拿大很有用，是吧？"
	
DESCRIBE.UM_SCORPION = "离我的靴子远点！"
DESCRIBE.SCORPIONCARAPACE = "以前从来没吃过这个..."
DESCRIBE.SCORPIONCARAPACECOOKED = "好吧，如果真的没有别的东西了。"
DESCRIBE.HARDSHELLTACOS = "这个还不错。"
	
DESCRIBE.SKELETONMEAT = "不要扔出去，不要扔出去，不要扔出去..."
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "一场斧头大战，是吧？"
DESCRIBE.VAMPIREBAT = "你有点笨，是吧？"
							
--Swampyness
DESCRIBE.RICEPLANT = "看起来像昆虫的幼虫。"
DESCRIBE.RICE = "我不希望它那么硬。"
DESCRIBE.RICE_COOKED = "很好，但本可以做得更好。"
DESCRIBE.SEAFOODPAELLA = "吃光它！"
DESCRIBE.LICELOAF = "嗯，这是我能做的最好的了。"
DESCRIBE.SUNGLASSES = "我觉得怎么样？露西，我戴着它好看吗？"
	
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "用月石可以搭建一个很棒的小巢穴。"
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.FIRECRACKERS
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "我要让那些讨厌的虫子好看！"
DESCRIBE.STUMPLING = "森林在哭泣！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "振作起来，是吧？我们会陪着你的。"
DESCRIBE.SHADOW_TELEPORTER = "好吧，我会被诅咒的。"
DESCRIBE.POLLENMITEDEN = "勤劳的小家伙，是吧露西？"
DESCRIBE.POLLENMITES = "处理掉这些在伐木场出现的东西。"
DESCRIBE.SHADOW_CROWN = "我不是一无所有的国王，更不是傻瓜。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "这次不是为了偷工具包而来的，是吧？"
DESCRIBE.MARSH_GRASS = "这是灌木，是的。"
DESCRIBE.CURSED_ANTLER = "这将使我们永远存在！"
DESCRIBE.BERNIEBOX = "我不喜欢塞满东西。"
DESCRIBE.HOODED_FERN = "我喜欢户外活动。"
DESCRIBE.HOODEDWIDOW = "你可以拥有这些树！！"
DESCRIBE.GIANT_TREE = "真是个美女。"
DESCRIBE.WIDOWSGRASP = "也许这个可以撕开那些茧，是吧？"
DESCRIBE.WEBBEDCREATURE = "我真的应该把脖子伸长了去看看它到底是什么吗？"
ANNOUNCE.WEBBEDCREATURE = "即使是鹿鹅也没法打破它，也许蜘蛛可以？"
DESCRIBE.SNAPDRAGON_BUDDY = "这只看起来很友好。"
DESCRIBE.SNAPDRAGON = "一群看起来天赋异禀的家伙。"
DESCRIBE.SNAPPLANT = "哦，大自然的美丽！"
DESCRIBE.WHISPERPOD = "我认为它属于地下？"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "需要其他东西才能生长。",
	GROWING = "被观察的植物永远不能生长。",
}
DESCRIBE.FRUITBAT = "谁教会了水果飞行？"
DESCRIBE.PITCHERPLANT = "这是一种植物，但不是那种切碎的。"
DESCRIBE.APHID = "他们也喜欢树，是吧？"
DESCRIBE.NYMPH = "他们正在寻找更多的树木。"
DESCRIBE.GIANT_TREE_INFESTED = "别把它独占了，软蛋！"
DESCRIBE.GIANT_BLUEBERRY = "水份挺多的，是吧？"
DESCRIBE.STEAMEDHAMS = "令人垂涎的汉堡包。"
DESCRIBE.BLUEBERRYPANCAKES = "这不是枫树糖浆，但它也是不错的。"
DESCRIBE.SIMPSALAD = "只是一些粗饲料，是吧？"
DESCRIBE.DEVILSFRUITCAKE = "看起来像是瞬间空洞，是吗？"
DESCRIBE.BEEFALOWINGS = "看- 太热了！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我站得像鹿鹅一样坚挺！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "好吧，结束了。"
DESCRIBE.WIDOWSHEAD = "呃，还不错。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = DESCRIBE.PUMPKIN_LANTERN
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "我觉得我在看东西，是吧？"
DESCRIBE.VIPERFRUIT = "它的口感非常好。"
DESCRIBE.VIPERJAM = "非常适合一块吐司。"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "它在左右摇晃，是吧？",
		FROZE = "好吧，它不再动了。",
		REGROWING = "这是一场考验，是吧？",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "可怜的小东西。",
    GENERIC = "真可爱，它不是露西吗？",
    ASHLEY_BROKEN = "可怜的小东西。",
    ASHLEY = "真可爱，它不是露西吗？",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "我想我现在应该习惯奇怪的东西了。",
    ASHLEY = "我想我现在应该习惯奇怪的东西了。",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "呃，是的，又过了一天。",
    ASHLEY = "呃，是的，又过了一天。",
}
DESCRIBE.ANTIHISTAMINE = "它会在花粉热季节清理你的鼻腔。"
ANNOUNCE.CURSED_ITEM_EQUIP = "哎呀，好烫手！"
DESCRIBE.VETSITEM = "尽管我受到诅咒，但不是寻常的诅咒类型。"
DESCRIBE.SCREECHER_TRINKET = "这些符号一开始就是让我遇到麻烦的原因。"
ACTIONFAIL.GIVE = {NOTNIGHT = "也许我应该在月亮出来的时候再试一次，是吧？"}

DESCRIBE.MAGMAHOUND = "那东西会烧毁一片森林！！"
DESCRIBE.LIGHTNINGHOUND = "闪电永远不会击中两次... 是吧，露西？"
DESCRIBE.SPOREHOUND = "那只蟾蜍现在在做什么？"
DESCRIBE.GLACIALHOUND = "冰川，嗯，对我来说还是不冷不热。"
DESCRIBE.RNESKELETON = "他经历过更好的日子。"
DESCRIBE.RAT_WHIP = "它不是我想要保留的东西。"
DESCRIBE.KLAUS_AMULET = "锁链脱落了！"
DESCRIBE.CRABCLAW = "我认为，应该利用动物的每一部分。" 
DESCRIBE.HAT_RATMASK = "干得不错，是吧，露西？"

DESCRIBE.ORANGE_VOMIT = "呕吐物..."
DESCRIBE.GREEN_VOMIT = "呕吐物..."
DESCRIBE.RED_VOMIT = "呕吐物..."
DESCRIBE.PINK_VOMIT = "呕吐物..."
DESCRIBE.YELLOW_VOMIT = "呕吐物..."
DESCRIBE.PURPLE_VOMIT = "呕吐物..."
DESCRIBE.PALE_VOMIT = "呕吐物..."
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "这块金属还没死，是吧？"
DESCRIBE.KNOOK = "它们团结在一起的事实有点令人钦佩。"
DESCRIBE.ROSHIP = "它可以把恶心的黏液吐得很远。"
	
DESCRIBE.UM_PAWN = "我认为它想表达的信息非常清楚，是吧？"
DESCRIBE.UM_PAWN_NIGHTMARE = "我认为它想表达的信息非常清楚，是吧？"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH	
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
	
DESCRIBE.ANCIENT_AMULET_RED = "如果我被砍成了碎片，还是一个整体。"
DESCRIBE.UM_BEAR_TRAP = "很惊讶它们能把它这么快地放置好。"
DESCRIBE.UM_BEAR_TRAP_OLD = "有人遗漏了他们的工具。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "危险的游戏。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "危险的游戏。"
DESCRIBE.CORNCAN = "我会和露西一起去。"
DESCRIBE.SKULLCHEST_CHILD = "谁知道木头和魔法能制作如此出色的道具！"
	
DESCRIBE.SLOBBERLOBBER = "我再也不会输掉吐痰比赛了！"
DESCRIBE.GORE_HORN_HAT = "不能从一只狂暴的鹿鹅身上得到任何东西。"
DESCRIBE.BEARGERCLAW = "做一个漂亮的奖杯，是吧？"
DESCRIBE.FEATHER_FROCK = "恶心。"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n我认为它不会在蟹钳之外的地方有用。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n我认为它不会在蟹钳之外的地方有用。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n我认为它不会在蟹钳之外的地方有用。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n我认为它不会在蟹钳之外的地方有用。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n我认为它不会在蟹钳之外的地方有用。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n我认为它不会在蟹钳之外的地方有用。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n我认为它不会在蟹钳之外的地方有用。"
	
DESCRIBE.RED_MUSHED_ROOM = "可怜的东西现在都糊了。"
DESCRIBE.GREEN_MUSHED_ROOM = "可怜的东西现在都糊了。"
DESCRIBE.BLUE_MUSHED_ROOM = "可怜的东西现在都糊了。"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "让您的头脑放松。"
DESCRIBE.SKULLFLASK_EMPTY = "好吧，它现在已经消失了。"
DESCRIBE.STANTON_SHADOW_TONIC = "这不会是我吃过的最奇怪的东西..."
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "有屁快放，软蛋！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "把这些恐惧从我脑海里清除！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "这个地方真的很吸引我..."
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "在有娱乐项目的时候享用它会非常好。"
DESCRIBE.DEERCLOPS_BARRIER = "它试图把我们困在里面。"

DESCRIBE.MOONMAW_DRAGONFLY = "我的诅咒还不算差。"
DESCRIBE.MOONMAW_LAVAE = "小心！"
DESCRIBE.SNAPPERTURTLE = "我知道不要抚摸它们。"
DESCRIBE.SNAPPERTURTLEBABY = "他们仍然会拼命咬住。"
DESCRIBE.SNAPPERTURTLENEST = ""
DESCRIBE.GLASS_SCALES = "好吧，你该看看这个，露西！"
DESCRIBE.MOONGLASS_GEODE = "我不想拿着它太久，它可能会使我发生变异，是吧？"
DESCRIBE.ARMOR_GLASSMAIL = "让月亮离我的身体这么近，确定没有危险吗？"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "我不想在接收端。"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "它们在找我！"
DESCRIBE.SNOTROAST = "这会很麻烦..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "都在我的胡须上！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN_UM = "我宁愿砍木头也不愿意读这个。"
DESCRIBE.FLORAL_BANDAGE = "我会留几个以防不测。"
DESCRIBE.DORMANT_RAIN_HORN = "这很不错，不是吗，露西？"
DESCRIBE.RAIN_HORN = "那只老螃蟹是怎么做到的？"
DESCRIBE.DRIFTWOODFISHINGROD = "我喜欢在湖边放松，不用着急。"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "不希望任何害虫带走我们的工具包。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "最好清理我们的食物，可能会吸引熊，或其他更糟的生物。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "它们在树林里一直很忙，是吧？",
}

DESCRIBE.PIED_RAT = "他领导着所有那些该死的害虫！"
DESCRIBE.PIED_PIPER_FLUTE = "那些畜生必须听我的！"
DESCRIBE.UNCOMPROMISING_PACKRAT = "该死的害虫！"
	
ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "如果我不上岸，我会失去我的装备！"

ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "我不确定它是否有效。",
	CHARGE_FULL = "有点多余？",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "它现在正在工作！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "起作用了！我的手！"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "抱歉，我有我需要的所有工具。"
ACTIONFAIL.WINONATOOLBOX = "我不会把露西放在那里。"
DESCRIBE.WINONA_CATAPULT_ITEM = "它坏了吗？"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "它坏了吗？"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "它坏了吗？"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "它坏了吗？"
DESCRIBE.POWERCELL = "某种电气技巧。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "."
DESCRIBE.MINERHAT_ELECTRICAL = "呃，我怎么没想到。"
DESCRIBE.OCEAN_SPEAKER = "你觉得它在说什么很重要吗，露西？"
--DESCRIBE.UM_SIREN = "寻找海洋生物还不错，嗯？"

DESCRIBE.OCUPUS_BEAK = "无论是否是鸟，仍然是一只软管。"
DESCRIBE.OCUPUS_TENTACLE = "不。我不想和它有任何关系。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "它正盯着我看，我不能吃它。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "剥皮后还不错。"
DESCRIBE.UM_OCUPUS_EYE = "我真的不想去那里。"
DESCRIBE.UM_OCUPUS_EYETACLE = "我认为我们应该把它们拿掉。"
DESCRIBE.UM_OCUPUS_TENTACLE = "下面肯定有一只乌贼。"
DESCRIBE.UM_OCUPUS_BEAK = "那最好不是鸟。"
DESCRIBE.BEAKBASHER = "棒子上的喙。太棒了。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "我无话可说。"

DESCRIBE.ARMOR_REED_UM = "至少它是某种东西。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "这似乎有点异国情调，别想。"
DESCRIBE.ROCKJAWLEATHER = "这是皮肤，我们都有。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
DESCRIBE.STUFFED_PEEPER_POPPERS = "这绝对不会正确。"
DESCRIBE.UM_DEVILED_EGGS = "鸟类的真实本性显露出来。"
DESCRIBE.LUSH_ENTRANCE = "你觉得有什么值得探索的吗，露西？"
DESCRIBE.CRITTER_FIGGY = "只要你远离树木，我不会和你吵架的，听到了吗？"
DESCRIBE.GIANT_TREE_BIRDNEST = "我有绝佳的机会将它扼杀在原地。"

    DESCRIBE.SLUDGE = "当然是淤泥，但是什么样的淤泥？"
DESCRIBE.SLUDGE_OIL = "我认为呼吸是不安全的。"
    DESCRIBE.SLUDGE_SACK = "我更喜欢不那么湿的东西。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "一团烂泥球，不如把它射到某个地方。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "我的船至少不会被划伤。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "这淤泥真的很有弹性，嗯。"
    DESCRIBE.BOATPATCH_SLUDGE = "有点瑕疵，但她会没事的。"
    DESCRIBE.UM_COPPER_PIPE = "闻起来像硬币。"
    DESCRIBE.BRINE_BALM = "像蜜蜂蜇一样痛！" 
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "呃，这东西是从树上来的，不是吗？"
    DESCRIBE.UM_BEEGUN = "如果是我，我不会对此感到太高兴。"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "难怪他是国王。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "触摸它会让我的手闻起来像硬币。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "我觉得我更喜欢木头。"
DESCRIBE.BOAT_BUMPER_COPPER = "这艘船现在安全了。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "不是木头，但足够接近。"
DESCRIBE.UM_DREAMCATCHER = "好久没看到这些了。"
DESCRIBE.UM_BRINEISHMOSS = "恶心！苔藓。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "一定有人做了一个噩梦。"
DESCRIBE.SLUDGE_CORK = "雕刻成一个大洞，嗯。"
DESCRIBE.SLUDGESTACK = "那应该有什么用处？"
DESCRIBE.SPECTER_SHIPWRECK = "木头倒进了下水道。"

DESCRIBE.UNCOMPROMISING_HARPOON = "远距离刺伤从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
    DESCRIBE.UM_MAGNERANG = "就像扔马蹄铁一样。"
DESCRIBE.UM_MAGNERANGREEL = "我是一个简单的人，我不担心它是如何工作的。"
DESCRIBE.SIREN_THRONE = "看起来很朴素的摇滚，嗯？"
DESCRIBE.LAVASPIT_SLUDGE = "现在这是一种快速生火的方法，嗯？"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "拆掉你的墙，嗯？"

DESCRIBE.PORTABLEBOAT_ITEM = "我更喜欢更坚固的东西。也许是橡木。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "他们接下来会怎么想？"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "我们在北方并没有得到很多这样的东西。"
DESCRIBE.UM_ORNAMENT_RAT = "哦很好，这只是个玩具。"

DESCRIBE.TRINKET_WATHOM1 = "好吧，正确的负载'很糟糕。"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "她是个美女'！可惜它被砸碎了......"
DESCRIBE.WIXIE_CLOCK = "精湛的技艺！"
DESCRIBE.WIXIE_WARDROBE = "它有一种很好的橡木味，还有一丝噩梦的味道。"
DESCRIBE.CHARLES_T_HORSE = "可怜的东西。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "适合孩子们的精美玩具。"
DESCRIBE.SLINGSHOT_MATILDA = "三只鸟换三块石头，嗯？"
DESCRIBE.SLINGSHOT_GNASHER = "树林低语着黑暗的秘密，嗯？"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
		
DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "对玻璃制品的兴趣不大。"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "加拿大经典。"
DESCRIBE.SMALLFISHMEAT_DRIED = "一小口。"

DESCRIBE.WIXIEGUN = "那是不对的。"

DESCRIBE.MARA_BOSS1 = "这东西可不是天天都能看得见的"
ANNOUNCE.GAS_DAMAGE = "咳! 咳。"

-- 火炭荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "我估计这个是个大麻烦。"
DESCRIBE.UM_SMOLDER_SPORE = "它在寻找什么吗？"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "我觉得我可以防止这个。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "我觉得我可以阻止它。"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "这让我感到与自然融为一体。真的很热，很烦人的自然。"
DESCRIBE.UM_BLOWDART_PYRE = "感觉真有可能引发我关心的事情。" --上帝，我刚刚写了什么？

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "避开这只大鸟。"
DESCRIBE.UM_TORNADO = "大自然是一个残酷的主人。"
DESCRIBE.UM_WATERFALL = "真是一场灾难。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "周围没有龙卷风，但我可以告诉你。"
