ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WORMWOOD.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WORMWOOD.ACTIONFAIL

--	[ 		Wormwood Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "什么在看着我？"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "进入肉类部分"
ANNOUNCE.ANNOUNCE_WINONAGEN = "怎么走？"
ANNOUNCE.ANNOUNCE_RATRAID = "吱吱声！"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "窃贼吱吱吱吱！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "回家了？"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"水伤害别人？！",
"水正在燃烧！",
"为什么水不好？！",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "朋友？生病的朋友？不！不好！"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "现在虚弱了很多。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了"
--FoodBuffs
	
--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "什么"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "呃"
DESCRIBE.CALIFORNIAKING = "有气味的饮品"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "被监视了"
DESCRIBE.UNCOMPROMISING_RAT = "毛茸茸的偷窃者"
DESCRIBE.UNCOMPROMISING_RATHERD = "吱吱兽的洞"
DESCRIBE.UNCOMPROMISING_RATBURROW = "吱吱兽的洞"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "吱吱兽的洞"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "吱吱兽的洞"
	
DESCRIBE.WINKY =
{
    GENERIC = "你好！大吱吱！",
    ATTACKER = "吱吱！卑鄙！",
    MURDERER = "我们不是一路人!肮脏的吱吱!",
    REVIVER = "吱吱有大心脏？",
    GHOST = "噢，吱吱需要帮助",
    FIRESTARTER = "伤害朋友！",
}
DESCRIBE.WATHOM =
{
GENERIC = "可怕的红牙",
     ATTACKER = "红牙生气了！",
     MURDERER = "死对头！",
     REVIVER = "Toother 是朋友？",
     GHOST = "哦，糟糕的漂浮物",
     FIRESTARTER = "%s 像火一样红。",
}
DESCRIBE.WIXIE =
{
GENERIC = "大坏蛋",
     ATTACKER = "%s 疯了！",
     MURDERER = "%s 伤害了朋友",
     REVIVER = "%s 帮帮我？",
     GHOST = "不要再刻薄了",
     FIRESTARTER = "%s 生火！",
}
		
DESCRIBE.RATPOISONBOTTLE = "蘑菇朋友汤！"
DESCRIBE.RATPOISON = "闻起来很香"

DESCRIBE.MONSTERSMALLMEAT = "现在不生气"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "奇怪的食物"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "耐嚼！"

DESCRIBE.UM_MONSTEREGG = "双胞胎嘛?"
DESCRIBE.UM_MONSTEREGG_COOKED = "哦,不是为了肚子"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "朋友，请停下来"
DESCRIBE.TOADLING = "呱呱叫的朋友？"
	
DESCRIBE.GASMASK = "穿着鸟类的衣服呼吸"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "睡着了？"
ANNOUNCE.ANNOUNCE_SNEEZE = "呵啾！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "快乐时光即将来临！"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "噢，快乐时光结束了"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"可怕！",
	"火！伤害朋友！",
	"不是朋友！不是朋友！！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "糟糕的拥抱！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "Brrr.... 下雪了"
ANNOUNCE.SHADOWTALKER = {
"独单一人",
"不像他们",
"伤心",
}
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "肚子里的东西太多",
	OVERSTUFFED = "太满了！",
}
DESCRIBE.UM_SAND = "污垢"
DESCRIBE.UM_SANDHILL = "一堆泥土"
DESCRIBE.SNOWPILE = "朋友杀手！"
DESCRIBE.SNOWGOGGLES = "猫眼？"
	
DESCRIBE.SNOWMONG = "冷挖掘机！"
DESCRIBE.SHOCKWORM = "带电的摇摆兽"
DESCRIBE.ZASPBERRY = "带电的食物"
DESCRIBE.ZASPBERRYPARFAIT = "甜甜的食物"
DESCRIBE.ICEBOOMERANG = "让东西停下来"
DESCRIBE.MINOTAUR_BOULDER = "大石头"
DESCRIBE.MINOTAUR_BOULDER_BIG = "呃... 用头撞大石头？"
DESCRIBE.VETERANSHRINE = "悲伤的头？"
DESCRIBE.VET_SKULL = "哦。哦天哪。"
DESCRIBE.UM_BOSS_SOUL = "迷路了？"
DESCRIBE.UM_DARK_VESTIGES = "坏东西"
DESCRIBE.UM_VOXOLOPHONE = "对话盒"

DESCRIBE.UM_EXHUMER = "死去的朋友？"
DESCRIBE.UM_WINGSUIT = "喜欢推特的朋友们！"
DESCRIBE.UM_MOONFLY_LANTERN = "里面有聪明的朋友"

DESCRIBE.SNOWBALL_THROWABLE = "好玩！"
DESCRIBE.RAT_TAIL = "来自吱吱兽的屁股"
DESCRIBE.PLAGUEMASK = "鸟的脸"
DESCRIBE.SPIDER_TRAPDOOR = "长腿虫没有头发？"
DESCRIBE.TRAPDOOR = "朋友的头发"
DESCRIBE.HOODEDTRAPDOOR = "石头"
DESCRIBE.WICKER_TENTACLE = "摇摆兽生病了？"
DESCRIBE.HONEY_LOG = "送给朋友！"

DESCRIBE.BUSHCRAB = "朋友？ 是... 不是？"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "治愈朋友！"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "无法咀嚼"
DESCRIBE.AIR_CONDITIONER = "快乐时光中断了？"
DESCRIBE.SPOREPACK = "怎么了？"
DESCRIBE.SALTPACK = "很有趣的气味"
	
DESCRIBE.UM_SCORPION = "刺伤人的昆虫"
DESCRIBE.SCORPIONCARAPACE = "松脆的昆虫"
DESCRIBE.SCORPIONCARAPACECOOKED = "烧焦的昆虫"
DESCRIBE.HARDSHELLTACOS = "松脆的昆虫食物"
	
DESCRIBE.SKELETONMEAT = "呃，很耐嚼"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "发生什么事了，朋友？"
DESCRIBE.VAMPIREBAT = "飞行的爪子"
								
--Swampyness
DESCRIBE.RICEPLANT = "水里的朋友！"
DESCRIBE.RICE = "水里的朋友的宝宝"
DESCRIBE.RICE_COOKED = "闻一闻"
DESCRIBE.SEAFOODPAELLA = "闻一闻"
DESCRIBE.LICELOAF = "很多水里的朋友的宝宝"
DESCRIBE.SUNGLASSES = "火球阻挡器"
	
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "月岩可以建造一个很好的家"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "暴揍昆虫"
DESCRIBE.STUMPLING = "小朋友不开心"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "想家了..."
DESCRIBE.SHADOW_TELEPORTER = "朋友的礼物？"
DESCRIBE.POLLENMITEDEN = "不是朋友"
DESCRIBE.POLLENMITES = "走开"
DESCRIBE.SHADOW_CROWN = "受到更多伤害，但是走得更快"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "朋友在毛茸茸的偷窥者身体里长出来了"
DESCRIBE.MARSH_GRASS = "很好的头发，朋友！"
DESCRIBE.CURSED_ANTLER = "可以重击的棒子"
DESCRIBE.BERNIEBOX = "被困在里面了"
DESCRIBE.HOODED_FERN = "大朋友的头发很好"
DESCRIBE.HOODEDWIDOW = "非常大的多腿虫的妈妈！"
DESCRIBE.GIANT_TREE = "大朋友？"
DESCRIBE.WIDOWSGRASP = "多腿虫的腿"
DESCRIBE.WEBBEDCREATURE = "多腿虫的零食"
ANNOUNCE.WEBBEDCREATURE = "需要多腿虫的尖刺"
DESCRIBE.SNAPDRAGON_BUDDY = "朋友饿了"
DESCRIBE.SNAPDRAGON = "大朋友！大胃王！"
DESCRIBE.SNAPPLANT = "看起来不错！"
DESCRIBE.WHISPERPOD = "需要一些泥土吗？"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "需要种子",
	GROWING = "快好了！",
}
DESCRIBE.FRUITBAT = "飞行的朋友"
DESCRIBE.PITCHERPLANT = "悬挂的朋友"
DESCRIBE.APHID = "吃大朋友！"
DESCRIBE.NYMPH = "不！不！不！坏虫子！!"
DESCRIBE.GIANT_TREE_INFESTED = "大朋友生病了"
DESCRIBE.GIANT_BLUEBERRY = "好耶！水！"
DESCRIBE.PURPLESTEAMEDHAMS = "哎呀！"
DESCRIBE.GREENSTEAMEDHAMS ="天啊！"
DESCRIBE.BLUEBERRYPANCAKES = "美味的果汁"
DESCRIBE.DEVILSFRUITCAKE = "邪恶的蛋糕？"
DESCRIBE.SIMPSALAD = "需要更多"
DESCRIBE.BEEFALOWINGS = "脆脆的"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "不会被推动"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "噢，又可以被推动了"
DESCRIBE.WIDOWSHEAD = "更大的多腿虫的头"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "笑容很好"
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "让脑袋觉得有趣"
DESCRIBE.VIPERFRUIT = "漩涡"
DESCRIBE.VIPERJAM = "朋友的家"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "爆炸水果",
		FROZE = "冷的爆炸水果",
		REGROWING = "生长！",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "发生了什么？",
    GENERIC = "你好，软软的朋友！",
    ASHLEY_BROKEN = "发生了什么？",
    ASHLEY = "你好，软软的朋友！",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "耶！软软的朋友可以玩了！",
    ASHLEY = "耶！软软的朋友可以玩了！",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "大的软软的朋友！",
    ASHLEY = "大的软软的朋友！",
}
DESCRIBE.ANTIHISTAMINE = "闻食物"
ANNOUNCE.CURSED_ITEM_EQUIP = "不好！"
DESCRIBE.VETSITEM = "想要诅咒。"
DESCRIBE.SCREECHER_TRINKET = "可怕，不是朋友"
ACTIONFAIL.GIVE = {NOTNIGHT = "需要月亮"}

DESCRIBE.MAGMAHOUND = "坏！坏！"
DESCRIBE.LIGHTNINGHOUND = "带电的汪汪兽！"
DESCRIBE.SPOREHOUND = "带蘑菇的... 汪汪兽？ 朋友？"
DESCRIBE.GLACIALHOUND = "大的冰冻汪汪兽！"
DESCRIBE.RNESKELETON = "活的。朋友？"
DESCRIBE.RAT_WHIP = "耐嚼"
DESCRIBE.KLAUS_AMULET = "感觉强壮"
DESCRIBE.CRABCLAW = "剪 剪 剪 剪" 
DESCRIBE.HAT_RATMASK = "难闻的吱吱兽"

DESCRIBE.ORANGE_VOMIT = "有趣的味道"
DESCRIBE.GREEN_VOMIT = "有趣的味道"
DESCRIBE.RED_VOMIT = "有趣的味道"
DESCRIBE.PINK_VOMIT = "有趣的味道"
DESCRIBE.YELLOW_VOMIT = "有趣的味道"
DESCRIBE.PURPLE_VOMIT = "有趣的味道"
DESCRIBE.PALE_VOMIT = "有趣的味道"
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "带电的"
DESCRIBE.KNOOK = "咔嚓咔嚓，咔嚓咔嚓"
DESCRIBE.ROSHIP = "咔-啾"
	
DESCRIBE.UM_PAWN = "不"
DESCRIBE.UM_PAWN_NIGHTMARE = "不"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH	
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
	
DESCRIBE.ANCIENT_AMULET_RED = "灵魂？"
DESCRIBE.UM_BEAR_TRAP = "金属嘴巴"
DESCRIBE.UM_BEAR_TRAP_OLD = "旧的金属嘴巴"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "可怕的牙齿"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "真可怕的牙齿"
DESCRIBE.CORNCAN = "里面有朋友的东西？"
DESCRIBE.SKULLCHEST_CHILD = "来自其他地方的东西"
	
DESCRIBE.SLOBBERLOBBER = "热！热！离远点！"
DESCRIBE.GORE_HORN_HAT = "尖尖的"
DESCRIBE.BEARGERCLAW = "大爪子"
DESCRIBE.FEATHER_FROCK = "蓬松的羽毛"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n重塑形状。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n重塑形状。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n重塑形状。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n重塑形状。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n重塑形状。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n重塑形状。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n重塑形状。"
	
DESCRIBE.RED_MUSHED_ROOM = "糊状的朋友..."
DESCRIBE.GREEN_MUSHED_ROOM = "糊状的朋友..."
DESCRIBE.BLUE_MUSHED_ROOM = "糊状的朋友..."
	
--StantonStuff
DESCRIBE.SKULLFLASK = "保持头部清醒"
DESCRIBE.SKULLFLASK_EMPTY = "空的"
DESCRIBE.STANTON_SHADOW_TONIC = "饮料？"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "另一个骨头人"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "别害怕！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "害怕..."
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "现在可以看朋友了"
DESCRIBE.DEERCLOPS_BARRIER = "打碎弱者"
	
DESCRIBE.MOONMAW_DRAGONFLY = "最像月亮的苍蝇" --Reference to WormiestWood, who suggested this first. We love our community :)
DESCRIBE.MOONMAW_LAVAE = "很熟悉"
DESCRIBE.SNAPPERTURTLE = "你好"
DESCRIBE.SNAPPERTURTLEBABY = "小小的"
DESCRIBE.SNAPPERTURTLENEST = "睡觉的地方"
DESCRIBE.GLASS_SCALES = "很好的光"
DESCRIBE.MOONGLASS_GEODE = "感觉很舒服"
DESCRIBE.ARMOR_GLASSMAIL = "月亮喜欢我"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "石头朋友"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE
DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR
	
DESCRIBE.WOODPECKER = "笃-笃-笃"
DESCRIBE.SNOTROAST = "呃... 鼻子里的东西"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "肚子好饱！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN_UM = "溅起水花"
DESCRIBE.FLORAL_BANDAGE = "朋友听起来多汁"
DESCRIBE.DORMANT_RAIN_HORN = "漂亮的贝壳"
DESCRIBE.RAIN_HORN = "湿的贝壳"
DESCRIBE.DRIFTWOODFISHINGROD = "像是朋友的木棍可以进入很深的水里。"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "地上的东西太多了！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "食物的气味太难闻了！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "那里有偷东西的人",
}

DESCRIBE.PIED_RAT = "真的很大的吱吱兽"
DESCRIBE.PIED_PIPER_FLUTE = "嘟-嘟-嘟！"
DESCRIBE.UNCOMPROMISING_PACKRAT = "能带更多东西的吱吱兽"
	
ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "OH!漂浮的沉没！"

ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "不",
	CHARGE_FULL = "不",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "滋滋滋！抓紧！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "滋滋滋!"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "携带物品箱"
ACTIONFAIL.WINONATOOLBOX = "不适合我"
DESCRIBE.WINONA_CATAPULT_ITEM = "重金属！"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "重金属！"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "重金属！"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "重金属！"
DESCRIBE.POWERCELL = "吱吱作响盒子"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "滋滋声的根源"
DESCRIBE.MINERHAT_ELECTRICAL = "可以摧毁它"
DESCRIBE.OCEAN_SPEAKER = "歌盒朋友？不……"
DESCRIBE.UM_SIREN = "是歌舞女郎"

DESCRIBE.OCUPUS_BEAK = "鹰钩鼻"
DESCRIBE.OCUPUS_TENTACLE = "大吸盘手"
DESCRIBE.OCUPUS_TENTACLE_EYE = "死神"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "吸盘肉"
DESCRIBE.UM_OCUPUS_EYE = "观察者视野。"
DESCRIBE.UM_OCUPUS_EYETACLE = "监视者让我们留在这里。"
DESCRIBE.UM_OCUPUS_TENTACLE = "来自海洋的武器。"
DESCRIBE.UM_OCUPUS_BEAK = "喙头伤了头。"
DESCRIBE.BEAKBASHER = "喙击碎机。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "水怪守护着我们。"

DESCRIBE.ARMOR_REED_UM = DESCRIBE.ARMORGRASS
DESCRIBE.ARMOR_SHARKSUIT_UM = ""
DESCRIBE.ROCKJAWLEATHER = "一块儿皮肤"

DESCRIBE.EYEOFTERROR_MINI_ALLY = "Helpful peeper friend"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = "眼球朋友"
DESCRIBE.STUFFED_PEEPER_POPPERS = "眨眼？不……"
DESCRIBE.UM_DEVILED_EGGS = "糟糕的高音喇叭"
DESCRIBE.LUSH_ENTRANCE = "朋友隧道？"
DESCRIBE.CRITTER_FIGGY = "朋友！"
DESCRIBE.GIANT_TREE_BIRDNEST = "小高音回家"

    DESCRIBE.SLUDGE = "黏糊糊的臭斑点"
DESCRIBE.SLUDGE_OIL = "不渴"
    DESCRIBE.SLUDGE_SACK = "内部粘稠"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "轰！轰！火岩"
DESCRIBE.BOAT_BUMPER_SLUDGE = "波音！"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "有弹性的大臭水滴"
    DESCRIBE.BOATPATCH_SLUDGE = "圆形浮动固定器"
    DESCRIBE.UM_COPPER_PIPE = "金属朋友？不。"
    DESCRIBE.BRINE_BALM = "噢！朋友小气！"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "闷闷不乐？"
DESCRIBE.UM_BEEGUN = "Buzzer pew pew pew！"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "蟹盒"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM

DESCRIBE.STEERINGWHEEL_COPPER = "没有朋友在制作过程中受到伤害"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "需要漂浮来引导"
DESCRIBE.BOAT_BUMPER_COPPER = "金属屏障"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "金属屏障"
DESCRIBE.UM_DREAMCATCHER = "朋友喜欢拿着睡眠捕手"
DESCRIBE.UM_BRINEISHMOSS = "柔软的朋友头发！"
DESCRIBE.UM_COALESCED_NIGHTMARE = "可怕的黑暗事物"
DESCRIBE.SLUDGE_CORK = "臭臭的修复剂"
DESCRIBE.SLUDGESTACK = "臭臭的家"
DESCRIBE.SPECTER_SHIPWRECK = "噢……朋友坠毁了"

DESCRIBE.UNCOMPROMISING_HARPOON = "投掷者刺刀"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "啊偶！疼！"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "拉线盒"
DESCRIBE.UM_MAGNERANG = "哇哇哇哇哇"
DESCRIBE.UM_MAGNERANGREEL = "哇哇哇盒子"
DESCRIBE.SIREN_THRONE = "硬座"
DESCRIBE.LAVASPIT_SLUDGE = "太热了！！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "强壮的嗡嗡声！"

DESCRIBE.PORTABLEBOAT_ITEM = "软软的浮船"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "旋转！旋转！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "可怕。但可爱？"
DESCRIBE.UM_ORNAMENT_RAT = "活蹦乱跳?"

DESCRIBE.TRINKET_WATHOM1 = "在这里留下了一块"
	
DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "木制朋友发出美妙的声音"
DESCRIBE.WIXIE_CLOCK = "拉动东西会让尖的东西旋转！"
DESCRIBE.WIXIE_WARDROBE = "里面是什么？坏了吗？"
DESCRIBE.CHARLES_T_HORSE = "可怕的东西"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "嘶嘶！"
DESCRIBE.SLINGSHOT_MATILDA = "啪啪啪！"
DESCRIBE.SLINGSHOT_GNASHER = "朋友在说话？"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
		
DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "眼睛？……蛋？"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "鱼干"
DESCRIBE.SMALLFISHMEAT_DRIED = "小鱼干"

DESCRIBE.WIXIEGUN = "那是不对的。"

DESCRIBE.MARA_BOSS1 = "不对劲！快跑!!"
ANNOUNCE.GAS_DAMAGE = "kack！kack！"

--Pyre Nettle的东西
DESCRIBE.UM_PYRE_NETTLES  = {
"火的朋友，太可怕了",
"火的朋友, 太可怕了",
"火的朋友，太可怕了",
"火的朋友, 太可怕了",
"火的朋友，太可怕了",
"火的朋友，太可怕了",
"火的朋友！热情的家伙"
}
DESCRIBE.UM_SMOLDER_SPORE = "害羞，应该独自离开"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "不不，你为什么这么做"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "啊! 糟糕! 不不不不不不不不!!"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "舒适的...."
DESCRIBE.UM_BLOWDART_PYRE = "对不起..."

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "为什么生气？"
DESCRIBE.UM_TORNADO = "可怕的呜呜声"
DESCRIBE.UM_WATERFALL = "坠落的水花"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有吓唬人的东西。"
