ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WARLY
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WARLY.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WARLY.ACTIONFAIL

--	[ 		Warly Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "我的朋友！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES =
"最好由顾客本人享用。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "工程学不在我的烹饪范畴内。"
ANNOUNCE.ANNOUNCE_RATRAID = "哦不..."
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "拿上灭鼠药！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "混蛋！它们要跑了！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "不不不，这种天气会毁了我的华服！",
    "哎哟！这雨是怎么回事？", "啊！我正在被炒制！"
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "啊！这是个埋在地下的自助餐！"
-- FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "太太太冷了"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我觉得恶心..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了"
ANNOUNCE.ANNOUNCE_RNEFOG = "有人在那里吗？"
-- FoodBuffs

-- CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "哦不！它来了！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING =
"我宁愿不要再经历一次。"
DESCRIBE.CALIFORNIAKING = "我不想再碰这东西了...."
-- CaliforniaKing

DESCRIBE.UNCOMPROMISING_RAT =
"别让那些肮脏的小害虫靠近我的厨房！"
DESCRIBE.UNCOMPROMISING_RATHERD = "麻烦的源头！"
DESCRIBE.UNCOMPROMISING_RATBURROW = "麻烦的源头！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "那最好不要惹出什么麻烦。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW =
"我不信任从那里来的任何食材！"

DESCRIBE.WINKY = {
    GENERIC = "在食物附近记得戴发网，%s！",
    ATTACKER = "把那份攻击性远离我的厨房！",
    MURDERER = "谋杀可换不来奶酪！",
    REVIVER = "谢谢你%s！也许我们什么时候可以一起做饭。",
    GHOST = "好吧，至少她不会再跑到食物里了。",
    FIRESTARTER = "调小火力，%s！你会烧掉所有食物的！"
}
DESCRIBE.WATHOM = {
    GENERIC = "拜托别在我的食物上流口水，%s。",
    ATTACKER = "我无法熄灭你对暴力的渴望，%s！",
    MURDERER = "这锅已经煮过头了！",
    REVIVER = "谢谢，%s！",
    GHOST = "你真是个怪人，%s。",
    FIRESTARTER = "调小火力，%s！"
}
DESCRIBE.WIXIE = {
    GENERIC = "一个小恶魔！",
    ATTACKER = "%s脑子里正在酝酿麻烦！",
    MURDERER = "我受不了她所有的暴力行为！",
    REVIVER = "谢谢你%s，但请远离我的厨房！",
    GHOST = "我们应该帮助%s吗？我不太确定。",
    FIRESTARTER = "她喜欢把一切都煮过头！"
}

DESCRIBE.RATPOISONBOTTLE = "一瓶安心剂。"
DESCRIBE.RATPOISON = "晚餐上桌了..."

DESCRIBE.MONSTERSMALLMEAT = "正在制作中的珍馐？"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "嗯，怎样拯救这道菜呢...？"
DESCRIBE.MONSTERSMALLMEAT_DRIED =
"我讨厌浪费好食物，但是...这不是。"

DESCRIBE.UM_MONSTEREGG = "对完美的嘲讽！"
DESCRIBE.UM_MONSTEREGG_COOKED = "没有任何香料能拯救它。"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "多么难吃的嫩芽。"
DESCRIBE.TOADLING =
"看来它们离不开那真菌的奇异香气。"

DESCRIBE.GASMASK = "我可以在烟熏房里用这个。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "我的天！必须把它处理掉！"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿嚏！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "呃！我的过敏症！"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "我想...我的鼻子通畅了！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
    "什么？还有？！", "小心别被烤焦了！",
    "地面正在被炙烤！"
}
ANNOUNCE.ANNOUNCE_ROOTING = "绝对不是香料根茎！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "感觉像风暴正在酝酿！"
ANNOUNCE.SHADOWTALKER = {
    "她孤身一人", "她不记得我了", "我不在她身边"
}
ANNOUNCE.ANNOUNCE_OVER_EAT = {
    STUFFED = "啊，也许我多吃了一口...",
    OVERSTUFFED = "强迫自己吃东西很难享受美食！"
}
DESCRIBE.UM_SAND = "许多微小的石头。"
DESCRIBE.UM_SANDHILL = "沙子堆成了一个小堆。"
DESCRIBE.SNOWPILE = "雪对我来说是新事物，看起来是个麻烦。"
DESCRIBE.SNOWGOGGLES = "仍然不是我的风格，但至少看得更清楚了。"

DESCRIBE.SNOWMONG = "这不是冷冻甜品！"
DESCRIBE.SHOCKWORM = "触摸它可能会把我完美地烤熟！"
DESCRIBE.ZASPBERRY = "也许做个不错的树莓芭菲？"
DESCRIBE.ZASPBERRYPARFAIT =
"我只能想象它的味道！希望不会电到任何人..."
DESCRIBE.ICEBOOMERANG = "也许如果我蘸上调料，留到夏天再用？"
DESCRIBE.MINOTAUR_BOULDER = "小心你们的头！"
DESCRIBE.MINOTAUR_BOULDER_BIG =
"让我们也让那家伙尝尝自己的苦头！"
DESCRIBE.VETERANSHRINE = "为了食材我竟然做到这种地步..."
DESCRIBE.VET_SKULL = "这些骨头煮不烂。"
DESCRIBE.UM_BOSS_SOUL = "这是我们称之为'生命'的菜肴中最重要的一部分。"
DESCRIBE.UM_DARK_VESTIGES = "不管它是什么，都不能吃！"
DESCRIBE.UM_VOXOLOPHONE = "这不是我第一次听收音机了。"

DESCRIBE.UM_EXHUMER = "起死回生会招来厄运。"
DESCRIBE.UM_WINGSUIT = "鸟儿被拔了毛！"
DESCRIBE.UM_MOONFLY_LANTERN = "至少可以说，这是一盏有用的灯。"

DESCRIBE.RAT_TAIL = "我不想让它靠近我的手！或者我的食物！或者任何地方！"
DESCRIBE.PLAGUEMASK = "也许我应该知足。"
DESCRIBE.SPIDER_TRAPDOOR = "又是跳跃蜘蛛？我的天..."
DESCRIBE.TRAPDOOR = "我不想绊倒然后洒了什么东西。"
DESCRIBE.HOODEDTRAPDOOR = "最好密切注意那个。"
DESCRIBE.WICKER_TENTACLE = "如果它不在陆地上，我会说它看起来晕船了。"
DESCRIBE.HONEY_LOG = "虽然不是紫薯卷，但努力值得赞赏。"

DESCRIBE.BUSHCRAB = "浆果和蟹饼，有人要吗？不要？"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "我怀疑这不会是好的食用油。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "我...不会去烹饪那个。"
DESCRIBE.AIR_CONDITIONER = "啊，我的肺清爽了！"
DESCRIBE.SPOREPACK = "绝对不行。"
DESCRIBE.SALTPACK = "有人介意我用这盐吗？"


DESCRIBE.SKELETONMEAT = "有些菜肴可能不该被制作。"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "他想做碎肝！"
DESCRIBE.VAMPIREBAT = "我向你保证，我尝起来很糟糕！"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN =
"一些月岩将是建造新小家的完美材料。"
DESCRIBE.CHARLIEPHONOGRAPH_100 = "我想知道她的唱片收藏里有什么？"
DESCRIBE.BUGZAPPER = "回到...我经常要用这些"
-- Swampyness
DESCRIBE.RICEPLANT = "新鲜的沼泽食材！"
DESCRIBE.RICE = "我会留着以后用"
DESCRIBE.RICE_COOKED = "我本可以做得更好"
DESCRIBE.SEAFOODPAELLA = "海鲜与米饭融合的方式...."
DESCRIBE.LICELOAF = "略有改善，但勉强可以接受。"
DESCRIBE.SUNGLASSES = "不用再烤眼球了。"

DESCRIBE.STUMPLING = "我真希望能回到我的厨房！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "我怀疑它不卫生，但我应该留着它。"
DESCRIBE.SHADOW_TELEPORTER =
"说我迷信也好，但这里有危险的事情发生..."
DESCRIBE.POLLENMITEDEN = "我宁愿面对一堆巧克力。"
DESCRIBE.POLLENMITES = "这里的虫子真的很糟糕。"
DESCRIBE.SHADOW_CROWN = "这东西被诅咒了，我确信！"
DESCRIBE.UM_SHADOW_AXE = "终于，我可以在这里得到一些帮助了。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "我不在菜单上！"
DESCRIBE.MARSH_GRASS = "它提供了风景。"
DESCRIBE.CURSED_ANTLER = "我对骨头略知一二。"
DESCRIBE.BERNIEBOX = "这个谜题留给薇洛去解吧。"
DESCRIBE.HOODED_FERN = "好吧，它在那里。"
DESCRIBE.HOODEDWIDOW = "我想我从它那里得不到怪物肉。"
DESCRIBE.GIANT_TREE = "真是个奇迹。"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST

DESCRIBE.WIDOWSGRASP = "我可以炸它？"
DESCRIBE.SILKSACK = "这不是储存农产品的最佳场所。"
DESCRIBE.SILKEN_BUNDLE = "我怀疑蜘蛛丝不会长时间保存我们的食物。"

DESCRIBE.WEBBEDCREATURE = "我真的想从那里面获取食材吗？"
ANNOUNCE.WEBBEDCREATURE =
"我刺不穿它。我的手和蜘蛛的不同。"
DESCRIBE.SNAPDRAGON_BUDDY = "它的饥饿在呼唤我！"
DESCRIBE.SNAPDRAGON = "天哪，你真大。"
DESCRIBE.SNAPPLANT = "一株活泼的植物！"
DESCRIBE.WHISPERPOD = "让我们给你找些土壤！"
DESCRIBE.WHISPERPOD_NORMAL_GROUND = {
    GENERIC = "农作物种子可能会派上用场。",
    GROWING = "就这样，再长大一点..."
}
DESCRIBE.FRUITBAT = "实际上我不介意这一个。"
DESCRIBE.PITCHERPLANT = "我想知道里面有没有露水？"
DESCRIBE.APHID = "一种可怕的害虫。"
DESCRIBE.NYMPH = "害虫和瘟疫。"
DESCRIBE.GIANT_TREE_INFESTED = "它似乎病得很重。"
DESCRIBE.GIANT_BLUEBERRY = "哦呵呵，我对你有很多想法！"
DESCRIBE.BLUEBERRYPANCAKES = "甚至不用往浆果里加糖。"
DESCRIBE.DEVILSFRUITCAKE = "我甚至没有出卖我的灵魂！"
DESCRIBE.SIMPSALAD =
"简单是可以的，但我需要的不止这些。"
DESCRIBE.BEEFALOWINGS = "角真的突出了辣椒的热度。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE =
"我拥有了皮弗娄牛般的坚韧！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "又回到被撞倒的状态。"
DESCRIBE.WIDOWSHEAD = "另一个头？我想知道这个头会做什么。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = DESCRIBE.PUMPKIN_LANTERN

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "那颗浆果闻起来很诱人。"
DESCRIBE.VIPERFRUIT = "也许可以做成果酱？"
DESCRIBE.VIPERFRUIT_LESSER = DESCRIBE.VIPERFRUIT
DESCRIBE.VIPERJAM = "完美的风味融合！"

DESCRIBE.BLUEBERRYPLANT = {
    READY = "哦，可能性无穷！",
    FROZE = "在这种状态下你不能用，我的朋友！",
    REGROWING = "哦好，它会重新长出来的。我想要更多！"
}

DESCRIBE.ANTIHISTAMINE = "我讨厌在食物附近打喷嚏，这会有帮助。"
ANNOUNCE.CURSED_ITEM_EQUIP = "我的手被烤焦了！"
DESCRIBE.VETSITEM = "我似乎缺少一些黑暗的配料。"
DESCRIBE.SCREECHER_TRINKET = "黑暗正在蠢蠢欲动。"
ACTIONFAIL.GIVE.NOTNIGHT = "有些菜肴最好在晚上供应。"

DESCRIBE.MAGMAHOUND = "行走的熔炉。要是能被驯养就好了..."
DESCRIBE.LIGHTNINGHOUND = "绝对来自热带。"
DESCRIBE.SPOREHOUND = "这条狗生病了。"
DESCRIBE.GLACIALHOUND = "我不喜欢它冰冷的凝视。"
DESCRIBE.RNESKELETON = "没有胃了？抱歉朋友，我帮不了你！"
DESCRIBE.RAT_WHIP = "这是个坏主意。"
DESCRIBE.KLAUS_AMULET = "钢铁令人胆寒。"
DESCRIBE.CRABCLAW = "这只蟹钳上的肉不多。"
DESCRIBE.HAT_RATMASK = "天哪，什么可怕的气味！"

DESCRIBE.ORANGE_VOMIT = "厨师最不想看到的东西！"
DESCRIBE.GREEN_VOMIT = "厨师最不想看到的东西！"
DESCRIBE.RED_VOMIT = "厨师最不想看到的东西！"
DESCRIBE.PINK_VOMIT = "厨师最不想看到的东西！"
DESCRIBE.YELLOW_VOMIT = "厨师最不想看到的东西！"
DESCRIBE.PURPLE_VOMIT = "厨师最不想看到的东西！"
DESCRIBE.PALE_VOMIT = "厨师最不想看到的东西！"

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = {
    GUARD = DESCRIBE.PIGMAN.GUARD,
    WEREPIG = DESCRIBE.PIGMAN.WEREPIG
}
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH

DESCRIBE.BIGHT = "多么可怕的混合体！"
DESCRIBE.KNOOK = "这匹马从里到外都被烤透了。"
DESCRIBE.ROSHIP = "它会做出惊人的菜肴！"

DESCRIBE.UM_PAWN = "我会注意脚下。"
DESCRIBE.UM_PAWN_NIGHTMARE = "我会注意脚下。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "它搅动着我的灵魂。就像炖菜一样。"
DESCRIBE.UM_BEAR_TRAP = "我会保持距离。"
DESCRIBE.UM_BEAR_TRAP_OLD = "我会保持距离。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "有效就行。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "有效就行。"
DESCRIBE.SKULLCHEST_CHILD = "现在我可以从远方获取新鲜农产品了！"

DESCRIBE.SLOBBERLOBBER =
"不！不要靠近食物！或者食物附近的任何地方！\n再说一遍，把它拿走！"
DESCRIBE.GORE_HORN_HAT = "串烧时间！"
DESCRIBE.BEARGERCLAW = "至少我的手是干净的。"
DESCRIBE.FEATHER_FROCK =
"准备家禽时拔羽毛其实没必要。"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM ..
    "\n...除了螃蟹钳之外它毫无用处！"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM ..
    "\n...除了螃蟹钳之外它毫无用处！"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM ..
    "\n...除了螃蟹钳之外它毫无用处！"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM ..
    "\n...除了螃蟹钳之外它毫无用处！"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM ..
    "\n...除了螃蟹钳之外它毫无用处！"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM ..
    "\n...除了螃蟹钳之外它毫无用处！"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM ..
    "\n...除了螃蟹钳之外它毫无用处！"

DESCRIBE.RED_MUSHED_ROOM = "太稠了不能做釉料。"
DESCRIBE.GREEN_MUSHED_ROOM = "太稠了不能做釉料。"
DESCRIBE.BLUE_MUSHED_ROOM = "太稠了不能做釉料。"

-- StantonStuff
DESCRIBE.SKULLFLASK =
"他赌上了他的食谱。我还是不确定这是不是酒。"
DESCRIBE.SKULLFLASK_EMPTY = "这就是全部了。"
DESCRIBE.STANTON_SHADOW_TONIC =
"嗯，这是什么酒？味道...很奇怪。"
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "来一杯？我已经很久没喝葡萄酒了！"
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "如此安慰的味道。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "哦..."
-- StantonStuff

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "剧院食品总能提升任何体验。"
DESCRIBE.DEERCLOPS_BARRIER = "我们需要突破障碍！"

DESCRIBE.MOONMAW_DRAGONFLY = "我无法使用那个动物的任何部分！"
DESCRIBE.MOONMAW_LAVAE = "比刀还锋利，直冲我的脸而来！"
DESCRIBE.SNAPPERTURTLE =
"我见过很多你这样的！我不会原谅你伤了我的脚趾！"
DESCRIBE.SNAPPERTURTLEBABY = "小时候近乎无助。"
DESCRIBE.SNAPPERTURTLENEST = "它们似乎在这里筑巢。"
DESCRIBE.GLASS_SCALES = "哦，美丽！"
DESCRIBE.MOONGLASS_GEODE = "不太像玻璃。"
DESCRIBE.ARMOR_GLASSMAIL = "美妙！我刀枪不入！"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "跟我作对不是个好主意！"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "木头可能会给它带来烟熏味。"
DESCRIBE.SNOTROAST = "这一定是我创造过的最糟糕的菜肴。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我再也不会吃了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "这道菜真是灾难。"
DESCRIBE.BOOK_RAIN_UM = "我对雨有很多经验。"
DESCRIBE.FLORAL_BANDAGE =
"我不确定这是急救用品还是新种类的菜肴。"
DESCRIBE.DORMANT_RAIN_HORN =
"奇怪，我记得刚到这里之前见过这个。"
DESCRIBE.RAIN_HORN =
"我的记忆一定模糊了。我以为这还能做别的。"
DESCRIBE.DRIFTWOODFISHINGROD = "我想快速钓鱼应该没关系。"

ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
    LEVEL_1 = "我们的物品放在地上，谁知道什么会把它们拿走。"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
    LEVEL_1 = "看到这么多旧食物真是丢脸。"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
    LEVEL_1 = "那些卑鄙的老鼠在野外某处！"
}

DESCRIBE.PIED_RAT = "多么油腻！"
DESCRIBE.PIED_PIPER_FLUTE = "我必须要碰它吗？"
DESCRIBE.UNCOMPROMISING_PACKRAT = "别碰我的货物！"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "不要打包离开让我葬身大海！"

ACTIONFAIL.CHARGE_FROM = {
    NOT_ENOUGH_CHARGE = "没电了。",
    CHARGE_FULL = "它已经有电了！"
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED =
"那还是有点危险。"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED =
"哎哟！手指烧焦了我还怎么做饭！"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "不是为锅碗瓢盆设计的，但我可以凑合用。"
ACTIONFAIL.WINONATOOLBOX = "我想里面应该没有厨具。"
DESCRIBE.WINONA_CATAPULT_ITEM_UM = "我还是坚持用我的厨具。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM_UM = "我还是坚持用我的厨具。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM_UM = "我还是坚持用我的厨具。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM_UM = "我还是坚持用我的厨具。"
DESCRIBE.POWERCELL = "我想这是电池的食物。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL =
"我可以用电池供电的...嗯，一切。"
DESCRIBE.MINERHAT_ELECTRICAL = "这让在黑暗中做饭更容易。"
DESCRIBE.LANTERN_ELECTRICAL = "她很快就做好了这个升级，令人印象深刻！"
DESCRIBE.OCEAN_SPEAKER = "我从来就不是机器迷。"
-- DESCRIBE.UM_SIREN = "Apologies Mademoiselle Wigfrid, but it she the supperior singer!"


DESCRIBE.OCUPUS_BEAK = "最多算是个超大的碗。"
DESCRIBE.OCUPUS_TENTACLE = "有些人喜欢生吃。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "嗯，我能用这个做什么？"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "我需要一些酱油或者芥末。"
DESCRIBE.UM_OCUPUS_EYE = "我不喜欢这是什么东西。"
DESCRIBE.UM_OCUPUS_EYETACLE = "如果它看不见，野兽就会放过我们。"
DESCRIBE.UM_OCUPUS_TENTACLE = "绝对是鱿鱼。"
DESCRIBE.UM_OCUPUS_BEAK = "是你吗！？"
DESCRIBE.BEAKBASHER = "锤子？我本来想做串烧的。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "浪费了一株曼德拉草。本来可以做很好的汤。"

DESCRIBE.ARMOR_REED_UM = "我仍然能感受到微风穿过它..."
DESCRIBE.ARMOR_SHARKSUIT_UM = "鲨鱼翅汤不在菜单上！"
DESCRIBE.ROCKJAWLEATHER =
"呃...我不认为我有关于鲨鱼皮的食谱。"

DESCRIBE.EYEOFTERROR_MINI_ALLY =
"我不介意多几只...呃...眼睛来喂？"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS = "我...我想我听错了订单。"
DESCRIBE.UM_DEVILED_EGGS = "恶魔不开胃。"
DESCRIBE.LUSH_ENTRANCE = "从下面传来非常强烈的气味。"
DESCRIBE.CRITTER_FIGGY =
"你叫什么来着？菲吉，像水果一样，对吧？"
DESCRIBE.GIANT_TREE_BIRDNEST = "食物自己送上门来了！"

DESCRIBE.SLUDGE = "令人厌恶！"
DESCRIBE.SLUDGE_OIL = "它已经被煮成了基础物质。"
DESCRIBE.SLUDGE_SACK = "不适合储存食材。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM =
"这会把我瞄准的任何东西炸飞！"
DESCRIBE.BOAT_BUMPER_SLUDGE = "它很恶心，这就是为什么它能把东西赶走。"
DESCRIBE.BOAT_BUMPER_SLUDGE_KIT = "我应该把它贴在我的船上吗？"
DESCRIBE.BOATPATCH_SLUDGE = "能固定住的塞子。"
DESCRIBE.UM_COPPER_PIPE = "."
DESCRIBE.BRINE_BALM = "咸试剂的强力混合物。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "就像打开一个易碎的蛋。对吧？"
DESCRIBE.UM_BEEGUN = "我宁愿养蜂取蜜，但如果必须的话..."
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "华丽！"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER = "我听说铜很卫生。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "我听说铜很卫生。"
DESCRIBE.BOAT_BUMPER_COPPER =
"它很坚固，但不能阻止船只摇晃。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "密集防护。"
DESCRIBE.UM_DREAMCATCHER = "捕捉噩梦的网。"
DESCRIBE.UM_BRINEISHMOSS = "盐渍苔藓。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "坏思想的浓汤。"
DESCRIBE.SLUDGE_CORK = "不幸的是，不是葡萄酒的软木塞。"
DESCRIBE.SLUDGESTACK = "它散发着腐烂鸡蛋的味道！"
DESCRIBE.SPECTER_SHIPWRECK = "我希望我的船不要变成那样。"

DESCRIBE.UNCOMPROMISING_HARPOON =
"远程刺击从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它不像看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是真正的交易。"
DESCRIBE.UM_MAGNERANG = "磁铁在厨房里没有位置！"
DESCRIBE.UM_MAGNERANGREEL = ""
DESCRIBE.CORNCAN = "我以后可以用这玉米做菜！"
DESCRIBE.LAVASPIT_SLUDGE = "我更喜欢在平底锅里生火！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER =
"这让采蜂蜜变得更加复杂。"

DESCRIBE.PORTABLEBOAT_ITEM = "让我想起我做过的第一个牛排。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "要有光！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "你愿意帮我清理残羹剩饭吗？"
DESCRIBE.UM_ORNAMENT_RAT = "我的厨房里不准有害虫！"

DESCRIBE.TRINKET_WATHOM1 = "那是...那是那野兽的一块？？"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

-- WIXIE RELATED STRINGS

DESCRIBE.WIXIE_PIANO = "晚餐和演出！"
DESCRIBE.WIXIE_CLOCK = "我的舒芙蕾烘焙了多久了？"
DESCRIBE.WIXIE_WARDROBE = "麻烦正在酝酿！"
DESCRIBE.CHARLES_T_HORSE = "这匹母马很稀有！"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "充满激情的手艺！"
DESCRIBE.SLINGSHOT_MATILDA = "看起来是一场幸运的赌博。"
DESCRIBE.SLINGSHOT_GNASHER = "她咬得很厉害！"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "我希望孩子们不会误以为是糖果。"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,

    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,

    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT
}
DESCRIBE.FISHMEAT_DRIED = "柠檬片在哪里？"
DESCRIBE.SMALLFISHMEAT_DRIED = "低等级的开胃菜。"

DESCRIBE.WIXIEGUN = "保护我的砂锅菜！"
DESCRIBE.MARA_BOSS1 = "啊。"
ANNOUNCE.GAS_DAMAGE = "咳！咳！"

-- Pyre Nettle stuff
DESCRIBE.UM_PYRE_NETTLES = "嗯...也许它能为我的味觉增添香料？"
DESCRIBE.UM_SMOLDER_SPORE = "它们很有力量！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "这是一个辛辣的肉丸！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "啊！！我正在被烤！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "一些保持热度的东西..."
DESCRIBE.UM_BLOWDART_PYRE = "你不是个辣的吗？"

-- Under the Weather Part 1
DESCRIBE.ALPHA_LIGHTNINGGOAT = "一块硬肉。"
DESCRIBE.UM_TORNADO = "风暴已经酝酿好了！"
DESCRIBE.UM_WATERFALL = "咸水已经进入洞穴！"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有风暴正在酝酿。"

DESCRIBE.UM_BOAT_ENGINE = {
    ON = "嗡嗡作响！",
    LOWFUEL = "它需要补充燃料了。",
    OVERHEATING = "它正在过热！"
}

-- Broiling Hills
DESCRIBE.BOULDER_CRAB =
{
    GENERIC = "这不是石头！",
    NAKED = "我为它感到难过。",
}

DESCRIBE.BOULDER_CRAB_HOLE = "这是个洞。"

DESCRIBE.UM_HOTSPRING = "它被熔岩加热。"

DESCRIBE.UM_PLANT_HOTSPRINGS = DESCRIBE.MARSH_PLANT

DESCRIBE.ROCK_LICHEN =
{
    GENERIC = "它们喜欢湿度。",
    PICKED = "菌落会及时重新生长。",
}

-- All things Snaildrake
DESCRIBE.SNAILDRAKE_MAGMA = "它们似乎有爆炸性的性情。"
DESCRIBE.SNAILDRAKE_SLIME = DESCRIBE.SNAILDRAKE_MAGMA
DESCRIBE.SNAPALM = "我不确定拿着这个是否安全。"
DESCRIBE.SNAILDRAKEHAT = "它会弄乱我的头发。"
DESCRIBE.SNAILDRAKEBUCKET =
{
    GENERIC = "看起来可以被填满。",
    WATER = "我取了一蜗牛壳的水。",
    LAVA = "热乎乎的东西。",
}
DESCRIBE.SNAILDRAKE_HOLE = "这只是个洞。"

-- All things Rimeweed
DESCRIBE.RIMEWEED_MAIN = "那杂草造成了这种藤蔓混乱。"
DESCRIBE.RIMEWEED_BARRIER = "看起来像一个带刺的冷锋。"

DESCRIBE.UM_RIMEWEED_ITEMVINE = "它带刺且触感冰冷。"
DESCRIBE.UM_RIMEWEED_ITEMFLOWER = "它出奇地耐寒。"

DESCRIBE.RIMEWEED_WHIP = "我会站在处理的一端。"

DESCRIBE.UM_RIMEWEED_TEQUILA = "天气太冷了享受不了。"
DESCRIBE.UM_RIMEWEED_SPAGETT = "脆脆的意大利面，不是我的首选。"

-- Lava Caves
DESCRIBE.MAGMAROCK1 = DESCRIBE.ROCKS
DESCRIBE.MAGMABONE = "我想知道虫子有没有碰到它。"

DESCRIBE.UM_COOKPOT_WAGSTAFF = {
    EMPTY = "瓦格斯塔夫请写这些引语",
    COOKING_LONG = DESCRIBE.COOKPOT.COOKING_LONG,
    COOKING_SHORT = DESCRIBE.COOKPOT.COOKING_SHORT,
    DONE = DESCRIBE.COOKPOT.DONE,
    BURNT = DESCRIBE.COOKPOT.BURNT,
}
DESCRIBE.UM_COOKPOT_WAGSTAFF_DISPLAY = "嗯...多么有趣的展示。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER = "给了我尝试新食谱的另一次机会。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER2 = "这个食谱会保持这样。"

DESCRIBE.UM_RICE_PUDDING = "一道深受世界喜爱的菜肴。不过，这仍然是相当简单的做法。"

DESCRIBE.UM_BOATBOTTLE = {
    FULL = "这肯定不是安全的想法？",
    EMPTY = "好吧，看起来现在我又多了件可以携带的东西。"
}

ANNOUNCE.ANNOUNCE_BUTTERFLY_SLIP = {
    "现在现在，耐心是关键。",
    "心急吃不了热豆腐。",
    "我应该等它放松警惕。",
    "嘎！现在现在，想想黄油。这一切都值得。",
    "如果它已经降落了可能更容易击中。"
}

DESCRIBE.WATHOM_CORPSE = "他...他还在呼吸！我的天，他可能还活着！"

DESCRIBE.WATHGRITHR_SHIELD_DREADSTONE = "它比看起来轻。"
ANNOUNCE.ANNOUNCE_WEAPON_TOOWEAK_ICESHIELD = "我们的朋友可以享用一顿美餐。"