local require = GLOBAL.require

STRINGS = GLOBAL.STRINGS
GLOBAL.STRINGS.CHARACTERS.WATHOM = require "wathom_speech"
ANNOUNCE = STRINGS.CHARACTERS.WATHOM
DESCRIBE = STRINGS.CHARACTERS.WATHOM.DESCRIBE
ACTIONFAIL = STRINGS.CHARACTERS.WATHOM.ACTIONFAIL

--	[ 		Wathom Descriptions		]   --

ANNOUNCE.DREADEYE_SPOOKED = "它...醒了。正在注视我们。"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "永不真正死亡。"
ANNOUNCE.ANNOUNCE_WINONAGEN =
"古老设计,不兼容。我,愿意学习。"
ANNOUNCE.ANNOUNCE_RATRAID = "老鼠的叫声。"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "老鼠,开战!"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "补给,被洗劫!"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "甲壳,灼烧!!", "天气,有毒!蟾蜍寄生虫,大概。",
    "雨,糟糕。"
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "感染,代理!"
-- FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好好好冷冷冷。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "勇气考验,没什么新鲜!"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION =
    ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_VETCURSE = "挑战,失败。"
ANNOUNCE.ANNOUNCE_RNEFOG = "低语,阴谋。隐藏之下,警告。"
-- FoodBuffs

-- CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING =
"好,好喝,喝好好,喝咕噜...呃嗯.."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "我死了吗?"
DESCRIBE.CALIFORNIAKING = "整个存在,恳求不要。"
-- CaliforniaKing

-- Content Creators
DESCRIBE.CCTRINKET_DON = "详细历史,前任抄写员。\"Don.\""
DESCRIBE.CCTRINKET_JAZZY = "雕刻。\"J a z z y\"?"
DESCRIBE.CCTRINKET_FREDDO = "雕刻。\"F r e d d o\"?"
-- Content Creators
DESCRIBE.UNCOMPROMISING_RAT = "煽动者,麻烦。宁愿死。"
DESCRIBE.UNCOMPROMISING_RATHERD = "痕迹,啮齿动物。附近。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "物品,被盗。"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "隧道,啮齿盟友。"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "领地,有智慧的老鼠。"

DESCRIBE.WINKY = {
    GENERIC = "%s,有智慧的啮齿动物。进化不可能。",
    ATTACKER = "%s,遗忘之地。",
    MURDERER = "%s,瘟疫携带者。程序,根除。",
    REVIVER = "%s,不自然。好奇,亲属关系?",
    GHOST = "%s,死了。",
    FIRESTARTER = "问题,老鼠煽动,不断增加。"
}
DESCRIBE.WIXIE = {
    GENERIC = "问题,经常制造。",
    ATTACKER = "去别处,打架。",
    MURDERER = "准度差,弹弓无效!",
    REVIVER = "你还可以忍受。",
    GHOST = "挑战要看情况,%s。技能,宝贵。",
    FIRESTARTER = "负担,增加。"
}
DESCRIBE.WATHOM = {
    GENERIC = "%s,什么意思?造物主的替代品?",
    ATTACKER = "%s,自我破坏。",
    MURDERER = "目标,危险。%s,角色受挑战!",
    REVIVER = "对抗我们,没有更好。",
    GHOST = "不安。优越性,已证明?",
    FIRESTARTER = "%s,火焰。答案。"
}

DESCRIBE.RATPOISONBOTTLE = "生存,最聪明。"
DESCRIBE.RATPOISON = "少一个问题。"

DESCRIBE.MONSTERSMALLMEAT = "毒素,太浓缩。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "不死,更好。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "大部分毒素,排出。"

DESCRIBE.UM_MONSTEREGG = "钙质,有毛。怎么。"
DESCRIBE.UM_MONSTEREGG_COOKED = "无法分辨,浣熊毛球。"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "污染,源头!"
DESCRIBE.TOADLING = "染病。好奇,寄生虫存在?"
DESCRIBE.UNCOMPROMISING_TOAD = "寄生影响,增长。"

DESCRIBE.GASMASK = "生理限制,无效化。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.UM_SPIDERQUEENCORPSE = "分解停止。为什么?"
ANNOUNCE.ANNOUNCE_SNEEZE = "咕RRR啊-啾!"
ANNOUNCE.ANNOUNCE_HAYFEVER = "猖獗,春天的花粉。太棒了。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "感官障碍,过去。"
ANNOUNCE.ANNOUNCE_FIREFALL = { "火焰,从天而降!", "警报!上方,注意!" }
ANNOUNCE.ANNOUNCE_ROOTING = "不!"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "风,带来寒冷。"

ANNOUNCE.SHADOWTALKER = {
    "深渊,召唤。", "造物主计划。每个人都在计划。",
    "远古遗忘。时间浪费。"
}

ANNOUNCE.ANNOUNCE_OVER_EAT = {
    STUFFED = "不要再吃了...",
    OVERSTUFFED = "嗯...错误..."
}
ANNOUNCE.CURSED_ITEM_EQUIP = "呃啊!所有权,拒绝。"
DESCRIBE.VETSITEM = "被诅咒者,接受。"
DESCRIBE.SCREECHER_TRINKET = "感激,早已死去。"

DESCRIBE.UM_SAND = "微量痕迹,魔法孵化。"
DESCRIBE.UM_SANDHILL = "浓度,沙子。"
DESCRIBE.SNOWPILE = "浓度,遮蔽。"
DESCRIBE.SNOWGOGGLES = "冬眠,无关紧要。"

DESCRIBE.SNOWMONG = "霜冻,嬗变!"
DESCRIBE.SHOCKWORM = "血管,鳞片,电流!"
DESCRIBE.ZASPBERRY = "生物电,利用。"
DESCRIBE.ZASPBERRYPARFAIT = "合适食物,顶级掠食者。"
DESCRIBE.ICEBOOMERANG = "冬天本身,导电。"

DESCRIBE.MINOTAUR_BOULDER = "警报,上方!"
DESCRIBE.MINOTAUR_BOULDER_BIG =
"守卫,动量不可控。策略识别!"
DESCRIBE.BUSHCRAB = "优秀模仿者,愚者受骗。"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "好奇。另外祭坛,恢复魔法?"
DESCRIBE.TOADLINGSPAWNER = "警报。"
DESCRIBE.VETERANSHRINE = "心跳加速,兴奋!仪式,召唤!"
DESCRIBE.VET_SKULL = "存在此处。死亡,无法逃脱。"
DESCRIBE.UM_BOSS_SOUL = "两个灵魂。生命,光明。死亡,黑暗。"
DESCRIBE.UM_DARK_VESTIGES = "显现,死亡。"
DESCRIBE.UM_VOXOLOPHONE = "构造,熟悉。声音..不是。"

DESCRIBE.UM_EXHUMER = "造物主魔法,终结的开始。"
DESCRIBE.UM_WINGSUIT = "物理极限,打破。"
DESCRIBE.UM_MOONFLY_LANTERN = "月光,安全。"

DESCRIBE.WICKER_TENTACLE = "可怜的变异。"
DESCRIBE.HONEY_LOG = "天气,不愉快。"

DESCRIBE.RAT_TAIL =
"只有皮,骨头。平息,盟友担忧-疾病不太可能。"
DESCRIBE.PLAGUEMASK = "地位,奢侈。"
DESCRIBE.SALTPACK = "霜冻,工业对抗。"
DESCRIBE.SPOREPACK = "气味忽略,实用性有益。"
DESCRIBE.SPIDER_TRAPDOOR = "陷阱蜘蛛。常见,这里。"
DESCRIBE.TRAPDOOR = "狩猎场,几种生物。"
DESCRIBE.HOODEDTRAPDOOR = DESCRIBE.TRAPDOOR
DESCRIBE.SHROOM_SKIN_FRAGMENT = "本身,无用。"
DESCRIBE.AIR_CONDITIONER = "生存,征服。"



DESCRIBE.SKELETONMEAT = "肉体,人类。可食用,但有更好用途,魔法。"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "显现,阴影。性情,特别敌对。"
DESCRIBE.VAMPIREBAT = "过了青春期,存活。令人惊讶。"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "可修复,祭坛石?"
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP

-- Swampyness
DESCRIBE.RICEPLANT = "植被,沼泽水。"
DESCRIBE.RICE = "谷物,不可食用。"
DESCRIBE.RICE_COOKED = "质地,小石子。"
DESCRIBE.SEAFOODPAELLA = "疾病对抗者。"

DESCRIBE.STUMPLING = "树人,青少年。"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.BUGZAPPER = "小甲壳,导电。"
DESCRIBE.MOON_TEAR = "信息,祭坛本身?"
DESCRIBE.SHADOW_TELEPORTER = "邀请?"
DESCRIBE.POLLENMITEDEN = "虫害。"
DESCRIBE.POLLENMITES = "虫害。"
DESCRIBE.SHADOW_CROWN = "来自它们的战利品。"
DESCRIBE.UM_SHADOW_AXE = "来自它们...还是他?"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.LICELOAF = "那是食物?"
DESCRIBE.SUNGLASSES = "为什么?"
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "虫害,未知?"
DESCRIBE.MARSH_GRASS = "草。太细,太脆。"
DESCRIBE.CURSED_ANTLER = "冬之王,愤怒武器化。"
DESCRIBE.BERNIEBOX = "盒子。"
DESCRIBE.HOODED_FERN = "植被。"
DESCRIBE.HOODEDWIDOW = "顶级蛛形纲!"
DESCRIBE.GIANT_TREE = "好奇。树种,非本地。"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST

DESCRIBE.WIDOWSGRASP = "胜利者奖品,囤积者战利品。"
DESCRIBE.SILKSACK = "包含,保持物资聚集。"
DESCRIBE.SILKEN_BUNDLE = "粘性物资,不会保持食物新鲜。"

DESCRIBE.WEBBEDCREATURE = "看看里面不会有伤害,对吧?"
ANNOUNCE.WEBBEDCREATURE = "异常厚。织网者,异常大?"
DESCRIBE.SNAPDRAGON_BUDDY = "寻找食物。"
DESCRIBE.SNAPDRAGON = "物种,侵入性。"
DESCRIBE.SNAPPLANT = "植物,哺乳动物?"
DESCRIBE.WHISPERPOD = "好奇,自我孵化?"
DESCRIBE.WHISPERPOD_NORMAL_GROUND = {
    GENERIC = "种子需要。",
    GROWING = "什么都不需要,现在不需要。"
}
DESCRIBE.FRUITBAT = "性情,平静。假设,猎人,小猎物。"
DESCRIBE.PITCHERPLANT = "功能,不确定。"
DESCRIBE.APHID = "动物,不熟悉。"
DESCRIBE.NYMPH = "让我想起...蜜蜂?好奇。"
DESCRIBE.GIANT_TREE_INFESTED = "内树,虫害。渴望树汁,也许。"
DESCRIBE.GIANT_BLUEBERRY = "根切断。安全保证。"
DESCRIBE.BLUEBERRYPANCAKES = "奇怪组合,生存导向。"
DESCRIBE.DEVILSFRUITCAKE = "营养,保存在糖中。"
DESCRIBE.SIMPSALAD = "只有树叶?"
DESCRIBE.BEEFALOWINGS = "振奋精神,打败皮弗娄牛!"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "停止,什么都不!"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "僵硬,后退。"
DESCRIBE.WIDOWSHEAD = "收集战利品,不寻常。诱人,然而。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "为什么。"
DESCRIBE.SNOWCONE = "只是冰。"

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "低语,敌对!"
DESCRIBE.VIPERFRUIT = "氛围操纵,专注。"
DESCRIBE.VIPERFRUIT_LESSER = DESCRIBE.VIPERFRUIT
DESCRIBE.VIPERJAM = "恩惠,来自它们。"

DESCRIBE.BLUEBERRYPLANT = {
    READY = "悸动,有节奏。",
    FROZE = "死了,可能。",
    REGROWING = "持续抽动,根部。好奇。快速切断,完好果实?"
}

DESCRIBE.ANTIHISTAMINE = "属性,缓解疾病。"

DESCRIBE.HEATROCK_LEVEL = {
    TINY = "不活跃。",
    SMALL = "轻微保持。",
    MED = "温度,部分调节。",
    LARGE = "温度,调节。",
    HUGE = "温度,强力保持。"
}

DESCRIBE.DURABILITY_LEVEL = {
    QUARTER = "破烂,丢弃。",
    HALF = "理想,更好状态。",
    THREEQUARTER = "状态,可用。",
    FULL = "状态,完美。"
}

--ACTIONFAIL.READ.GENERIC = "魔法,惰性。"
ACTIONFAIL.GIVE.NOTNIGHT = "需要存在,祭坛的凝视。"

RECIPE_DESC = STRINGS.RECIPE_DESC

RECIPE_DESC.RAT_BURROW = "巢穴,啮齿动物。"

-- Xmas Update
DESCRIBE.MAGMAHOUND = "岩浆,活化!"
DESCRIBE.LIGHTNINGHOUND = "周围电离!"
DESCRIBE.SPOREHOUND = "瘟疫传播者。"
DESCRIBE.GLACIALHOUND = "骚扰,远程!"
DESCRIBE.RNESKELETON = "人类遗骸,活化。"
DESCRIBE.RAT_WHIP = "夜晚,行走,跟踪。"
DESCRIBE.KLAUS_AMULET = "克劳斯的诅咒。"
DESCRIBE.CRABCLAW = "宝石魔法,粗糙。"
DESCRIBE.HAT_RATMASK = "隐藏,无关紧要。"

DESCRIBE.ORANGE_VOMIT = "呕吐,故意。为什么?"
DESCRIBE.GREEN_VOMIT = "呕吐,故意。为什么?"
DESCRIBE.RED_VOMIT = "呕吐,故意。为什么?"
DESCRIBE.PINK_VOMIT = "呕吐,故意。为什么?"
DESCRIBE.YELLOW_VOMIT = "呕吐,故意。为什么?"
DESCRIBE.PURPLE_VOMIT = "呕吐,故意。为什么?"
DESCRIBE.PALE_VOMIT = "呕吐,故意。为什么?"

DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = {
    GUARD = DESCRIBE.PIGMAN.GUARD,
    WEREPIG = DESCRIBE.PIGMAN.WEREPIG
}
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH

DESCRIBE.BIGHT = "造物主的干预,后果实现。"
DESCRIBE.KNOOK = "造物主的干预,后果实现。"
DESCRIBE.ROSHIP = "造物主的干预,后果实现。"

DESCRIBE.UM_PAWN = "好奇,不熟悉。"
DESCRIBE.UM_PAWN_NIGHTMARE = "有领地意识。迟缓,反应速度。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID = DESCRIBE.CAVE_EXIT

-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "生命力,连接。"
DESCRIBE.UM_BEAR_TRAP = "警报!"
DESCRIBE.UM_BEAR_TRAP_OLD = "不孤单。猎人,狡猾。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "直截了当,有效。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "直截了当,有效。"
DESCRIBE.CORNCAN = "好奇,起源。"
DESCRIBE.SKULLCHEST_CHILD = "好奇。移动,跨位面?"

DESCRIBE.SLOBBERLOBBER = "权杖,龙!"
DESCRIBE.GORE_HORN_HAT = "冲锋,冲锋,冲锋!"
DESCRIBE.BEARGERCLAW = "腐烂,永远不会太快。"
DESCRIBE.FEATHER_FROCK = "羽毛利用。"

DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM .. "\n...破碎。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM .. "\n...破碎。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM .. "\n...破碎。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM .. "\n...破碎。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM .. "\n...破碎。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM .. "\n...破碎。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM .. "\n...破碎。"

DESCRIBE.RED_MUSHED_ROOM = "副产品,功能。"
DESCRIBE.GREEN_MUSHED_ROOM = "副产品,功能。"
DESCRIBE.BLUE_MUSHED_ROOM = "副产品,功能。"

DESCRIBE.HEAT_SCALES_ARMOR = "担忧,责任。"

-- StantonStuff
DESCRIBE.SKULLFLASK = "存在,增强!"
DESCRIBE.SKULLFLASK_EMPTY = "乐趣,最喜欢。再生。"
DESCRIBE.STANTON_SHADOW_TONIC = "气味,有毒。"
DESCRIBE.STANTON_SHADOW_TONIC2 = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "遗骸,活化。同伴情谊,寻求?"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "哈!哈!今天,死亡!"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "再来!"
-- StantonStuff

DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE

DESCRIBE.THEATERCORN = "参与令人兴奋,超过观察。"
DESCRIBE.DEERCLOPS_BARRIER = "战术,创新!"

DESCRIBE.MOONMAW_DRAGONFLY = "命运,追寻祭坛?"
DESCRIBE.MOONMAW_LAVAE = "被粉碎!"
DESCRIBE.SNAPPERTURTLE = "奇怪。"
DESCRIBE.SNAPPERTURTLEBABY = "奇怪。"
DESCRIBE.SNAPPERTURTLENEST = "巢穴,动物。"
DESCRIBE.GLASS_SCALES = "照明,令人作呕。"
DESCRIBE.MOONGLASS_GEODE = "物体,值得研究。"
DESCRIBE.ARMOR_GLASSMAIL = "现在碰我!"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "保持距离。"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "鸟,物种不确定。"
DESCRIBE.SNOTROAST = "生存..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "新陈代谢,减慢。不愉快的感觉,然而。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = "不适,停止。饥饿,回来。"
DESCRIBE.BOOK_RAIN_UM = "天气操纵。"
DESCRIBE.FLORAL_BANDAGE = "植物关系,互利。"
DESCRIBE.DORMANT_RAIN_HORN = "好奇,异国。"
DESCRIBE.RAIN_HORN = "好奇,异国。"
DESCRIBE.DRIFTWOODFISHINGROD = "盐水导向。"

ANNOUNCE.ANNOUNCE_NORATBURROWS = "附近啮齿动物,根除。"

ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
    LEVEL_1 = "刺耳声,附近刺激。补给,分类离开。"
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = { LEVEL_1 = "食物,气味吸引。" }
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
    LEVEL_1 = "附近啮齿动物,繁殖。附近巢穴?"
}

DESCRIBE.PIED_RAT = "魔法源,强制。优先!"
DESCRIBE.PIED_PIPER_FLUTE = "配件,强制。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "物品,定位!"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "价值最低!逃跑!"

ACTIONFAIL.CHARGE_FROM = {
    NOT_ENOUGH_CHARGE = "能量,不满意。",
    CHARGE_FULL = "过载,不理想。"
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "电流成功!"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "呃啊!错误!"

----UNDER THE WEATHER----

DESCRIBE.WINONA_TOOLBOX = "工具,不寻常。"
ACTIONFAIL.WINONATOOLBOX = "未训练。"
DESCRIBE.WINONA_CATAPULT_ITEM_UM = "机器,倒塌。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM_UM = "机器,倒塌。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM_UM = "机器,倒塌。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM_UM = "机器,倒塌。"
DESCRIBE.POWERCELL = "电源,电力。设计限制。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "转换,电力输入。"
DESCRIBE.MINERHAT_ELECTRICAL = "修补,操纵。"
DESCRIBE.LANTERN_ELECTRICAL = "增强,但仍然不需要。"
DESCRIBE.OCEAN_SPEAKER = "好奇,意义,目的。"

DESCRIBE.OCUPUS_BEAK = "海洋顶级掠食者?呸。"
DESCRIBE.OCUPUS_TENTACLE = "不喜欢。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "眼睛是给失败者的。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "现在勉强可以接受。"
DESCRIBE.UM_OCUPUS_EYE = "注视,捕猎。"
DESCRIBE.UM_OCUPUS_EYETACLE = "摧毁视力,释放。"
DESCRIBE.UM_OCUPUS_TENTACLE = "你马上就知道这里谁说了算。"
DESCRIBE.UM_OCUPUS_BEAK = "打乱思绪。"
DESCRIBE.BEAKBASHER = "纠正错误,持续更久。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "曼德拉草,眼睛,预警,准备。"

DESCRIBE.ARMOR_REED_UM = "奢侈。物理保护缺乏。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "海洋见鬼去。"
DESCRIBE.ROCKJAWLEATHER = "好奇,疏水性质。"

-- DESCRIBE.UM_SIREN = "科学说我们可能可以\"互相帮助\"。"
-- WHAT THE FUCK VARIANT
-- DESCRIBE.UM_SIREN = "youtube.com/watch?v=O2XY3Y7JIa0" --谁加的这个??????????????
-- 什么???????

DESCRIBE.EYEOFTERROR_MINI_ALLY = "跨维度起源。不太可能的出生地。"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS = "眼球。"
DESCRIBE.UM_DEVILED_EGGS = "资源,凑合。"
DESCRIBE.LUSH_ENTRANCE = "洞穴,未探索?好奇。"
DESCRIBE.CRITTER_FIGGY = "障碍,最小。好。"
DESCRIBE.GIANT_TREE_BIRDNEST = "位置,巢。"
ACTIONFAIL.UPGRADE.NOT_HARVESTED = "障碍。需要,清理。"

DESCRIBE.SLUDGE = "厚。嗯。"
DESCRIBE.SLUDGE_OIL = "厚。嗯。"
DESCRIBE.SLUDGE_SACK = "不愉快。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "弹药,临时。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "保护,临时。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "保护,临时。"
DESCRIBE.BOATPATCH_SLUDGE = "最后手段。"
DESCRIBE.UM_COPPER_PIPE = "有经验的陌生人。"
DESCRIBE.BRINE_BALM = "痛苦刺激,强化。"
DESCRIBE.UNCOMPROMISING_FISHINGNET = "钓鱼竿,不,无关紧要。"
DESCRIBE.UM_AMBER = "好奇,内容。"
DESCRIBE.UM_BEEGUN = "天然蜂巢,开发。"
DESCRIBE.SUNKENCHEST_ROYAL_RANDOM = "宝藏。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER = "材料,优越。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "材料,优越。"
DESCRIBE.BOAT_BUMPER_COPPER = "材料,优越。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "材料,优越。"
DESCRIBE.UM_DREAMCATCHER = "对它们,仪式恳求。"
DESCRIBE.UM_BRINEISHMOSS = ""
DESCRIBE.UM_COALESCED_NIGHTMARE = "悸动。"
DESCRIBE.SLUDGE_CORK = "不实用,船只。其他用途?"
DESCRIBE.SLUDGESTACK = "外观独特。调查,奖励?"
DESCRIBE.SPECTER_SHIPWRECK = "船,沉没。"

DESCRIBE.UNCOMPROMISING_HARPOON = "过来这里。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "给我过来!"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "海洋战斗,仍然不理想。"
DESCRIBE.UM_MAGNERANG = "食物链,智慧主导。"
DESCRIBE.UM_MAGNERANGREEL = "返回!"
DESCRIBE.LAVASPIT_SLUDGE = "芳香,燃烧。"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "优先级,零。"

DESCRIBE.PORTABLEBOAT_ITEM =
"不足,重量容量。缓解,暂时。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "发电,动能。"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "像老鼠。"
DESCRIBE.UM_ORNAMENT_RAT = "害虫。填充。"

DESCRIBE.TRINKET_WATHOM1 = "该死。"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL

-- WIXIE RELATED STRINGS

DESCRIBE.WIXIE_PIANO = "发声器,旋律。存在,原因未知。"
DESCRIBE.WIXIE_CLOCK = "简单时钟。远古人,建造了更大的。"
DESCRIBE.WIXIE_WARDROBE = "好奇。入口,目的地未知。"
DESCRIBE.CHARLES_T_HORSE = "收回。内在黑暗。"

DESCRIBE.THE_REAL_CHARLES_T_HORSE = "玩具。描绘,生物未知。"
DESCRIBE.SLINGSHOT_MATILDA = "。"
DESCRIBE.SLINGSHOT_GNASHER = ""

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = ""

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,

    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,

    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT
}
DESCRIBE.FISHMEAT_DRIED = ""
DESCRIBE.SMALLFISHMEAT_DRIED = ""

DESCRIBE.WIXIEGUN = ""

DESCRIBE.MARA_BOSS1 = "逃跑。"
ANNOUNCE.GAS_DAMAGE = "不能...呼吸...!"

-- Pyre Nettle stuff
DESCRIBE.UM_PYRE_NETTLES = "起源,上层深处...扩张?"
DESCRIBE.UM_SMOLDER_SPORE = "寻找。小心。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "决定,绝妙。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "危险,遗忘。"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "削弱猎物。削弱掠食者。好处,快速打击。有用..."
DESCRIBE.UM_BLOWDART_PYRE = "无情。有效。印象深刻..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "决定,绝妙..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "危险,遗忘"

-- Under the Weather Part 1
DESCRIBE.ALPHA_LIGHTNINGGOAT = "熟悉气息,守卫。"
DESCRIBE.UM_TORNADO = "强风,感官...混乱。"
DESCRIBE.UM_WATERFALL = "上方,损坏。外壳裂缝。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "强风,远离附近。"

DESCRIBE.UM_BOAT_ENGINE = {
    ON = "请写台词",
    LOWFUEL = "请写台词",
    OVERHEATING = "请写台词"
}

-- Broiling Hills
DESCRIBE.BOULDER_CRAB =
{
    GENERIC = "不是石头!",
    NAKED = "我为它感到难过。",
}

DESCRIBE.BOULDER_CRAB_HOLE = "一个洞。"

DESCRIBE.UM_HOTSPRING = "被岩浆加热。"

DESCRIBE.UM_PLANT_HOTSPRINGS = DESCRIBE.MARSH_PLANT --POND_ALGAE

DESCRIBE.ROCK_LICHEN =
{
    GENERIC = "它们喜欢湿度。",
    PICKED = "群落会及时重新生长。",
}

-- All things Snaildrake
DESCRIBE.SNAILDRAKE_MAGMA = "它们似乎有爆炸性脾气。"
DESCRIBE.SNAILDRAKE_SLIME = DESCRIBE.SNAILDRAKE_MAGMA
DESCRIBE.SNAPALM = "我不确定拿着这个是否安全。"
DESCRIBE.SNAILDRAKEHAT = "会弄乱我的头发。"
DESCRIBE.SNAILDRAKEBUCKET =
{
    GENERIC = "看起来可以装满。",
    WATER = "我提来了一蜗牛壳的水。",
    LAVA = "热腾腾的东西。",
}
DESCRIBE.SNAILDRAKE_HOLE = "只是一个洞。"

-- All things Rimeweed
DESCRIBE.RIMEWEED_MAIN = "那杂草正在制造这片藤蔓混乱。"
DESCRIBE.RIMEWEED_BARRIER = "看起来像一个刺痛的冷锋。"

DESCRIBE.UM_RIMEWEED_ITEMVINE = "触感刺痛而寒冷。"
DESCRIBE.UM_RIMEWEED_ITEMFLOWER = "它出奇地坚固。"

DESCRIBE.RIMEWEED_WHIP = "我会待在攻击的一端。"

DESCRIBE.UM_RIMEWEED_TEQUILA = "太冷了无法享受。"
DESCRIBE.UM_RIMEWEED_SPAGETT = "脆脆的意大利面,不是我的首选。"

-- Lava Caves
DESCRIBE.MAGMAROCK1 = DESCRIBE.ROCKS
DESCRIBE.MAGMABONE = "我想知道虫子有没有吃到它。"

DESCRIBE.UM_COOKPOT_WAGSTAFF = {
    EMPTY = "哟威格你在做什么菜",
    COOKING_LONG = DESCRIBE.COOKPOT.COOKING_LONG,
    COOKING_SHORT = DESCRIBE.COOKPOT.COOKING_SHORT,
    DONE = DESCRIBE.COOKPOT.DONE,
    BURNT = DESCRIBE.COOKPOT.BURNT,
}
DESCRIBE.UM_COOKPOT_WAGSTAFF_DISPLAY = "嗯...真是个有趣的展示。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER = "给我另一次尝试新配方的机会。"
DESCRIBE.UM_COOKPOT_WAGSTAFF_LEVER2 = "这个配方会保持这样。"

local general_scripts = require("play_generalscripts")
local fn = require("play_commonfn")

STRINGS.STAGEACTOR.WATHOM1 = {
    "增强!增强!",
    "...",
    "好吧。这肯定是暂时的。",
    "真的?我个人对这种生物分不清!",
    "哈哈哈哈哈!",
    "嘘!嘘!走开,愚蠢的鸟。",
    "好吧,这真是浪费时间。"
}

-- general_scripts.WATHOM1 = {
--     cast = { "wathom" },
--     lines = {
--         { actionfn = fn.callbirds, duration = 1.3, },
--         { roles = { "wathom" }, duration = 3, line = STRINGS.STAGEACTOR.WATHOM1[1] },
--         { roles = {"wathom"}, duration = 1.3, anim = "umrun", animtype = "hold"},
--         { actionfn = fn.findpositions,	duration = 1, line = ".", positions={["wathom"] = 3,} },
--         { actionfn = fn.findpositions,	duration = 0.7, anim = "umrun", animtype = "hold",  positions={["wathom"] = 2,} },
--         { actionfn = fn.findpositions,	duration = 0.7, anim = "umrun", animtype = "loop", positions={["wathom"] = 1,} },
--         { roles = {"wathom"}, duration = 2.069, anim = "umrun", animtype = "loop"},
--         {
--             roles = { "wathom" },
--             duration = 2.5,
--             anim = "emote_angry",
--             animtype = "loop",
--             castsound = {
--                 wathom = "wathomcustomvoice/wathomvoiceevent/bark"
--             },
--         },
--         {roles = {"BIRD2"},				duration = 1.2,		line = STRINGS.STAGEACTOR.WATHOM1[2]},
--         { roles = {"wathom"}, duration = 1, anim = "umrun"},
--         {
--             roles = { "wathom" },
--             duration = 2,
--             anim = "emote_angry",
--             --animtype = "loop",
--             castsound = {
--                 wathom = "wathomcustomvoice/wathomvoiceevent/shadowbark"
--             },
--         },
--         {
--             roles = { "wathom" },
--             duration = 2,
--             anim = "emote_angry",
--             --animtype = "loop",
--             castsound = {
--                 wathom = "wathomcustomvoice/wathomvoiceevent/shadowbark"
--             },
--         },
--         {
--             roles = { "wathom" },
--             duration = 2.3,
--             anim = "emoteXL_angry",
--             --animtype = "loop",
--             castsound = {
--                 wathom = "wathomcustomvoice/wathomvoiceevent/ampedbark"
--             },
--         },
--         {roles = {"wathom"},		duration = 2.0, anim="death2", animtype="hold", castsound = {wathom = "wathomcustomvoice/wathomvoiceevent/death_voice"},},
--         {roles = {"BIRD2"},				duration = 1.8,		line = STRINGS.STAGEACTOR.WATHOM1[3], sgparam="disappointed"},
--         {roles = {"BIRD1"},				duration = 2.6,		line = STRINGS.STAGEACTOR.WATHOM1[4], sgparam="excited"},
--         {roles = {"BIRD1","BIRD2"},		duration = 2.3,		line = STRINGS.STAGEACTOR.WATHOM1[5], sgparam="laugh"},
--         {actionfn = fn.exitbirds,		duration = 0.3, },
--         {actionfn = fn.crowdcomment,	duration = 3,		line = STRINGS.STAGEACTOR.WATHOM1[6], anim = "emote_fistshake", prefabs = {"winky"},},
--         {actionfn = fn.crowdcomment,	duration = 3,		line = STRINGS.STAGEACTOR.WATHOM1[7], anim = "emote_impatient", prefabs = {"wixie"},},
--         {roles = {"wathom"},		duration = 1.5,		anim="corpse_revive"},
--         {actionfn = fn.actorsbow,		duration = 1, },
--     }
-- }

DESCRIBE.UM_RICE_PUDDING = "然而,不。"

DESCRIBE.UM_BOATBOTTLE = {
    FULL = "微型存储,需要船。",
    EMPTY = "微型化,船。释放需要水。"
}

ANNOUNCE.ANNOUNCE_BUTTERFLY_SLIP = {"猎物本能,必须理解。",
    "出击时机,尚未到。",
    "耗尽猎物。等待它休息。",
    "无尽追逐不会成功。",
    "当前战术,不成功。耐心,需要。"}

DESCRIBE.WATHOM_CORPSE = "起来!再次起来!"

DESCRIBE.WATHGRITHR_SHIELD_DREADSTONE = "持有监狱。恢复完整性。致命高效。"
ANNOUNCE.ANNOUNCE_WEAPON_TOOWEAK_ICESHIELD = "元素克制,需要。"


