ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WICKERBOTTOM.ACTIONFAIL

--	[ 		Wickerbottom Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "哦！！这不是我所期待的......"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "我们需要身体才能让心脏发挥作用。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "亲爱的薇诺娜，有这个模型的文档吗？"
ANNOUNCE.ANNOUNCE_RATRAID = "啊，新的研究课题！"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "好吧好吧，你是不是长大了！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "噢！上一堂追踪课程的好机会！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
    "这降水含有危险的化学物质！", "需要立即寻找遮蔽物！",
    "我的皮肤正在遭受腐蚀性损害！"
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "一个巨大的担子菌！"
--FoodBuffs
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我的生存机率降低了。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好些了。"
--FoodBuffs
	
--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "越来越难以集中注意力。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "这些好处值得用视力障碍来换取吗？"
DESCRIBE.CALIFORNIAKING = "如果我患有过敏症，它会很有用。"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "这雾让我很难看清我周围的环境。"
DESCRIBE.UNCOMPROMISING_RAT = "具有盗窃癖的啮齿目生物，样本量相当大。"
DESCRIBE.UNCOMPROMISING_RATHERD = "毫无疑问是一个巨大隧道系统的入口。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "毫无疑问是一个巨大隧道系统的入口。"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "毫无疑问是一个巨大隧道系统的入口"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "毫无疑问是一个巨大隧道系统的入口"
	
DESCRIBE.WINKY =
{
    GENERIC = "你无视分类.",
    ATTACKER = "除非受到威胁或挨饿，否则老鼠通常不会具有攻击性。",
    MURDERER = "远离孩子们",
    REVIVER = "你进化得很厉害",
    GHOST = "我们越早帮助她，我们就能越早停止提问",
    FIRESTARTER = "火！这是前所未有的！",
}
DESCRIBE.WATHOM =
{
GENERIC = "相当令人印象深刻的外骨骼，%s。",
     ATTACKER = "%s 是攻击性的之一。",
     MURDERER = "顶级掠食者正在捕猎中。",
     REVIVER = "让这成为我们双方的一次学习经历，%s。",
     GHOST = "这与我的专业领域相去甚远。",
     FIRESTARTER = "别烧我的书，%s。",
}
DESCRIBE.WIXIE =
{
GENERIC = "我会将 %s 归类为'问题青年'。",
     ATTACKER = "%s 需要一个好榜样和一本好书。\n恐怕我只有后者。",
     MURDERER = "我认为 %s 无法提供帮助。",
     REVIVER = "你在进步，%s!",
     GHOST = "%s 可以使用第二次机会。",
     FIRESTARTER = "又一个萤火虫？啧啧，我寄予厚望......",
}
		
DESCRIBE.RATPOISONBOTTLE = "真菌的有毒元素已被完全激活。"
DESCRIBE.RATPOISON = "从混合物中散发出的轻微化学气味会吸引啮齿动物。"

DESCRIBE.MONSTERSMALLMEAT = "少量来源不明的肉类。"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "被轻微处理过，但仍不能完全安全地食用。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "又咸又奇怪。"

DESCRIBE.UM_MONSTEREGG = "它是未受精的。 谢天谢地。"
DESCRIBE.UM_MONSTEREGG_COOKED = "没有吐司可以节省这顿饭."

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "这种奇怪的植物会不会是污染雨的原因？"
DESCRIBE.TOADLING = "它们似乎对附近的真菌屈从了。"
	
DESCRIBE.GASMASK = "我可以缓解这可怕的过敏症。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "一只皇家蜘蛛，死后。"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿... 啾！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "闻一闻，一定是花粉热季节了。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "啊... 我终于可以呼吸了。"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"这个地方从不宁静！",
	"这种热量变得越来越不寻常。",
	"小心地面！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "我应该砍断它获得自由！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "恐怕我们马上就会遇到暴风雪了。"
ANNOUNCE.SHADOWTALKER = {
"睡眠... 睡眠...",
"休息吧...",
"我知道的太多了",
}
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "我吃饱了，谢谢。",
	OVERSTUFFED = "这么多食物不健康！",
}
DESCRIBE.UM_SAND = "沙子似乎总能进入我的书本中。"
DESCRIBE.UM_SANDHILL = "沙丘的标志性形状是由风形成的。"
DESCRIBE.SNOWPILE = "暴风雪的夜晚，总是会让人想起火边的故事。"
DESCRIBE.SNOWGOGGLES = "适合冬季阅读？ ...也许不是。"
	
DESCRIBE.SNOWMONG = "我不知道。"
DESCRIBE.SHOCKWORM = "高导电的环节生物！"
DESCRIBE.ZASPBERRY = "胡说八道，根本没有蓝色的悬钩子属植物。"
DESCRIBE.ZASPBERRYPARFAIT = "多么令人愉悦，有点刺激的法式甜点。"
DESCRIBE.ICEBOOMERANG = "一个被切断的附肢，在接触时会显著降低体温。"
DESCRIBE.MINOTAUR_BOULDER = "天呐天呐！它把整个地方都压在我们头上！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "它的大小可能对我们有利..."
DESCRIBE.SNOWBALL_THROWABLE = "一把雪，混合在一起可以投掷出去。"
DESCRIBE.VETERANSHRINE = "这当然不是最好的主意。"
DESCRIBE.RAT_TAIL = "天呐，我相信它感染了鼠疫。"
DESCRIBE.PLAGUEMASK = "一种面具，在鼠疫期间由瘟疫医生推广。"
DESCRIBE.SPIDER_TRAPDOOR = "从外形上看是一种蛛形纲栉科生物。"
DESCRIBE.TRAPDOOR = "地形中一个不起眼的土丘。"
DESCRIBE.HOODEDTRAPDOOR = "地形中一块不起眼的岩石。"
DESCRIBE.WICKER_TENTACLE = "它们似乎患有某种退化性疾病。"
DESCRIBE.HONEY_LOG = "胡说八道，这个地方完全是胡说八道！"

DESCRIBE.BUSHCRAB = "紫金牛属的甲壳类生物！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "我会充分利用它的变异特性。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "恐怕它的用途仅限于这个尺寸。"
DESCRIBE.AIR_CONDITIONER = "它过滤掉附近空气中的污染物。"
DESCRIBE.SPOREPACK = "一个蟾蜍皮制成的大袋子，它的气味难闻。"
DESCRIBE.SALTPACK = "设备将氯化钠释放到大气中。"
	
DESCRIBE.UM_SCORPION = "蝎子，它是某种沙漠分类中的物种。"
DESCRIBE.SCORPIONCARAPACE = "虽然它不应该有毒，但在这种情况下不适合食用。"
DESCRIBE.SCORPIONCARAPACECOOKED = "我相信它需要的不仅仅是明火。"
DESCRIBE.HARDSHELLTACOS = "像这样处理的蝎子味道很好。"
	
DESCRIBE.SKELETONMEAT = "哦，我的老天爷！"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "其中一个暗影以威尔逊的形式出现，它武装起来了。"
DESCRIBE.VAMPIREBAT = "这只已经成年了。"
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "月球残骸可能会成为一些小动物的完美新家。"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "这会给那些螨虫一个教训！"
--Swampyness
DESCRIBE.RICEPLANT = "那是水稻吗？"
DESCRIBE.RICE = "不烹饪的话，它有些太硬了。"
DESCRIBE.RICE_COOKED = "我可以吃，但如果有别的东西会更好。"
DESCRIBE.SEAFOODPAELLA = "这应该可以清理我的鼻腔，这样我就可以重新开始阅读了。"
DESCRIBE.LICELOAF = "简单但有效的口粮。"
	
DESCRIBE.STUMPLING = "植物群继续变得暴力起来。"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "将来可能会有一些神秘的目的。"
DESCRIBE.SHADOW_TELEPORTER = "它似乎对那颗宝石很感兴趣，也许这值得仔细看看。"
DESCRIBE.POLLENMITEDEN = "显然是群居昆虫的杰作。"
DESCRIBE.POLLENMITES = "一大群蜂螨，寄生虫的奇怪行为。"
DESCRIBE.SHADOW_CROWN = "它在佩戴者身上散发出黑暗的光环。"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.SUNGLASSES = "是时候进行一些日光阅读了。"
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "看起来食人花是盗贼啮齿动物的寄生虫，它还活着吗？"
DESCRIBE.MARSH_GRASS = "一棵不起眼的灌木。"
DESCRIBE.CURSED_ANTLER = "它作为一种武器似乎非常耐用。"
DESCRIBE.BERNIEBOX = "当我还是个孩子的时候，玩具从来没有像这样包装过。"
DESCRIBE.HOODED_FERN = "阴影是蕨类植物繁衍的完美环境。"
DESCRIBE.HOODEDWIDOW = "团结的捕食者，它似乎接近食物链的顶端。"
DESCRIBE.GIANT_TREE = "红杉科，红杉树。"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST
DESCRIBE.WIDOWSGRASP = "蛛形纲捕食者的肢体。"
DESCRIBE.WEBBEDCREATURE = "它似乎不是一个巢穴，我猜它里面有储存了什么东西。"
ANNOUNCE.WEBBEDCREATURE = "只有蜘蛛本身可以匹配这种抗拉强度。"
DESCRIBE.SNAPDRAGON_BUDDY = "这让我想起来了捕蝇草。"
DESCRIBE.SNAPDRAGON = "真正的天然畸形者！"
DESCRIBE.SNAPPLANT = "我相信它已经形成了一种共生关系。"
DESCRIBE.WHISPERPOD = "可能需要一些园艺工作。"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "也许是植物生长的宿主？",
	GROWING = "它还没有准备好收获。",
}
DESCRIBE.FRUITBAT = "它似乎与猪笼草有某种联系。"
DESCRIBE.PITCHERPLANT = "可以看到果蝠进进出出。"
DESCRIBE.APHID = "它们感染了红杉树。"
DESCRIBE.NYMPH = "它正在寻求更多的红杉。"
DESCRIBE.GIANT_TREE_INFESTED = "这棵红杉树的受损有些严重。"
DESCRIBE.GIANT_BLUEBERRY = "我希望它可以稳定一点。"
DESCRIBE.STEAMEDHAMS = "我已准备好迎接难忘的午餐。"
DESCRIBE.BLUEBERRYPANCAKES = "我相信果汁已经稳定了。"
DESCRIBE.SIMPSALAD = "它可能热量不高，但对你还是有好处的。"
DESCRIBE.BEEFALOWINGS = "不是很豪华的菜，但还是不错的。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我没那么容易被移动了。"
DESCRIBE.DEVILSFRUITCAKE = "它的浓郁味道“极其”诱人，因此得名。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "我的质量已恢复正常。"
DESCRIBE.WIDOWSHEAD = "似乎头部还在传输信息..."
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "我不相信瓜果通常是这样雕刻的，但我们确实这样做了。"
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "它似乎含有致幻胆汁。"
DESCRIBE.VIPERFRUIT = "完全消耗掉它可以掌控蛇的能力。"
DESCRIBE.VIPERJAM = "它似乎增强了原材料浆果的特性。"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "普通的蓝球菌浆果不会跳动。",
		FROZE = "普通的蓝球菌浆果也不会冻成固体。",
		REGROWING = "看来根仍然完好无损。",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "那只熊需要修理。",
    GENERIC = "这是一只泰迪熊。",
    ASHLEY_BROKEN = "那只小猫需要修理。",
    ASHLEY = "这是一只毛绒猫。",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "那只泰迪熊似乎以某种方式被激活了。",
    ASHLEY = "那个玩具似乎可以用某种方式被激活。",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "既古怪又令人迷惑。",
    ASHLEY = "既古怪又令人迷惑。",
}
	
ACTIONFAIL.READ =
{
    GENERIC = "在这种情况下我无法集中注意力！",
}
DESCRIBE.ANTIHISTAMINE = "我相信这有抗组胺药的特性。"
ANNOUNCE.CURSED_ITEM_EQUIP = "似乎有一种被诅咒的力量在这里徘徊。"
DESCRIBE.VETSITEM = "诅咒？ 没有这样的事，我会证明的！"
DESCRIBE.SCREECHER_TRINKET = "也许是异教符号？"
ACTIONFAIL.GIVE = {NOTNIGHT = "当月亮在附近时，月亮魔法视乎效果最好。"}

DESCRIBE.MAGMAHOUND = "可以吐出岩浆的猎犬。"
DESCRIBE.LIGHTNINGHOUND = "我必须小心脚下，它们给大地充上了电。"
DESCRIBE.SPOREHOUND = "我想知道蟾蜍是如何传播蘑菇的？"
DESCRIBE.GLACIALHOUND = "这一只可以喷射出冰冻的尖刺。"
DESCRIBE.RNESKELETON = "一具活的人类骨骼。"
DESCRIBE.RAT_WHIP = "用老鼠附肢制成的临时鞭子，可爱。"
DESCRIBE.KLAUS_AMULET = "我的老骨头涣然一新！"
DESCRIBE.CRABCLAW = "附近有明显的雕刻，我猜是宝石。" 
DESCRIBE.HAT_RATMASK = "增强我们鼻子的能力。" 

DESCRIBE.ORANGE_VOMIT = "令人愉悦。"
DESCRIBE.GREEN_VOMIT = "令人愉悦。"
DESCRIBE.RED_VOMIT = "令人愉悦。"
DESCRIBE.PINK_VOMIT = "令人愉悦。"
DESCRIBE.YELLOW_VOMIT = "令人愉悦。"
DESCRIBE.PURPLE_VOMIT = "令人愉悦。"
DESCRIBE.PALE_VOMIT = "令人愉悦。"
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "它还能正常工作真是个奇迹。"
DESCRIBE.KNOOK = "它们协同工作的效果出奇的好。"
DESCRIBE.ROSHIP = "它缺乏主教的火力。"
	
DESCRIBE.UM_PAWN = "要保持距离"
DESCRIBE.UM_PAWN_NIGHTMARE = "它听起来不太妙，最好远离。"
	
DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH		
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
	
DESCRIBE.UM_BEAR_TRAP = "一个普通的陷阱，我最好远离它。"
DESCRIBE.UM_BEAR_TRAP_OLD = "一个普通的陷阱，我最好远离它。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "相当巧妙，但也很残忍。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "相当巧妙，但也很残忍。"
DESCRIBE.CORNCAN = "腌制的玉米。"
DESCRIBE.SKULLCHEST_CHILD = "里面的物品逐渐变黑。"
	
DESCRIBE.ANCIENT_AMULET_RED = "灵魂？我以前从不相信这种胡言乱语..."
DESCRIBE.SLOBBERLOBBER = " 一切都在流口水，亲爱的。"
DESCRIBE.GORE_HORN_HAT = "自然的刀。"
DESCRIBE.BEARGERCLAW = "熊獾之手，专为挖掘而设计。"
DESCRIBE.FEATHER_FROCK = "这不是一件有效的衣服。"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n它的导电通路已经不可挽回地改变了。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n它的导电通路已经不可挽回地改变了。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n它的导电通路已经不可挽回地改变了。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n它的导电通路已经不可挽回地改变了。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n它的导电通路已经不可挽回地改变了。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n它的导电通路已经不可挽回地改变了。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n它的导电通路已经不可挽回地改变了。"
	
DESCRIBE.RED_MUSHED_ROOM = "也许糊状物的稠度有助于达到目的。"
DESCRIBE.GREEN_MUSHED_ROOM = "也许糊状物的稠度有助于达到目的。"
DESCRIBE.BLUE_MUSHED_ROOM = "也许糊状物的稠度有助于达到目的。"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "它让我保持警觉，但毫不在意。"
DESCRIBE.SKULLFLASK_EMPTY = "我可以看到液体慢慢回流。"
DESCRIBE.STANTON_SHADOW_TONIC = "睡着了？ 我希望如此。"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "真正的谈话对象？你好。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "我可以学习，毫不动摇。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "科学不再使我心安。"
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "我想知道包是从哪里来的。"
DESCRIBE.DEERCLOPS_BARRIER = "怪物的冰魔法熟练度似乎有所提高。"


DESCRIBE.MOONMAW_DRAGONFLY = "我不确定从哪里开始描述。"
DESCRIBE.MOONMAW_LAVAE = "我看到里面有一个胎儿，精巧的。"
DESCRIBE.SNAPPERTURTLE = "鳄龟属的鳄龟！ 对孩子们来说不安全！"
DESCRIBE.SNAPPERTURTLEBABY = "在婴儿期，它们的大嘴仍然很危险。"
DESCRIBE.SNAPPERTURTLENEST = "动物的筑巢地。"
DESCRIBE.GLASS_SCALES = "它们发出鲜明的蓝色光芒。"
DESCRIBE.MOONGLASS_GEODE = "一个月光晶体，它充满能量脉动。"
DESCRIBE.ARMOR_GLASSMAIL = "非常迷人..."
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "任何被碎片环捕获的东西都会受到严重撕裂。"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE

DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR
	
DESCRIBE.WOODPECKER = "某种啄木鸟科生物。"
DESCRIBE.SNOTROAST = "它一定充满了疫病。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我从未尝过如此恶心的东西。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN_UM = "适合下雨天。"
DESCRIBE.FLORAL_BANDAGE = "仙人掌花的药用特性与药膏搭配得很好。"
DESCRIBE.DORMANT_RAIN_HORN = "一个不起眼的海螺壳，像这里的大多数东西一样，它一定有一些隐藏的目的。"
DESCRIBE.RAIN_HORN = "有趣，我应该在 \"下雨天\" 里添加一个有关于此的条目。"
DESCRIBE.DRIFTWOODFISHINGROD = "看起来鱼对这种材料更感兴趣。"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "我不喜欢我们杂乱无章的工作空间，就像老鼠喜欢它一样。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "我们的食物状况出现了一些问题。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "那些害虫肯定在外面计划着什么。",
}

DESCRIBE.PIED_RAT = "被污秽浸透。"
DESCRIBE.PIED_PIPER_FLUTE = "我确定，其中充满了可怕的疫病。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "它们获得了情报，还是窃取了情报？"
	
ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "如果我们能上岸，我们就能取回这艘木筏！"

ACTIONFAIL.CHARGE_FROM =
{		
	NOT_ENOUGH_CHARGE = "它需要燃料源才能发挥作用。",
	CHARGE_FULL = "那根本不可能。",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "能量转换成功！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "没想到会成为管道！"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "有组织的工作场所是高效的工作场所。"
ACTIONFAIL.WINONATOOLBOX = "我自己不是勤杂工，不过我知道一两件事。"
DESCRIBE.WINONA_CATAPULT_ITEM = "我不知道它是什么，需要放在一起。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "我不知道它是什么，需要放在一起。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "我不知道它是什么，需要放在一起。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "我不知道它是什么，需要放在一起。"
DESCRIBE.POWERCELL = "一个装满电的盒子，我对这个不太熟悉。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "整体大于部分之和。"
DESCRIBE.MINERHAT_ELECTRICAL = "现在它是电动的，这将非常有用。"
DESCRIBE.OCEAN_SPEAKER = "我的天，这可不是你期望一路看到的东西。"
--DESCRIBE.UM_SIREN = "我的天，她似乎携带着一种非常善于操纵的频率。"

DESCRIBE.OCUPUS_BEAK = "大型不明头足类动物的喙。"
DESCRIBE.OCUPUS_TENTACLE = "在这种状态下它是不可食用的。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "."
DESCRIBE.OCUPUS_TENTACLE_COOKED = "现在咀嚼非常重要。"

DESCRIBE.ARMOR_REED_UM = "当捆绑得足够近时，效果出奇的好。"
DESCRIBE.ARMOR_SHARKSUIT_UM = ""
DESCRIBE.ROCKJAWLEATHER = "不幸的是，它更容易检查它是否已经死亡。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
DESCRIBE.STUFFED_PEEPER_POPPERS = "我相信我可能误读了食谱书。"
DESCRIBE.UM_DEVILED_EGGS = "恰如其名。"
DESCRIBE.LUSH_ENTRANCE = "很好奇。它闻起来很浓烈的苔藓植物。"
DESCRIBE.CRITTER_FIGGY = "这里有一个毛刺虫？还有一个……特别是圆形的。"
DESCRIBE.GIANT_TREE_BIRDNEST = "哦，天哪。除了它的妈妈我不会回来拿它的。"
	
DESCRIBE.SLUDGE = "潜在危险，但非常有用。"
DESCRIBE.SLUDGE_OIL = "杂质已被清除。"
    DESCRIBE.SLUDGE_SACK = "它将提供充足的存储空间。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "另一场激烈的事故等待发生。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "任何碎片都应该立即弹开！"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "有助于让碎片远离我的船。"
    DESCRIBE.BOATPATCH_SLUDGE = "有几个备用插头是个好主意。"
    DESCRIBE.UM_COPPER_PIPE = "我不相信铜会生长……"
    DESCRIBE.BRINE_BALM = "一种痛苦的防腐剂。"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "据推测，里面有一些古老的东西。"
DESCRIBE.UM_BEEGUN = "它是如何以如此强大的力量推动蜜蜂的？"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "一定是富有的。"
DESCRIBE.STEERINGWHEEL_COPPER = "我现在应该可以转动整个驳船了。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "机械装置允许它与方向舵一起工作。"
DESCRIBE.BOAT_BUMPER_COPPER = "它应该持续一千年。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "我们应该把它放在哪里？"
DESCRIBE.UM_DREAMCATCHER = "对我没多大用处。"
DESCRIBE.UM_BRINEISHMOSS = "它几乎到处生长。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "某人消极思想的本质。"
DESCRIBE.SLUDGE_CORK = "不适合船，它适合更大的洞。"
DESCRIBE.SLUDGESTACK = "这让人想起热液喷口。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER = "我现在应该能够转动整艘驳船了。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM =
"该机制允许它与方向舵一起工作。"
DESCRIBE.BOAT_BUMPER_COPPER = "它应该能持续一千年。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "我们应该把它放在哪里？"
DESCRIBE.UM_DREAMCATCHER = "对我来说没什么用。"
DESCRIBE.UM_BRINEISHMOSS = "它几乎到处生长。"
DESCRIBE.UM_COALECED_NIGHTMARE = "某人消极想法的本质。"
DESCRIBE.SLUDGE_CORK = "不适合船，它适合更大的洞。"
DESCRIBE.SLUDGESTACK = "这让人想起热液喷口。"
DESCRIBE.SPECTER_SHIPWRECK = "一艘废弃的沉船。"

DESCRIBE.UNCOMPROMISING_HARPOON = "远距离刺伤从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
DESCRIBE.UM_MAGNERANG = "这不是磁铁的预期用途！"
DESCRIBE.UM_MAGNERANGREEL = "我不相信磁铁是这样工作的。"
DESCRIBE.SIREN_THRONE = "很好奇。似乎有什么东西从这个阵型中安了家。"
DESCRIBE.LAVASPIT_SLUDGE = "保持距离是明智之举。"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "坚持。"

DESCRIBE.PORTABLEBOAT_ITEM = "它看起来不太稳定。"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "对动力学原理的迷人运用！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "弗吉尼亚马的优秀模型。"
DESCRIBE.UM_ORNAMENT_RAT = "小猫会喜欢的！"

DESCRIBE.TRINKET_WATHOM1 = "哦，这一定是那个有知觉的生物的亚种！"
DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "我已经很久没有弹过这些了。"
DESCRIBE.WIXIE_CLOCK = "我想念我老祖父钟的滴答声。"
DESCRIBE.WIXIE_WARDROBE = "一个普通的衣橱，乍一看。"
DESCRIBE.CHARLES_T_HORSE = "被时间遗忘的童年玩具。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "给孩子们的迷人玩具。"
DESCRIBE.SLINGSHOT_MATILDA = "她变得鲁莽了。"
DESCRIBE.SLINGSHOT_GNASHER = "我为那个小女孩担心。"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_THULECITE
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
		
DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_THULECITE

DESCRIBE.BAGOFMARBLES = "这看起来像是绊倒的危险。"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "富含钠和油。"
DESCRIBE.SMALLFISHMEAT_DRIED = "吃完饭一定要洗手。"

DESCRIBE.WIXIEGUN = "这不属于孩子的手。"

DESCRIBE.MARA_BOSS1 = "这到底是..."
ANNOUNCE.GAS_DAMAGE = "咳。咳咳。咳咳"

-- 火炭荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "野生菌株的毒性增强，似乎降低了毒素的效力。"
DESCRIBE.UM_SMOLDER_SPORE = "荨麻似乎是通过一种共生的真菌感染来传播的...... 令人着迷！"

ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "我想我是感到怀念了。"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "哦，那个小标本让我忘了！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "一种基本的天然伪装和威慑剂。"
DESCRIBE.UM_BLOWDART_PYRE = "常规和心理战的平等部分! 呃...咳咳。"

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "它是兽群的保护者。"
DESCRIBE.UM_TORNADO = "是自然现象，还是超自然的？"
DESCRIBE.UM_WATERFALL = "龙卷风似乎刺穿了一些贮水池。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "机器没有接收到龙卷风。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有龙卷风被机器接收。"