ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WOLFGANG
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WOLFGANG.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WOLFGANG.ACTIONFAIL

--	[ 		Wolfgang Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "啊哈！眼睛吓坏了沃尔夫冈！"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "心不在幽灵中。身体在哪里？"
ANNOUNCE.ANNOUNCE_WINONAGEN = "Wolfgang 是如何让盒子工作的？"
ANNOUNCE.ANNOUNCE_RATRAID = "Wolfgang 听到微小的吱吱声？"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "是大老鼠！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "不！回来！坏老鼠！坏老鼠！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"雨正在燃烧沃尔夫冈的肌肉！",
"雨正在啃咬沃尔夫冈！",
"雨正在出拳！沃尔夫冈在哪里回拳？",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "啊！蘑菇树？"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好....冷...."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "肌肉... 感觉虚弱..."
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了。"
--FoodBuffs

--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "沃尔夫冈是.... 强大的？"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "沃尔夫冈现在感觉好多了。"
DESCRIBE.CALIFORNIAKING = "沃尔夫冈会打败饮料！"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "别--别盯着沃尔夫冈了！！"
DESCRIBE.UNCOMPROMISING_RAT = "是贪婪的小毛球！"
DESCRIBE.UNCOMPROMISING_RATHERD = "圆圆的眼孔让沃尔夫冈不舒服。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "圆圆的眼孔让沃尔夫冈不舒服。"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = 
"圆圆的眼孔让沃尔夫冈不舒服"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "圆圆的眼孔让沃尔夫冈不舒服"
	
DESCRIBE.WINKY =
{
    GENERIC = "啊！更大更可怕！",
    ATTACKER = "别伤害我!",
    MURDERER = "可怕的老鼠正在伤害人！",
    REVIVER = "谢谢你！但你还是很可怕......",
    GHOST = "沃尔夫冈讨厌老鼠！沃尔夫冈讨厌鬼！",
    FIRESTARTER = "不要烧东西！",
}
DESCRIBE.WATHOM =
{
	GENERIC = "啊！%s 是可怕的怪物！",
     ATTACKER = "可怕的怪物正在伤害我们！",
     MURDERER = "%s 生气了！快跑！！",
     REVIVER = "你比我最初想的要多，%s！",
     GHOST = "啊！鬼比其他人更可怕...",
     FIRESTARTER = "可怕的怪物正在燃烧东西！",
}
DESCRIBE.WIXIE =
{
GENERIC = "哈哈！你说的很有趣，%s！",
     ATTACKER = "试图伤害 Wolfgang，小 %s？",
     MURDERER = "小女孩很可怕！",
     REVIVER = "谢谢你，有趣的小女孩！",
     GHOST = "下次吃甜菜根，对你有好处。",
     FIRESTARTER = "有趣的小女孩在烧东西！",
}
		
DESCRIBE.RATPOISONBOTTLE = "恶心的死亡汤。"
DESCRIBE.RATPOISON = "如果老鼠死了，沃尔夫冈就不必抓老鼠了！哈哈哈！"

DESCRIBE.MONSTERSMALLMEAT = "看起来很糟糕，闻起来很糟糕。很糟糕吗？"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "看起来还是不太好。沃尔夫冈去找更好的肉？"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "小块劣质肉现在是块石头了。"

DESCRIBE.UM_MONSTEREGG = "可怕的蛋."
DESCRIBE.UM_MONSTEREGG_COOKED = "Yue!恶心！"

DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "臭臭的蘑菇让雨变得刺痛！"
DESCRIBE.TOADLING = "小青蛙看起来不太对。"
	
DESCRIBE.GASMASK = "对沃尔夫冈的肺有好处。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "可怕的大蜘蛛死了！"
ANNOUNCE.ANNOUNCE_SNEEZE = "阿啾！ 原谅沃尔夫冈。"
ANNOUNCE.ANNOUNCE_HAYFEVER = "像沃尔夫冈一样强壮的过敏症。"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "哈！ 沃尔夫冈打败了过敏症！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"沃尔夫冈不喜欢可怕的尖叫声！",
	"可怕的怪物生气了！",
	"火！火！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "太硬了，沃尔夫冈不能打碎它。"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "沃尔夫冈抗风，也抗风暴！"
ANNOUNCE.SHADOWTALKER = {
"我很虚弱",
"我很害怕",
"不够强壮",
}
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "沃尔夫冈吃饱了，准备战斗！",
	OVERSTUFFED = "吃太多不利于锻炼。",
}
DESCRIBE.UM_SAND = "当沃尔夫冈握住它时，它从沃尔夫冈强壮的大手中滑落。"
DESCRIBE.UM_SANDHILL = "小而易碎的山丘。"
DESCRIBE.SNOWPILE = "寒冷对肌肉没有好处。"
DESCRIBE.SNOWGOGGLES = "帽子... 有点紧... 对沃尔夫冈而言。"
	
DESCRIBE.SNOWMONG = "雪正在反击！"
DESCRIBE.SHOCKWORM = "沃尔夫冈震惊了！"
DESCRIBE.ZASPBERRY = "闪闪发光的浆果！"
DESCRIBE.ZASPBERRYPARFAIT = "没有人能触碰强大的沃尔夫冈。"
DESCRIBE.ICEBOOMERANG = "小冰棍太冷了，手握不住。"
DESCRIBE.MINOTAUR_BOULDER = "如果没有危险，沃尔夫冈会尝试举起来！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "来吧！打碎这个！"
DESCRIBE.SNOWBALL_THROWABLE = "很有趣的游戏！"
DESCRIBE.VETERANSHRINE = "沃尔夫冈不喜欢盯着头部看！"
DESCRIBE.VET_SKULL = "骨头头很小！"
DESCRIBE.UM_BOSS_SOUL = "是强大的灵魂。"
DESCRIBE.UM_DARK_VESTIGES = "很臭。"
DESCRIBE.UM_VOXOLOPHONE = "小盒子令人毛骨悚然。"

DESCRIBE.UM_EXHUMER = "沃尔夫冈讨厌骨头。"
DESCRIBE.UM_WINGSUIT = "沃尔夫冈用力拍打翅膀，飞得很远！"
DESCRIBE.UM_MOONFLY_LANTERN = "沃尔夫冈不需要夜灯，但是晚上的灯很好？"

DESCRIBE.RAT_TAIL = "是臭臭的皮革吗？"
DESCRIBE.PLAGUEMASK = "是鸟面具。"
DESCRIBE.SPIDER_TRAPDOOR = "别吓沃尔夫冈！"
DESCRIBE.TRAPDOOR = "草丛中的小山丘。"
DESCRIBE.HOODEDTRAPDOOR = "是石头。"
DESCRIBE.WICKER_TENTACLE = "瘦小怪物生病了。"
DESCRIBE.HONEY_LOG = "毛骨悚然的长着脸的木头变成了毛骨悚然的零食木头！"

DESCRIBE.BUSHCRAB = "只是想要食物！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "祖母曾经在沃尔夫冈生病时给他做汤。"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "剥皮？噢。"
DESCRIBE.AIR_CONDITIONER = "让沃尔夫冈的肺保持强大！"
DESCRIBE.SPOREPACK = "蘑菇袋很臭。"
DESCRIBE.SALTPACK = "沃尔夫冈比雪强！"
	
DESCRIBE.UM_SCORPION = "离沃尔夫冈远点！"
DESCRIBE.SCORPIONCARAPACE = "不适合沃尔夫冈的胃！"
DESCRIBE.SCORPIONCARAPACECOOKED = "还是不适合沃尔夫冈的胃！"
DESCRIBE.HARDSHELLTACOS = "适合沃尔夫冈的胃！"
	
DESCRIBE.SKELETONMEAT = "是... 人肉...？"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "朋友，不！我是沃尔夫冈！"
DESCRIBE.VAMPIREBAT = "是更大的漂浮怪物！"
						
--Swampyness
DESCRIBE.RICEPLANT = "是植物，长有食物。"
DESCRIBE.RICE = "沃尔夫冈会把它粉碎成更小的颗粒！"
DESCRIBE.RICE_COOKED = "沃尔夫冈胃部的燃料！"
DESCRIBE.SEAFOODPAELLA = "让鼻子感觉好笑！"
DESCRIBE.LICELOAF = "无聊的食物仍然是美味的食物！"
DESCRIBE.SUNGLASSES = "呸！ 这些不合身！"
	
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "沃尔夫冈用月岩建造了新家。"
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.FIRECRACKERS
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "小棍子打小虫子。"
DESCRIBE.STUMPLING = "是木头小孩子。"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "它像沃尔夫冈一样坚强，但像孩子一样悲伤。"
DESCRIBE.SHADOW_TELEPORTER = "试试沃尔夫冈的力量！徒手撬开那颗宝石！"
DESCRIBE.POLLENMITEDEN = "沃尔夫冈把虫子砸回家！"
DESCRIBE.POLLENMITES = "小虫子！沃尔夫冈一口气杀死数百只！"
DESCRIBE.SHADOW_CROWN = "让沃尔夫冈更快！但皮肤感觉虚弱..."
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "哎呀！小毛球吓到了沃尔夫冈！"
DESCRIBE.MARSH_GRASS = "是强大的灌木丛！"
DESCRIBE.CURSED_ANTLER = "哈！棒子很强大！"
DESCRIBE.BERNIEBOX = "沃尔夫冈小时候也得到过玩具。"
DESCRIBE.HOODED_FERN = "它们和洞穴里的不一样。"
DESCRIBE.HOODEDWIDOW = "啊啊啊！ 啊啊啊啊啊哎！！"
DESCRIBE.GIANT_TREE = "最强大的树！"
DESCRIBE.WIDOWSGRASP = "怪物腿！"
DESCRIBE.WEBBEDCREATURE = "沃尔夫冈不想碰它。"
ANNOUNCE.WEBBEDCREATURE = "蜘蛛并不强大！！"
DESCRIBE.SNAPDRAGON_BUDDY = "植物需要食物才能和沃尔夫冈一样茁壮成长。"
DESCRIBE.SNAPDRAGON = "最强大的植物！"
DESCRIBE.SNAPPLANT = "漂亮的植物！"
DESCRIBE.WHISPERPOD = "沃尔夫冈使用绿拇指？"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "需要一些东西来变大变强！",
	GROWING = "它还在生长。",
}
DESCRIBE.FRUITBAT = "飞行的水果！"
DESCRIBE.PITCHERPLANT = "如果不跳过旅行日，沃尔夫冈可以到达！"
DESCRIBE.APHID = "是小虫子！"
DESCRIBE.NYMPH = "小虫子去哪儿了？"
DESCRIBE.GIANT_TREE_INFESTED = "树生病了！"
DESCRIBE.GIANT_BLUEBERRY = "强大的浆果，献给强大的沃尔夫冈。"
DESCRIBE.STEAMEDHAMS = "是令人垂涎的汉堡。"
DESCRIBE.BLUEBERRYPANCAKES = "强壮的煎饼！"
DESCRIBE.DEVILSFRUITCAKE = "蛋糕怎么可能是邪恶的呢？"
DESCRIBE.SIMPSALAD = "小沙拉！"
DESCRIBE.BEEFALOWINGS = "又大又好吃！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "沃尔夫冈太强壮了，难以被撼动！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "强壮的沃尔夫冈不会被推动！"
DESCRIBE.WIDOWSHEAD = "和臭虫接吻有助于提升视野。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "还是很可怕！"
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "蛇制造出更可怕的蛇！"
DESCRIBE.VIPERFRUIT = "蛇帮助沃尔夫冈？"
DESCRIBE.VIPERJAM = "不能泄漏。沃尔夫冈很伤心。"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "不能用肌肉冲出地面吗？",
		FROZE = "哈！沃尔夫冈要吧看到浆果的倒影！",
		REGROWING = "浆果没有消失？",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "坏得很彻底。",
    GENERIC = "真可爱！",
    ASHLEY_BROKEN = "坏得很彻底。",
    ASHLEY = "真可爱！",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "太勇敢了！",
    ASHLEY = "太勇敢了！",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "哦不！沃尔夫冈缩小了！",
    ASHLEY = "哦不！沃尔夫冈缩小了！",
}
DESCRIBE.ANTIHISTAMINE = "打喷嚏时使用有好处。"
ANNOUNCE.CURSED_ITEM_EQUIP = "沃尔夫冈越用力挤压就越痛！"
DESCRIBE.VETSITEM = "你说的话？需要更多的诅咒？"
DESCRIBE.SCREECHER_TRINKET = "啊！看起来很吓人！"
ACTIONFAIL.GIVE = {NOTNIGHT = "需要大月亮？"}

DESCRIBE.MAGMAHOUND = "啊，啊！"
DESCRIBE.LIGHTNINGHOUND = "呀，呀！"
DESCRIBE.SPOREHOUND = "呜呜呜！哎呀！"
DESCRIBE.GLACIALHOUND = "嗷！嗷嗷嗷！"
DESCRIBE.RNESKELETON = "沃--沃尔夫冈会揍你的，退后一点！"
DESCRIBE.RAT_WHIP = "鞭打！"
DESCRIBE.KLAUS_AMULET = "沃尔夫冈是世界上最强大的人！"
DESCRIBE.CRABCLAW = "小石头的小洞！" 
DESCRIBE.HAT_RATMASK = "沃尔夫冈必须独自寻找老鼠吗？" 

DESCRIBE.ORANGE_VOMIT = "是面部便便。"
DESCRIBE.GREEN_VOMIT = "是面部便便。"
DESCRIBE.RED_VOMIT = "是面部便便。"
DESCRIBE.PINK_VOMIT = "是面部便便。"
DESCRIBE.YELLOW_VOMIT = "是面部便便。"
DESCRIBE.PURPLE_VOMIT = "是面部便便。"
DESCRIBE.PALE_VOMIT = "是面部便便。"
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "垃圾正在移动！"
DESCRIBE.KNOOK = "头脑就是舌头！让沃尔夫冈发笑。"
DESCRIBE.ROSHIP = "这个吓到沃尔夫冈了。"
	
DESCRIBE.UM_PAWN = "沃尔夫冈不喜欢哔哔声。"
DESCRIBE.UM_PAWN_NIGHTMARE = "沃尔夫冈不喜欢哔哔声。"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH		
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW
	
DESCRIBE.ANCIENT_AMULET_RED = "没有灵魂的沃尔夫冈就是没有力量的沃尔夫冈。"
DESCRIBE.UM_BEAR_TRAP = "沃尔夫冈太聪明了，不会踩到陷阱！"
DESCRIBE.UM_BEAR_TRAP_OLD = "沃尔夫冈太聪明了，不会踩到陷阱！"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "大型金属牙齿，抓地力很强。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "大型金属牙齿，抓地力很强。"
DESCRIBE.CORNCAN = "玉米被困在里面，沃尔夫冈徒手救人！"
DESCRIBE.SKULLCHEST_CHILD = "沃尔夫冈不喜欢看起来像头骨的箱子。"
	
DESCRIBE.SLOBBERLOBBER = "沃尔夫冈没有不尊重的意思。"
DESCRIBE.GORE_HORN_HAT = "沃尔夫冈的脑袋现在更大了！"
DESCRIBE.BEARGERCLAW = "沃尔夫冈现在像一头大熊！"
DESCRIBE.FEATHER_FROCK = "一点也不重。"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n沃尔夫冈用力过猛，宝石坏掉了。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n沃尔夫冈用力过猛，宝石坏掉了。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n沃尔夫冈用力过猛，宝石坏掉了。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n沃尔夫冈用力过猛，宝石坏掉了。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n沃尔夫冈用力过猛，宝石坏掉了。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n沃尔夫冈用力过猛，宝石坏掉了。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n沃尔夫冈用力过猛，宝石坏掉了。"
	
DESCRIBE.RED_MUSHED_ROOM = "蘑菇不是挑战。"
DESCRIBE.GREEN_MUSHED_ROOM = "蘑菇不是挑战。"
DESCRIBE.BLUE_MUSHED_ROOM = "蘑菇不是挑战。"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "死人的饮料？"
DESCRIBE.SKULLFLASK_EMPTY = "饮料过会就回来了。"
DESCRIBE.STANTON_SHADOW_TONIC = "哈... 哈...？"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "不--不是坏人？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "头脑很强壮！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "沃尔夫冈又害怕了..."
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "记得有人吃过它... 很久以前..."
DESCRIBE.DEERCLOPS_BARRIER = "沃--沃尔夫冈没有和怪物一起被困在这里！" 

--Stuff for Canis to check
DESCRIBE.MOONMAW_DRAGONFLY = "如果龙蝇被困在月球上，我们会被困住吗？" 
DESCRIBE.MOONMAW_LAVAE = "啊！刺穿了沃尔夫冈的肌肉！"
DESCRIBE.SNAPPERTURTLE = "哈哈。真是有趣的动物。"
DESCRIBE.SNAPPERTURTLEBABY = "小动物宝宝。"
DESCRIBE.SNAPPERTURTLENEST = "是家。"
DESCRIBE.GLASS_SCALES = "是好看的光亮。"
DESCRIBE.MOONGLASS_GEODE = "是月光！"
DESCRIBE.ARMOR_GLASSMAIL = "没有人比这更强大！"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = ""
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE
	
DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "鸟的头发很漂亮。"
DESCRIBE.SNOTROAST = "这么多鼻屎！哈哈哈！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "现在全是沃尔夫冈的鼻屎！啊哈哈哈！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN_UM = "沃尔夫冈就没有比阅读关于雨的书更好的事情去做吗？"
DESCRIBE.FLORAL_BANDAGE = "非常适合对巨人发出嘘声。"
DESCRIBE.DORMANT_RAIN_HORN = "很漂亮的贝壳。"
DESCRIBE.RAIN_HORN = "吹奏贝壳会让水从天上掉下来！"
DESCRIBE.DRIFTWOODFISHINGROD = "仍然是为了小池塘准备的，只是现在看起来不一样了。"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "地上到处都是东西！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "食物必须收好，不要让老鼠看见！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "可怕的老鼠出没在森林里。",
}

DESCRIBE.PIED_RAT = "啊啊！最大的老鼠！"
DESCRIBE.PIED_PIPER_FLUTE = "至少老鼠死了。"
DESCRIBE.UNCOMPROMISING_PACKRAT = "有背包的小老鼠！"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "浮船正在下沉！"

ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "里面没有闪电。",
	CHARGE_FULL = "它不起作用，因为它已经很好了.",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "这次没有震惊到沃尔夫冈。 很好。"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "噢!电击手指！"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "Wolfgang 没有把哑铃放在那里。"
ACTIONFAIL.WINONATOOLBOX = "Wolfgang 没有把哑铃放在那里。"
DESCRIBE.WINONA_CATAPULT_ITEM = "用于提升？"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "为了提升？"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "用于提升？"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "用于提升？"
DESCRIBE.POWERCELL = "是一盒电击。"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "现在必须连接灯。"
DESCRIBE.MINERHAT_ELECTRICAL = "头灯现在是电动头灯。"
DESCRIBE.OCEAN_SPEAKER = "是演讲者！马戏团里有很多人！"
--DESCRIBE.UM_SIREN = "终于是一个值得尊敬的对手，我们的战斗将成为传奇！"

DESCRIBE.OCUPUS_BEAK = "嘴巴和沃尔夫冈一样大！"
DESCRIBE.OCUPUS_TENTACLE = "现在是软盘哈哈。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "大大的软眼哈哈！"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "有嚼劲？呸！我吃这个没问题。"

DESCRIBE.ARMOR_REED_UM = "光滑的空心管套装。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "坚如磐石！哈！"
DESCRIBE.ROCKJAWLEATHER = "非常坚韧，很难撕开！"
	
DESCRIBE.EYEOFTERROR_MINI_ALLY = DESCRIBE.EYEOFTERROR_MINI
DESCRIBE.STUFFED_PEEPER_POPPERS = "哈！小眼球觉得它还能吓到沃尔夫冈！"
DESCRIBE.UM_DEVILED_EGGS = "多毛和邪恶。"
DESCRIBE.LUSH_ENTRANCE = "真是个可怕的洞！"
DESCRIBE.CRITTER_FIGGY = "是无花果！最强大的虫子！"
DESCRIBE.GIANT_TREE_BIRDNEST = "是一把小鸡蛋！"
	
DESCRIBE.SLUDGE = "有一种非常强烈的气味。不好闻……"
DESCRIBE.SLUDGE_OIL = "气味使大脑昏昏欲睡。"
    DESCRIBE.SLUDGE_SACK = "Wolfgang 必须随身携带发臭的麻袋吗？"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "炽热的爆炸球。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "将使船保持强劲，非常好。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "黏糊糊的粘液可以保证船的安全。"
    DESCRIBE.BOATPATCH_SLUDGE = "把洞变成填充洞。"
    DESCRIBE.UM_COPPER_PIPE = "弯管没问题。"
    DESCRIBE.BRINE_BALM = "没有痛苦，没有收获。"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "有光泽的大石头。"
DESCRIBE.UM_BEEGUN = "我喜欢向他们射击我不喜欢的东西。"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "得到这个是一项艰巨的工作，感到自豪。"
DESCRIBE.STEERINGWHEEL_COPPER = "适合沃尔夫冈的强力车轮！"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "一个强大的轮子！"
DESCRIBE.BOAT_BUMPER_COPPER = "它会在损坏之前撞到很多东西。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "金属非常坚固，适合造船。"
DESCRIBE.UM_DREAMCATCHER = "用于捕捉梦境。"
DESCRIBE.UM_BRINEISHMOSS = "很无聊。"
DESCRIBE.UM_COALESCED_NIGHTMARE = "沃尔夫冈讨厌噩梦！"
DESCRIBE.SLUDGE_CORK = "插头怎么不能用于船？"
DESCRIBE.SLUDGESTACK = "污泥是从哪里来的？"
DESCRIBE.SPECTER_SHIPWRECK = "应该航行回去，这里是船只死亡的地方。"

DESCRIBE.UNCOMPROMISING_HARPOON = "投掷非常容易。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "看看这能扔多远。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
    DESCRIBE.UM_MAGNERANG = "沃尔夫冈不需要磁铁来拉东西。"
DESCRIBE.UM_MAGNERANGREEL = "它会拉东西。"
DESCRIBE.SIREN_THRONE = "是强大的王座！"
DESCRIBE.LAVASPIT_SLUDGE = "一团糟。"
	
DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "沃尔夫冈无法突破蜂墙！"

DESCRIBE.PORTABLEBOAT_ITEM = "小船很懦弱！"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "强风造出强光！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "啊！别咬！"
DESCRIBE.UM_ORNAMENT_RAT = "别让大象看见！"
	
DESCRIBE.TRINKET_WATHOM1 = "禁忌土豆。"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "被一股强大的力量砸碎了？沃尔夫冈必须找到！"
DESCRIBE.WIXIE_CLOCK = "谁坏了？"
DESCRIBE.WIXIE_WARDROBE = "靠近它会让沃尔夫冈不寒而栗。"
DESCRIBE.CHARLES_T_HORSE = "可怕的马！"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "马戏团的小马！沃尔夫冈喜欢这个！"
DESCRIBE.SLINGSHOT_MATILDA = "为什么一次重击就可以命中很多次？"
DESCRIBE.SLINGSHOT_GNASHER = "像沃尔夫冈的健身房，是吗？"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "漩涡是怎么进去的？"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "看起来像皮革，尝起来像鱼。"
DESCRIBE.SMALLFISHMEAT_DRIED = "看起来像皮革，尝起来像鱼。"

DESCRIBE.WIXIEGUN = "沃尔夫冈不喜欢这样......"

DESCRIBE.MARA_BOSS1 = "不 不 不 不!!"
ANNOUNCE.GAS_DAMAGE = "咳咳! !"

-- 荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "可怕的孩子说他们能做漂亮的枕头！"
DESCRIBE.UM_SMOLDER_SPORE = "看起来很虚弱。也许应该小心..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "嘴里不舒服！！"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "口袋不舒服！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "偶尔戳一下，但要让坏蛋远离。"
DESCRIBE.UM_BLOWDART_PYRE = "不喜欢。给人以火女孩的闪回。"

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "来! 沃尔夫冈翻转你！"
DESCRIBE.UM_TORNADO = "沃尔夫冈会把风打跑！！如果沃尔夫冈不害怕..."
DESCRIBE.UM_WATERFALL = "沃尔夫冈喜欢洗澡而不是淋浴。"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有可怕的龙卷风。"
