ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WORTOX
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WORTOX.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WORTOX.ACTIONFAIL

--	[ 		Wortox Descriptions		]	--

ANNOUNCE.DREADEYE_SPOOKED = "有人在耍花样。... "
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "开玩笑的！。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "让人类玩得开心吧。我要跑到别的地方去！"
ANNOUNCE.ANNOUNCE_RATRAID = "风笛手呼唤！最好把它都藏起来！"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "开什么玩笑！来找我吧，害虫！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "简单，太简单了！你的恶作剧很俗气！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"突袭！我需要一个棚子！",
"一转眼，水就开始燃烧了！",
"哎哟！ 哼！",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "惊喜，惊喜！多么令人兴趣的事！"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "我还有另一个诅咒？"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了。"
--FoodBuffs
	
--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "恶作剧！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "太棒了！"
DESCRIBE.CALIFORNIAKING = "我会在其他人的饮品中加一些！"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "我喜欢诱人的命运！哼！"
DESCRIBE.UNCOMPROMISING_RAT = "你不会再拿着我的长笛跑掉了吧，嗯？"
DESCRIBE.UNCOMPROMISING_RATHERD = "通往小恶作剧者巢穴的传送门。"
DESCRIBE.UNCOMPROMISING_RATBURROW = "通往小恶作剧者巢穴的传送门。"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "通往小恶作剧者巢穴的传送门."
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "通往小恶作剧者巢穴的传送门."
	
DESCRIBE.WINKY =
{
    GENERIC = "来这里找麻烦?",
    ATTACKER = "看来已经开始恶作剧了!",
    MURDERER = "玩得太过火了!",
    REVIVER = "我们两足动物需要团结在一起!",
    GHOST = "噢噢噢，你要小心点!",
    FIRESTARTER = "小心，它学会了使用火!",
}
DESCRIBE.WATHOM =
{
GENERIC = "%s 笑得很开心！",
     ATTACKER = "%s 不怀好意！",
     MURDERER = "%s 恶作剧太过火了！",
     REVIVER = "我们可能还是朋友，%s!",
     GHOST = "你和以前的一样，是不是 %s？",
     FIRESTARTER = "%s 喜欢熊熊大火！",
}
DESCRIBE.WIXIE =
{
GENERIC = "你的俏皮话不是很微妙，是吗 %s？",
     ATTACKER = "%s 诉诸了暴力！",
     MURDERER = "红衣杀手！",
     REVIVER = "Ohoho，帮助一个有需要的恶作剧者，%s？",
     GHOST = "业力叮咬，不是 %s 吗？",
     FIRESTARTER = "另一只萤火虫在我们中间！",
}
		
DESCRIBE.RATPOISONBOTTLE = "我的天呐，这真是一种死法！"
DESCRIBE.RATPOISON = "致命的浮油！这应该可以解决问题。"

DESCRIBE.MONSTERSMALLMEAT = "你真是个诡异的小恶魔！"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "无论被烹饪成什么样，都不是我的菜。"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "呼，最可怕的。"

DESCRIBE.UM_MONSTEREGG = "我不喜欢紫色的蛋."
DESCRIBE.UM_MONSTEREGG_COOKED = "更恶心了！"
 
DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "这似乎是那个恶意菌丝体的来源！"
DESCRIBE.TOADLING = "来跳吧...或者玩玩？"

DESCRIBE.GASMASK = "冻结喷嚏！"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "这具尸体一点也不幸福！"
ANNOUNCE.ANNOUNCE_SNEEZE = "啊啾！ 哼！"
ANNOUNCE.ANNOUNCE_HAYFEVER = "灰尘正在恶作剧我的鼻子！"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "它正在缓解，因为不再打喷嚏了！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"恐惧！",
	"火焰！",
	"愤怒！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "你不能压制我！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "刺骨的风吹在我的皮毛上，感觉很糟糕！"
ANNOUNCE.SHADOWTALKER = {
"我可以改变，我已经改变了",
"我仍然感到饥饿",
"就这样笑吧",
}
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "我的胃已经饱了，但我的灵魂仍然饥饿。",
	OVERSTUFFED = "我一点也不觉得饿！",
}
DESCRIBE.UM_SAND = "粗糙，使人发痒。"
DESCRIBE.UM_SANDHILL = "大粒砾石！"
DESCRIBE.SNOWPILE = "哦哦，我们可以用这个完成多大的恶作剧啊！哼！"
DESCRIBE.SNOWGOGGLES = "猫眼！"
	
DESCRIBE.SNOWMONG = "你的牙齿好大啊！"
DESCRIBE.SHOCKWORM = "这只正在发光！"
DESCRIBE.ZASPBERRY = "这会让某人大吃一惊！"
DESCRIBE.ZASPBERRYPARFAIT = "哼，我的敌人不会知道是什么击中了他们！"
DESCRIBE.ICEBOOMERANG = "他们停止了攻击，被拦住了！"
DESCRIBE.MINOTAUR_BOULDER = "它学会了一个新把戏！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "来打我！我保证这不是骗局！"
DESCRIBE.VETERANSHRINE = "如果是在你自己身上，这不是恶作剧。"
DESCRIBE.VET_SKULL = "又一个可怜的凡人结束了生命。"
DESCRIBE.UM_BOSS_SOUL = "这个特别强！"
DESCRIBE.UM_DARK_VESTIGES = "不完全是灵魂……我不确定它是什么！"
DESCRIBE.UM_VOXOLOPHONE = "你是从哪个维度跳出来的？"

DESCRIBE.UM_EXHUMER = "一支恶作剧大军就在我的手掌之中！"
DESCRIBE.UM_WINGSUIT = "飞行对我没有吸引力。"
DESCRIBE.UM_MOONFLY_LANTERN = "呼吁吁！多么绚丽的光之舞啊！"

DESCRIBE.SNOWBALL_THROWABLE = "呼吁吁！我喜欢这个游戏！"
DESCRIBE.RAT_TAIL = "毛茸茸的尾巴更好看！"
DESCRIBE.PLAGUEMASK = "乌鸦嘴。当事情黯淡时。"
DESCRIBE.SPIDER_TRAPDOOR = "这个是个卑鄙的小恶作剧者。"
DESCRIBE.TRAPDOOR = "下面有东西。" 
DESCRIBE.HOODEDTRAPDOOR = DESCRIBE.TRAPDOOR 
DESCRIBE.WICKER_TENTACLE = "它在书本位面之外活不了多久。"
DESCRIBE.HONEY_LOG = "多么令人作呕的甜食！"

DESCRIBE.BUSHCRAB = "哇哦，真是个骗子！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "臭气熏天！"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "一口的大小！"
DESCRIBE.AIR_CONDITIONER = "我可以在里面装满胡椒！哼！"
DESCRIBE.SPOREPACK = "它很粗鲁，会腐烂你的食物！"
DESCRIBE.SALTPACK = "我现在可以平静地在雪地里游玩了！"
	
DESCRIBE.UM_SCORPION = "它爬行，蠕动，然后让你入睡！"
DESCRIBE.SCORPIONCARAPACE = "这种食物甚于不符合人类的口味！"
DESCRIBE.SCORPIONCARAPACECOOKED = "薇洛这次错了，火并没有改变它。"
DESCRIBE.HARDSHELLTACOS = "这可能是人类可以接受的食物，但不是我！"

DESCRIBE.SKELETONMEAT = "我不在乎肉的味道有多好，我不喜欢人类的食物！"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "你抓不到我！你打不到我！哼！"
DESCRIBE.VAMPIREBAT = "嗯，你活得比预期的要长。"

-- Swampyness
DESCRIBE.RICEPLANT = "这只是一种植物，没有附加条件！"
DESCRIBE.RICE = "令人作呕的人类食物。"
DESCRIBE.RICE_COOKED = "仍然不是最好的。"
DESCRIBE.SEAFOODPAELLA = "它可能无法满足我的胃口，但它确实能抚慰的我的鼻子。"
DESCRIBE.LICELOAF = "我为不得不吃它的人类而感到难过。"
DESCRIBE.SUNGLASSES = "是时候享受阳光下的乐趣了！"
	
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "月岩将成为一个很棒的小庇护所！"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "来吧，只是有点刺痛！"
DESCRIBE.STUMPLING = "来吧！砍掉那些树只是个玩笑！"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "为丢失的区块哭泣是没有用的！"
DESCRIBE.SHADOW_TELEPORTER = "我觉得这是个骗局，让我们假装上当吧！"
DESCRIBE.POLLENMITEDEN = "有人在家吗？"
DESCRIBE.POLLENMITES = "讨厌的东西！"
DESCRIBE.SHADOW_CROWN = "让我们开始冒险吧！"
DESCRIBE.RNEGHOST = DESCRIBE.GHOST
DESCRIBE.TRAPDOORGRASS = DESCRIBE.GRASS
DESCRIBE.LUREPLAGUE_RAT = "带走死人。"
DESCRIBE.MARSH_GRASS = "灌木丛。"
DESCRIBE.CURSED_ANTLER = "这么大的东西很难错过！"
DESCRIBE.BERNIEBOX = 
"我很想看看里面有什么，希望她快点打开。"
DESCRIBE.HOODED_FERN = "它们并不总是长得那么大。"
DESCRIBE.HOODEDWIDOW = "灵魂守护者！"
DESCRIBE.GIANT_TREE = "它们越大... 哼！"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST
DESCRIBE.WIDOWSGRASP = "它付出了一条胳膊和一条腿的代价！哼！"
DESCRIBE.WEBBEDCREATURE = "盗窃是老套路，但它永远不会过时！"
ANNOUNCE.WEBBEDCREATURE = "它只对蜘蛛开放！"
DESCRIBE.SNAPDRAGON_BUDDY = "对花朵来说，它真是个巨人！"
DESCRIBE.SNAPDRAGON = "我有一种预感，他们是同类中的领导者。"
DESCRIBE.SNAPPLANT = "他们有一群被俘虏的观众！"
DESCRIBE.WHISPERPOD = "它的根需要一些土壤。"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "它需要以种子为食！",
	GROWING = "长大，长高，或者根本不长！",
}
DESCRIBE.FRUITBAT = "会飞的水果！我之前见过。"
DESCRIBE.PITCHERPLANT = "看呐，这是一株植物，但这次它很高！"
DESCRIBE.APHID = "它们冲向了树！"
DESCRIBE.NYMPH = "要多种树了。"
DESCRIBE.GIANT_TREE_INFESTED = "是什么让你生虫了？"
DESCRIBE.GIANT_BLUEBERRY = "我可以像水球一样使用它吗？哼"
DESCRIBE.STEAMEDHAMS = "这道菜一定是在开玩笑。"
DESCRIBE.BLUEBERRYPANCAKES = "这些煎饼已经被化掉了！"
DESCRIBE.SIMPSALAD = "我觉得人类不太喜欢这个。"
DESCRIBE.BEEFALOWINGS = "还不错，作为人类的食物。"
DESCRIBE.DEVILSFRUITCAKE = "七层蛋糕，超级好吃！"

ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我的步伐很轻，但现在我很重！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = "还是抓不住我！"
DESCRIBE.WIDOWSHEAD = " \"顶级捕食者\"， 嘘！"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "我们用西瓜做了一个南瓜灯，哈哈！"

-- Viperstuff Quotes
DESCRIBE.VIPERWORM = "一条非常擅长作假的蛇！"
DESCRIBE.VIPERFRUIT = "它很臭，但很独特！"
DESCRIBE.VIPERJAM = "我相信人类会喜欢这种味道的。"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "如果你不给它空间，它会剧烈爆炸！",
		FROZE = "终于冷静下来了。",
		REGROWING = "多么愉快的经历！",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "他看起来是个好人。",
    GENERIC = "真可惜。",
    ASHLEY_BROKEN = "她看起来是个好人。",
    ASHLEY = "真可惜。",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "先生，你知道你没有灵魂吗？",
    ASHLEY = "女士，你知道你没有灵魂吗？",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "它已经长得足够大，可以帮我们赢得很有战斗了！",
    ASHLEY = "它已经长得足够大，可以帮我们赢得很有战斗了！",
}
DESCRIBE.ANTIHISTAMINE = "保持我的鼻子干净。"
ANNOUNCE.CURSED_ITEM_EQUIP = "它烧焦了我的爪子！这是恶作剧吗？"
DESCRIBE.VETSITEM = "喔喔！它想骗我诅咒自己！ 也许我会..."
DESCRIBE.SCREECHER_TRINKET = "你来自哪个维度，朋友？"
ACTIONFAIL.GIVE = {NOTNIGHT = "等月亮出来的时候再玩吧！"}

DESCRIBE.MAGMAHOUND = "它点燃了我们的欲望！"
DESCRIBE.LIGHTNINGHOUND = "一个元素能量的施法者！"
DESCRIBE.SPOREHOUND = "即使是毒菌也想加入新的猎犬行动！"
DESCRIBE.GLACIALHOUND = "它让我变得冰冷！"
DESCRIBE.RNESKELETON = "你的灵魂回来了？！不是这样的！"
DESCRIBE.RAT_WHIP = "和小猫一样残忍！"
DESCRIBE.KLAUS_AMULET = "你有我心脏的钥匙吗？"
DESCRIBE.CRABCLAW = "魔法很有趣！哼！" 
DESCRIBE.HAT_RATMASK = "让我们期待这次颇有成效的搜索吧！哼！" 

DESCRIBE.ORANGE_VOMIT = "哼！恶心！"
DESCRIBE.GREEN_VOMIT = "哼！恶心！"
DESCRIBE.RED_VOMIT = "哼！恶心！"
DESCRIBE.PINK_VOMIT = "哼！恶心！"
DESCRIBE.YELLOW_VOMIT = "哼！恶心！"
DESCRIBE.PURPLE_VOMIT = "哼！恶心！"
DESCRIBE.PALE_VOMIT = "哼！恶心！"
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = DESCRIBE.PIGMAN.GUARD,
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}
	
DESCRIBE.BIGHT = "让它活着太残忍了！"
DESCRIBE.KNOOK = "他一跳向我，我就会被绊倒！"
DESCRIBE.ROSHIP = "这颠簸让我感到很生气。"
	
DESCRIBE.UM_PAWN = "别靠得太近，你会后悔的！"
DESCRIBE.UM_PAWN_NIGHTMARE = "别靠得太近，你会后悔的！"

DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT
	
DESCRIBE.PIGKING_PIGTORCH = DESCRIBE.PIGTORCH	
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "噢噢噢，这里有多少灵魂？我想一定不少吧！"
DESCRIBE.UM_BEAR_TRAP = "你一定是个笨蛋才会上这个当！"
DESCRIBE.UM_BEAR_TRAP_OLD = "你一定是个笨蛋才会上这个当！"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "天呐，你的牙齿好大啊！"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "天呐，你的牙齿好大啊！"
DESCRIBE.CORNCAN = "通向玉米监狱。"
DESCRIBE.SKULLCHEST_CHILD = "现在这是一件我觉得有趣的物品。"
	
DESCRIBE.SLOBBERLOBBER = "现在我可以吐出真正的火焰了！"
DESCRIBE.GORE_HORN_HAT = "我说，角越多越好！"
DESCRIBE.BEARGERCLAW = "是好运还是厄运？我只是忘记了！"
DESCRIBE.FEATHER_FROCK = "羽毛般的愚蠢！"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n它改变了形状，现在只可以在蟹钳中使用。"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n它改变了形状，现在只可以在蟹钳中使用。"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n它改变了形状，现在只可以在蟹钳中使用。"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n它改变了形状，现在只可以在蟹钳中使用。"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n它改变了形状，现在只可以在蟹钳中使用。"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n它改变了形状，现在只可以在蟹钳中使用。"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n它改变了形状，现在只可以在蟹钳中使用。"
	
DESCRIBE.RED_MUSHED_ROOM = "奇怪又粘稠，糊状又有嚼劲！"
DESCRIBE.GREEN_MUSHED_ROOM = "奇怪又粘稠，糊状又有嚼劲！"
DESCRIBE.BLUE_MUSHED_ROOM = "奇怪又粘稠，糊状又有嚼劲！"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "我仍然不确定这是否是人类的食物。"
DESCRIBE.SKULLFLASK_EMPTY = "我狼吞虎咽！"
DESCRIBE.STANTON_SHADOW_TONIC = "这是人类的食物吗？"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "你内心栖息着什么样的灵魂？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "被捉弄的人变成了恶作剧者！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "现在恶作剧者变成了被捉弄的人。"
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "为演出设计的食物！"
DESCRIBE.DEERCLOPS_BARRIER = "收容这个恶魔的愚蠢尝试。"
	

DESCRIBE.MOONMAW_DRAGONFLY = "看起来你离月亮太近了。"
DESCRIBE.MOONMAW_LAVAE = "哼！多么致命！"
DESCRIBE.SNAPPERTURTLE = "要我给你小费吗？"
DESCRIBE.SNAPPERTURTLEBABY = "靠近你妈妈，小家伙。"
DESCRIBE.SNAPPERTURTLENEST = "他们睡觉的地方，再生的地方！"
DESCRIBE.GLASS_SCALES = "多么古怪！"
DESCRIBE.MOONGLASS_GEODE = "比看起来更轻！"
DESCRIBE.ARMOR_GLASSMAIL = "哼！我能习惯这个！"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "它可能会造成刮伤或截肢！"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.ARMOR_GLASSMAIL_SHARDS
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE
DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR
	
DESCRIBE.WOODPECKER = "我不会觉得钻洞是种好的生活方式。"
DESCRIBE.SNOTROAST = "真恶心。"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "也许我疯了，吃了这么糟糕的东西。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN_UM = "哼，哼，这也很无聊！"
DESCRIBE.FLORAL_BANDAGE = "我应该用红蘑菇装满它，让你笑得开心点。"
DESCRIBE.DORMANT_RAIN_HORN = "现在，它只是一个外壳。"
DESCRIBE.RAIN_HORN = "吹一下它，就会下雨。"
DESCRIBE.DRIFTWOODFISHINGROD = "木头浸了水，现在鱼儿要上钩了。"

ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
        LEVEL_1 = "如此肮脏，我们必须让我们的基地变整洁！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "人类食物的另一个缺点，毛茸茸的小动物渴望它。",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "我明白了，一群盗贼在地平线上！",
}

DESCRIBE.PIED_RAT = "他的歌声会让随从变得强壮！"
DESCRIBE.PIED_PIPER_FLUTE = "我们也开始唱歌吧，他们会在我们的翅膀下！"
DESCRIBE.UNCOMPROMISING_PACKRAT = "他会用自己的包拿走我们所有的东西，把它夺回来！"

ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "快跑！"
	
ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "没有火花！",
	CHARGE_FULL ="不能做那个傻鹅，海豚？!",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "就是这张票！"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "麻了！"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "放置交易工具的地方。"
ACTIONFAIL.WINONATOOLBOX = "我的交易工具在另一种盒子里。"
DESCRIBE.WINONA_CATAPULT_ITEM = "这对我来说有点太复杂了。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "这对我来说有点太复杂了。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "这对我来说有点太复杂了。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "这对我来说有点太复杂了。"
DESCRIBE.POWERCELL = "令人震惊！"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "各种奇怪的电线。"
DESCRIBE.MINERHAT_ELECTRICAL = "我可以用震惊和敬畏填满它！"
DESCRIBE.OCEAN_SPEAKER = "它播放的曲调可以预示我们的厄运！" --哦，天啊，操，我倒霉了！！！！！！
--DESCRIBE.UM_SIREN = "My, is that a siren on the horizon?"

--DESCRIBE.OCUPUS_BEAK = ""
DESCRIBE.OCUPUS_TENTACLE = "你必须是个真正的傻瓜才能吃这个。"
DESCRIBE.OCUPUS_TENTACLE_EYE = "我很高兴我们现在意见一致。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = ""
DESCRIBE.UM_OCUPUS_EYE = "有东西正在寻找某个小鬼。"
DESCRIBE.UM_OCUPUS_EYETACLE = "如果它看不见，我们就会离开！"
DESCRIBE.UM_OCUPUS_TENTACLE = "它又大又湿，还想抓我！"
DESCRIBE.UM_OCUPUS_BEAK = "它现在真的想让我死。"
DESCRIBE.BEAKBASHER = "建立新的啄食顺序。"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "哇天啊，那双眼睛就像冬青树一样。"

DESCRIBE.ARMOR_REED_UM = "它会在一阵微风中分崩离析！"
DESCRIBE.ARMOR_SHARKSUIT_UM = "它让我像海洋怪胎一样圆滑。"
DESCRIBE.ROCKJAWLEATHER = "只是皮外伤。"

DESCRIBE.EYEOFTERROR_MINI_ALLY =
"看来我们的意见开始一致了！"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS = "凡人肯定不会喜欢这个。"
DESCRIBE.UM_DEVILED_EGGS = "你在哄我！"
DESCRIBE.LUSH_ENTRANCE = "天啊，嗬嗬！多么不祥的洞！"
DESCRIBE.CRITTER_FIGGY = "我们可以成为伙伴，我觉得那太理想了！"
DESCRIBE.GIANT_TREE_BIRDNEST = "鸟巢，至少有人告诉我。"

    DESCRIBE.SLUDGE = "一团粘液。"
DESCRIBE.SLUDGE_OIL = "一股腐臭的气味让我皱了皱鼻子。"
    DESCRIBE.SLUDGE_SACK = "恶心、粘稠且有点腥。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "它会让敌人化为灰烬！"
DESCRIBE.BOAT_BUMPER_SLUDGE = "有了这些污泥，我们的船就动弹不得！"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "有了这些污泥，我们的船就动弹不得！"
    DESCRIBE.BOATPATCH_SLUDGE = "当我们被击中时，用淤泥堵住它！"
    DESCRIBE.UM_COPPER_PIPE = "谁知道金属会长大。"
    DESCRIBE.BRINE_BALM = "我必须在我柔软的毛皮上涂上这种黏糊糊的咸海粘液吗？"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = DESCRIBE.FISHINGNET
DESCRIBE.UM_AMBER = "植物和虫子的监狱。"
    DESCRIBE.UM_BEEGUN = "你最好在抽签中迅速行动。"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "国王的赎金。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER = "驾驶方向盘！"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "如果我愿意，我可以驾驭世界！"
DESCRIBE.BOAT_BUMPER_COPPER = "呵呵，你不会把它炸毁的！"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "我确实说这很困难！"
DESCRIBE.UM_DREAMCATCHER = "哦，我的，哦，我的，一扇通往你思想的门！"
DESCRIBE.UM_BRINEISHMOSS = "我是这片苔藓的老大，明白吗？"
DESCRIBE.UM_COALESCED_NIGHTMARE = "潜伏在人们脑海中的是什么？"
DESCRIBE.SLUDGE_CORK = "船漏了它堵不上，太舒服了！" 
DESCRIBE.SLUDGESTACK = "看着它出污泥！" 
DESCRIBE.SPECTER_SHIPWRECK = "一个毁灭的地方，太快了。"

DESCRIBE.UNCOMPROMISING_HARPOON = "远距离刺伤从未如此简单。"
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "它没有看起来那么重。"
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "这是卷轴交易。"
DESCRIBE.UM_MAGNERANG = "它转了一圈又一圈！"
DESCRIBE.UM_MAGNERANGREEL = "让你的敌人靠近！"
DESCRIBE.SIREN_THRONE = "多么令人震惊，这是一块石头！"
DESCRIBE.LAVASPIT_SLUDGE = "来自地狱的火焰要扑灭！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "我们必须在他们的蜜蜂围栏上找到一个缺口！"

DESCRIBE.PORTABLEBOAT_ITEM = "我们需要一个微粒来帮助这艘船漂浮！"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "那些人类很聪明！"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "你喜欢把戏吗？" 
DESCRIBE.UM_ORNAMENT_RAT = "抓住他的尾巴！" 

DESCRIBE.TRINKET_WATHOM1 = "你遇到了可怕的命运，不是吗？"

DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "来一首欢快的曲子怎么样？"
DESCRIBE.WIXIE_CLOCK = "布谷！布谷！"
DESCRIBE.WIXIE_WARDROBE = "嗯？某种传送门？"
DESCRIBE.CHARLES_T_HORSE = "你有什么秘密？我等不及要知道了！"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "快跑！"
DESCRIBE.SLINGSHOT_MATILDA = "三倍乐趣！"
DESCRIBE.SLINGSHOT_GNASHER = "那是什么？惹上麻烦了？我已经惹上麻烦了！"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
		
DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "我觉得她疯了！"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "根据人类的说法，晾干会更好吃。"
DESCRIBE.SMALLFISHMEAT_DRIED = "就是不明白。"

DESCRIBE.WIXIEGUN = "恶作剧太多了！"

DESCRIBE.MARA_BOSS1 = "你曾拥有过灵魂吗？有趣的玩意"
ANNOUNCE.GAS_DAMAGE = {
"咳咳。"
}

-- 火炭荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "嗬，真是个火爆的家伙！"
DESCRIBE.UM_SMOLDER_SPORE = "你不是一个有耐心的小恐怖分子吗？"
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = "这很好."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP = "噢！！"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "这和我的皮毛不太匹配，但我可以搞点恶作剧..."
DESCRIBE.UM_BLOWDART_PYRE = "这些可以在瞬间毁掉某人的整个生活。多么愚蠢啊！"

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "我们很相像，我和你! 除去流血。"
DESCRIBE.UM_TORNADO = "Hyu-hyu，这看起来很有趣！"
DESCRIBE.UM_WATERFALL = "水已经来到我们身边了！"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有什么惊喜可以破坏！"