ANNOUNCE = GLOBAL.STRINGS.CHARACTERS.WURT
DESCRIBE = GLOBAL.STRINGS.CHARACTERS.WURT.DESCRIBE
ACTIONFAIL = GLOBAL.STRINGS.CHARACTERS.WURT.ACTIONFAIL

--	[ 		Wurt Descriptions		]	--
DESCRIBE.DEERCLOPS = "他看起来不开心，笨蛋。"

ANNOUNCE.DREADEYE_SPOOKED = "什-那是什么？"
ANNOUNCE.ANNOUNCE_HARDCORE_RES = "别进去，笨蛋。"
ANNOUNCE.ANNOUNCE_WINONAGEN = "需要这样做！"
ANNOUNCE.ANNOUNCE_RATRAID = "那是什么吱吱声？"
ANNOUNCE.ANNOUNCE_RATRAID_SPAWN = "鬼鬼祟祟的东西！"
ANNOUNCE.ANNOUNCE_RATRAID_OVER = "小坏蛋拿东西！跟着！拿！"
ANNOUNCE.ANNOUNCE_ACIDRAIN = {
"噢！燃烧的雨！",
"好痛！下雨好痛！",
"噢！这雨糟透了！",
}
ANNOUNCE.ANNOUNCE_TOADSTOOLED = "啊！蘑菇！大蘑菇！"
--FoodBuffs
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_FROZENFURY = "好...冷..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_VETCURSE = "浮-浮浪噗！！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LESSERELECTRICATTACK = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICRETALIATION = ANNOUNCE.ANNOUNCE_DETACH_BUFF_ELECTRICATTACK
ANNOUNCE.ANNOUNCE_DETACH_BUFF_FROZENFURY = "现在感觉好多了"
--FoodBuffs
	
--CaliforniaKing
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_CALIFORNIAKING = "救命，我吃了一些不能吃的东西。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_CALIFORNIAKING = "救命，我吃了一些不能吃的东西。"
DESCRIBE.CALIFORNIAKING = "这不是食物，浮浪噗，是谋杀！"
--CaliforniaKing
	
ANNOUNCE.ANNOUNCE_RNEFOG = "别看了！！"
DESCRIBE.UNCOMPROMISING_RAT = "蜘蛛人一家？有头发。"
DESCRIBE.UNCOMPROMISING_RATHERD = "洞里的小眼睛！你好！"
DESCRIBE.UNCOMPROMISING_RATBURROW = "洞里的小眼睛！你好！"
DESCRIBE.UNCOMPROMISING_WINKYBURROW = "洞里的小眼睛！你好！"
DESCRIBE.UNCOMPROMISING_WINKYHOMEBURROW = "洞里的小眼睛！你好！"
	
DESCRIBE.WINKY =
{
    GENERIC = "毛茸茸的吱吱声是很好的吱吱声！",
    ATTACKER = "吱吱声不好听！",
    MURDERER = "发出了一声惨叫！",
    REVIVER = "吱吱是人鱼的朋友！",
    GHOST = "如果帮助吱吱，那么吱吱是朋友？",
    FIRESTARTER = "别烧，吱吱！",
}
DESCRIBE.WATHOM =
{
GENERIC = "牙齿看起来很眼熟......",
     ATTACKER = "为什么要伤害我？我们太相似了！",
     MURDERER = "%s 是杀手！快跑！",
     REVIVER = "我们现在是朋友了，%s?",
     GHOST = "奇怪的漂浮物，%s 看起来很糟糕！",
     FIRESTARTER = "%s 像火一样红！",
}
DESCRIBE.WIXIE =
{
GENERIC = "Glurph...我不明白你说的话，%s！",
     ATTACKER = "%s 很卑鄙，走开！",
     MURDERER = "'桶里的鱼'是什么意思？我问 wicker-lady...",
     REVIVER = "Ohoho，帮助一个有需要的恶作剧者，%s？",
     GHOST = "哦？%s 是正常的漂浮物吗？我还以为是怪物...",
     FIRESTARTER = "别再燃烧了，%s！",
}
		
DESCRIBE.RATPOISONBOTTLE = "蔬菜，但味道真的很差。"
DESCRIBE.RATPOISON = "撒出来了！反正也不好。"

DESCRIBE.MONSTERSMALLMEAT = "不，不好。蜘蛛人留下的？"
DESCRIBE.COOKEDMONSTERSMALLMEAT = "浮浪噗！ 闻起来太糟糕了！"
DESCRIBE.MONSTERSMALLMEAT_DRIED = "现在更糟了！浮浪噗！"

DESCRIBE.UM_MONSTEREGG = "不错！我喜欢它."
DESCRIBE.UM_MONSTEREGG_COOKED = "不...怎么更糟糕了..."
 
DESCRIBE.MUSHROOMSPROUT_OVERWORLD = "蘑菇？蘑菇疯了！"
DESCRIBE.TOADLING = "蔬菜？...青蛙？ 不确定能不能吃。"
	
DESCRIBE.GASMASK = "难闻，难闻。"
DESCRIBE.MOCK_DRAGONFLY = DESCRIBE.DRAGONFLY
DESCRIBE.MOTHERGOOSE = DESCRIBE.MOOSE
DESCRIBE.SPIDERQUEENCORPSE = "喜欢这个气味！"
ANNOUNCE.ANNOUNCE_SNEEZE = "啊啾！ 嗝。"
ANNOUNCE.ANNOUNCE_HAYFEVER = "鼻子的感觉很有趣！"
ANNOUNCE.ANNOUNCE_HAYFEVER_OFF = "鼻子感觉又好了！"
ANNOUNCE.ANNOUNCE_FIREFALL = {
	"浮浪噗, 太可怕了！",
	"大蚂蚁生气了！",
	"地面着火了！浮浪噗！",
}
ANNOUNCE.ANNOUNCE_ROOTING = "卡住了！"
ANNOUNCE.ANNOUNCE_SNOWSTORM = "Brr... 冷风，我认为暴风雪要来了。"
ANNOUNCE.SHADOWTALKER = {
"无鳞生物相信我吗？",
"从哪里... 来...",
"为什么... 我的角呢？ 是... 鱼人？",
}
ANNOUNCE.ANNOUNCE_OVER_EAT =
{
	STUFFED = "肚子疼！别再吃了！",
	OVERSTUFFED = "浮浪噗, 肚子饱了！",
}
	
DESCRIBE.UM_SAND = "颗粒状的东西。"
DESCRIBE.UM_SANDHILL = "鳞片发痒..."
DESCRIBE.SNOWPILE = "好玩！ Brr..."
DESCRIBE.SNOWGOGGLES = "傻傻的眼睛长在傻傻的帽子上！"
	
DESCRIBE.SNOWMONG = "不好玩！！！"
DESCRIBE.SHOCKWORM = "火花虫！！"
DESCRIBE.ZASPBERRY = "带电的--浆果？"
DESCRIBE.ZASPBERRYPARFAIT = "痒痒的肚子。"
DESCRIBE.ICEBOOMERANG = "真好玩，浮浪噗。"
DESCRIBE.MINOTAUR_BOULDER = "啊哈！危险！"
DESCRIBE.MINOTAUR_BOULDER_BIG = "会伤到脾气暴躁的东西的头！"
SNOWBALL_THROWABLE = "你为什么向我们扔东西？！"
DESCRIBE.VETERANSHRINE = "我讨厌它，浮浪噗！"
DESCRIBE.VET_SKULL = "噢，死人？"
DESCRIBE.UM_BOSS_SOUL = "坏灵魂……"
DESCRIBE.UM_DARK_VESTIGES = "谁是人？"
DESCRIBE.UM_VOXOLOPHONE = "金属盒子在和我们说话吗？"

DESCRIBE.UM_EXHUMER = "咕噜！可怕的铲子……"
DESCRIBE.UM_WINGSUIT = "现在有鳞的人像鸟人了！"
DESCRIBE.UM_MOONFLY_LANTERN = "噢，闪闪发光！"

DESCRIBE.RAT_TAIL = "擦在脸上感觉很好，扑通扑通！"
DESCRIBE.PLAGUEMASK = "如果看起来像这样，也许小鸟不会飞走？"
DESCRIBE.SPIDER_TRAPDOOR = "咕噜咕噜！蜘蛛人现在也制造陷阱了？！"
DESCRIBE.TRAPDOOR ="应该寻找什么……？什么也没看到！"
DESCRIBE.HOODEDTRAPDOOR = DESCRIBE.TRAPDOOR
DESCRIBE.WICKER_TENTACLE = "天哪！柳条女士让沼泽看起来能帮忙！"
DESCRIBE.HONEY_LOG = "你确定这样可以吗？"

DESCRIBE.BUSHCRAB = "螃蟹！"
DESCRIBE.LAVAE2 = DESCRIBE.LAVAE
DESCRIBE.DISEASECUREBOMB = "植物立刻拿来制作零食！"
DESCRIBE.SHROOM_SKIN_FRAGMENT = "闻起来像我！"
DESCRIBE.AIR_CONDITIONER = "闻起来怪怪的，浮浪噗。"
DESCRIBE.SPOREPACK = "闻起来像家！"
DESCRIBE.SALTPACK = "眼睛受伤了！"
	
DESCRIBE.SCORPION = "看起来像蜘蛛人？"
DESCRIBE.SCORPIONCARAPACE = "糟糕！ 比肉还糟糕！"
DESCRIBE.SCORPIONCARAPACECOOKED = "快把它扔掉！"
DESCRIBE.HARDSHELLTACOS = "把那东西拿走！"
	
DESCRIBE.SKELETONMEAT = "什么问题？"
DESCRIBE.CHIMP = DESCRIBE.MONKEY
DESCRIBE.SWILSON = "浮浪噗！ 无鳞生物背叛了！"
DESCRIBE.VAMPIREBAT = "更大！Grrr！"
									
--Swampyness
DESCRIBE.RICEPLANT = "一株浸湿的沼泽植物。"
DESCRIBE.RICE = "最好打湿。"
DESCRIBE.RICE_COOKED = "好吃！浮浪噗。"
DESCRIBE.SEAFOODPAELLA = "为什么..."
DESCRIBE.LICELOAF = "可以使用更多口味，浮浪噗。"
DESCRIBE.SUNGLASSES = "浮浪噗！为什么不适合？！"
	
DESCRIBE.CRITTERLAB_REAL = DESCRIBE.CRITTERLAB
DESCRIBE.CRITTERLAB_REAL_BROKEN = "月岩为小东西创造了新家。"
DESCRIBE.WALRUS_CAMP_SUMMER = DESCRIBE.WALRUS_CAMP
DESCRIBE.CHARLIEPHONOGRAPH_100 = DESCRIBE.MAXWELLPHONOGRAPH
DESCRIBE.BUGZAPPER = "用棍子打虫子，浮浪噗。"
DESCRIBE.STUMPLING = "以前从来没见过。"
DESCRIBE.BIRCHLING = DESCRIBE.STUMPLING
DESCRIBE.MOON_TEAR = "不是快乐的潮湿，而是悲伤的潮湿..."
DESCRIBE.SHADOW_TELEPORTER = "宝藏在它的爪子里！"
DESCRIBE.POLLENMITEDEN = "浮浪噗... 很可怕。"
DESCRIBE.POLLENMITES = "浮浪噗！让人发痒的飞行生物..."
DESCRIBE.SHADOW_CROWN = "让身体和头部更痛..."
DESCRIBE.RNEGHOST = "幽灵可能是冷的，但不能有火！"
DESCRIBE.TRAPDOORGRASS = "大草。"
DESCRIBE.LUREPLAGUE_RAT = "很明显不是蜘蛛人！"
DESCRIBE.MARSH_GRASS = "鱼？"
DESCRIBE.CURSED_ANTLER = "格浪噗，真的很重..."
DESCRIBE.BERNIEBOX = "有趣的盒子... 里面有什么？"
DESCRIBE.HOODED_FERN = "味道还可以。"
DESCRIBE.HOODEDWIDOW = "浮-浮浪噗！！ 我比一口还小！"
DESCRIBE.GIANT_TREE = "唔, 大树！"
DESCRIBE.ANCIENTHOODEDTURF = DESCRIBE.TURF_FOREST
DESCRIBE.HOODEDMOSS = DESCRIBE.TURF_FOREST
DESCRIBE.WIDOWSGRASP = "抓住了它的爪子！"
DESCRIBE.WEBBEDCREATURE = "属于蜘蛛族，弗洛普。"
ANNOUNCE.WEBBEDCREATURE = "无法破解！浮浪噗！蜘蛛人如何破解？"
DESCRIBE.SNAPDRAGON_BUDDY = "植物想吃更多植物吗？"
DESCRIBE.SNAPDRAGON ="看起来很友好，弗洛普。"
DESCRIBE.SNAPPLANT ="大植物喜欢那朵丑陋的花。"
DESCRIBE.WHISPERPOD = "想要土壤？"
DESCRIBE.WHISPERPOD_NORMAL_GROUND =
{
	GENERIC = "需要种子来生长吗？",
	GROWING = "准备好了吗？浮浪噗",
}
DESCRIBE.FRUITBAT = "看起来很好吃，浮浪噗。"
DESCRIBE.PITCHERPLANT = "无法到达。"
DESCRIBE.APHID = "虫子，浮浪噗。"
DESCRIBE.NYMPH = "你想去哪？"
DESCRIBE.GIANT_TREE_INFESTED = "虫子吃大树。"
DESCRIBE.GIANT_BLUEBERRY = "好吃！"
DESCRIBE.STEAMEDHAMS = "汉堡？恶心！"
DESCRIBE.DEVILSFRUITCAKE = "里面有一个多汁的袋子！"
DESCRIBE.BLUEBERRYPANCAKES = "松软多汁！"
DESCRIBE.SIMPSALAD = "至少比肉好，浮浪噗。"
DESCRIBE.BEEFALOWINGS = "可怜的皮弗罗牛..."
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_KNOCKBACKIMMUNE = "我无法获得这个收益，谁来帮帮我，我不应该有这个收益，哦天呐。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_KNOCKBACKIMMUNE = ":Waldo:"
DESCRIBE.WIDOWSHEAD = "大头。"
DESCRIBE.HOODED_MUSHTREE_TALL = DESCRIBE.MUSHTREE_TALL
DESCRIBE.HOODED_MUSHTREE_MEDIUM = DESCRIBE.MUSHTREE_MEDIUM
DESCRIBE.HOODED_MUSHTREE_SMALL = DESCRIBE.MUSHTREE_SMALL
DESCRIBE.WATERMELON_LANTERN = "好看的西瓜脸。"
	
	--Viperstuff Quotes
DESCRIBE.VIPERWORM = "蛇！！！"
DESCRIBE.VIPERFRUIT = "吃起来安全吗？"
DESCRIBE.VIPERJAM = "很难打开！"
	
	
DESCRIBE.BLUEBERRYPLANT =         
	{
    READY = "看起来很好吃！虽然很难挖掘...",
		FROZE = "看起来很冷",
		REGROWING = "巨大的爆炸声很吓人，浮浪噗！",
	}
DESCRIBE.BERNIE_INACTIVE =
{
    BROKEN = "哇...",
    GENERIC = "不玩了吗？",
    ASHLEY_BROKEN = "哇...",
    ASHLEY = "不玩了吗？",
}
	
DESCRIBE.BERNIE_ACTIVE =
{
    GENERIC = "想跟它玩！",
    ASHLEY = "想跟它玩！",
}
DESCRIBE.BERNIE_BIG =
{
    GENERIC = "好玩的玩具，浮浪噗！",
    ASHLEY = "好玩的玩具, 浮浪噗！",
}
DESCRIBE.ANTIHISTAMINE = "保持鼻子强壮！"
ANNOUNCE.CURSED_ITEM_EQUIP = "浮浪噗！痛！"
DESCRIBE.VETSITEM = "想要我诅咒？！...不是那种诅咒？"
DESCRIBE.SCREECHER_TRINKET = "格浪噗，吓人！"
ACTIONFAIL.GIVE = {NOTNIGHT = "它睡着了吗？ 也许会在晚上醒来。"}

DESCRIBE.MAGMAHOUND = "浮浪浮！快跑！"
DESCRIBE.LIGHTNINGHOUND = "闪电很痛！！"
DESCRIBE.SPOREHOUND = "生病的狗。"
DESCRIBE.GLACIALHOUND = "大冷狗。"
DESCRIBE.RNESKELETON = "它还没死！！"
DESCRIBE.RAT_WHIP = "玩起来很有趣！ ... 哎哟！"
DESCRIBE.KLAUS_AMULET = "冷！ Brr!"
DESCRIBE.CRABCLAW = "很大, 很痛！" 
DESCRIBE.HAT_RATMASK = "这么多气味！！" 

DESCRIBE.ORANGE_VOMIT = "浮浪噗..."
DESCRIBE.GREEN_VOMIT = "浮浪噗..."
DESCRIBE.RED_VOMIT = "浮浪噗..."
DESCRIBE.PINK_VOMIT = "浮浪噗..."
DESCRIBE.YELLOW_VOMIT = "浮浪噗..."
DESCRIBE.PURPLE_VOMIT = "浮浪噗..."
DESCRIBE.PALE_VOMIT = "浮浪噗..."
	
DESCRIBE.WALRUS_CAMP_EMPTY = DESCRIBE.WALRUS_CAMP.EMPTY
DESCRIBE.PIGKING_PIGGUARD = 
{
GUARD = "Pigfolk 窃取了皇家守卫的想法！不公平！！",
WEREPIG = DESCRIBE.PIGMAN.WEREPIG,
}

DESCRIBE.BIGHT = "格嘞噗！ 还不够坏！"
DESCRIBE.KNOOK = "跳跃的金属人真可怕！"
DESCRIBE.ROSHIP = "鳞片和电击不能很好地混合！"
	
DESCRIBE.UM_PAWN = "不喜欢金属人的鼻子。"
DESCRIBE.UM_PAWN_NIGHTMARE = "不喜欢金属人的鼻子。"
	
DESCRIBE.CAVE_ENTRANCE_SUNKDECID = DESCRIBE.CAVE_ENTRANCE
DESCRIBE.CAVE_ENTRANCE_OPEN_SUNKDECID = DESCRIBE.CAVE_ENTRANCE_OPEN
DESCRIBE.CAVE_EXIT_SUNKDECID= DESCRIBE.CAVE_EXIT

DESCRIBE.PIGKING_PIGTORCH = "要让更好的火棍围绕更好的国王！"
-- Blowgun stuff
DESCRIBE.UNCOMPROMISING_BLOWGUN = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_TOOTH = DESCRIBE.BLOWDART_PIPE
DESCRIBE.BLOWGUNAMMO_FIRE = DESCRIBE.BLOWDART_FIRE
DESCRIBE.BLOWGUNAMMO_SLEEP = DESCRIBE.BLOWDART_SLEEP
DESCRIBE.BLOWGUNAMMO_ELECTRIC = DESCRIBE.BLOWDART_YELLOW

DESCRIBE.ANCIENT_AMULET_RED = "为什么魔法的石头有灵魂？"
DESCRIBE.UM_BEAR_TRAP = "冰屋里的人有恶意。"
DESCRIBE.UM_BEAR_TRAP_OLD = "冰屋里的人有恶意。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "骂骂咧咧的陷阱。"
DESCRIBE.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "骂骂咧咧的陷阱。"
DESCRIBE.CORNCAN = "从哪里来的？猪人？"
DESCRIBE.SKULLCHEST_CHILD = "装东西的盒子，但很奇怪。"
	
DESCRIBE.SLOBBERLOBBER = "很热，伯嘞浮。"
DESCRIBE.GORE_HORN_HAT = "格嘞噗, 很嫉妒..."
DESCRIBE.BEARGERCLAW = "熊爪，獾爪！"
DESCRIBE.FEATHER_FROCK = "羽毛很恶心，鳞片更好！"
	
DESCRIBE.REDGEM_CRACKED = DESCRIBE.REDGEM.."\n不同的宝石？"
DESCRIBE.BLUEGEM_CRACKED = DESCRIBE.BLUEGEM.."\n不同的宝石？"
DESCRIBE.ORANGEGEM_CRACKED = DESCRIBE.ORANGEGEM.."\n不同的宝石？"
DESCRIBE.GREENGEM_CRACKED = DESCRIBE.GREENGEM.."\n不同的宝石？"
DESCRIBE.YELLOWGEM_CRACKED = DESCRIBE.YELLOWGEM.."\n不同的宝石？"
DESCRIBE.PURPLEGEM_CRACKED = DESCRIBE.PURPLEGEM.."\n不同的宝石？"
DESCRIBE.OPALPRECIOUSGEM_CRACKED = DESCRIBE.OPALPRECIOUSGEM.."\n不同的宝石？"
	
DESCRIBE.RED_MUSHED_ROOM = "我把它压扁了。"
DESCRIBE.GREEN_MUSHED_ROOM = "我把它压扁了。"
DESCRIBE.BLUE_MUSHED_ROOM = "我把它压扁了。"
	
--StantonStuff
DESCRIBE.SKULLFLASK = "有趣的饮料。"
DESCRIBE.SKULLFLASK_EMPTY = "空的。"
DESCRIBE.STANTON_SHADOW_TONIC = "应该喝吗？"
DESCRIBE.STANTON_SHADOW_TONIC_FANCY = DESCRIBE.STANTON_SHADOW_TONIC
DESCRIBE.STANTON = "你没死？"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_HYPERCOURAGE = "饮料给鱼人勇气！"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_HYPERCOURAGE = "再来点饮料？"
--StantonStuff
	
DESCRIBE.ARMORLAVAE = DESCRIBE.LAVAE
	
DESCRIBE.THEATERCORN = "喜欢在吃的时候看鱼人和猪人打架。"
DESCRIBE.DEERCLOPS_BARRIER = "必须突围，不喜欢被困。"
	

DESCRIBE.MOONMAW_DRAGONFLY = "好看的鳞片！"
DESCRIBE.MOONMAW_LAVAE = "不！不要刺伤！"
DESCRIBE.SNAPPERTURTLE = "新邻域！朋友，不是朋友？"
DESCRIBE.SNAPPERTURTLEBABY = "小小的！"
DESCRIBE.SNAPPERTURTLENEST = "这里有新人类吗？"
DESCRIBE.GLASS_SCALES = "漂亮！想装饰头部，浮浪噗！"
DESCRIBE.MOONGLASS_GEODE = "不是鳞片？"
DESCRIBE.ARMOR_GLASSMAIL = "最好的鳞片！"
DESCRIBE.ARMOR_GLASSMAIL_SHARDS = "飞行的石头很吓人！！"
DESCRIBE.MOONMAW_GLASSSHARDS_RING = "它在做什么？！"
DESCRIBE.MOONMAW_GLASSSHARDS = DESCRIBE.MOONMAW_GLASSSHARDS_RING
DESCRIBE.MOONMAW_LAVAE_RING = DESCRIBE.MOONMAW_LAVAE
DESCRIBE.MUTATOR_TRAPDOOR = DESCRIBE.MUTATOR_WARRIOR

DESCRIBE.WOODPECKER = "颜色艳丽的鸟。"
DESCRIBE.SNOTROAST = "浮浪噗！ 更糟了！"
ANNOUNCE.ANNOUNCE_ATTACH_BUFF_LARGEHUNGERSLOW = "我不是说这个，浮浪噗。"
ANNOUNCE.ANNOUNCE_DETACH_BUFF_LARGEHUNGERSLOW = ""
DESCRIBE.BOOK_RAIN = "湿书是好书。"
DESCRIBE.FLORAL_BANDAGE = "花和蜂蜜是对抗伤痛的好组合。"
DESCRIBE.DORMANT_RAIN_HORN = "贝壳看起来很有趣。"
DESCRIBE.RAIN_HORN = "我喜欢泡水，浮浪噗！"
DESCRIBE.DRIFTWOODFISHINGROD = "用咸味的捕捞器抓到很多鱼。"

    ANNOUNCE.ANNOUNCE_RATSNIFFER_ITEMS = {
LEVEL_1 = "小毛茸怪物想要我们的东西！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_FOOD = {
LEVEL_1 = "小毛茸怪物想要我们的食物！",
}
ANNOUNCE.ANNOUNCE_RATSNIFFER_BURROWS = {
LEVEL_1 = "小毛茸怪物在外边，要一起冲过来了！",
}

DESCRIBE.PIED_RAT = "绝对不是蜘蛛人！"
DESCRIBE.PIED_PIPER_FLUTE = "不是蜘蛛人，可以加入鱼人王国吗？"
DESCRIBE.UNCOMPROMISING_PACKRAT = "不喜欢他！"
	
ANNOUNCE.ANNOUNCE_PORTABLEBOAT_SINK = "我们现在去游泳吗？"
	


ACTIONFAIL.CHARGE_FROM =
{
	NOT_ENOUGH_CHARGE = "没用！",
	CHARGE_FULL = "/汩汩!/",
}
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_INSULATED = "没有让我震惊！ 弗洛普!"
ANNOUNCE.ANNOUNCE_CHARGE_SUCCESS_ELECTROCUTED = "/汩汩!/"
	
----UNDER THE WEATHER----
	
DESCRIBE.WINONA_TOOLBOX = "Weenowna-lady 不喜欢我在里面玩东西......"
ACTIONFAIL.WINONATOOLBOX = "无法打开锁！"
DESCRIBE.WINONA_CATAPULT_ITEM = "强硬的女士用品之一。"
DESCRIBE.WINONA_SPOTLIGHT_ITEM = "强硬的女士用品之一。"
DESCRIBE.WINONA_BATTERY_LOW_ITEM = "强硬的女士用品之一。"
DESCRIBE.WINONA_BATTERY_HIGH_ITEM = "强硬的女士用品之一。"
DESCRIBE.POWERCELL = "不要舔！"
DESCRIBE.WINONA_UPGRADEKIT_ELECTRICAL = "给灯箱。"
DESCRIBE.MINERHAT_ELECTRICAL = "现在有一个盒子。"
DESCRIBE.OCEAN_SPEAKER = "它在喊什么？"
--DESCRIBE.UM_SIREN = "Glorp is traitor!! Me think...?"
	
DESCRIBE.OCUPUS_BEAK = "Bird mouth?"
DESCRIBE.OCUPUS_TENTACLE = ""
DESCRIBE.OCUPUS_TENTACLE_EYE = "眼球，花花公子。"
DESCRIBE.OCUPUS_TENTACLE_COOKED = "不！不是食物。"
DESCRIBE.UM_OCUPUS_EYE = "很多眼球。"
DESCRIBE.UM_OCUPUS_EYETACLE = "移除眼球以便放手。"
DESCRIBE.UM_OCUPUS_TENTACLE = "不知道它也在这里！"
DESCRIBE.UM_OCUPUS_BEAK = "它的尖叫声很痛。"
DESCRIBE.BEAKBASHER = "打破更多东西！哈哈！"
DESCRIBE.HOUNDIOUS_OBSERVIOUS = "它告诉我们小狗什么时候来。"

DESCRIBE.ARMOR_REED_UM = "人鱼使用我们在沼泽中获得的一切。"
DESCRIBE.ARMOR_SHARKSUIT_UM = "天平在天平上感觉很好。"
DESCRIBE.ROCKJAWLEATHER = "抱歉，你太坏了。"

DESCRIBE.EYEOFTERROR_MINI_ALLY = "咕噜咕噜……没有榴莲给你！全给我了！"
DESCRIBE.EYEOFTERROR_MINI_GROUNDED_ALLY = DESCRIBE.EYEOFTERROR_MINI_GROUNDED

DESCRIBE.STUFFED_PEEPER_POPPERS = "浪费了优质榴莲。"
DESCRIBE.UM_DEVILED_EGGS = "坏蛋。非常坏的蛋。"
DESCRIBE.LUSH_ENTRANCE = "Glorp...可怕的洞..."
DESCRIBE.CRITTER_FIGGY = "蓬松！蓬松！"
DESCRIBE.GIANT_TREE_BIRDNEST = "翻滚！小鸟在里面！"

    DESCRIBE.SLUDGE = "这东西是...咕噜咕噜..."
DESCRIBE.SLUDGE_OIL = "滴滴。"
    DESCRIBE.SLUDGE_SACK = "软包，花花公子。"
DESCRIBE.CANNONBALL_SLUDGE_ITEM = "现在用力。"
DESCRIBE.BOAT_BUMPER_SLUDGE = "让船保持强劲。"
DESCRIBE.BOAT_BUMBER_SLUDGE_KIT = "摇摇晃晃。"
    DESCRIBE.BOATPATCH_SLUDGE = "小东西阻止了水。但是我想要水。"
    DESCRIBE.UM_COPPER_PIPE = "吞咽？"
    DESCRIBE.BRINE_BALM = "像盐，但是太咸了！"
    DESCRIBE.UNCOMPROMISING_FISHINGNET = "最好不要伤害他们。"
DESCRIBE.UM_AMBER = "惊喜摇滚！"
    DESCRIBE.UM_BEEGUN = "现在！工作！"
DESCRIBE.BULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.CHERRYBULLETBEE = DESCRIBE.KILLERBEE
DESCRIBE.SUNKENCHEST_ROYAL = "需要这个。带给国王。"
DESCRIBE.SUNKENCHEST_ROYAL_RED = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_BLUE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_PURPLE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_GREEN = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_ORANGE = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_YELLOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.SUNKENCHEST_ROYAL_RAINBOW = DESCRIBE.SUNKENCHEST_ROYAL_RANDOM
DESCRIBE.STEERINGWHEEL_COPPER = "不好吃。"
DESCRIBE.STEERINGWHEEL_COPPER_ITEM = "闪亮的轮子玩意！"
DESCRIBE.BOAT_BUMPER_COPPER = "船看起来像铁人，颤抖。"
DESCRIBE.BOAT_BUMPER_COPPER_KIT = "让船看起来像铁人。"
DESCRIBE.UM_DREAMCATCHER = "糟糕的睡眠捕捉器？弗洛普。这是怎么回事？"
DESCRIBE.UM_BRINEISHMOSS = "苔藓好吃"
DESCRIBE.UM_COALESCED_NIGHTMARE = "可怕的东西。坏东西！"
DESCRIBE.SLUDGE_CORK = "大插头东西。"
DESCRIBE.SLUDGESTACK = "哎呀哎呀。"
DESCRIBE.SPECTER_SHIPWRECK = "船不圆？"

DESCRIBE.UNCOMPROMISING_HARPOON = "." -- 未实现
DESCRIBE.UNCOMPROMISING_HARPOON_HEAVY = "." -- 未实现
DESCRIBE.UNCOMPROMISING_HARPOONREEL = "." -- 未实现
DESCRIBE.UM_MAGNERANG = "磁铁？它是如何工作的？"
DESCRIBE.UM_MAGNERANGREEL = "小马蹄铁！"
DESCRIBE.SIREN_THRONE = "漂亮女人的摇滚？"
DESCRIBE.LAVASPIT_SLUDGE = "咕噜！太热了！"

DESCRIBE.UM_BEEGUARD_SHOOTER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_SEEKER = DESCRIBE.BEEGUARD
DESCRIBE.UM_BEEGUARD_BLOCKER = "毒刺墙！咕噜咕噜！"

DESCRIBE.PORTABLEBOAT_ITEM = "人鱼可以更好地漂浮！"
DESCRIBE.MASTUPGRADE_WINDTURBINE_ITEM = "它使风……变成光？"

DESCRIBE.UM_ORNAMENT_OPOSSUM = "沼泽猫！"
DESCRIBE.UM_ORNAMENT_RAT = "鬼鬼祟祟的东西在打瞌睡？"

DESCRIBE.TRINKET_WATHOM1 = "看起来像 瓦西！也许他想要它？"
	
DESCRIBE.CODEX_MANTRA = DESCRIBE.WAXWELLJOURNAL
	
-- WIXIE RELATED STRINGS
	
DESCRIBE.WIXIE_PIANO = "发出有趣的小声音！"
DESCRIBE.WIXIE_CLOCK = "拉动东西会让尖的东西旋转！"
DESCRIBE.WIXIE_WARDROBE = "里面是什么？坏了吗？"
DESCRIBE.CHARLES_T_HORSE = "就像可怕的有弹性的人。"
DESCRIBE.THE_REAL_CHARLES_T_HORSE = "像有弹性的人，但没有弹性。"
DESCRIBE.SLINGSHOT_MATILDA = "发出有趣的声音！"
DESCRIBE.SLINGSHOT_GNASHER = "坏东西造坏东西！"

DESCRIBE.SLINGSHOTAMMO_LAZY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SHADOW = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FIRECRACKERS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_HONEY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_RUBBER = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TREMOR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONROCK = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_MOONGLASS = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SALT = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_SLIME = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_GOOP = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_FLARE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_INSANITY = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_LUNARVINE = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.SLINGSHOTAMMO_LIMESTONE = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_TAR = DESCRIBE.SLINGSHOTAMMO_ROCK
DESCRIBE.SLINGSHOTAMMO_OBSIDIAN = DESCRIBE.SLINGSHOTAMMO_ROCK

DESCRIBE.BAGOFMARBLES = "哦哦，像小鱼卵！"

DESCRIBE.MEATRACK_HAT = {
    GENERIC = DESCRIBE.MEATRACK.GENERIC,
			
    DRYING = DESCRIBE.MEATRACK.DRYING,
    DRYINGINRAIN = DESCRIBE.MEATRACK.DRYINGINRAIN,
			
    DRYING_NOTMEAT = DESCRIBE.MEATRACK.DRYING_NOTMEAT,
    DRYINGINRAIN_NOTMEAT = DESCRIBE.MEATRACK.DRYINGINRAIN_NOTMEAT,
}
DESCRIBE.FISHMEAT_DRIED = "哦，不..." 
DESCRIBE.SMALLFISHMEAT_DRIED = "我觉得恶心..." 

DESCRIBE.WIXIEGUN = "好重..."

DESCRIBE.MARA_BOSS1 = "呃!"
ANNOUNCE.GAS_DAMAGE = "呼!呼!"

-- 烧焦的荨麻的东西
DESCRIBE.UM_PYRE_NETTLES = "仍然是燃烧的味道！"
DESCRIBE.UM_SMOLDER_SPORE = "F-flurpt..."
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_EATEN = {
"知道它会发生，但它看起来这么好！！",
"后悔死了！！"
}
ANNOUNCE.ANNOUNCE_SMOLDER_SPORE_INVENTORY_POP ="真好! 忘了有这个了!!"
DESCRIBE.UM_ARMOR_PYRE_NETTLES = "让鳞片受伤。还是不好的植物！"
DESCRIBE.UM_BLOWDART_PYRE = "别让这个东西跑掉！"

--《天气预报》第一部分
DESCRIBE.ALPHA_LIGHTNINGGOAT = "你也是个国王？"
DESCRIBE.UM_TORNADO = "噗，看起来很糟糕..."
DESCRIBE.UM_WATERFALL = "耶！ 泥泞来了！"
ANNOUNCE.ANNOUNCE_UM_NO_TORNADO = "没有风。"
