local STRINGS = GLOBAL.STRINGS
local RECIPE_DESC = STRINGS.RECIPE_DESC

STRINGS.UI.CRAFTING.NEEDSTECH.BOMBMIXER = "把炸药放到炸弹混合机上开始混合！"
STRINGS.ACTIONS.OPEN_CRAFTING.BOMBMIXER = "在此混合"
RECIPE_DESC.TRANSMUTE_MONSTERMEAT = "把怪物碎肉转化为怪物肉"
RECIPE_DESC.TRANSMUTE_MONSTERSMALLMEAT = "把小怪物碎肉转化为怪物肉"

RECIPE_DESC.WATERMELON_LANTERN = "多汁的照明。"
RECIPE_DESC.CRITTERLAB_REAL = "可爱的小伙伴们来毁掉气氛。"
RECIPE_DESC.UM_SAND = "把大石头变成小石子。"
RECIPE_DESC.SNOWGOGGLES = "让眼睛清晰，耳朵更暖。"
RECIPE_DESC.RATPOISONBOTTLE = "对害虫来说极具诱惑力。"
RECIPE_DESC.DISEASECUREBOMB = "有效的防疫炸弹。"
RECIPE_DESC.ICE = "固态的水。"
RECIPE_DESC.GASMASK = "让周围闻起来像鸟。"
RECIPE_DESC.PLAGUEMASK = "你就是疫病的解药！"
RECIPE_DESC.SALTPACK = "为世界加点味道。"
RECIPE_DESC.RATPOISON = "致命的盛宴。"
RECIPE_DESC.SHROOM_SKIN = "缝合的皮肤。"
RECIPE_DESC.SPOREPACK = "不卫生的储存。"
RECIPE_DESC.AIR_CONDITIONER = "调节空气。"
if TUNING.DSTU and TUNING.DSTU.LONGPIG then
    RECIPE_DESC.REVIVER = "以死肉复活，为死去的朋友续命。"
end
RECIPE_DESC.HONEY_LOG = "一根蜜木，驱赶病魔。"
RECIPE_DESC.BUGZAPPER = "用电击回击叮咬的小虫子！"
RECIPE_DESC.ANCIENT_AMULET_RED = "召回你逝去的灵魂。"
RECIPE_DESC.RAT_WHIP = "饥饿的打击！"
RECIPE_DESC.TURF_HOODEDMOSS = "长着兜帽的苔藓地，带着月光的气息。"
RECIPE_DESC.TURF_ANCIENTHOODEDTURF = "戴着兜帽的古林往昔风貌。"
RECIPE_DESC.SKULLCHEST_CHILD = "跨维度的物品储藏。"
RECIPE_DESC.UM_BEAR_TRAP_EQUIPPABLE_TOOTH = "这些牙齿要咬住目标！"
RECIPE_DESC.UM_BEAR_TRAP_EQUIPPABLE_GOLD = "我和我的闪亮牙齿！"
RECIPE_DESC.ARMOR_GLASSMAIL = "用破碎玻璃把自己包围。"
RECIPE_DESC.MUTATOR_TRAPDOOR = "它们据说相当聪明。"
RECIPE_DESC.DRIFTWOODFISHINGROD = "去高级钓鱼吧。为高级鱼准备。"
RECIPE_DESC.UNCOMPROMISING_FISHINGNET = "只有网，别无他物！"
RECIPE_DESC.UNCOMPROMISING_HARPOON = "把他们拖上甲板！"
RECIPE_DESC.UNCOMPROMISING_HARPOON_HEAVY = "准备来点链式惩罚吗？"
RECIPE_DESC.UM_MAGNERANG = "相互吸引！"
RECIPE_DESC.BOOK_RAIN_UM = "天气效应的汇编目录。"
RECIPE_DESC.RAIN_HORN = "让世界为水所覆。"
RECIPE_DESC.HAT_RATMASK = "闻出那些害虫！"
RECIPE_DESC.FLORAL_BANDAGE = "带着花香的疗伤。"
RECIPE_DESC.UM_RIMEWEED_ICEPACK = "冰镇疗伤！"
RECIPE_DESC.WINONA_TOOLBOX = "工程师总有工具在手。"
RECIPE_DESC.POWERCELL = "便携的电力来源！"
RECIPE_DESC.WINONA_UPGRADEKIT_ELECTRICAL = "任何旧灯都能被电气化。"
RECIPE_DESC.BOATPATCH_SLUDGE = "当你的船出现不该有的洞时。"
RECIPE_DESC.ARMOR_REED_UM = "防水的护甲。"
RECIPE_DESC.ARMOR_SHARKSUIT_UM = "化身为鲨。"
RECIPE_DESC.SLUDGE_SACK = "贼人的手只剩粘糊糊的东西。"
RECIPE_DESC.BOAT_BUMPER_SLUDGE_KIT = "缓和撞击。"
RECIPE_DESC.SLUDGE_OIL = "只有最纯粹的污油。"
RECIPE_DESC.SLUDGE_CORK = "对船来说过于笨重的木塞。"
RECIPE_DESC.CANNONBALL_SLUDGE_ITEM = "开火！"
RECIPE_DESC.BRINE_BALM = "在伤口上撒一把盐。"
RECIPE_DESC.CRITTER_FIGGY_BUILDER = "它们喜欢在东西上挖洞。"
-- RECIPE_DESC.STEERINGWHEEL_COPPER_ITEM = "Steer more than your masts."
RECIPE_DESC.TRINKET_6 = "现代奇迹的关键配件。"
RECIPE_DESC.PORTABLEBOAT_ITEM = "收拾好，一起上路！"
RECIPE_DESC.MASTUPGRADE_WINDTURBINE_ITEM = "扬帆全速前进！"
RECIPE_DESC.CODEX_MANTRA = "跟我念一遍。"
if TUNING.DSTU and TUNING.DSTU.TELESTAFF_REWORK then
    RECIPE_DESC.TELEBASE = "现在完全不用金子了！"
end
-- sailing rebalance strings
RECIPE_DESC.MOONSTORM_STATIC_ITEM = "月之力，被封存！"
RECIPE_DESC.ALTERGUARDIANHATSHARD = "驾驭月光的碎片。"
RECIPE_DESC.WATERPLANT_PLANTER = "种出你自己的海藻。"
RECIPE_DESC.BLUEPRINT = "学习新的制作图。"
RECIPE_DESC.PUMPKINCOOKIE = "奶奶的南瓜饼干。"
RECIPE_DESC.HERMIT_BUNDLE_LURES = "今天就去钓鱼吧！"
RECIPE_DESC.BOOTLEG = "虽不及原版，但将就着用。"
-- Pyre Nettle stuff
RECIPE_DESC.UM_ARMOR_PYRE_NETTLES = "伤你一点，伤它们很多。"
RECIPE_DESC.UM_BLOWDART_PYRE = "里外都暖和的吹箭！"
RECIPE_DESC.UM_ARMOR_BRAMBLE_RIMEWEED = "大自然在说：冷静点。"
RECIPE_DESC.UM_BLOWDART_RIME = "冰冷的远程打击。"

RECIPE_DESC.BOAT_ANCIENT_ITEM = "他们不再按从前的方式造船了。"
RECIPE_DESC.BOAT_ANCIENT_ITEM_BLUEPRINT = "过去总有值得学习之处。"

-- Veteran Shrine Crafts

RECIPE_DESC.CURSED_ANTLER = "冰封、粉碎、终结。"
RECIPE_DESC.BEARGERCLAW = "把石头掷出去！"
RECIPE_DESC.KLAUS_AMULET = "双倍一击！"
RECIPE_DESC.SILKSACK = "把贵重物品包好保存。"
RECIPE_DESC.FEATHER_FROCK = "鸟羽织成的衣裳，诸如此类。"
RECIPE_DESC.GORE_HORN_HAT = "冲锋！！"
RECIPE_DESC.CRABCLAW = "镶嵌宝石，驱动它们的力量。"
RECIPE_DESC.SLOBBERLOBBER = "到处飞溅熔岩口水！"
RECIPE_DESC.UM_BEEGUN = "子弹蜜蜂来啦！"
RECIPE_DESC.UM_WINGSUIT = "展翼起飞！"
RECIPE_DESC.UM_EXHUMER = "审判者、陪审者、复活者。"
RECIPE_DESC.UM_BEEGUN_CHERRY = "剧毒的子弹蜜蜂！"
RECIPE_DESC.UM_MOONFLY_LANTERN = "点亮路途，引你前行！"

RECIPE_DESC.WINONA_CATAPULT_ITEM_UM = RECIPE_DESC.WINONA_CATAPULT
RECIPE_DESC.WINONA_SPOTLIGHT_ITEM_UM = RECIPE_DESC.WINONA_SPOTLIGHT
RECIPE_DESC.WINONA_BATTERY_LOW_ITEM_UM = RECIPE_DESC.WINONA_BATTERY_LOW
RECIPE_DESC.WINONA_BATTERY_HIGH_ITEM_UM = RECIPE_DESC.WINONA_BATTERY_HIGH
RECIPE_DESC.UM_BOAT_ENGINE = "让帆船在大海上全速前进。"

RECIPE_DESC.PACT_ARMOR_SANITY = "裹着你的罪孽。"
RECIPE_DESC.PACT_SWORD_SANITY = "沉重如肩上无法卸下的重担。"

RECIPE_DESC.UM_ASTRAL_PROJECTOR = "灵魂与肉体分离——小心别让东西溜进来。"
RECIPE_DESC.UM_ASTRAL_PROJECTOR_TARGET = "你还是原来的你吗？"
RECIPE_DESC.UM_INKUBATOR = "新生诞生，但代价未卜。"
RECIPE_DESC.UM_SCRAPPER = "把任何东西或任何人化为基元。"
RECIPE_DESC.PLAUNT_MANNY = "她在预感不祥时会搓搓膝盖。"


--Wixie
RECIPE_DESC.MEATRACK_HAT = "风干肉味的帽子。"
RECIPE_DESC.BEAKBASHER = "拿着带喙的棍子猛击。"
RECIPE_DESC.BAGOFMARBLES = "小心脚下！"
RECIPE_DESC.SLINGSHOT_CLAIRE = "自由——至少行动上的自由。"
RECIPE_DESC.SLINGSHOT_JESSIE = "可塑的思维枪。"
RECIPE_DESC.SLINGSHOTAMMO_OBSIDIAN = "一发玩味的纵火弹。"
RECIPE_DESC.SLINGSHOTAMMO_TAR = "留下一串粘稠痕迹！"
RECIPE_DESC.THE_REAL_CHARLES_T_HORSE = "上马吧，查尔斯！"
RECIPE_DESC.SLINGSHOT_GNASHER = "多点吠声，多点撕咬力！"
RECIPE_DESC.SLINGSHOT_MATILDA = "一大堆麻烦！"
RECIPE_DESC.SLINGSHOT = "制造各种恶作剧！"
RECIPE_DESC.SLINGSHOTAMMO_FLARE = "燃烧一击！"
RECIPE_DESC.SLINGSHOTAMMO_LAZY = "现在你看不见我……"
RECIPE_DESC.SLINGSHOTAMMO_SHADOW = "播撒恐惧。"
RECIPE_DESC.SLINGSHOTAMMO_FIRECRACKERS = "给生性好闹的孩子们用的。"
RECIPE_DESC.SLINGSHOTAMMO_HONEY = "甜蜜一击，哎呀！"
RECIPE_DESC.SLINGSHOTAMMO_RUBBER = "有弹性的回弹弹。"
RECIPE_DESC.SLINGSHOTAMMO_TREMOR = "看看能摇落些什么。"
RECIPE_DESC.SLINGSHOTAMMO_MOONROCK = "把战斗带到另一维度。"
RECIPE_DESC.SLINGSHOTAMMO_MOONGLASS = "小心你的手！"
RECIPE_DESC.SLINGSHOTAMMO_SALT = "在伤口上撒点盐！"
RECIPE_DESC.SLINGSHOTAMMO_SLIME = "黏糊糊的时间到了！"
RECIPE_DESC.SLINGSHOTAMMO_GOOP = "黏糊给你，黏糊给我！"

--Other new stuff that I want to put at the bottom because yes (Atoba started this I swear!!)
RECIPE_DESC.UM_HAT_RIME = "给寒冷的佩戴者准备的冰冷头盔。"
RECIPE_DESC.UM_ICE_SICLE = "砍掉植物同时给自己降温。"
RECIPE_DESC.JAWED_SCYTHE = "用来砍除茂密植物的镰刀。"
RECIPE_DESC.UM_RIBOPODDEN = "为机会主义拾荒者提供的巢穴。"
--[[RECIPE_DESC.UNCOMPROMISING_WINKYBURROW = "A network of interconnected burrows."
RECIPE_DESC.UNCOMPROMISING_WINKYHOMEBURROW = "Hole, sweet hole." --Don't let Canis read this]]
RECIPE_DESC.OAR_MONKEY = "现在你可以做猴划了。"
--
RECIPE_DESC.UM_BOATBOTTLE = "把整艘船收起来以备后用。"
RECIPE_DESC.UM_HAT_LEAFWING = "化身为短暂的果蝠。"
RECIPE_DESC.SCRAP_MONOCLEHAT = "远眺地平线。"
RECIPE_DESC.TURF_UM_HOTSPRING_GRASS = "一小片蒸汽缭绕的湿草地。"
RECIPE_DESC.TURF_UM_HOTSPRING_WHITEROCK = "温暖白色的温泉岩床。"
RECIPE_DESC.TURF_UM_HOTSPRING_YELLOWROCK = "软绵的黄石温泉地面。"
RECIPE_DESC.UM_FYRE_BOMB = "一个朴素直接的炸弹。"
RECIPE_DESC.UM_HAT_BEE_MOON = "戴着会惹怒变异蜜蜂的帽子。"
RECIPE_DESC.UM_EYEBALM = "在风暴中稳步前行的护目膏。"
RECIPE_DESC.UM_BEEMINE_MOON_ITEM = "武装化的变异蜜蜂。事情只会变糟。"
RECIPE_DESC.UM_DETONATOR = "引爆几乎任何爆炸物，或任何目标。"
RECIPE_DESC.UM_RECORD_MOONMAW = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_TOT = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_STRANGER = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_SHADOW_WIXIE = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_WIXIE = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_WATHOM = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_WINKY = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_MENU = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_HOODED_WIDOW = RECIPE_DESC.RECORD
RECIPE_DESC.UM_RECORD_WALTER = RECIPE_DESC.RECORD

RECIPE_DESC.WATHGRITHR_SHIELD_DREADSTONE = "将黑暗锻造成盾牌。"

RECIPE_DESC.UM_FLAMETHROWER = "对任何稍微可燃的东西都是极佳的威慑。"
RECIPE_DESC.UM_FIRECREAM = "让火焰远离。"
RECIPE_DESC.UM_HAT_PEPPERDRAGON = "颠覆温度规则。"
RECIPE_DESC.UM_BOOMBERRY_BOMB = "棍上的果实地雷。"

RECIPE_DESC.UM_FEATHER_TOTEM = "手中三根羽毛，对无法逃脱死亡的人更有价值。"
