STRINGS.CHARACTERS.WOLFGANG.NEED_MORE_MIGHTINESS = "强壮的肌肉需要休息！"
STRINGS.CHARACTERS.WOLFGANG.NEED_MORE_SANITY = "太吓人了！"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_1_TITLE = "强力劳作 I"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_2_TITLE = "强力劳作 II"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_3_TITLE = "强力劳作 III"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_4_TITLE = "强力劳作 IV"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_EXPERT_TITLE = "强力劳作专家"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_1_DESC = "砍伐、挖掘和锤击时使用秒杀消耗的力量值降低到17%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_2_DESC = "砍伐、挖掘和锤击时使用秒杀消耗的力量值降低到33%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_3_DESC = "砍伐、挖掘和锤击时使用秒杀消耗的力量值降低到50%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_4_DESC = "砍伐、挖掘和锤击时使用秒杀消耗的力量值降低到67%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_CRITWORK_EXPERT_DESC = "砍伐、挖掘和锤击时使用秒杀消耗的力量值降低到75%。\n你在强壮状态时，可以突破工具的挖掘等级挖掘更硬的物品。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_COACH_DESC = "学会制作训练哨。\n在训练时，普通以及强壮状态下的沃尔夫冈会增加随从的伤害。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_TITLE = "练腿日"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_2_TITLE = "练腿日 II"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_3_TITLE = "练腿日 III"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_4_TITLE = "练腿日 IV"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_EXPERT_TITLE = "练腿日专家"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_DESC = "飞跃消耗的力量值降低到10%，并且会对落点的敌人造成伤害。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_2_DESC = "飞跃消耗的力量值降低到20%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_3_DESC = "飞跃消耗的力量值降低到30%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_4_DESC = "飞跃消耗的力量值降低到40%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_LEGS_EXPERT_DESC = "飞跃消耗的力量值降低到50%,，冷却时间减半，\n并且你可以背负重物飞跃对落点造成更多伤害，伤害范围也更广。"


STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_GYM_OVERBUFF_1_DESC = "力量值最高可达110。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_GYM_OVERBUFF_2_DESC = "力量值最高可达120。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_GYM_OVERBUFF_3_DESC = "力量值最高可达130。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_GYM_OVERBUFF_4_DESC = "力量值最高可达140。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_GYM_OVERBUFF_5_TITLE = "突破极限专家"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_GYM_OVERBUFF_5_DESC = "力量值最高可达150, 并且使用健身房将获得的力量值翻倍。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_1_TITLE = "强力重击 I"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_2_TITLE = "强力重击 II"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_3_TITLE = "强力重击 III"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_4_TITLE = "强力重击 IV"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_5_TITLE = "强力重击 V"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_1_DESC = "强力重击的力量值降低到10%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_2_DESC = "强力重击的力量值降低到20%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_3_DESC = "强力重击的力量值降低到30%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_4_DESC = "强力重击的力量值降低到40%。"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_MIGHTY_STRIKES_5_DESC = "强力重击的力量值降低到50%。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_SHADOW_TITLE = "恶魔契约"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_SHADOW_DESC = "女王将以毁灭性的力量奖励你的忠诚。\n现在可以永远保持强壮状态，并且只有1.5x饥饿速度，但肉体变得更加脆弱。"

STRINGS.SKILLTREE.ALLEGIANCE_LOCK_SHADOW_DESC = "掌控暗影力量，但选择后禁锢其他专精。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_SHADOW_MASTERY_TITLE = "掌握暗影"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_SHADOW_MASTERY_DESC = "基础攻击伤害更低，但每次攻击、飞跃和使用强力劳作技能时对攻击伤害加成，受到伤害重置加成。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_LUNAR_TITLE = "骇人成长"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_LUNAR_DESC = "神秘创始人将通过月光能量催生成的另类骇人形态来奖励你的好奇心。\n扭曲为另类形态，无比强大、浑身鱼鳞。航海与捕鱼技巧更为娴熟。"

STRINGS.SKILLTREE.ALLEGIANCE_LOCK_LUNAR_DESC = "掌控过剩的饥饿，但选择后禁锢其他专精。"

STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_LUNAR_MASTERY_TITLE = "掌握月光"
STRINGS.SKILLTREE.WOLFGANG.WOLFGANG_ALLEGIANCE_LUNAR_MASTERY_DESC = "使用技能时力量值不足将会扣除饥饿值作为替代。\n飞跃落在水上时会在落点生成浮冰平台。\n免疫诅咒饰品效果。"

STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_MONSTERTONORMAL = "沃尔夫冈感觉好渺小。"
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_NORMALTOMONSTER = "大海在呼唤沃尔夫冈！"
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_IGNOREDTRINKETCURSE = "区区小镯子配不上我强大的鳞片！"

STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_WASHED_ASHORE = "沃尔夫冈很高兴回到陆地上。"
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_FELLINTOVOID = "沃尔夫冈勉强抓住了岩壁边缘！"
STRINGS.CHARACTERS.WOLFGANG.ANNOUNCE_BOAT_SINK = "海水好冷！"